import {AiConnectionPanel} from './ai-connection-ui.tsx';
import {useState} from 'react';
import {call,read} from './api.ts';
import type {Page,Source} from './dto.ts';
import {ErrorBox,Field,Modal,Pager,useAction,useLoad} from './ui.tsx';
import {outcomeUnknown} from './talent-edit.tsx';
interface Operations {
 candidate:null|{digest:string;providerIdentityHash:string;configRevision:number;currency:string;perTaskLimitUnits:number;dailyLimitUnits:number;maxAttempts:number};
 approval:null|{id:string;revision:number;enabled:boolean};enabled:boolean;
 budgets:Array<{id:string;revision:number;period:string;currency:string;reservedUnits:number;settledUnits:number;frozen:boolean}>;
 unresolved:Array<{id:string;revision:number;runId:string;state:string;providerIdentityHash:string;providerIdempotencyKey:string}>;
}
export function AiOperationsPanel({onClose}:{onClose:()=>void}){
 const [connectionLocked,setConnectionLocked]=useState(false);
 const [tick,setTick]=useState(0),[page,setPage]=useState(1),[confirmed,setConfirmed]=useState(false),[attempt,setAttempt]=useState(''),[sourceId,setSourceId]=useState(''),[outcome,setOutcome]=useState<'SUCCEEDED'|'NOT_EXECUTED'>('SUCCEEDED'),[amount,setAmount]=useState(''),[proofChecked,setProofChecked]=useState(false),[pending,setPending]=useState<(()=>Promise<void>)|null>(null);
 const load=useLoad(()=>read<Operations>('ai.operations'),tick),sources=useLoad(()=>read<Page<Source>>('source.list',{}, {page:String(page),pageSize:'20'}),page),action=useAction(),unknown=outcomeUnknown(action.error),frozen=action.busy||unknown,row=load.data,a=row?.unresolved.find(a=>a.id===attempt),source=sources.data?.items.find(s=>s.id===sourceId);
 const mutate=(fn:()=>Promise<void>)=>{setPending(()=>fn);void action.run(async()=>{await fn();setPending(null);setConfirmed(false);setProofChecked(false);setTick(t=>t+1);});};
 return <Modal title="AI 配置与费用核对" wide onClose={()=>{if(!frozen&&!connectionLocked)onClose();}}><div className="modal-body"><ErrorBox error={load.error}/><ErrorBox error={action.error}/>{unknown&&pending&&<><p className="notice">结果未知，请保持本次内容并原样重试。</p><button disabled={action.busy} onClick={()=>mutate(pending)}>原样重试核对操作</button></>}<AiConnectionPanel setLocked={setConnectionLocked} changed={()=>setTick(t=>t+1)}/><fieldset disabled={frozen||load.busy||connectionLocked}>
 <h3>调用配置</h3>{row?.candidate?<><p>配置版本 {row.candidate.configRevision} · {row.enabled?'已批准启用':'未启用'}</p><p>币种 {row.candidate.currency}；单次预留 {row.candidate.perTaskLimitUnits}；每日上限 {row.candidate.dailyLimitUnits}（部署配置的最小计费单位）。</p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已核对模型连接及调用限额</label><button disabled={!confirmed} onClick={()=>{const d={configDigest:row.candidate!.digest,expectedRevision:row.approval?.revision??0,enabled:!row.approval?.enabled,confirmConfiguration:true};mutate(async()=>{await call('ai.approval',d);});}}>{row.approval?.enabled?'停用当前配置':'批准当前配置'}</button></>:<p className="notice">请先保存模型连接。人工资料操作不受影响。</p>}
 <h3>待核对请求</h3><p>只核对费用，不补写建议或重新发送。先在来源中登记并核验供应商证明，再逐笔确认。</p><Field label="待核对请求"><select value={attempt} onChange={e=>{setAttempt(e.target.value);setProofChecked(false);}}><option value="">请选择</option>{row?.unresolved.map(a=><option key={a.id} value={a.id}>{a.providerIdempotencyKey} · {a.state==='UNKNOWN'?'待核对':'仍在等待结果'}</option>)}</select></Field><ErrorBox error={sources.error}/><Field label="供应商核对证据"><select value={sourceId} onChange={e=>{setSourceId(e.target.value);setProofChecked(false);}}><option value="">请选择已核验来源</option>{sources.data?.items.filter(s=>s.status==='CONFIRMED'&&s.basisMode==='INTERNAL_USE').map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></Field>{sources.data&&<Pager page={page} pageSize={20} total={sources.data.total} setPage={setPage}/>}<Field label="核对结果"><select value={outcome} onChange={e=>{setOutcome(e.target.value as typeof outcome);setProofChecked(false);}}><option value="SUCCEEDED">供应商确认已执行</option><option value="NOT_EXECUTED">供应商确认未执行且未收费</option></select></Field>{outcome==='SUCCEEDED'&&<Field label="已确认费用（配置最小单位）"><input type="number" min="0" max="2000000000" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></Field>}<label><input type="checkbox" checked={proofChecked} onChange={e=>setProofChecked(e.target.checked)}/>证据对应所选供应商和原请求编号，金额已经人工核对</label><button disabled={!a||a.state!=='UNKNOWN'||!source||sources.busy||!proofChecked||(outcome==='SUCCEEDED'&&(amount===''||!Number.isSafeInteger(Number(amount))||Number(amount)<0))} onClick={()=>{if(!a||!source)return;const d={expectedRevision:a.revision,outcome,amountUnits:outcome==='NOT_EXECUTED'?0:Number(amount),evidenceSourceId:source.id,evidenceSourceRevision:source.revision,providerIdempotencyKey:a.providerIdempotencyKey,providerIdentityHash:a.providerIdentityHash,confirmProviderResult:true};mutate(async()=>{await call('ai.reconcile',d,{id:a.id});setAttempt('');});}}>确认核对并关闭旧任务</button>
 <h3>费用记录</h3>{row?.budgets.map(b=><article className="panel" key={b.id}><p>{b.period} · {b.currency} · 已核对 {b.settledUnits} · 未决预留 {b.reservedUnits}{b.frozen?' · 已冻结':''}</p>{b.frozen&&<button disabled={!!row.unresolved.length||!row.enabled} onClick={()=>{if(!window.confirm('确认所有未决费用已经核对，并按当前批准的限额恢复调用？历史超额金额会保留。'))return;mutate(async()=>{await call('ai.unfreeze',{expectedRevision:b.revision,confirmOverrun:true},{id:b.id});});}}>确认费用后解除冻结</button>}</article>)}</fieldset><footer className="modal-footer"><button disabled={frozen||connectionLocked} onClick={onClose}>返回</button></footer></div></Modal>;
}
