import {useState,type ReactNode} from 'react';
import {Button,Menu,Breadcrumb,Tooltip} from 'antd';
import {DashboardOutlined,TeamOutlined,UnorderedListOutlined,PictureOutlined,ProjectOutlined,CheckSquareOutlined,FolderOutlined,SettingOutlined,MenuFoldOutlined,MenuUnfoldOutlined} from '@ant-design/icons';
import type {Me} from './dto.ts';
import {labels} from './ui.tsx';
const primary=[['dashboard','工作台',DashboardOutlined],['people','人才库',TeamOutlined],['shortlists','候选清单',UnorderedListOutlined],['works','作品库',PictureOutlined],['projects','项目',ProjectOutlined],['review','审核',CheckSquareOutlined]] as const;
const groups:Array<[string,Array<[string,string,string]>]>=[['资料工具',[['sources','资料来源','sources.read'],['media','全局素材','assets.read'],['imports','导入资料','records.write'],['exports','内部导出','data.export'],['ai','AI 辅助整理','ai.use']]],['协作与权限',[['handoffs','资料交接','records.read'],['members','成员与范围','members.manage']]],['系统维护',[['merges','人才合并','data.merge'],['deletions','删除任务','data.delete'],['catalog','分类字典','catalog.manage'],['audit','操作记录','audit.read']]]];
function BrandMark(){return <svg className="once-mark" viewBox="0 0 28 28" role="img" aria-label="ONCE 品牌图标"><rect x="2" y="2" width="24" height="24" rx="5" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="14" cy="14" r="6" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M14 2v6M14 20v6" stroke="currentColor" strokeWidth="2"/></svg>;}
export function AppShell({me,active,onNavigate,children}:{me:Me;active:string;onNavigate:(key:string)=>void;children:ReactNode}){
 const [collapsed,setCollapsed]=useState(()=>window.innerWidth<1100),[managementOpen,setManagementOpen]=useState(false);
 const management=groups.some(([,items])=>items.some(i=>i[0]===active));
 const navigate=(key:string)=>{onNavigate(key);if(window.innerWidth<760)setCollapsed(true);};
 const title=primary.find(p=>p[0]===active)?.[1]??groups.flatMap(([,items])=>items).find(i=>i[0]===active)?.[1]??'账号设置';
 const managementItems=groups.flatMap(([group,items])=>{const allowed=items.filter(i=>me.permissions.includes(i[2])||i[0]==='exports'&&me.permissions.includes('sources.review')||i[0]==='ai'&&me.permissions.includes('sources.review'));return allowed.length?[{type:'group' as const,label:<span className="nav-group-label">{group}</span>,children:allowed.map(([key,label])=>({key,label,icon:<FolderOutlined/>}))}]:[];});
 return <div className={'once-shell '+(collapsed?'is-collapsed':'')}><a className="skip-link" href="#workspace-content">跳到工作内容</a><aside className="once-sidebar" aria-label="工作空间导航"><div className="brand"><BrandMark/>{!collapsed&&<div>ONCE<small>PRODUCTION DESK</small></div>}</div>{!collapsed&&<div className="workspace-label">{me.workspaceName??'内部工作空间'}</div>}<nav aria-label="工作空间"><Menu mode="inline" inlineCollapsed={collapsed} selectedKeys={[active]} openKeys={management||managementOpen?['management']:[]} onOpenChange={keys=>setManagementOpen(keys.includes('management'))} onClick={({key})=>navigate(key)} items={[
 ...primary.filter(p=>p[0]!=='review'||me.permissions.includes('talent.review')||me.permissions.includes('sources.review')||me.permissions.includes('sources.write')).map(([key,label,Icon])=>({key,label,icon:<Icon/>,title:label})),
 ...(managementItems.length?[{key:'management',label:'管理与设置',icon:<SettingOutlined/>,children:managementItems}]:[])
 ]}/></nav><div className="sidebar-foot">{!collapsed&&<><div className="avatar">{me.displayName.slice(0,1)}</div><div><strong>{me.displayName}</strong><small>{labels[me.role]}</small></div></>}<Tooltip title="账号设置"><Button type="text" aria-label="账号设置" icon={<SettingOutlined/>} onClick={()=>navigate('account')}/></Tooltip></div></aside><div className="once-main"><header className="topbar"><Button type="text" aria-label={collapsed?'展开导航':'折叠导航'} aria-expanded={!collapsed} icon={collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>} onClick={()=>setCollapsed(v=>!v)}/><Breadcrumb items={[{title:'制作工作空间'},{title}]}/><span className="internal-chip">仅内部使用</span></header><main className="content" id="workspace-content" tabIndex={-1}>{children}</main></div></div>;
}
