import {useState,type ReactNode} from 'react';
import type {Me} from './dto.ts';
import {labels} from './ui.tsx';
const primary=[['dashboard','工作台','◈'],['people','人才库','◎'],['shortlists','候选清单','◇'],['works','作品库','▧'],['projects','项目','▦'],['review','审核','✓']];
const groups:Array<[string,Array<[string,string,string]>]>=[['资料工具',[['sources','资料来源','sources.read'],['media','全局素材','assets.read'],['imports','导入资料','records.write'],['exports','内部导出','data.export'],['ai','AI 辅助整理','ai.use']]],['协作与权限',[['handoffs','资料交接','records.read'],['members','成员与范围','members.manage']]],['系统维护',[['merges','人才合并','data.merge'],['deletions','删除任务','data.delete'],['catalog','分类字典','catalog.manage'],['audit','操作记录','audit.read']]]];
export function AppShell({me,active,onNavigate,children}:{me:Me;active:string;onNavigate:(key:string)=>void;children:ReactNode}){
 const management=groups.some(([,items])=>items.some(i=>i[0]===active)),[mobile,setMobile]=useState(false);
 const navigate=(key:string)=>{onNavigate(key);setMobile(false);};
 const title=primary.find(p=>p[0]===active)?.[1]??groups.flatMap(([,items])=>items).find(i=>i[0]===active)?.[1]??'账号设置';
 return <div className="shell ux-shell"><a className="skip-link" href="#workspace-content">跳到工作内容</a><aside className={'sidebar '+(mobile?'is-open':'')} aria-label="工作空间导航"><div className="brand">ONCE<span>内部制作资源</span></div><div className="workspace-label"><i/>{me.workspaceName??'内部工作空间'}</div><nav aria-label="日常业务">{primary.filter(p=>p[0]!=='review'||me.permissions.includes('talent.review')||me.permissions.includes('sources.review')||me.permissions.includes('sources.write')).map(([key,name,icon])=><button key={key} aria-current={active===key?'page':undefined} className={active===key?'selected':''} onClick={()=>navigate(key!)}><span className="nav-icon" aria-hidden="true">{icon}</span>{name}</button>)}</nav><details className="management-nav" open={management||undefined}><summary>管理与设置</summary><nav aria-label="管理与设置">{groups.map(([group,items])=><div className="nav-group" key={group}><small>{group}</small>{items.filter(i=>me.permissions.includes(i[2])||i[0]==='exports'&&me.permissions.includes('sources.review')||i[0]==='ai'&&me.permissions.includes('sources.review')).map(([key,name])=><button key={key} className={active===key?'selected':''} onClick={()=>navigate(key)}>{name}</button>)}</div>)}</nav></details><div className="sidebar-foot"><div className="avatar">{me.displayName.slice(0,1)}</div><div><strong>{me.displayName}</strong><small>{labels[me.role]}</small></div><button aria-label="账号设置" className="account-button" onClick={()=>navigate('account')}>⚙</button></div></aside><div className="main"><header className="topbar"><button className="mobile-menu" aria-label={mobile?'收起导航':'打开导航'} aria-expanded={mobile} onClick={()=>setMobile(v=>!v)}>☰</button><span>工作空间 / {title}</span><span className="internal-chip">仅内部使用</span></header><main className="content" id="workspace-content" tabIndex={-1}>{children}</main></div></div>;
}
