import {AdminTable,AdminForm} from './foundation/patterns.tsx';
import {useState} from 'react';
import {call,read,ApiError} from './api.ts';
import type {Me,Source,Receipt} from './dto.ts';
import {Modal,Field,ErrorBox,Submit,useAction,useLoad} from './ui.tsx';
export function SourceTextForm({me,source,onClose,onSaved}:{me:Me;source?:Source;onClose:()=>void;onSaved:()=>void}){
 const [title,setTitle]=useState(source?.title??''),[provider,setProvider]=useState(source?.providerClaim??''),[text,setText]=useState(source?.textPayload??''),[basis,setBasis]=useState(''),[mode,setMode]=useState<'TEMP_ORGANIZE'|'INTERNAL_USE'>('TEMP_ORGANIZE'),[until,setUntil]=useState('');const a=useAction(),unknown=a.error instanceof ApiError&&a.error.unknownOutcome;
 return <Modal title={source?'编辑来源原文':'新增文字来源'} onClose={onClose} wide><AdminForm onSubmit={e=>{e.preventDefault();void a.run(async()=>{if(source)await call('source.update',{expectedRevision:source.revision,title,providerClaim:provider,textPayload:text},{id:source.id});else await call('source.create',{title,type:'TEXT',providerClaim:provider,textPayload:text,basisMode:mode,basisDescription:basis,...(until?{validUntil:new Date(until).toISOString()}:{})});onSaved();});}}><div className="modal-body"><ErrorBox error={a.error}/><fieldset disabled={a.busy||!!unknown}><Field label="来源标题"><input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="材料提供者说明"><input required maxLength={200} value={provider} onChange={e=>setProvider(e.target.value)}/></Field><Field label="受限原始文字" hint="仅保存有权处理的材料，最多 30000 字。AI 使用仍须另行选择任务、授权和预算。"><textarea required maxLength={30000} rows={10} value={text} onChange={e=>setText(e.target.value)}/></Field>{!source&&<><Field label="使用依据"><select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="TEMP_ORGANIZE">本人范围内临时整理（最长七天）</option>{me.permissions.includes('sources.review')&&<option value="INTERNAL_USE">已核验的内部使用</option>}</select></Field><Field label="依据说明"><textarea required minLength={4} maxLength={2000} value={basis} onChange={e=>setBasis(e.target.value)}/></Field><Field label="依据截止时点" hint="临时整理留空时为七天；内部使用必须填写真实截止时点。"><input required={mode==='INTERNAL_USE'} type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)}/></Field></>}<p>原文不会写入普通审计；修改来源版本后，旧 AI 授权和字段核验须重新核对。</p><Submit busy={a.busy}>保存来源</Submit></fieldset>{unknown&&<p>保存结果未知，请在页面上方核对原请求，暂勿重新建立来源。</p>}</div></AdminForm></Modal>;
}
type Upgrade={id:string;revision:number;rows:{index:number;personId?:string;displayName?:string;expectedPersonRevision?:number;sourceRevision?:number;state:string;reason:string|null}[]};
export function ImportUpgrade({id,onClose}:{id:string;onClose:()=>void}){
 const [version,setVersion]=useState(0),[selected,setSelected]=useState<number[]>([]),[ack,setAck]=useState(false),[saved,setSaved]=useState(false);const load=useLoad(()=>read<Upgrade>('import.upgradePreview',{id}),id+':'+version),a=useAction();const unknown=a.error instanceof ApiError&&a.error.unknownOutcome;
 const labels:Record<string,string>={READY:'可补齐',COMPLETE:'已经完整',REVIEW_REQUIRED:'须人工核对',BLOCKED:'当前不可处理'};
 return <Modal title="旧导入专业档案补齐" onClose={onClose} wide><div className="modal-body"><ErrorBox error={a.error??load.error}/><p>保留原人才 ID、来源和导入检查点。只为尚未建立专业档案的旧记录补齐；已有改动不会被覆盖。每次最多 20 行。</p>{saved&&<p className="success">本次补齐已保存，请核对刷新后的状态。</p>}<button onClick={()=>{setSelected([]);setSaved(false);setVersion(v=>v+1);}}>重新读取预览</button><AdminForm onSubmit={e=>{e.preventDefault();void a.run(async()=>{if(!load.data)return;await call<'import.upgrade',Receipt>('import.upgrade',{expectedRevision:load.data.revision,confirm:ack,entries:load.data.rows.filter(r=>selected.includes(r.index)&&r.state==='READY').map(r=>({index:r.index,personId:r.personId!,expectedPersonRevision:r.expectedPersonRevision!,sourceRevision:r.sourceRevision!}))},{id});setSaved(true);setSelected([]);setVersion(v=>v+1);});}}><fieldset disabled={a.busy||load.busy||!!unknown||saved}><AdminTable><thead><tr><th>选择</th><th>档案</th><th>核对结果</th></tr></thead><tbody>{load.data?.rows.map(r=><tr key={r.index}><td><input type="checkbox" aria-label={'选择旧导入第 '+(r.index+1)+' 行'} disabled={r.state!=='READY'||selected.length>=20&&!selected.includes(r.index)} checked={selected.includes(r.index)} onChange={e=>setSelected(e.target.checked?[...selected,r.index]:selected.filter(i=>i!==r.index))}/></td><td>{r.displayName??'原导入第 '+(r.index+1)+' 行'}</td><td>{labels[r.state]}{r.reason&&<small>{r.reason}</small>}</td></tr>)}</tbody></AdminTable><label><input type="checkbox" required checked={ack} onChange={e=>setAck(e.target.checked)}/>已核对所选记录及其原有来源，确认补齐专业档案。</label><Submit busy={a.busy} disabled={!selected.length}>补齐所选 {selected.length} 行</Submit></fieldset></AdminForm></div></Modal>;
}
