import {useState} from 'react';
import type {Inputs} from './generated/requests.ts';
export type CollectionPlan=Inputs['td2.collection.save']['collection'];
export type CollectionAsset={id:string;fileName:string;mime:string;referenceKind?:CollectionPlan['items'][number]['referenceKind']};
export const collectionLabels:Record<CollectionPlan['collectionTypeCode'],string>={MODEL_CARD:'模卡',POLAROIDS:'素颜照',PORTFOLIO:'作品集',SHOWREEL:'Showreel',INTRO_VIDEO:'介绍视频',OTHER:'其他素材'};
export const collectionTagLabels:Record<string,string>={FASHION:'时尚',BEAUTY:'美妆',COMMERCIAL:'商业',LINGERIE:'内衣',RUNWAY:'走秀',LIFESTYLE:'生活方式',INDUSTRIAL:'工业',PRODUCT:'产品'};
export const blankCollection=():CollectionPlan=>({clientItemKey:'collection_'+crypto.randomUUID().slice(0,8),targetCollectionId:null,expectedCollectionRevision:null,personRoleId:null,collectionTypeCode:'MODEL_CARD',title:'我的模卡',isCurrent:false,coverAssetId:null,tagCodes:[],items:[]});
export function CollectionMedia({asset,base}:{asset:CollectionAsset;base:string}){return asset.mime==='video/mp4'?<video controls preload="metadata" src={base+asset.id+'/playback'}/>:asset.mime==='application/pdf'?<a className="collection-pdf" href={base+asset.id+'/attachment'} target="_blank" rel="noreferrer">PDF 附件 · {asset.fileName}</a>:<img loading="lazy" src={base+asset.id+'/preview'} alt={asset.fileName}/>;}
export function CollectionPlanEditor({plan,onChange,assets,roles,base,disabled}:{plan:CollectionPlan;onChange:(p:CollectionPlan)=>void;assets:CollectionAsset[];roles:Array<{id:string;label:string}>;base:string;disabled:boolean}){
 const [choice,setChoice]=useState('');const set=(value:Partial<CollectionPlan>)=>onChange({...plan,...value});
 const available=assets.filter(a=>!plan.items.some(i=>i.assetId===a.id));
 const move=(index:number,delta:number)=>{const items=[...plan.items];[items[index],items[index+delta]]=[items[index+delta]!,items[index]!];set({items});};
 return <fieldset className="collection-editor" disabled={disabled}><div className="form-grid"><label>集合类型<select aria-label="集合类型" value={plan.collectionTypeCode} onChange={e=>set({collectionTypeCode:e.target.value as CollectionPlan['collectionTypeCode']})}>{Object.entries(collectionLabels).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><label>集合名称<input value={plan.title} maxLength={200} required onChange={e=>set({title:e.target.value})}/></label><label>所属职业<select aria-label="所属职业" value={plan.personRoleId??''} disabled={!!plan.targetCollectionId} onChange={e=>set({personRoleId:e.target.value||null})}><option value="">人物通用素材</option>{roles.map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select></label><label className="check-chip"><input type="checkbox" checked={plan.isCurrent} onChange={e=>set({isCurrent:e.target.checked})}/>设为该职业的当前版本</label></div><p className="muted">集合封面由您明确选择，不会替换人物封面。模卡可附 PDF，封面仍须选照片。移出仅解除集合关系，不删除原件。</p><div className="check-grid" aria-label="集合内容标签">{Object.entries(collectionTagLabels).map(([code,label])=><label className="check-chip" key={code}><input type="checkbox" checked={plan.tagCodes.includes(code as CollectionPlan['tagCodes'][number])} onChange={e=>set({tagCodes:e.target.checked?[...plan.tagCodes,code as CollectionPlan['tagCodes'][number]]:plan.tagCodes.filter(t=>t!==code)})}/>{label}</label>)}</div>
 <div className="detail-actions"><label>选择可用素材<select aria-label="选择可用素材" value={choice} onChange={e=>setChoice(e.target.value)}><option value="">请选择</option>{available.map(a=><option value={a.id} key={a.id}>{a.fileName}{a.referenceKind==='EXISTING_ADOPTED_ASSET_REFERENCE'?' · 已采纳原件':''}</option>)}</select></label><button type="button" disabled={!choice} onClick={()=>{const asset=available.find(a=>a.id===choice);if(asset)set({items:[...plan.items,{assetId:asset.id,referenceKind:asset.referenceKind??'EXISTING_ADOPTED_ASSET_REFERENCE',caption:'',featured:false}]});setChoice('');}}>加入集合</button></div>
 <ol className="collection-grid">{plan.items.map((item,index)=>{const asset=assets.find(a=>a.id===item.assetId);return <li className="collection-frame" key={item.assetId}>{asset?<CollectionMedia asset={asset} base={base}/>:<p>此素材当前不可用，请重新核对。</p>}<div className="collection-caption"><strong>{index+1}. {asset?.fileName??'素材不可用'}</strong><label>素材说明<input maxLength={1000} value={item.caption} onChange={e=>set({items:plan.items.map((i,n)=>n===index?{...i,caption:e.target.value}:i)})}/></label><label><input type="checkbox" checked={item.featured} onChange={e=>set({items:plan.items.map((i,n)=>n===index?{...i,featured:e.target.checked}:i)})}/>精选</label>{asset?.mime.startsWith('image/')&&<label><input type="radio" name={'cover-'+plan.clientItemKey} checked={plan.coverAssetId===item.assetId} onChange={()=>set({coverAssetId:item.assetId})}/>集合封面</label>}<div className="detail-actions"><button type="button" disabled={index===0} aria-label={'上移 '+(asset?.fileName??'素材')} onClick={()=>move(index,-1)}>上移</button><button type="button" disabled={index===plan.items.length-1} aria-label={'下移 '+(asset?.fileName??'素材')} onClick={()=>move(index,1)}>下移</button><button type="button" onClick={()=>set({items:plan.items.filter(i=>i.assetId!==item.assetId),coverAssetId:plan.coverAssetId===item.assetId?null:plan.coverAssetId})}>移出集合</button></div></div></li>;})}</ol>{!plan.items.length&&<p className="empty">先上传并等待处理完成，再把素材加入集合。</p>}</fieldset>;
}
export type CollectionView={id:string;revision:number;title:string;collectionTypeCode:CollectionPlan['collectionTypeCode'];personRoleId:string|null;isCurrent:boolean;coverAssetId:string|null;tagCodes:string[];items:Array<{assetId:string;caption:string;featured:boolean;asset:CollectionAsset}>};
export function CollectionGallery({collections,base,onEdit}:{collections:CollectionView[];base:string;onEdit?:(c:CollectionView)=>void}){return <div className="collection-gallery">{collections.map(c=><section key={c.id} className="collection-section"><header><p className="eyebrow">{collectionLabels[c.collectionTypeCode]}{c.isCurrent?' · 当前版本':''}</p><h3>{c.title}</h3><p>{c.tagCodes.map(t=>collectionTagLabels[t]??t).join(' · ')}</p>{onEdit&&<button onClick={()=>onEdit(c)}>整理此集合</button>}</header>{c.coverAssetId&&c.items.some(i=>i.assetId===c.coverAssetId)&&<img className="collection-cover" src={base+c.coverAssetId+'/preview'} alt={c.title+'封面'}/>}<div className="collection-grid">{c.items.map(i=><figure className="collection-frame" key={i.assetId}><CollectionMedia asset={{...i.asset,id:i.assetId}} base={base}/><figcaption>{i.caption||i.asset.fileName}{i.featured?' · 精选':''}<small>来源当前可用</small></figcaption></figure>)}</div>{!c.items.length&&<p>暂无当前可见素材。来源撤回或过期的素材不展示。</p>}</section>)}</div>;}
export function CollectionDiff({plan,before,assets=[]}:{plan:CollectionPlan;before?:CollectionView|null;assets?:CollectionAsset[]}){
 const old=before?.items??[],name=(id:string)=>assets.find(a=>a.id===id)?.fileName??old.find(i=>i.assetId===id)?.asset.fileName??'当前不可读素材';
 const added=plan.items.filter(i=>!old.some(o=>o.assetId===i.assetId)),removed=old.filter(o=>!plan.items.some(i=>i.assetId===o.assetId));
 return <section className="collection-diff"><h4>{collectionLabels[plan.collectionTypeCode]} · {plan.title}</h4><p>{before?'修改已有集合':'新增集合'}{plan.isCurrent?'，设为当前版本':''}</p><p>新增：{added.map(i=>name(i.assetId)).join('、')||'无'}</p><p>移出：{removed.map(i=>name(i.assetId)).join('、')||'无'}</p><p>原顺序：{old.map(i=>name(i.assetId)).join(' → ')||'无'}</p><p>新顺序：{plan.items.map(i=>name(i.assetId)).join(' → ')||'无'}</p><p>封面：{before?.coverAssetId?name(before.coverAssetId):'未指定'} → {plan.coverAssetId?name(plan.coverAssetId):'未指定'}</p><p>标签：{before?.tagCodes.map(t=>collectionTagLabels[t]??t).join('、')||'无'} → {plan.tagCodes.map(t=>collectionTagLabels[t]).join('、')||'无'}</p><ol>{plan.items.map(i=><li key={i.assetId}>{name(i.assetId)} · {i.caption||'未填写说明'} · {i.referenceKind==='EXISTING_ADOPTED_ASSET_REFERENCE'?'复用已采纳原件':'本次新素材'}{i.featured?' · 精选':''}</li>)}</ol></section>;
}
