import {useState} from 'react';
import {call,read} from './api.ts';
import {useLoad,useAction,ErrorBox,Field} from './ui.tsx';
import type {Scope} from './dto.ts';
type Batch={id:string;revision:number;state:string;mode:'NEW'|'EXISTING';principalName:string;externalSubmissionKey:string;sourceDeclaration:{title:string;providerClaim:string;materialDescription:string};proposedPersonId:string|null;rebaseRequired:boolean;target:{displayName:string;scopeId:string}|null;items:Array<{clientItemKey:string;kind:string;values:Record<string,unknown>;dependencyGroup:string;dependsOn:string[]}>};
const labels:Record<string,string>={displayName:'姓名',aliases:'别名',intro:'简介',roleCode:'职业',genderCode:'性别',nationalityCodes:'国籍',castingMarketCode:'模特业务分类',experienceCode:'从业类型',heightCm:'身高（cm）',measuredOn:'量尺日期',datePrecision:'日期精度',birthPrecision:'出生精度',birthYear:'出生年份',birthDate:'出生日期',minAgeYears:'年龄下界',maxAgeYears:'年龄上界',ageAsOfDate:'年龄声明日期'};
function candidateText(values:Record<string,unknown>){return Object.entries(values).filter(([k])=>k!=='field').map(([k,v])=>(labels[k==='value'?String(values.field):k]??k)+'：'+(v===null?'未知':Array.isArray(v)?(v.join(' / ')||'无'):String(v))).join('；');}
export function IngestionReviewInbox(){const [tick,setTick]=useState(0),[batch,setBatch]=useState<Batch|null>(null),[accepted,setAccepted]=useState<string[]>([]),[basis,setBasis]=useState(''),[scope,setScope]=useState(''),[until,setUntil]=useState(''),[reason,setReason]=useState('');const a=useAction(),list=useLoad(()=>read<{items:Batch[]}>('ingestionReview.list'),tick),scopes=useLoad(()=>read<{items:Scope[]}>('scope.list'),'ingestion-scopes');
 async function decide(reject:boolean){if(!batch)return;await call('ingestionReview.review',{expectedRevision:batch.revision,acceptedKeys:reject?[]:accepted,decision:reject?'REJECT':batch.mode==='NEW'?'CREATE_NEW':'LINK_EXISTING',...(!reject?(batch.mode==='NEW'?{formalScopeId:scope}:{targetPersonId:batch.proposedPersonId!}):{}),reviewBasis:basis,validUntil:until?new Date(until+'T00:00:00Z').toISOString():new Date(Date.now()+30*86400000).toISOString(),publicReason:reason},{id:batch.id});setBatch(null);setTick(t=>t+1);}
 return <section className="panel padded"><h2>外部 Agent 文字投稿</h2><p>材料提供者提出候选事实。内部审核明确建立或关联人物，并决定正式范围及有期限的使用依据。</p><ErrorBox error={a.error??list.error??scopes.error}/>{list.data?.items.filter(s=>s.state==='SUBMITTED').map(s=><button key={s.id} onClick={()=>void a.run(async()=>{const current=await read<Batch>('ingestionReview.get',{id:s.id});setBatch(current);setAccepted(current.items.map(i=>i.clientItemKey));setBasis('');setScope('');setUntil('');setReason('');})}>审核 {s.principalName} · {s.sourceDeclaration.title} · {s.mode==='NEW'?'建议新建':'建议关联已有档案'}</button>)}{batch&&<div role="region" aria-label="Agent 投稿审核"><h3>{batch.principalName} · {batch.sourceDeclaration.title}</h3><p>提供者声明：{batch.sourceDeclaration.providerClaim}</p><p>材料说明：{batch.sourceDeclaration.materialDescription}</p><p>外部批次：{batch.externalSubmissionKey}</p>{batch.mode==='EXISTING'&&<p>建议关联：{batch.target?.displayName??'目标不可见'}；{batch.rebaseRequired?'目标基线变化或无正式范围权限，须重新提交':'目标基线一致；审核将关联该精确档案'}</p>}{batch.items.map(i=><article key={i.clientItemKey}><label><input type="checkbox" checked={accepted.includes(i.clientItemKey)} onChange={e=>setAccepted(old=>e.target.checked?[...old,i.clientItemKey]:old.filter(k=>k!==i.clientItemKey))}/>{candidateText(i.values)}</label><p>依赖组：{i.dependencyGroup}；依赖：{i.dependsOn.join('、')||'无'}</p></article>)}{batch.mode==='NEW'&&<Field label="正式人才范围（由审核人明确选择）"><select value={scope} onChange={e=>setScope(e.target.value)}><option value="">请选择正式范围</option>{scopes.data?.items.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>}<Field label="内部使用审核依据"><textarea value={basis} minLength={4} maxLength={2000} onChange={e=>setBasis(e.target.value)}/></Field><Field label="使用截止日期"><input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></Field><Field label="给提供者的处理说明"><textarea value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></Field><button disabled={a.busy||basis.trim().length<4||!until||!accepted.length||batch.rebaseRequired||(batch.mode==='NEW'&&!scope)} onClick={()=>void a.run(()=>decide(false))}>{batch.mode==='NEW'?'审核并建立正式人物':'审核并关联该人物'}</button><button disabled={a.busy||basis.trim().length<4} onClick={()=>void a.run(()=>decide(true))}>拒绝本批候选事实</button></div>}</section>;
}
