import {useState} from 'react';
import {call,read} from './api.ts';
import {useLoad,useAction,ErrorBox,Modal} from './ui.tsx';
import type {TalentDetail} from './talent-dto.ts';
import type {Source,Page} from './dto.ts';
import {outcomeUnknown} from './talent-edit.tsx';
import {blankCollection,CollectionGallery,CollectionPlanEditor,type CollectionPlan,type CollectionView,type CollectionAsset} from './collection-ui.tsx';
export function InternalCollections({detail,onSaved}:{detail:TalentDetail;onSaved:()=>void}){
 const [plan,setPlan]=useState<CollectionPlan|null>(null),[sourceId,setSource]=useState(''),[page,setPage]=useState(1),[pool,setPool]=useState<CollectionAsset[]>([]);const action=useAction(),frozen=action.busy||outcomeUnknown(action.error);
 const sources=useLoad(()=>plan?read<Page<Source>>('source.list',{}, {pageSize:'100'}):Promise.resolve(null),String(!!plan));
 const assets=useLoad(async()=>{if(!plan)return null;const result=await read<Page<CollectionAsset>>('asset.list',{}, {personId:detail.id,page:String(page),pageSize:'100'});setPool(old=>[...old.filter(a=>!result.items.some(b=>b.id===a.id)),...result.items]);return result;},detail.id+':'+!!plan+':'+page);
 const collections:CollectionView[]=detail.facts.mediaCollections.filter(c=>c.usable).map(c=>({id:c.id,revision:c.revision,title:String(c.title),collectionTypeCode:c.collectionTypeCode as CollectionPlan['collectionTypeCode'],personRoleId:c.personRoleId as string|null,isCurrent:!!c.isCurrent,coverAssetId:c.coverAssetId as string|null,tagCodes:detail.facts.mediaCollectionTags.filter(t=>t.usable&&t.collectionId===c.id).map(t=>String(t.tagCode)),items:c.items as CollectionView['items']}));
 const start=(c?:CollectionView)=>{setPlan(c?{clientItemKey:'collection_'+c.id.slice(0,8),targetCollectionId:c.id,expectedCollectionRevision:c.revision,personRoleId:c.personRoleId,collectionTypeCode:c.collectionTypeCode,title:c.title,isCurrent:c.isCurrent,coverAssetId:c.coverAssetId,tagCodes:c.tagCodes as CollectionPlan['tagCodes'],items:c.items.map(i=>({assetId:i.assetId,referenceKind:'EXISTING_ADOPTED_ASSET_REFERENCE',caption:i.caption,featured:i.featured}))}:blankCollection());setSource('');setPool(c?.items.map(i=>({...i.asset,id:i.assetId}))??[]);};
 return <section className="panel padded" aria-label="媒体集合"><h2>模卡与媒体资料</h2><p>按用途整理正式媒体。作品集可直接使用照片和视频，无需先建立作品案例。</p>{detail.canEdit&&<button onClick={()=>start()}>新建媒体集合</button>}<CollectionGallery collections={collections} base="/api/v1/assets/" onEdit={detail.canEdit?start:undefined}/>{!collections.length&&<p>暂无可用集合。</p>}{plan&&<Modal title="整理媒体集合" onClose={()=>{if(!frozen)setPlan(null);}} wide><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{const source=sources.data?.items.find(s=>s.id===sourceId);if(!source)throw new Error('请选择独立内部来源');await call('td2.collection.save',{schemaVersion:'once-talent-v2.1.0',expectedPersonRevision:detail.revision,sourceId,sourceRevision:source.revision,collection:plan},{id:detail.id});setPlan(null);onSaved();});}}><div className="modal-body"><ErrorBox error={action.error??sources.error??assets.error}/><label>本次整理的独立内部来源<select required disabled={frozen} value={sourceId} onChange={e=>setSource(e.target.value)}><option value="">请选择当前有效来源</option>{sources.data?.items.filter(s=>s.current&&s.allowsInternalAuthoring!==false).map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><CollectionPlanEditor plan={plan} onChange={setPlan} assets={pool} roles={detail.facts.personRoles.filter(r=>r.usable).map(r=>({id:r.id,label:({model:'模特',actor:'演员',kol:'达人'} as Record<string,string>)[String(r.roleCode)]??String(r.roleCode)}))} base="/api/v1/assets/" disabled={frozen}/>{assets.data&&pool.length<assets.data.total&&<button type="button" onClick={()=>setPage(p=>p+1)}>加载更多可用素材</button>}</div><footer className="modal-footer"><button type="button" disabled={frozen} onClick={()=>setPlan(null)}>取消</button><button className="primary" disabled={action.busy}>{outcomeUnknown(action.error)?'核对原提交':'保存正式集合'}</button></footer></form></Modal>}</section>;
}
