import {useState} from 'react';
import {call,read} from './api.ts';
import type {Page,Source} from './dto.ts';
import {ErrorBox,Field,Modal,Pager,useAction,useLoad} from './ui.tsx';
import {outcomeUnknown} from './talent-edit.tsx';
type Kind='PERSON'|'WORK'|'PROJECT';
interface LocaleText {id:string;revision:number;subjectKind:Kind;subjectId:string;subjectRevision:number;locale:'zh'|'en';text:string;state:'DRAFT'|'REVIEWED';needsReview:boolean;textRestricted:boolean;canEdit:boolean;history:Array<{id:string;revision:number;personId:string;text:string;reviewedAt:string|null}>;hasImportedBasis:boolean;originalReview:{reviewedAt:string;matchesCurrentText:boolean}|null;sources:Array<{id:string;revision:number}>;note:string;}
const language=(locale:string)=>locale==='zh'?'中文':'英文';
export function LocaleWorkspace({kind,id,canWrite,onClose}:{kind:Kind;id:string;canWrite:boolean;onClose:()=>void}){
 const [tick,setTick]=useState(0),[editing,setEditing]=useState<LocaleText|'new'|null>(null);
 const load=useLoad(()=>read<Page<LocaleText>>('locale.list',{}, {subjectKind:kind,subjectId:id,pageSize:'20'}),kind+id+tick);
 if(editing)return <LocaleEditor kind={kind} id={id} existing={editing==='new'?undefined:editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);setTick(x=>x+1);}}/>;
 return <Modal title="内部中英文文本" onClose={onClose} wide><div className="modal-body"><p className="muted">用于内部资料整理。每份文本保留对应档案和依据来源；人工复核不代表原事实已获核验。</p><ErrorBox error={load.error}/>{load.busy?<p>正在核对文本和当前访问范围…</p>:load.data&&<>{!load.data.items.length&&<p>暂无当前可见的语言文本。</p>}{load.data.items.map(row=><article className="talent-fact" key={row.id}><div className="panel-heading"><h3>{language(row.locale)}</h3><span>{row.textRestricted?'依据范围变化，正文受限':row.needsReview?'待复核':'已人工复核'}</span></div>{row.hasImportedBasis&&<p className="muted">此文本由内部迁移重建，原依据记录已保留。{row.state==='REVIEWED'?'本文已由当前环境的成员重新复核。':row.originalReview&&!row.originalReview.matchesCurrentText?'原复核针对较早正文，不能当作本次正文的确认。':'当前环境的复核需由成员另行确认。'}</p>}{row.textRestricted?<p className="notice">请重新核对原资料与当前可用来源，再填写文本。</p>:<p className="pre-line">{row.text}</p>}{row.history.length>0&&<details><summary>合并保留原文（{row.history.length}）</summary><p className="muted">以下是合并时保留的原文，只供核对，不代表当前正文已经复核。</p>{row.history.map(h=><div className="talent-fact" key={h.id+':'+h.revision}><p>原档案：{h.personId}</p><p className="pre-line">{h.text}</p>{h.reviewedAt&&<p className="muted">原复核时间：{h.reviewedAt}</p>}</div>)}</details>}{row.canEdit&&<button onClick={()=>setEditing(row)}>编辑并复核{language(row.locale)}</button>}</article>)}{canWrite&&load.data.items.length<2&&<button className="primary" onClick={()=>setEditing('new')}>新增语言文本</button>}</>}</div><footer className="modal-footer"><button onClick={onClose}>返回资料</button></footer></Modal>;
}
function LocaleEditor({kind,id,existing,onClose,onSaved}:{kind:Kind;id:string;existing?:LocaleText;onClose:()=>void;onSaved:()=>void}){
 const rootOp=kind==='PERSON'?'person.get':kind==='WORK'?'work.get':'project.get';
 const load=useLoad(async()=>({root:await read<{revision:number;status:string}>(rootOp,{id}),sources:await Promise.all((existing?.sources??[]).map(s=>read<Source>('source.get',{id:s.id})))}),id+(existing?.id??'new'));
 if(load.data&&!load.busy)return <LocaleForm kind={kind} id={id} existing={existing} root={load.data.root} initialSources={load.data.sources} onClose={onClose} onSaved={onSaved}/>;
 return <Modal title="内部文本" onClose={onClose}><div className="modal-body"><ErrorBox error={load.error}/>{load.busy?<p>正在核对档案与依据…</p>:<button onClick={onClose}>返回文本列表</button>}</div></Modal>;
}
function LocaleForm({kind,id,existing,root,initialSources,onClose,onSaved}:{kind:Kind;id:string;existing?:LocaleText;root:{revision:number;status:string};initialSources:Source[];onClose:()=>void;onSaved:()=>void}){
 const [locale,setLocale]=useState<'zh'|'en'>(existing?.locale??'en'),[text,setText]=useState(existing?.text??''),[confirmed,setConfirmed]=useState(false),[sources,setSources]=useState(initialSources),[page,setPage]=useState(1);
 const action=useAction(),unknown=outcomeUnknown(action.error),frozen=action.busy||unknown;
 const listing=useLoad(()=>read<Page<Source>>('source.list',{}, {page:String(page),pageSize:'10'}),page);
 return <Modal title={(existing?'编辑并复核':'新增')+'内部文本'} onClose={()=>{if(!frozen)onClose();}} wide><div className="modal-body"><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{const content={text,sourceRefs:sources.map(s=>({id:s.id,expectedRevision:s.revision})),expectedSubjectRevision:root.revision,confirmCurrentBasis:confirmed};if(existing)await call('locale.update',{...content,expectedRevision:existing.revision},{id:existing.id});else await call('locale.create',{...content,subjectKind:kind,subjectId:id,locale});onSaved();});}}><ErrorBox error={action.error}/>{unknown&&<p className="notice">保存结果未知，内容已锁定。请原样重试这次提交。</p>}{existing?.textRestricted&&<p className="notice">旧正文因依据范围变化受到限制，请根据当前可用资料重新填写。</p>}<fieldset disabled={frozen||root.status==='ARCHIVED'}><Field label="文本语言"><select value={locale} disabled={!!existing} onChange={e=>setLocale(e.target.value as 'zh'|'en')}><option value="zh">中文</option><option value="en">英文</option></select></Field><Field label="内部文本"><textarea required maxLength={10000} rows={9} value={text} onChange={e=>setText(e.target.value)}/></Field><h3>明确依据来源</h3><p>请选择实际用于这份文本的来源，最多 20 项。</p>{sources.map(s=><div className="wp-row" key={s.id}><div><strong>{s.title}</strong><p>{s.basisDescription}</p></div><button type="button" onClick={()=>setSources(items=>items.filter(i=>i.id!==s.id))}>移除依据</button></div>)}<ErrorBox error={listing.error}/>{listing.busy?<p>正在查询来源…</p>:listing.data?.items.filter(s=>s.current).map(s=><button type="button" key={s.id} disabled={sources.some(i=>i.id===s.id)||sources.length>=20} onClick={()=>setSources(items=>[...items,s])}>选择依据：{s.title}</button>)}{listing.data&&<Pager page={page} pageSize={10} total={listing.data.total} setPage={setPage}/>}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我已按当前档案和所选依据复核本文</label><p className="muted">未勾选时保存为待复核草稿。此项确认不会改变原事实的核验状态。</p></fieldset><footer className="modal-footer"><button type="button" disabled={frozen} onClick={onClose}>返回文本列表</button><button type="submit" className="primary" disabled={action.busy||!text.trim()||!sources.length||root.status==='ARCHIVED'}>{unknown?'原样重试保存':'保存内部文本'}</button></footer></form></div></Modal>;
}
