import {TalentSourceChoice,TalentRelationChoice,outcomeUnknown} from './talent-edit.tsx';
import {useState} from 'react';
import {read,call} from './api.ts';
import type {Me,CatalogItem,Page,Source} from './dto.ts';
import {useLoad,PageTitle,ErrorBox,Pager,Tag,Empty,Modal,Field,useAction} from './ui.tsx';
import {TalentRegistryCreate} from './talent-registry.tsx';
export function OrganizationWorkspace({me,catalog}:{me:Me;catalog:CatalogItem[]}){
 const [brandEdit,setBrandEdit]=useState<BrandRow|null|undefined>(undefined);
 const [kind,setKind]=useState<'organization'|'brand'>('organization'),[page,setPage]=useState(1),[tick,setTick]=useState(0),[create,setCreate]=useState(false);
 const load=useLoad(()=>read<Page<BrandRow>>(kind==='organization'?'td2.organization.list':'brand.list',{}, {page:String(page),pageSize:'20'}),kind+page+':'+tick);
 return <><PageTitle overline="" title="机构与品牌" description="查看当前可访问的机构和品牌。项目中的客户与品牌关联仍在项目详情维护。" action={me.permissions.includes('records.write')?<div className="detail-actions"><button onClick={()=>setCreate(true)}>登记机构</button><button onClick={()=>setBrandEdit(null)}>登记品牌</button></div>:undefined}/><div className="record-tabs">{(['organization','brand'] as const).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setPage(1);}}>{k==='organization'?'机构':'品牌'}</button>)}</div><ErrorBox error={load.error}/>{load.busy?<p>正在读取…</p>:load.data&&<><section className="panel"><div className="simple-list">{load.data.items.map(r=><div key={r.id}><strong>{r.name}</strong><Tag value={r.status}/>{kind==='brand'&&me.permissions.includes('records.write')&&<button onClick={()=>setBrandEdit(r)}>编辑品牌</button>}</div>)}</div>{!load.data.items.length&&<Empty title="暂无当前可见记录"/>}</section><Pager page={page} pageSize={20} total={load.data.total} setPage={setPage}/></>}{brandEdit!==undefined&&<BrandForm existing={brandEdit??undefined} onClose={()=>setBrandEdit(undefined)} onSaved={()=>{setBrandEdit(undefined);setTick(t=>t+1);}}/>}{create&&<TalentRegistryCreate mode="organization" catalog={catalog} onClose={()=>setCreate(false)} onSaved={()=>{setCreate(false);setTick(t=>t+1);}}/>}</>;
}

interface BrandRow{id:string;name:string;status:'ACTIVE'|'ARCHIVED';revision:number;sourceId:string;organization:{id:string;name:string}|null;}
function BrandForm({existing,onClose,onSaved}:{existing?:BrandRow;onClose:()=>void;onSaved:()=>void}){
 const [name,setName]=useState(existing?.name??''),[status,setStatus]=useState(existing?.status??'ACTIVE'),[organization,setOrganization]=useState(existing?.organization?.id??''),[organizationName,setOrganizationName]=useState(existing?.organization?.name??''),[changed,setChanged]=useState(false),[source,setSource]=useState<Source|null>(null),action=useAction();
 const freeze=action.busy||outcomeUnknown(action.error);
 const close=()=>{if(!freeze&&(!(name!== (existing?.name??'')||status!==(existing?.status??'ACTIVE')||changed||source)||confirm('当前修改尚未保存，确认关闭？')))onClose();};
 return <Modal title={existing?'编辑品牌':'登记品牌'} onClose={close}><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{if(existing)await call('brand.patch',{expectedRevision:existing.revision,...(name!==existing.name?{name}:{}),...(status!==existing.status?{status}:{}),...(changed?{organizationId:organization||null}:{})},{id:existing.id});else {if(!source)return;await call('brand.create',{sourceId:source.id,sourceRevision:source.revision,name,organizationId:organization||null});}onSaved();});}}><div className="modal-body"><ErrorBox error={action.error}/><fieldset disabled={freeze}><Field label="品牌名称 *"><input value={name} required maxLength={160} onChange={e=>setName(e.target.value)}/></Field>{existing&&<Field label="状态"><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="ACTIVE">使用中</option><option value="ARCHIVED">已归档</option></select></Field>}<p>所属机构：{organizationName||'未确认或当前不可见'}</p><TalentRelationChoice kind="organization" value={organization} onChange={(id,label)=>{setOrganization(id);setOrganizationName(label);setChanged(true);}}/><button type="button" onClick={()=>{setOrganization('');setOrganizationName('');setChanged(true);}}>明确清除所属机构</button></fieldset>{!existing&&<TalentSourceChoice value={source} onChange={setSource} disabled={freeze}/>}</div><footer className="modal-footer"><button type="button" disabled={freeze} onClick={close}>取消</button><button type="submit" className="primary" disabled={action.busy||(!existing&&!source)||(!!existing&&name===existing.name&&status===existing.status&&!changed)}>{outcomeUnknown(action.error)?'核对原提交':'保存品牌'}</button></footer></form></Modal>;
}
