import {useEffect,useState} from 'react';
import type {TalentAccountMe} from './dto.ts';
import {blankCollection,CollectionPlanEditor,CollectionGallery,type CollectionPlan,type CollectionAsset,type CollectionView} from './collection-ui.tsx';
export type PortalCollections={collections:CollectionView[];assets:Array<CollectionAsset&{personRoleId:string|null}>;roles:Array<{id:string;roleCode:string}>};
export async function readPortalCollections(me:TalentAccountMe,personId:string){const r=await fetch('/api/v1/portal/profiles/'+personId+'/collections',{credentials:'same-origin',headers:{'X-ONCE-Talent-Account':me.talentAccountId}});if(!r.ok)throw new Error('当前账号的媒体资料不可访问，请重新核对授权。');return await r.json() as PortalCollections;}
export function PortalCollectionGallery({me,personId,version}:{me:TalentAccountMe;personId:string;version:string}){const [data,setData]=useState<PortalCollections|null>(null),[error,setError]=useState('');useEffect(()=>{let live=true;setData(null);readPortalCollections(me,personId).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[me.talentAccountId,personId,version]);return <section aria-label="本人已采纳集合"><h3>已采纳的媒体资料</h3>{error&&<p role="alert">{error}</p>}{data&&<CollectionGallery collections={data.collections} base={'/api/v1/portal/accounts/'+me.talentAccountId+'/assets/'}/>}</section>;}
export function PortalCollectionDraft({me,submission,command,refresh,disabled}:{me:TalentAccountMe;submission:{id:string;revision:number;personId:string|null;state:string;items:Array<{kind?:string;collection?:CollectionPlan}>;media?:Array<{id:string;fileName:string;mime:string;state:string;usageState:string|null}>};command:(path:string,body:unknown)=>Promise<unknown>;refresh:()=>Promise<void>;disabled:boolean}){
 const serverPlans=submission.items.flatMap(i=>i.kind==='COLLECTION'&&i.collection?[i.collection]:[]),serialized=JSON.stringify(serverPlans);
 const [plans,setPlans]=useState<CollectionPlan[]>(serverPlans),[formal,setFormal]=useState<PortalCollections|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{setPlans(serverPlans);},[submission.id,serialized]);
 useEffect(()=>{setFormal(null);if(submission.personId)void readPortalCollections(me,submission.personId).then(setFormal).catch(e=>setError(e.message));},[submission.id,me.talentAccountId,submission.personId]);
 const assets:CollectionAsset[]=[...(submission.media??[]).filter(m=>m.state==='READY'&&m.usageState==='STAGED').map(m=>({...m,referenceKind:'SUBMISSION_STAGED_ASSET' as const})),...(formal?.assets??[]).map(m=>({...m,referenceKind:'EXISTING_ADOPTED_ASSET_REFERENCE' as const}))];
 const base='/api/v1/portal/accounts/'+me.talentAccountId+'/assets/';
 return <section className="panel padded" aria-label="整理本人媒体集合"><h3>整理模卡与作品集</h3><p>可以使用本批新素材，或复用自己仍有权维护的已采纳原件。保存到服务器后可刷新继续；审核通过后才成为正式资料。</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{plans.map((plan,index)=><section key={plan.clientItemKey}><CollectionPlanEditor plan={plan} onChange={p=>setPlans(old=>old.map((v,n)=>n===index?p:v))} assets={assets} roles={(formal?.roles??[]).map(r=>({id:r.id,label:({model:'模特',actor:'演员',kol:'达人'} as Record<string,string>)[r.roleCode]??r.roleCode}))} base={base} disabled={disabled||busy||submission.state!=='DRAFT'}/>{submission.state==='DRAFT'&&<button disabled={disabled||busy} onClick={()=>setPlans(p=>p.filter((_,n)=>n!==index))}>移除此集合草稿</button>}</section>)}{submission.state==='DRAFT'&&<><button disabled={disabled||busy||plans.length>=10} onClick={()=>setPlans(p=>[...p,blankCollection()])}>新增媒体集合</button>{formal?.collections.length? <label>修改自己已采纳的集合<select defaultValue="" onChange={e=>{const c=formal.collections.find(c=>c.id===e.target.value);if(c&&!plans.some(p=>p.targetCollectionId===c.id))setPlans(p=>[...p,{clientItemKey:'collection_'+c.id.slice(0,8),targetCollectionId:c.id,expectedCollectionRevision:c.revision,personRoleId:c.personRoleId,collectionTypeCode:c.collectionTypeCode,title:c.title,isCurrent:c.isCurrent,coverAssetId:c.coverAssetId,tagCodes:c.tagCodes as CollectionPlan['tagCodes'],items:c.items.map(i=>({assetId:i.assetId,caption:i.caption,featured:i.featured,referenceKind:'EXISTING_ADOPTED_ASSET_REFERENCE'}))}]);}}><option value="">请选择集合</option>{formal.collections.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>:null}<button disabled={disabled||busy} className="primary" onClick={()=>{setBusy(true);setError('');void command('/submissions/'+submission.id+'/collections',{expectedRevision:submission.revision,collections:plans}).then(async()=>{await refresh();setMessage('集合草稿已保存在服务器');}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>保存集合草稿</button></>}</section>;
}
