import {useRef,useState} from 'react';
import {ApiError,call,read,inspectPending,pendingKey} from './api.ts';
import type {Inputs} from './generated/requests.ts';
import type {CatalogItem,Page,Receipt,Scope} from './dto.ts';
import type {ShortlistDetail,ShortlistSummary} from './shortlist-dto.ts';
import type {CandidateContext} from './directory-state.ts';
import {ErrorBox,Field,Modal,Pager,useAction,useLoad} from './ui.tsx';
import {CommandRecovery} from './command-recovery.tsx';
import {useUnsaved} from './unsaved.ts';
type Choice={id:string;unavailable:boolean;displayName?:string;revision?:number;legacy?:boolean;roles?:{id:string;revision:number;roleCode:string}[]};
type Summary={added:number;existing:number};
export function BatchCandidateChoice({selection,catalog,initialListId,onClose,onDone,onViewList}:{selection:CandidateContext[];catalog:CatalogItem[];initialListId?:string;onClose:()=>void;onDone:(id:string,summary:Summary)=>void;onViewList?:(id:string)=>void}){
 const [selectedList,setSelectedList]=useState(initialListId??''),[page,setPage]=useState(1),[q,setQ]=useState(''),[search,setSearch]=useState(''),[tick,setTick]=useState(0),[creating,setCreating]=useState(false),[title,setTitle]=useState(''),[scope,setScope]=useState(''),[roles,setRoles]=useState<Record<string,string>>(()=>Object.fromEntries(selection.filter(s=>!s.pendingRole&&s.personRoleId).map(s=>[s.personId,s.personRoleId!]))),[done,setDone]=useState<Summary|null>(null),[message,setMessage]=useState('');
 const action=useAction(),createAction=useAction(),snapshot=useRef<Inputs['shortlist.batchAdd']|null>(null),newListReceipt=useRef<Receipt|null>(null);
 const lists=useLoad(()=>read<Page<ShortlistSummary>>('shortlist.list',{}, {page:String(page),pageSize:'10',q:search}),page+':'+search+':'+tick);
 const list=useLoad(()=>selectedList?read<ShortlistDetail>('shortlist.get',{id:selectedList}):Promise.resolve(null),selectedList+':'+tick);
 const choices=useLoad(()=>call<'shortlist.selection',{items:Choice[]}>('shortlist.selection',{personIds:[...new Set(selection.map(s=>s.personId))]}),JSON.stringify(selection.map(s=>s.personId))+':'+tick);
 const scopes=useLoad(()=>creating?read<{items:Scope[]}>('scope.list'):Promise.resolve(null),String(creating));
 const unknown=action.error instanceof ApiError&&action.error.unknownOutcome,createUnknown=createAction.error instanceof ApiError&&createAction.error.unknownOutcome,freeze=action.busy||unknown||createAction.busy||createUnknown;
 useUnsaved(creating&&!!title&&!done,'新候选清单');
 const chosen=(p:Choice)=>p.roles?.length===1?p.roles[0]:p.roles?.find(r=>r.id===roles[p.id]);
 const duplicate=(p:Choice)=>list.data?.items.some(i=>!i.unavailable&&i.person.id===p.id&&!i.work&&(i.personRoleId??null)===(chosen(p)?.id??null))??false;
 const valid=choices.data?.items.every(p=>!p.unavailable&&(p.legacy||chosen(p)))&&!!list.data?.canEdit;
 const finish=(receipt:Receipt)=>{const summary=receipt.summary;if(!summary)throw new Error('未返回完整批次结果，请核对清单。');setDone(summary);};
 const submit=()=>void action.run(async()=>{if(!list.data||!choices.data||!valid)return;snapshot.current??={expectedRevision:list.data.revision,entries:choices.data.items.map(p=>{const role=chosen(p);return {personId:p.id,expectedPersonRevision:p.revision!,...(role?{personRoleId:role.id,personRoleRevision:role.revision}:{})};})};finish(await call<'shortlist.batchAdd',Receipt>('shortlist.batchAdd',snapshot.current,{id:selectedList}));});
 const createList=()=>void createAction.run(async()=>{newListReceipt.current??=await call<'shortlist.create',Receipt>('shortlist.create',{title,scopeId:scope});setSelectedList(newListReceipt.current.resourceId);setCreating(false);setTitle('');setTick(t=>t+1);});
 const close=()=>{if(freeze)return;if(creating&&title&&!window.confirm('清单尚未保存，放弃填写？'))return;onClose();};
 return <Modal title={done?'已加入候选清单':'加入候选清单'} onClose={close} wide>{done?<><div className="modal-body"><div className="success" role="status">{list.data?.title??'目标清单'}：新增 {done.added} 项，{done.existing} 项已在清单。</div><p>人才档案和其他清单保持原样，可继续找人。</p></div><footer className="modal-footer"><button onClick={()=>onDone(selectedList,done)}>继续找人</button>{onViewList&&<button className="primary" onClick={()=>{onDone(selectedList,done);onViewList(selectedList);}}>查看清单</button>}</footer></>:<><div className="modal-body"><ErrorBox error={action.error??createAction.error??list.error??lists.error??choices.error??scopes.error}/>{message&&<p role="status">{message}</p>}
 {!initialListId&&<fieldset disabled={freeze}><div className="inline-search"><Field label="查找候选清单"><input value={q} maxLength={160} onChange={e=>setQ(e.target.value)} placeholder="输入清单标题"/></Field><button onClick={()=>{setSearch(q);setPage(1);}}>查找</button><button onClick={()=>{if(!creating)newListReceipt.current=null;setCreating(v=>!v);}}>{creating?'收起新建':'新建清单'}</button></div>{!creating&&<div className="choice-list">{lists.data?.items.map(l=><button key={l.id} aria-pressed={selectedList===l.id} onClick={()=>{setSelectedList(l.id);snapshot.current=null;}}>{l.title}</button>)}{lists.data&&<Pager page={page} pageSize={10} total={lists.data.total} setPage={setPage}/>}</div>}</fieldset>}
 {creating&&<form className="panel padded" onSubmit={e=>{e.preventDefault();createList();}}><fieldset disabled={createAction.busy||createUnknown}><Field label="新清单标题"><input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="清单可见范围"><select required value={scope} onChange={e=>setScope(e.target.value)}><option value="">请选择</option>{scopes.data?.items.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><button type="submit" className="primary">建立清单并继续</button></fieldset>{createUnknown&&<CommandRecovery operation="shortlist.create" busy={createAction.busy} onRetry={createList}/>}</form>}
 {list.data&&<div className="notice"><strong>目标：{list.data.title}</strong><p>{list.data.canEdit?'当前清单可编辑':'你当前不能编辑这份清单'} · 已有 {list.data.items.length} 项，最多100条。</p></div>}
 {(choices.busy||list.busy)&&<p role="status">正在核对当前资料和清单…</p>}
 <div className="batch-choices">{choices.data?.items.map((p,index)=><div className="batch-choice" key={p.id}><span>{index+1}</span><div><strong>{p.unavailable?'此项当前不可用':p.displayName}</strong>{p.unavailable?<p>资料、职业或访问权限已变化，请返回人才库调整选择。</p>:p.legacy?<p>按原有职业加入</p>:<Field label={'本次职业 '+p.displayName}><select disabled={freeze} value={chosen(p)?.id??''} required onChange={e=>{setRoles(r=>({...r,[p.id]:e.target.value}));snapshot.current=null;}}><option value="">请选择本次入选职业</option>{p.roles?.map(r=><option key={r.id} value={r.id}>{catalog.find(c=>c.namespace==='role'&&c.code===r.roleCode)?.labelZh??r.roleCode}</option>)}</select></Field>}</div>{duplicate(p)&&<span className="tag">已在清单</span>}</div>)}</div>
 <p className="muted">本次只加入人才与职业。任一新增项失效，本批新增都不写入；已有重复项保持原样。</p>
 {unknown&&<div className="notice"><p>结果未知，选择已冻结。先读取原批次结果。</p><button disabled={action.busy} onClick={()=>void action.run(async()=>{const key=pendingKey('shortlist.batchAdd',{id:selectedList});if(!key)return;const receipt=await inspectPending(key) as Receipt|null;if(!receipt){setMessage('还没有可确认的结果，请保留本次选择。');return;}finish(await call<'shortlist.batchAdd',Receipt>('shortlist.batchAdd',snapshot.current!,{id:selectedList}));})}>只读核对批次结果</button><details><summary>原样重试</summary><button disabled={action.busy} onClick={()=>void action.run(async()=>finish(await call<'shortlist.batchAdd',Receipt>('shortlist.batchAdd',snapshot.current!,{id:selectedList})))}>原样重试加入</button></details></div>}
 {!unknown&&!!action.error&&<button onClick={()=>{snapshot.current=null;setTick(t=>t+1);action.clear();}}>重新读取资料后核对</button>}</div><footer className="modal-footer"><button disabled={freeze} onClick={close}>取消</button><button className="primary" disabled={freeze||!valid||choices.busy||list.busy||!!choices.error||!!list.error||creating} onClick={submit}>{action.busy?'正在加入…':'确认加入候选'}</button></footer></>}</Modal>;
}
