import {useState} from 'react';
import {call,read,ApiError} from './api.ts';
import type {Me,Page,Receipt} from './dto.ts';
import {Modal,Field,ErrorBox,PageTitle,Submit,useAction,useLoad,Pager,date} from './ui.tsx';
type Options={revision:number;sourceRevision:number;reviewers:{id:string;name:string}[];publishers:{id:string;name:string;scopeIds:string[]}[];scopes:{id:string;name:string}[]};
type Task={id:string;revision:number;state:string;effectiveState:string;expiresAt:string;senderName:string;reviewerName:string;publisherName:string;targetScope:string|null;person:{id:string;displayName:string}|null;source:{title:string;providerClaim:string;basisDescription:string;validUntil:string;textPayload?:string}|null;canAccept:boolean;canReview:boolean;canPublish:boolean;canRevoke:boolean;canDecline:boolean};
const names:Record<string,string>={PENDING:'待接受核验',ACCEPTED:'核验中',REVIEWED:'待确认共享范围',PUBLISHED:'已共享至指定范围',DECLINED:'已退回',REVOKED:'已撤销',INVALIDATED:'已失效，请重新发起'};
export function SourceReviewInbox({me}:{me:Me}){
 const [version,setVersion]=useState(0),[page,setPage]=useState(1),[creating,setCreating]=useState(false),[selected,setSelected]=useState<string|null>(null);
 const load=useLoad(()=>read<Page<Task>>('sourceReview.list',{}, {page:String(page),pageSize:'20'}),version+':'+page),refresh=()=>setVersion(v=>v+1);
 return <><PageTitle overline="SOURCE REVIEW" title="核验与团队共享" description="先由维护人送审，核验人接受后查看指定材料；核验通过后，再由指定管理员确认共享范围。" action={<>{me.permissions.includes('records.write')&&me.permissions.includes('sources.write')&&<button onClick={()=>setCreating(true)}>发起核验</button>}<button onClick={refresh}>刷新</button></>}/><ErrorBox error={load.error}/><section className="panel padded">{load.data?.items.map(r=><div className="detail-actions" key={r.id}><strong>{names[r.effectiveState]??r.effectiveState}</strong><small>{r.senderName} 发起 · {r.reviewerName} 核验 · 任务 {r.id.slice(0,8)} · 截止 {date(r.expiresAt)}</small><button onClick={()=>setSelected(r.id)}>查看处理</button></div>)}{!load.busy&&!load.data?.items.length&&<p>暂无参与的核验任务。</p>}</section>{load.data&&<Pager page={page} pageSize={20} total={load.data.total} setPage={setPage}/>} {creating&&<SourceReviewOffer onClose={()=>setCreating(false)} onCreated={id=>{setCreating(false);setSelected(id);refresh();}}/>}{selected&&<ReviewDetail id={selected} onClose={()=>{setSelected(null);refresh();}}/>}</>;
}
function SourceReviewOffer({onClose,onCreated}:{onClose:()=>void;onCreated:(id:string)=>void}){
 const [page,setPage]=useState(1),[person,setPerson]=useState('');const candidates=useLoad(()=>read<Page<{id:string;displayName:string}>>('sourceReview.candidates',{}, {page:String(page),pageSize:'20'}),page);
 return <Modal title="送交核验" onClose={onClose} wide><div className="modal-body"><ErrorBox error={candidates.error}/><Field label="本人维护的人才或过期草稿"><select value={person} onChange={e=>setPerson(e.target.value)}><option value="">请选择</option>{candidates.data?.items.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select></Field>{candidates.data&&<Pager page={page} pageSize={20} total={candidates.data.total} setPage={setPage}/>} {person&&<ReviewOfferForm key={person} id={person} onCreated={onCreated}/>}</div></Modal>;
}
function ReviewOfferForm({id,onCreated}:{id:string;onCreated:(id:string)=>void}){
 const options=useLoad(()=>read<Options>('sourceReview.options',{id}),id),a=useAction();const [reviewer,setReviewer]=useState(''),[publisher,setPublisher]=useState(''),[scope,setScope]=useState(''),[until,setUntil]=useState(''),[ack,setAck]=useState(false);
 const unknown=a.error instanceof ApiError&&a.error.unknownOutcome;
 return <form onSubmit={e=>{e.preventDefault();void a.run(async()=>{if(!options.data)return;const r=await call<'sourceReview.create',Receipt>('sourceReview.create',{expectedRevision:options.data.revision,expectedSourceRevision:options.data.sourceRevision,reviewerId:reviewer,publisherId:publisher,targetScopeId:scope,expiresAt:new Date(until).toISOString(),acknowledgeLimitedAccess:ack},{id});onCreated(r.resourceId);});}}><ErrorBox error={a.error??options.error}/><fieldset disabled={a.busy||!!unknown||!options.data}><Field label="核验人"><select required value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">选择具备当前材料读取资格的核验人</option>{options.data?.reviewers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="核验通过后的目标范围"><select required value={scope} onChange={e=>{setScope(e.target.value);setPublisher('');}}><option value="">选择自己可以访问的范围</option>{options.data?.scopes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="确认共享的管理员"><select required value={publisher} onChange={e=>setPublisher(e.target.value)}><option value="">选择有权管理目标范围的成员</option>{options.data?.publishers.filter(p=>p.scopeIds.includes(scope)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="本次核验截止时点（最长七天）"><input required type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)}/></Field><label><input type="checkbox" required checked={ack} onChange={e=>setAck(e.target.checked)}/>授权所选核验人接受后查看当前来源材料；管理员只查看核验结论。共享需管理员再次确认，会影响该人才、该来源及其关联资料的可见性。</label><p className="muted">此任务不交出联系方式、附件或历史版本。共用来源不能直接共享，过期草稿也不会自动恢复有效期。</p><Submit busy={a.busy}>发起核验</Submit></fieldset>{unknown&&<p>结果未知，请使用页面上方的待确认请求核对原提交。</p>}</form>;
}
function ReviewDetail({id,onClose}:{id:string;onClose:()=>void}){
 const [version,setVersion]=useState(0),load=useLoad(()=>read<Task>('sourceReview.get',{id}),id+':'+version),a=useAction();const [basis,setBasis]=useState(''),[until,setUntil]=useState(''),[ack,setAck]=useState(false);const t=load.data,unknown=a.error instanceof ApiError&&a.error.unknownOutcome;
 const act=(action:'accept'|'decline'|'revoke')=>void a.run(async()=>{await call('sourceReview.'+action as 'sourceReview.accept',{expectedRevision:t!.revision},{id});setVersion(v=>v+1);});
 return <Modal title="核验处理" onClose={onClose} wide><div className="modal-body"><ErrorBox error={a.error??load.error}/>{t&&<><h3>{names[t.effectiveState]??t.effectiveState}</h3><p>{t.senderName} 发起 · {t.reviewerName} 核验 · {t.publisherName} 确认共享</p><p>任务截止 {date(t.expiresAt)}{t.targetScope&&' · 目标范围：'+t.targetScope}</p>{t.person&&<h3>{t.person.displayName}</h3>}{t.source&&<><h4>{t.source.title}</h4><p>{t.source.providerClaim}</p><p className="pre-line">{t.source.basisDescription}</p><p>来源截止 {date(t.source.validUntil)}</p>{t.source.textPayload!==undefined&&<Field label="本次受限原文"><textarea readOnly value={t.source.textPayload} rows={7}/></Field>}</>}<fieldset disabled={a.busy||load.busy||!!unknown}>{t.canAccept&&<button onClick={()=>act('accept')}>接受并查看本次核验材料</button>}{t.canReview&&<form onSubmit={e=>{e.preventDefault();void a.run(async()=>{await call('sourceReview.review',{expectedRevision:t.revision,basisDescription:basis,validUntil:new Date(until).toISOString()},{id});setBasis('');setUntil('');setVersion(v=>v+1);});}}><Field label="核验依据与允许的内部用途"><textarea required minLength={4} maxLength={2000} value={basis} onChange={e=>setBasis(e.target.value)}/></Field><Field label="确认后的依据截止时点"><input required type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)}/></Field><p>确认依据不会自动确认所有字段，也不会自动向团队共享。</p><Submit busy={a.busy}>确认内部使用依据</Submit></form>}{t.canPublish&&<form onSubmit={e=>{e.preventDefault();void a.run(async()=>{await call('sourceReview.publish',{expectedRevision:t.revision,confirmScope:ack},{id});setVersion(v=>v+1);});}}><label><input type="checkbox" required checked={ack} onChange={e=>setAck(e.target.checked)}/>已核对上述人才、依据和目标范围，确认同时调整人才及来源范围；关联资料仍按各自读取权限显示。</label><Submit busy={a.busy}>确认共享到上述范围</Submit></form>}<div className="detail-actions">{t.canDecline&&<button onClick={()=>act('decline')}>退回维护人</button>}{t.canRevoke&&<button onClick={()=>act('revoke')}>撤销本次核验</button>}</div></fieldset></>}</div></Modal>;
}
