import {AdminForm} from './foundation/patterns.tsx';
import {useState} from 'react';
import {call} from './api.ts';
import type {CatalogItem,Source} from './dto.ts';
import {ErrorBox,Field,Modal,useAction} from './ui.tsx';
import {TALENT_VERSION} from './talent-dto.ts';
import {TalentSourceChoice,outcomeUnknown} from './talent-edit.tsx';
export function TalentRegistryCreate({mode,catalog,onClose,onSaved}:{mode:'capability'|'organization';catalog:CatalogItem[];onClose:()=>void;onSaved:()=>void}) {
 const [name,setName]=useState(''),[code,setCode]=useState(''),[english,setEnglish]=useState(''),[aliases,setAliases]=useState(''),[roles,setRoles]=useState<string[]>([]),[levels,setLevels]=useState(false),[kind,setKind]=useState<'AGENCY'|'ISSUER'|'OTHER'>('OTHER'),[source,setSource]=useState<Source|null>(null),action=useAction(),freeze=action.busy||outcomeUnknown(action.error);
 const title=mode==='capability'?'登记专业能力':'登记机构',close=()=>{if(freeze)return;if((name||code||source)&&!window.confirm('尚有未保存的登记内容，确定关闭？'))return;onClose();};
 return <Modal title={title} onClose={close}><AdminForm onSubmit={e=>{e.preventDefault();void action.run(async()=>{if(mode==='capability')await call('td2.registry.create',{schemaVersion:TALENT_VERSION,code,labelZh:name,labelEn:english,aliases:aliases.split('\n').map(s=>s.trim()).filter(Boolean),applicableRoleCodes:roles,levelSchemeCode:levels?'ABILITY_5':null,semanticVersion:'1.0.0'});else {if(!source)return;await call('td2.organization.create',{schemaVersion:TALENT_VERSION,name,kind,sourceId:source.id,sourceRevision:source.revision});}onSaved();});}}><div className="modal-body"><ErrorBox error={action.error}/><fieldset disabled={freeze}><Field label={mode==='capability'?'能力名称 *':'机构名称 *'}><input value={name} required maxLength={mode==='capability'?120:200} onChange={e=>setName(e.target.value)}/></Field>{mode==='capability'?<><Field label="稳定代码 *" hint="使用小写英文、数字或下划线。登记后不可把代码改作另一种能力。"><input value={code} required maxLength={80} pattern="[a-z0-9_]+" onChange={e=>setCode(e.target.value)}/></Field><Field label="英文名称"><input value={english} maxLength={120} onChange={e=>setEnglish(e.target.value)}/></Field><Field label="别名（每行一个）"><textarea value={aliases} onChange={e=>setAliases(e.target.value)}/></Field><fieldset><legend>适用职业（不选择表示通用）</legend>{catalog.filter(c=>c.namespace==='role'&&c.status==='ACTIVE').map(r=><label key={r.code}><input type="checkbox" checked={roles.includes(r.code)} onChange={e=>setRoles(old=>e.target.checked?[...old,r.code]:old.filter(c=>c!==r.code))}/>{r.labelZh}</label>)}</fieldset><label><input type="checkbox" checked={levels} onChange={e=>setLevels(e.target.checked)}/>使用基础、工作、专业、流利、母语五级体系</label></>:<Field label="机构类型 *"><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="OTHER">其他机构</option><option value="AGENCY">经纪机构</option><option value="ISSUER">资质颁发机构</option></select></Field>}</fieldset>{mode==='organization'&&<TalentSourceChoice value={source} onChange={setSource} disabled={freeze}/>} {outcomeUnknown(action.error)&&<p className="notice">结果未知，请保留本次内容并原样重试。</p>}</div><footer className="modal-footer"><button type="button" disabled={freeze} onClick={close}>取消</button><button type="submit" className="primary" disabled={action.busy||(mode==='organization'&&!source)}>{outcomeUnknown(action.error)?'原样重试':'保存登记'}</button></footer></AdminForm></Modal>;
}
