import type { TalentFactKind } from './talent-dto.ts';
export type TalentInputKind = 'text' | 'textarea' | 'number' | 'date' | 'datetime-local' | 'choice' | 'role' | 'language' | 'city' | 'capability' | 'personRole' | 'translatorRole' | 'collection' | 'measurement' | 'asset' | 'organization' | 'person';
export interface TalentField {key:string;label:string;kind:TalentInputKind;required?:boolean;immutable?:boolean;options?:string[];hint?:string}
export interface TalentSection {title:string;slug:string;group:'common'|'casting'|'translation'|'professional'|'media';fields:TalentField[];hint?:string}
const field=(key:string,label:string,kind:TalentInputKind,extra:Omit<TalentField,'key'|'label'|'kind'>={}):TalentField=>({key,label,kind,...extra});
const select=(key:string,label:string,options:string[],extra:Omit<TalentField,'key'|'label'|'kind'|'options'>={}):TalentField=>field(key,label,'choice',{options,...extra});
const level=['BASIC','WORKING','PROFESSIONAL','FLUENT','NATIVE'];
const status=select('status','记录状态',['ACTIVE','INACTIVE']);
const period=[field('validFrom','生效时间','datetime-local'),field('validUntil','失效时间','datetime-local')];
const role=field('personRoleId','关联职业','personRole',{immutable:true});
export const TALENT_SECTIONS:Record<TalentFactKind,TalentSection>={
 talentProfiles:{title:'专业档案',slug:'profile',group:'common',fields:[field('internalSummary','内部简介','textarea'),select('status','档案状态',['ACTIVE','ARCHIVED'])]},
 personRoles:{title:'职业',slug:'roles',group:'common',hint:'同一人物可同时拥有多个职业。职业不会从量尺、图片或资质自动推断。',fields:[field('roleCode','职业','role',{required:true,immutable:true}),...period,status]},
 personLanguages:{title:'工作语言',slug:'languages',group:'common',hint:'未核实的熟练度请留空，语言能力与翻译服务分别记录。',fields:[field('languageCode','语言','language',{required:true,immutable:true}),...['speaking','listening','reading','writing'].map((prefix,i)=>select(prefix+'LevelCode',['口语','听力','阅读','写作'][i]!,level)),...period,status]},
 talentLocations:{title:'常驻与服务地区',slug:'locations',group:'common',fields:[field('locationCode','地区','city',{required:true}),select('relationCode','地区关系',['BASE','SERVICE'],{required:true}),...period,status]},
 personCapabilities:{title:'专业能力',slug:'capabilities',group:'professional',hint:'能力使用已登记的选项。未启用等级体系的能力请勿填写等级。',fields:[role,field('capabilityCode','能力','capability',{required:true,immutable:true}),select('levelCode','熟练度',level),...period,status]},
 castingProfiles:{title:'选角外观',slug:'casting',group:'casting',fields:[select('hairColorCode','发色',['BLACK','BROWN','BLONDE','RED','GRAY','WHITE','OTHER']),select('eyeColorCode','瞳色',['BLACK','BROWN','BLUE','GREEN','GRAY','HAZEL','OTHER']),field('appearanceObservedOn','观察日期','date')]},
 measurementSets:{title:'量尺记录',slug:'measurements',group:'casting',hint:'已确认的量尺保留历史；更正时新增记录并关联原记录。',fields:[field('measuredOn','量尺日期','date'),select('datePrecision','日期准确度',['EXACT_DAY','APPROXIMATE','UNKNOWN'],{required:true}),...['heightCm','bustCm','waistCm','hipsCm'].map((key,i)=>field(key,['身高（厘米）','胸围（厘米）','腰围（厘米）','臀围（厘米）'][i]!,'number')),field('shoeSizeValue','鞋码','text'),select('shoeSizeSystem','鞋码体系',['EU','US','UK','CN']),field('clothingSizeValue','服装尺码','text'),select('clothingSizeSystem','服装尺码体系',['INTL','EU','US','UK','CN']),field('supersedesId','更正的原量尺','measurement',{immutable:true})]},
 adultEligibilities:{title:'成年资格',slug:'adult-eligibility',group:'casting',hint:'仅凭外貌、图片或本人声明不能设为已核验成年。核验需要有效证明及截止时间。',fields:[select('state','资格状态',['UNKNOWN','SELF_DECLARED_ADULT','RESTRICTED'],{required:true}),field('validUntil','有效期截止','datetime-local'),field('evidenceAssetId','证明材料','asset',{immutable:true}),status]},
 translatorLanguagePairs:{title:'翻译方向',slug:'translation-pairs',group:'translation',fields:[field('personRoleId','翻译职业','translatorRole',{required:true,immutable:true}),field('sourceLanguageCode','源语言','language',{required:true,immutable:true}),field('targetLanguageCode','目标语言','language',{required:true,immutable:true}),status]},
 translatorServiceModes:{title:'翻译服务方式',slug:'translation-modes',group:'translation',fields:[field('personRoleId','翻译职业','translatorRole',{required:true,immutable:true}),select('modeCode','服务方式',['BUSINESS_MEETING','ON_SET','ESCORT','CONSECUTIVE','SIMULTANEOUS','WRITTEN'],{required:true,immutable:true}),status]},
 personCredentials:{title:'资质证明',slug:'credentials',group:'professional',hint:'资质记录与职业、能力分开。核验后仍受证明材料和有效期约束。',fields:[role,select('credentialTypeCode','资质类型',['DRONE_LICENSE','TRANSLATION_CERTIFICATE','DIVING_CERTIFICATE','EQUIPMENT_CERTIFICATE','OTHER'],{required:true}),field('issuerOrganizationId','颁发机构','organization',{immutable:true}),field('issuerName','颁发方名称','text'),field('issuedOn','签发日期','date'),field('expiresOn','到期日期','date'),field('evidenceAssetId','证明材料','asset',{immutable:true})]},
 representations:{title:'经纪与代表关系',slug:'representations',group:'professional',hint:'经纪机构与个人代表只能选择一个；这不会自动开放对方档案权限。',fields:[role,field('agencyOrganizationId','经纪机构','organization',{immutable:true}),field('agentPersonId','个人代表','person',{immutable:true}),select('relationCode','代表关系',['AGENT','AGENCY','MANAGER'],{required:true}),field('territoryCode','区域代码','text'),...period,status]},
 personExternalRefs:{title:'外部账号标识',slug:'external-refs',group:'professional',hint:'仅做精确身份映射，不会按相似名称自动合并。',fields:[select('providerCode','平台',['WECHAT','XIAOHONGSHU','INSTAGRAM','AGENCY_INTERNAL','SUPPLIER_SYSTEM'],{required:true,immutable:true}),field('namespaceCode','账号所属范围','text',{immutable:true}),field('issuerOrganizationId','所属机构','organization',{immutable:true}),field('externalKey','外部账号标识','text',{required:true,immutable:true})]},
 mediaCollections:{title:'媒体集合',slug:'collections',group:'media',hint:'集合组织已有素材，作品记录真实创作；集合类型与内容标签分别维护。',fields:[role,select('collectionTypeCode','集合类型',['MODEL_CARD','POLAROIDS','PORTFOLIO','SHOWREEL','INTRO_VIDEO','OTHER'],{required:true}),field('title','集合名称','text',{required:true}),select('status','集合状态',['ACTIVE','ARCHIVED'])]},
 mediaCollectionTags:{title:'集合内容标签',slug:'collection-tags',group:'media',fields:[field('collectionId','所属集合','collection',{required:true,immutable:true}),select('tagCode','内容标签',['FASHION','BEAUTY','COMMERCIAL','LINGERIE','RUNWAY','LIFESTYLE','INDUSTRIAL','PRODUCT'],{required:true,immutable:true})]}
};
export const TALENT_LABELS:Record<string,string>={ACTIVE:'生效',INACTIVE:'停用',ARCHIVED:'归档',DRAFT:'待确认',CONFIRMED:'已确认',SUPERSEDED:'已有更正',UNVERIFIED:'未核验',VERIFIED:'已核验',REVOKED:'已撤销',OBSERVED:'已记录',UNKNOWN:'未知',SELF_DECLARED_ADULT:'本人声明成年',VERIFIED_ADULT:'已核验成年',RESTRICTED:'限制使用',BASIC:'基础',WORKING:'可用于工作',PROFESSIONAL:'专业',FLUENT:'流利',NATIVE:'母语',BASE:'常驻',SERVICE:'可服务',EXACT_DAY:'准确日期',APPROXIMATE:'大致日期',BLACK:'黑色',BROWN:'棕色',BLONDE:'金色',RED:'红色',GRAY:'灰色',WHITE:'白色',BLUE:'蓝色',GREEN:'绿色',HAZEL:'榛色',OTHER:'其他',BUSINESS_MEETING:'商务会议',ON_SET:'现场拍摄',ESCORT:'陪同',CONSECUTIVE:'交替传译',SIMULTANEOUS:'同声传译',WRITTEN:'笔译',DRONE_LICENSE:'无人机执照',TRANSLATION_CERTIFICATE:'翻译资质',DIVING_CERTIFICATE:'潜水资质',EQUIPMENT_CERTIFICATE:'设备资质',AGENT:'个人经纪',AGENCY:'经纪机构',MANAGER:'经理人',WECHAT:'微信',XIAOHONGSHU:'小红书',INSTAGRAM:'Instagram',AGENCY_INTERNAL:'经纪机构内部',SUPPLIER_SYSTEM:'供应商系统',MODEL_CARD:'模特卡',POLAROIDS:'素颜照',PORTFOLIO:'作品集',SHOWREEL:'视频集锦',INTRO_VIDEO:'介绍视频',FASHION:'时尚',BEAUTY:'美妆',COMMERCIAL:'商业',LINGERIE:'内衣',RUNWAY:'秀场',LIFESTYLE:'生活方式',INDUSTRIAL:'工业',PRODUCT:'产品'};
