import {PersonCaseEditor} from './person-case-editor.tsx';
import {InternalWorkCases} from './work-case-ui.tsx';
import {TalentBasicSections} from './talent-basic-sections.tsx';
import {TalentIdentityEditor} from './talent-ui.tsx';
import {TalentContactEditor} from './talent-contact-editor.tsx';
import {BatchCandidateChoice} from './shortlist-batch-ui.tsx';
import {SourceReviewOffer,ReviewDetail} from './source-review-ui.tsx';
import {Modal as TaskDialog} from './ui.tsx';
import {InternalCollections} from './internal-collections.tsx';
import {TalentHandoffPanel} from './talent-handoff-ui.tsx';
import {TalentInvitationPanel} from './talent-review-ui.tsx';
import {useEffect,useRef,useState} from 'react';
import {rememberTalent} from './recent-talents.ts';
import {EditorFrame} from './ux-controls.tsx';
import {useUnsaved,allowLeave} from './unsaved.ts';
import {call,read} from './api.ts';
import type {Inputs} from './generated/requests.ts';
import type {CatalogItem,Me,Page,Receipt,Source} from './dto.ts';
import type {TalentDetail,TalentFact} from './talent-dto.ts';
import {ErrorBox,Field,Modal,PageTitle,Pager,Tag,useAction,useLoad,date as displayDate} from './ui.tsx';
import {outcomeUnknown} from './talent-edit.tsx';
import {MediaPanel} from './media-ui.tsx';
import {PersonProductionPanel} from './production-ui.tsx';
import {TALENT_LABELS} from './talent-fields.ts';
import {businessLabels,ageLabel} from './talent-directory.tsx';
import type {Selection} from './production-dto.ts';
type Update=Inputs['directory.talent.update'];
interface Photo{id:string;fileName:string;mime:string;state:string}
const profileOf=(d:TalentDetail)=>d.facts.talentProfiles.find(r=>r.status==='ACTIVE')??null;
function CoreForm({detail,source,me,catalog,onClose,onSaved,section='personal'}:{detail:TalentDetail;source:Source;me:Me;catalog:CatalogItem[];onClose:()=>void;onSaved:()=>void;section?:'personal'|'model'|'measurements'}){
 const profile=profileOf(detail),model=detail.facts.personRoles.find(r=>r.usable&&r.roleCode==='model'),city=detail.facts.talentLocations.find(r=>r.usable&&r.relationCode==='BASE');
 const [values,setValues]=useState<Record<string,unknown>>({genderCode:profile?.genderCode??null,birthPrecision:profile?.birthPrecision??'UNKNOWN',birthYear:profile?.birthYear??null,minAgeYears:profile?.minAgeYears??null,maxAgeYears:profile?.maxAgeYears??null,ageAsOfDate:profile?.ageAsOfDate??null,nationalityCodes:profile?.nationalityCodes??[],...(me.permissions.includes('sensitive.read')&&me.permissions.includes('sensitive.write')?{birthDate:profile?.birthDate??null}:{})});
 const [roles,setRoles]=useState<Record<string,unknown>>({castingMarketCode:model?.castingMarketCode??'UNCLASSIFIED',experienceCode:model?.experienceCode??'UNSPECIFIED',styleCodes:model?.styleCodes??[],serviceCodes:model?.serviceCodes??[]});
 const [location,setLocation]=useState(String(city?.locationCode??'')),[height,setHeight]=useState(''),[sizes,setSizes]=useState<Record<string,string>>({}),[date,setDate]=useState(''),[precision,setPrecision]=useState<'UNKNOWN'|'EXACT_DAY'|'APPROXIMATE'>('UNKNOWN'),[measure,setMeasure]=useState(section==='measurements'),[confirmMeasure,setConfirm]=useState(false);
 const sources=useLoad(async()=>Object.fromEntries(await Promise.all([...new Set([source.id,profile?.sourceId,model?.sourceId,city?.sourceId].filter((id):id is string=>!!id))].map(async id=>[id,await read<Source>('source.get',{id})] as const))),detail.id+':'+detail.revision);
 const snapshot=useRef<Update|null>(null),action=useAction(),frozen=action.busy||outcomeUnknown(action.error)||sources.busy||!!sources.error,set=(k:string,v:unknown)=>setValues(d=>({...d,[k]:v}));
 const canBirth=me.permissions.includes('sensitive.write')&&me.permissions.includes('sensitive.read');
 const changeBirth=(v:string)=>setValues(d=>({...d,birthPrecision:v,birthYear:null,minAgeYears:null,maxAgeYears:null,ageAsOfDate:null,...(canBirth?{birthDate:null}:{})}));
 const fingerprint=JSON.stringify([values,roles,location,height,sizes,date,precision,measure,confirmMeasure]),initial=useRef(fingerprint),dirty=fingerprint!==initial.current;const markSaved=useUnsaved(dirty,'本区人才资料');const close=()=>{if(action.busy||outcomeUnknown(action.error))return;if(dirty&&!window.confirm('本区资料尚未保存，放弃修改？'))return;markSaved();onClose();};
 const chips=(ns:string,key:string,data:Record<string,unknown>,change:(r:Record<string,unknown>)=>void)=>catalog.filter(c=>c.namespace===ns&&(c.status==='ACTIVE'||(data[key] as string[]).includes(c.code))).map(c=><label className="check-chip" key={c.code}><input type="checkbox" checked={(data[key] as string[]).includes(c.code)} disabled={c.status!=='ACTIVE'&&!(data[key] as string[]).includes(c.code)} onChange={e=>change({...data,[key]:e.target.checked?[...(data[key] as string[]),c.code]:(data[key] as string[]).filter(x=>x!==c.code)})}/>{c.labelZh}{c.status!=='ACTIVE'?'（停用）':''}</label>);
 return <EditorFrame title={section==='measurements'?'新增量尺记录':section==='model'?'编辑模特分类与意愿':'编辑个人资料'} onClose={close}><form onChange={()=>{if(!frozen)snapshot.current=null;}} onSubmit={e=>{e.preventDefault();void action.run(async()=>{
  if(!snapshot.current){
  if(measure&&!height&&!Object.values(sizes).some(Boolean))throw new Error('请填写至少一项量尺，不创建空记录。');
  const profileValues={...values};if(!canBirth&&profile?.birthPrecision==='EXACT_DATE')for(const key of ['birthPrecision','birthYear','minAgeYears','maxAgeYears','ageAsOfDate'])delete profileValues[key];
  const original={genderCode:profile?.genderCode??null,birthPrecision:profile?.birthPrecision??'UNKNOWN',birthDate:profile?.birthDate??null,birthYear:profile?.birthYear??null,minAgeYears:profile?.minAgeYears??null,maxAgeYears:profile?.maxAgeYears??null,ageAsOfDate:profile?.ageAsOfDate??null,nationalityCodes:profile?.nationalityCodes??[]};
  const profilePatch=section==='personal'?Object.fromEntries(Object.entries(profileValues).filter(([k,v])=>JSON.stringify(v)!==JSON.stringify(original[k as keyof typeof original]))):{};
  const modelPatch=section==='model'?Object.fromEntries(Object.entries(roles).filter(([k,v])=>JSON.stringify(v)!==JSON.stringify(model?.[k]))):{};
  if(!Object.keys(profilePatch).length&&!Object.keys(modelPatch).length&&location===String(city?.locationCode??'')&&!measure){onSaved();return;}
  const selectedBasis=(row:TalentFact|undefined|null)=>{const current=sources.data?.[row?.sourceId??source.id];if(!current?.current||current.allowsInternalAuthoring===false)throw new Error('该项来源当前不能用于直接修改。请在高级管理补充独立来源并逐项提交建议。');return {sourceId:current.id,sourceRevision:current.revision,...(row?{recordId:row.id,expectedRevision:row.revision}:{})};};
  const bases={...(Object.keys(profilePatch).length?{profile:selectedBasis(profile)}:{}),...(model&&Object.keys(modelPatch).length?{model:selectedBasis(model)}:{}),...(location!==String(city?.locationCode??'')?{location:selectedBasis(city)}:{}),...(measure?{measurement:selectedBasis(null)}:{})};
  const input:Update={schemaVersion:'once-talent-experience-v1',expectedRevision:detail.revision,bases,sourceId:source.id,sourceRevision:source.revision,...(Object.keys(profilePatch).length?{profile:profilePatch}:{}),...(location!==String(city?.locationCode??'')?{locationCode:location||null}:{}),...(model&&Object.keys(modelPatch).length?{model:modelPatch}:{}),...(measure?{measurement:{heightCm:height===''?null:Number(height),...Object.fromEntries(Object.entries(sizes).map(([k,v])=>[k,v===''?null:k.endsWith('Cm')?Number(v):v])),measuredOn:precision==='UNKNOWN'?null:date,datePrecision:precision,supersedesId:(detail.facts.castingProfiles.find(r=>r.usable)?.currentMeasurementSetId as string|null)??null},confirmMeasurement:confirmMeasure}:{})};
  snapshot.current=input;}
  await call<'directory.talent.update',Receipt>('directory.talent.update',snapshot.current,{id:detail.id});markSaved();onSaved();
 });}}><div className="modal-body"><ErrorBox error={action.error??sources.error}/><p>本次修正原资料的录入，沿用各项现有依据。收到另一份新资料时，请返回基本资料，使用“补充新资料”逐项记录新依据。</p><fieldset disabled={frozen}><div className="form-grid">
 {section==='personal'&&<><Field label="性别"><select value={String(values.genderCode??'')} onChange={e=>set('genderCode',e.target.value||null)}><option value="">未知</option>{['FEMALE','MALE','NON_BINARY','OTHER'].map(c=><option key={c} value={c}>{businessLabels[c]}</option>)}</select></Field>
 <Field label="出生信息精度" hint="只记录明确收到的资料；年龄区间不等于成年资格。"><select value={String(values.birthPrecision)} disabled={!canBirth&&profile?.birthPrecision==='EXACT_DATE'} onChange={e=>changeBirth(e.target.value)}>{['UNKNOWN',...(canBirth||profile?.birthPrecision==='EXACT_DATE'?['EXACT_DATE']:[]),'YEAR_ONLY','DECLARED_RANGE'].map(c=><option key={c} value={c}>{businessLabels[c]}</option>)}</select></Field>
 {values.birthPrecision==='EXACT_DATE'&&canBirth&&<Field label="出生日期（受限）"><input required type="date" value={String(values.birthDate??'')} onChange={e=>set('birthDate',e.target.value||null)}/></Field>}
 {values.birthPrecision==='YEAR_ONLY'&&<Field label="出生年份"><input required type="number" min={1900} max={new Date().getFullYear()} value={String(values.birthYear??'')} onChange={e=>set('birthYear',e.target.value===''?null:Number(e.target.value))}/></Field>}
 {values.birthPrecision==='DECLARED_RANGE'&&<><Field label="声明年龄下限"><input required type="number" min={0} max={130} value={String(values.minAgeYears??'')} onChange={e=>set('minAgeYears',e.target.value===''?null:Number(e.target.value))}/></Field><Field label="声明年龄上限"><input required type="number" min={0} max={130} value={String(values.maxAgeYears??'')} onChange={e=>set('maxAgeYears',e.target.value===''?null:Number(e.target.value))}/></Field><Field label="年龄声明日期"><input required type="date" value={String(values.ageAsOfDate??'')} onChange={e=>set('ageAsOfDate',e.target.value||null)}/></Field></>}
 <Field label="常驻城市"><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">未知</option>{catalog.filter(c=>c.namespace==='city'&&(c.status==='ACTIVE'||c.code===location)).map(c=><option key={c.code} value={c.code}>{c.labelZh}</option>)}</select></Field>
 </>}{model&&section==='model'&&<><Field label="国模 / 外模" hint="业务分类与国籍独立，不能从照片判断。"><select value={String(roles.castingMarketCode)} onChange={e=>setRoles(d=>({...d,castingMarketCode:e.target.value}))}>{['UNCLASSIFIED','DOMESTIC','INTERNATIONAL'].map(c=><option key={c} value={c}>{businessLabels[c]}</option>)}</select></Field><Field label="从业类型"><select value={String(roles.experienceCode)} onChange={e=>setRoles(d=>({...d,experienceCode:e.target.value}))}>{['UNSPECIFIED','AMATEUR','PROFESSIONAL'].map(c=><option key={c} value={c}>{businessLabels[c]}</option>)}</select></Field></>}
 {section==='personal'&&<Field label="国籍声明" wide hint="没有明确声明时不选；业务分类不会自动填入国籍。"><div className="check-grid">{chips('nationality','nationalityCodes',values,setValues)}</div></Field>}
 {model&&section==='model'&&<><Field label="模特风格标签" wide><div className="check-grid">{chips('roleStyle','styleCodes',roles,setRoles)}</div></Field><Field label="愿意参与的拍摄类型" wide hint="意愿不等于已拍摄经历。"><div className="check-grid">{chips('roleService','serviceCodes',roles,setRoles)}</div></Field></>}
 </div>{model&&section==='measurements'&&<><label><input type="checkbox" checked={measure} onChange={e=>setMeasure(e.target.checked)}/>新增一份量尺记录</label>{measure&&<div className="form-grid"><Field label="本次身高（厘米）"><input type="number" min={40} max={260} step="0.1" value={height} onChange={e=>setHeight(e.target.value)}/></Field>{[['bustCm','胸围（厘米）'],['waistCm','腰围（厘米）'],['hipsCm','臀围（厘米）']].map(([key,title])=><Field key={key} label={title!}><input type="number" min={20} max={250} step="0.1" value={sizes[key!]??''} onChange={e=>setSizes(s=>({...s,[key!]:e.target.value}))}/></Field>)}{[['shoe','鞋码',['EU','US','UK','CN']],['clothing','服装尺码',['INTL','EU','US','UK','CN']]].map(([key,title,systems])=><Field key={String(key)} label={String(title)}><input maxLength={30} value={sizes[key+'SizeValue']??''} onChange={e=>setSizes(s=>({...s,[key+'SizeValue']:e.target.value}))}/><select aria-label={title+'体系'} value={sizes[key+'SizeSystem']??''} onChange={e=>setSizes(s=>({...s,[key+'SizeSystem']:e.target.value}))}><option value="">体系未知</option>{(systems as string[]).map(c=><option key={c} value={c}>{c}</option>)}</select></Field>)}<Field label="量尺日期精度"><select value={precision} onChange={e=>{setPrecision(e.target.value as typeof precision);if(e.target.value==='UNKNOWN')setDate('');}}><option value="UNKNOWN">日期未知</option><option value="EXACT_DAY">准确日期</option><option value="APPROXIMATE">大约日期</option></select></Field>{precision!=='UNKNOWN'&&<Field label="量尺日期"><input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field>}{me.permissions.includes('sources.review')&&<label><input type="checkbox" checked={confirmMeasure} disabled={source.status!=='CONFIRMED'} onChange={e=>setConfirm(e.target.checked)}/>我已核对本次量尺，设为当前记录</label>}<p className="muted">已确认量尺不会原地覆盖，新记录保留历史。日期未知时保持为空；未确认记录不用于身高筛选。来源须先经明确核对，才能确认量尺。</p></div>}</>}</fieldset>{outcomeUnknown(action.error)&&<p role="status">结果尚不明确，原资料已冻结，请核对原提交。</p>}</div><footer className="modal-footer"><button type="button" disabled={frozen} onClick={close}>取消</button><button className="primary" type="submit" disabled={action.busy}>{action.busy?'正在保存…':outcomeUnknown(action.error)?'原样重试保存':'保存本区资料'}</button></footer></form></EditorFrame>;
}
export function TalentDirectoryDetail({id,me,catalog,onClose,onAdvanced,onProduction,refreshVersion=0,onViewList}:{id:string;me:Me;catalog:CatalogItem[];onClose:()=>void;onAdvanced:()=>void;onProduction:(p:Selection)=>void;refreshVersion?:number;onViewList?:(id:string)=>void}){
 const [tick,setTick]=useState(0),[tab,setTab]=useState('overview'),[edit,setEdit]=useState<'identity'|'personal'|'model'|'measurements'|'contacts'|null>(null),[task,setTask]=useState<'invite'|'access'|'review'|null>(null),[reviewId,setReviewId]=useState<string|null>(null),[joining,setJoining]=useState(false),[caseEditing,setCaseEditing]=useState(false),[notice,setNotice]=useState('');
 const load=useLoad(()=>read<TalentDetail>('directory.talent.get',{id}),id+':'+tick+':'+refreshVersion),d=load.data,p=d?profileOf(d):null;
 const source=useLoad(()=>p&&me.permissions.includes('sources.read')?read<Source>('source.get',{id:p.sourceId}):Promise.resolve(null),String(p?.sourceId)+':'+tick+':'+refreshVersion);
 useEffect(()=>{if(d&&!load.busy)rememberTalent(me,id);},[d,load.busy,id,me.membershipId]);
 const scopes=useLoad(()=>read<{items:{id:string;name:string}[]}>('scope.list'),me.membershipId);
 const label=(ns:string,code:unknown)=>catalog.find(c=>c.namespace===ns&&c.code===code)?.labelZh??String(code);
 const changed=()=>{setEdit(null);setTick(t=>t+1);setNotice('本区资料已保存。');};
 const move=(next:string)=>{if(allowLeave())setTab(next);};
 const currentIds=new Set(d?.facts.castingProfiles.filter(r=>r.usable).map(r=>r.currentMeasurementSetId)??[]),measurements=d?.facts.measurementSets.filter(r=>r.usable&&currentIds.has(r.id))??[];
 if(caseEditing&&d)return <PersonCaseEditor detail={d} me={me} catalog={catalog} initialSource={source.data??undefined} onClose={()=>setCaseEditing(false)} onSaved={()=>{setCaseEditing(false);setTick(t=>t+1);setNotice('作品、本人署名与素材已一起保存。');}}/>;
 if(edit==='identity'&&d)return <TalentIdentityEditor inline detail={d} onClose={()=>setEdit(null)} onSaved={changed}/>;
 if(edit==='contacts'&&d)return <TalentContactEditor detail={d} me={me} onClose={()=>setEdit(null)} onSaved={changed}/>;
 if(edit&&d&&source.data)return <CoreForm section={edit as 'personal'|'model'|'measurements'} detail={d} source={source.data} me={me} catalog={catalog} onClose={()=>setEdit(null)} onSaved={changed}/>;
 return <section className="talent-main-detail" aria-label="人才主详情"><button className="link-button back-button" onClick={()=>{if(allowLeave())onClose();}}>← 返回目录</button><ErrorBox error={load.error}/>{load.busy?<p role="status">正在读取当前资料…</p>:d&&<><PageTitle overline="人才档案" title={d.displayName} description={'当前范围：'+(scopes.data?.items.find(s=>s.id===d.scopeId)?.name??'按现有权限读取')} action={<div className="button-row">{me.permissions.includes('records.write')&&d.isTalent&&d.status!=='ARCHIVED'&&<button className="primary" onClick={()=>setJoining(true)}>加入候选</button>}{d.canEdit&&<button onClick={()=>{move('basic');setEdit('identity');}}>编辑资料</button>}<details className="more-actions"><summary>更多操作</summary><div>{me.permissions.includes('talent.invite')&&<button onClick={()=>setTask('invite')}>邀请本人维护</button>}{me.permissions.includes('records.write')&&me.permissions.includes('sources.write')&&<button onClick={()=>setTask('review')}>提交团队核验</button>}{me.permissions.includes('talent.review')&&<button onClick={()=>setTask('access')}>本人可见资料</button>}<button onClick={onAdvanced}>来源、历史与范围</button><button onClick={()=>setTick(t=>t+1)}>刷新资料</button></div></details></div>}/>
 <nav className="view-tabs detail-tabs" aria-label="人才资料分区">{[['overview','概览'],['basic','基本资料'],['media','照片视频'],['work','作品与合作']].map(([key,title])=><button key={key} aria-pressed={tab===key} onClick={()=>move(key!)}>{title}</button>)}</nav>{notice&&<div className="success" role="status">{notice}</div>}
 {tab==='overview'&&<><div className="panel padded talent-main-overview">{p?.coverAssetId?<img className="main-cover" src={'/api/v1/assets/'+p.coverAssetId+'/preview'} alt={d.displayName+'的封面'}/>:<div className="main-cover directory-cover-placeholder">暂无封面照片</div>}<div><Tag value={d.status}/><h2>{d.facts.personRoles.filter(r=>r.usable).map(r=>label('role',r.roleCode)).join(' / ')||'普通联系人'}</h2><p className="pre-line">{d.intro||'简介未填写'}</p><dl className="detail-grid"><div><dt>常驻城市</dt><dd>{d.facts.talentLocations.filter(r=>r.usable&&r.relationCode==='BASE').map(r=>label('city',r.locationCode)).join(' / ')||'未填写'}</dd></div><div><dt>性别</dt><dd>{businessLabels[String(p?.genderCode)]??'未填写'}</dd></div><div><dt>年龄</dt><dd>{ageLabel(d.ageRange??null)}</dd></div><div><dt>身高</dt><dd>{measurements[0]?.heightCm?measurements[0].heightCm+' cm':'暂无已确认记录'}</dd></div><div><dt>工作语言</dt><dd>{d.facts.personLanguages.filter(r=>r.usable).map(r=>label('language',r.languageCode)).join(' / ')||'未填写'}</dd></div></dl><div className="button-row"><button onClick={()=>move('basic')}>查看基本资料</button>{me.permissions.includes('assets.upload')&&<button onClick={()=>move('media')}>添加照片视频</button>}</div></div></div><InternalWorkCases key={id+':'+tick} personId={id}/></>}
 {tab==='basic'&&<><section className="panel padded"><div className="section-heading"><h2>姓名与简介</h2>{d.canEdit&&<button onClick={()=>setEdit('identity')}>编辑姓名与简介</button>}</div><p>{d.displayName}{d.aliases.length?' · '+d.aliases.join(' / '):''}</p><p className="pre-line">{d.intro||'简介未填写'}</p></section><section className="panel padded"><div className="section-heading"><h2>个人资料</h2>{d.canEdit&&source.data?.current&&<button onClick={()=>setEdit('personal')}>编辑个人资料</button>}</div><p>{businessLabels[String(p?.genderCode)]??'性别未填写'} · {ageLabel(d.ageRange??null)} · {(p?.nationalityCodes as string[]??[]).map(c=>label('nationality',c)).join(' / ')||'国籍未填写'}</p><p>常驻：{d.facts.talentLocations.filter(r=>r.usable&&r.relationCode==='BASE').map(r=>label('city',r.locationCode)).join(' / ')||'未填写'}</p><ErrorBox error={source.error}/>{d.facts.personRoles.some(r=>r.usable&&r.roleCode==='model')&&d.canEdit&&source.data?.current&&<div className="button-row"><button onClick={()=>setEdit('model')}>编辑模特分类与意愿</button><button onClick={()=>setEdit('measurements')}>新增量尺记录</button></div>}</section>{me.permissions.includes('sensitive.read')&&<section className="panel padded"><div className="section-heading"><h2>联系资料</h2><button onClick={()=>setEdit('contacts')}>查看受限联系方式</button></div><p>按需读取，不随人才简介展示。</p></section>}<TalentBasicSections detail={d} me={me} catalog={catalog} onSaved={changed}/></>}
 {tab==='media'&&<>{me.permissions.includes('assets.read')?<MediaPanel key={id} me={me} personId={id} source={source.data??undefined} compact onReady={()=>setTick(t=>t+1)} coverId={p?.coverAssetId as string|null} onSetCover={d.canEdit&&source.data?.current?async(assetId)=>{await call('directory.talent.update',{schemaVersion:'once-talent-experience-v1',expectedRevision:d.revision,sourceId:source.data!.id,sourceRevision:source.data!.revision,profile:{coverAssetId:assetId}},{id});setTick(t=>t+1);setNotice('封面已保存。');}:undefined}/>:<p>当前没有读取素材的权限。</p>}{me.permissions.includes('assets.read')&&<InternalCollections detail={d} me={me} onSaved={()=>setTick(t=>t+1)}/>}</>}
 {tab==='work'&&<>{d.canEdit&&me.permissions.includes('assets.read')&&<button className="primary" onClick={()=>setCaseEditing(true)}>添加作品案例</button>}<InternalWorkCases key={id+':'+tick} personId={id}/><PersonProductionPanel personId={id} onOpen={onProduction}/></>}
 {joining&&<BatchCandidateChoice selection={[{personId:id,personRoleId:null,pendingRole:true}]} catalog={catalog} onClose={()=>setJoining(false)} onDone={(_,summary)=>{setJoining(false);setNotice('新增 '+summary.added+' 项候选，已有 '+summary.existing+' 项。');}} onViewList={onViewList}/>}
 {task==='invite'&&<TaskDialog title={'邀请 '+d.displayName+' 本人维护'} onClose={()=>{if(allowLeave())setTask(null);}}><div className="modal-body"><TalentInvitationPanel personId={id}/></div></TaskDialog>}
 {task==='access'&&<TaskDialog title={d.displayName+' · 本人可见资料'} wide onClose={()=>{if(allowLeave())setTask(null);}}><div className="modal-body"><TalentHandoffPanel personId={id}/></div></TaskDialog>}
 {task==='review'&&<SourceReviewOffer personId={id} onClose={()=>setTask(null)} onCreated={review=>{setTask(null);setReviewId(review);setNotice('已发起团队核验，等待所选同事处理。');}}/>}{reviewId&&<ReviewDetail id={reviewId} onClose={()=>{setReviewId(null);setTick(t=>t+1);}}/>}
 </>}</section>;
}
