import {DIRECTORY_DIMENSIONS,DIRECTORY_AGE_PRESETS} from '../../../packages/core/src/talent-directory-contract.ts';
import {readDirectoryState,saveDirectoryState,clearDirectoryMemory,directoryRequest,type DirectoryDraft,type CandidateContext} from './directory-state.ts';
export {clearDirectoryMemory};
import {useEffect,useState} from 'react';
import {call,read} from './api.ts';
import type {CatalogItem,Me,Page} from './dto.ts';
import {ErrorBox,Empty,Field,Pager,PageTitle,Tag,useLoad} from './ui.tsx';
export interface DirectoryMatch {id:string;isTalent:boolean;displayName:string;status:string;revision:number;genderCode:string|null;nationalityCodes:string[];ageRange:{min:number;max:number;precision:string}|null;coverAssetId:string|null;heightCm:number|null;matchingRoleIds:string[];roles:Array<{id:string;roleCode:string;castingMarketCode:string;experienceCode:string}>;locations:Array<{locationCode:string;relationCode:string}>;languages:Array<{languageCode:string}>}
interface DirectoryPage extends Page<DirectoryMatch>{facets:Record<string,Record<string,number>>}
export const businessLabels:Record<string,string>={FEMALE:'女',MALE:'男',NON_BINARY:'非二元',OTHER:'其他',UNKNOWN:'未知',DOMESTIC:'国模',INTERNATIONAL:'外模',UNCLASSIFIED:'未分类',AMATEUR:'素人',PROFESSIONAL:'专业',UNSPECIFIED:'未确认',YEAR_ONLY:'仅出生年份',EXACT_DATE:'完整出生日期',DECLARED_RANGE:'声明年龄范围'};
export const ageLabel=(age:DirectoryMatch['ageRange'])=>age?age.min===age.max?age.min+' 岁':age.min+'–'+age.max+' 岁':'年龄未知';
/** One reusable directory query/view for the library and candidate picker; no second search engine. */
export function TalentDirectory({me,catalog,onOpen,onPick,tick=0,onCreate,surface='library'}:{me:Me;catalog:CatalogItem[];onOpen:(id:string)=>void;onPick?:(p:DirectoryMatch,context:CandidateContext)=>void;tick?:number;onCreate?:()=>void;surface?:'library'|'candidate'}){
 const key=me.membershipId+':'+surface,initial=readDirectoryState(surface);
 const [query,setQuery]=useState(initial.query),[draft,setDraft]=useState(initial.draft),[page,setPage]=useState(initial.page),[selected,setSelected]=useState(initial.selected),[refresh,setRefresh]=useState(0),[roleChoices,setRoleChoices]=useState(initial.roleChoices),[customAge,setCustomAge]=useState(false);
 useEffect(()=>{saveDirectoryState(surface,{query,draft,page,selected,roleChoices});},[key,query,draft,page,selected,roleChoices]);
 useEffect(()=>{const restore=()=>{const saved=readDirectoryState(surface);setQuery(saved.query);setDraft(saved.draft);setPage(saved.page);setSelected(saved.selected);setRoleChoices(saved.roleChoices);};window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore);},[surface]);
 const querySignature=JSON.stringify(query);
 const load=useLoad(async()=>({...await call<'directory.talent.search',DirectoryPage>('directory.talent.search',{...directoryRequest(query),page,pageSize:20}),requestedQuery:querySignature}),JSON.stringify([query,page,tick,refresh]));
 useEffect(()=>{if(load.data?.requestedQuery===querySignature&&load.data.page===page&&page>1&&!load.data.items.length)setPage(Math.max(1,Math.ceil(load.data.total/20)));},[load.data,page,querySignature]);
 const set=(k:string,v:string|string[])=>setDraft(d=>({...d,[k]:v}));
 const label=(ns:string,code:string)=>catalog.find(c=>c.namespace===ns&&c.code===code)?.labelZh??code;
 const select=(key:string,title:string,options:[string,string][],counts?:Record<string,number>)=>{const multiple=Object.hasOwn(DIRECTORY_DIMENSIONS,key);return <Field label={title} hint={multiple?'可多选，同类条件满足任一项即可':''}><select multiple={multiple} size={multiple?3:undefined} value={multiple?(Array.isArray(draft[key])?draft[key]:draft[key]?[String(draft[key])]:[]):String(draft[key]??'')} onChange={e=>set(key,multiple?Array.from(e.target.selectedOptions).map(o=>o.value):e.target.value)}>{!multiple&&<option value="">不限</option>}{options.map(([code,label])=><option key={code} value={code}>{label}{counts?'（'+(counts[code]??0)+'）':''}</option>)}</select></Field>;};
 const preset=customAge?'custom':DIRECTORY_AGE_PRESETS.items.find(p=>String(p.min)===draft.ageMin&&String(p.max)===draft.ageMax)?.id??(draft.ageMin||draft.ageMax?'custom':'');
 const contextFor=(p:DirectoryMatch):CandidateContext|null=>{const role=p.roles.length===1?p.roles[0]!.id:roleChoices[p.id];return p.isTalent===false?{personId:p.id,personRoleId:null}:role&&p.matchingRoleIds.includes(role)?{personId:p.id,personRoleId:role}:null;};
 const dictionary=(ns:string)=>catalog.filter(c=>c.namespace===ns&&c.status==='ACTIVE').map(c=>[c.code,c.labelZh] as [string,string]);
 return <section className="talent-directory" aria-label={surface==='candidate'?'候选找人':'统一人才目录'}>{surface==='library'&&<PageTitle overline="PEOPLE & TALENT" title="人才档案" description="按照片和当前资料找人，一个人保留同一份档案。" action={onCreate&&<button className="primary" onClick={onCreate}>＋ 新增人才</button>}/>}
 <form className="panel padded directory-filters" onSubmit={e=>{e.preventDefault();setRefresh(n=>n+1);setPage(1);setQuery(Object.fromEntries(Object.entries(draft).filter(([,v])=>v!==''&&(!Array.isArray(v)||v.length))));}}><div className="form-grid">
 <Field label="搜索姓名或别名"><input maxLength={160} value={String(draft.q??'')} onChange={e=>set('q',e.target.value)} placeholder="姓名、艺名、别名"/></Field>
 {select('mode','人物范围',[['ALL','全部人物'],['TALENT','人才'],['CONTACT','普通联系人']])}
 {select('role','职业',dictionary('role'),load.data?.facets.roles)}{select('gender','性别',['FEMALE','MALE','NON_BINARY','OTHER','UNKNOWN'].map(c=>[c,businessLabels[c]!] as [string,string]),load.data?.facets.genders)}
 {select('market','国模 / 外模',['DOMESTIC','INTERNATIONAL','UNCLASSIFIED'].map(c=>[c,businessLabels[c]!] as [string,string]),load.data?.facets.markets)}
 {select('experience','从业类型',['AMATEUR','PROFESSIONAL','UNSPECIFIED'].map(c=>[c,businessLabels[c]!] as [string,string]),load.data?.facets.experiences)}
 {select('location','城市',dictionary('city'),load.data?.facets.locations)}
 <Field label="年龄快捷筛选"><select value={preset} onChange={e=>{setCustomAge(e.target.value==='custom');const p=DIRECTORY_AGE_PRESETS.items.find(p=>p.id===e.target.value);setDraft(d=>({...d,ageMin:p?String(p.min):'',ageMax:p?String(p.max):'',ageUnknown:''}));}}><option value="">不限</option>{DIRECTORY_AGE_PRESETS.items.map(p=><option value={p.id} key={p.id}>{p.label}</option>)}<option value="custom">自定义</option></select></Field><Field label="年龄下限"><input type="number" min={0} max={130} value={String(draft.ageMin??'')} onChange={e=>{setCustomAge(true);setDraft(d=>({...d,ageMin:e.target.value,ageUnknown:''}));}}/></Field><Field label="年龄上限"><input type="number" min={0} max={130} value={String(draft.ageMax??'')} onChange={e=>{setCustomAge(true);setDraft(d=>({...d,ageMax:e.target.value,ageUnknown:''}));}}/></Field>
 <Field label="身高下限（厘米）"><input type="number" min={40} max={260} step="0.1" value={String(draft.heightMin??'')} onChange={e=>set('heightMin',e.target.value)}/></Field><Field label="身高上限（厘米）"><input type="number" min={40} max={260} step="0.1" value={String(draft.heightMax??'')} onChange={e=>set('heightMax',e.target.value)}/></Field>
 </div><details><summary>更多条件</summary><div className="form-grid">{select('nationality','国籍',dictionary('nationality'),load.data?.facets.nationalities)}{select('style','风格标签',dictionary('roleStyle'),load.data?.facets.styles)}{select('service','愿意参与的拍摄类型',dictionary('roleService'),load.data?.facets.services)}{select('language','工作语言',dictionary('language'),load.data?.facets.languages)}{select('industryCode','作品行业',dictionary('industry'),load.data?.facets.industries)}{select('workTypeCode','作品类型',dictionary('workType'),load.data?.facets.workTypes)}{select('status','档案状态',[['DRAFT','草稿'],['ACTIVE','在库'],['ARCHIVED','归档']])}<label><input type="checkbox" checked={draft.ageUnknown==='true'} onChange={e=>{set('ageUnknown',e.target.checked?'true':'');if(e.target.checked){setCustomAge(false);set('ageMin','');set('ageMax','');}}}/>只找年龄未知</label></div></details>
 <div className="detail-actions"><button type="submit" className="primary">组合找人</button><button type="button" onClick={()=>{setCustomAge(false);setDraft({mode:'ALL'});setQuery({mode:'ALL'});setPage(1);}}>重置条件</button><button type="button" onClick={()=>setRefresh(x=>x+1)}>刷新</button></div><small className="muted">年龄范围须完整落在条件内；身高仅用当前已确认量尺。标签不代表既有经历。括号计数应用其他条件后按人数计算。</small></form>
 <ErrorBox error={load.error}/>{load.busy?<p>正在查询当前可见资料…</p>:load.data&&<><div className="directory-count"><strong>匹配 {load.data.total} 位</strong><span>本次已选 {selected.length} 项</span><button onClick={()=>setSelected([])}>清空选择</button></div><div className="people-grid photo-directory">{load.data.items.map(p=><article key={p.id} className="directory-card"><button className="person-card" onClick={()=>onOpen(p.id)}>{p.coverAssetId?<img className="directory-cover" loading="lazy" src={'/api/v1/assets/'+p.coverAssetId+'/preview'} alt={p.displayName+'的封面'}/>:<div className="directory-cover-placeholder">暂无封面照片</div>}<div className="directory-card-body"><div className="card-top"><h3>{p.displayName}</h3><Tag value={p.status}/></div><p>{p.roles.map(r=>label('role',r.roleCode)).join(' / ')||'普通联系人'}</p><p>{p.genderCode?businessLabels[p.genderCode]:'性别未知'} · {ageLabel(p.ageRange)}</p><p>{p.locations.map(l=>label('city',l.locationCode)).join(' / ')||'城市未知'} · {p.heightCm==null?'身高未知':p.heightCm+' cm'}</p><small>{p.roles.filter(r=>r.roleCode==='model').map(r=>businessLabels[r.castingMarketCode]+' · '+businessLabels[r.experienceCode]).join('')}</small></div></button><footer>{p.roles.length>1&&<Field label={'候选职业 '+p.displayName}><select value={roleChoices[p.id]??''} onChange={e=>setRoleChoices(c=>({...c,[p.id]:e.target.value}))}><option value="">明确选择本次职业</option>{p.roles.filter(r=>p.matchingRoleIds.includes(r.id)).map(r=><option key={r.id} value={r.id}>{label('role',r.roleCode)}</option>)}</select></Field>}<label><input type="checkbox" disabled={!contextFor(p)} checked={!!contextFor(p)&&selected.some(s=>s.personId===p.id&&s.personRoleId===contextFor(p)!.personRoleId)} onChange={e=>{const context=contextFor(p);if(context)setSelected(ids=>e.target.checked?[...ids,context]:ids.filter(s=>s.personId!==p.id||s.personRoleId!==context.personRoleId));}}/>选择 {p.displayName}</label>{onPick&&<button disabled={!contextFor(p)} onClick={()=>{const context=contextFor(p);if(context)onPick(p,context);}}>加入当前清单</button>}</footer></article>)}</div>{!load.data.items.length&&<Empty title="当前条件没有可见人才">可减少筛选条件或重置。未知值不会被当成符合；来源或权限失效的资料不计入结果。</Empty>}<Pager page={page} pageSize={20} total={load.data.total} setPage={setPage}/></>}</section>;
}
