import {useEffect,useState} from 'react';
import {call,read} from './api.ts';
import type {CatalogItem,Me,Page} from './dto.ts';
import {ErrorBox,Empty,Field,Pager,PageTitle,Tag,useLoad} from './ui.tsx';
export interface DirectoryMatch {id:string;displayName:string;status:string;revision:number;genderCode:string|null;nationalityCodes:string[];ageRange:{min:number;max:number;precision:string}|null;coverAssetId:string|null;heightCm:number|null;roles:Array<{id:string;roleCode:string;castingMarketCode:string;experienceCode:string}>;locations:Array<{locationCode:string;relationCode:string}>;languages:Array<{languageCode:string}>}
interface DirectoryPage extends Page<DirectoryMatch>{facets:{roles:Record<string,number>;locations:Record<string,number>;genders:Record<string,number>;markets:Record<string,number>;experiences:Record<string,number>}}
const memories=new Map<string,{query:Record<string,string>;draft:Record<string,string>;page:number;selected:string[]}>();
window.addEventListener('once-session-expired',()=>memories.clear());
export const businessLabels:Record<string,string>={FEMALE:'女',MALE:'男',NON_BINARY:'非二元',OTHER:'其他',UNKNOWN:'未知',DOMESTIC:'国模',INTERNATIONAL:'外模',UNCLASSIFIED:'未分类',AMATEUR:'素人',PROFESSIONAL:'专业',UNSPECIFIED:'未确认',YEAR_ONLY:'仅出生年份',EXACT_DATE:'完整出生日期',DECLARED_RANGE:'声明年龄范围'};
export const ageLabel=(age:DirectoryMatch['ageRange'])=>age?age.min===age.max?age.min+' 岁':age.min+'–'+age.max+' 岁':'年龄未知';
/** One reusable directory query/view for the library and candidate picker; no second search engine. */
export function clearDirectoryMemory(){memories.clear();}
export function TalentDirectory({me,catalog,onOpen,onPick,tick=0,onCreate,surface='library'}:{me:Me;catalog:CatalogItem[];onOpen:(id:string)=>void;onPick?:(p:DirectoryMatch)=>void;tick?:number;onCreate?:()=>void;surface?:'library'|'candidate'}){
 const key=me.membershipId+':'+surface,initial=memories.get(key)??{query:{mode:'ALL'},draft:{mode:'ALL'},page:1,selected:[]};
 const [query,setQuery]=useState(initial.query),[draft,setDraft]=useState(initial.draft),[page,setPage]=useState(initial.page),[selected,setSelected]=useState(initial.selected),[refresh,setRefresh]=useState(0);
 useEffect(()=>{memories.set(key,{query,draft,page,selected});},[key,query,draft,page,selected]);
 const load=useLoad(()=>call<'directory.talent.search',DirectoryPage>('directory.talent.search',Object.fromEntries(Object.entries({...query,page,pageSize:20}).map(([k,v])=>[k,['ageMin','ageMax','heightMin','heightMax','page','pageSize'].includes(k)?Number(v):k==='ageUnknown'?String(v)==='true':v]))),JSON.stringify([query,page,tick,refresh]));
 useEffect(()=>{if(load.data&&page>1&&!load.data.items.length)setPage(Math.max(1,Math.ceil(load.data.total/20)));},[load.data,page]);
 const set=(k:string,v:string)=>setDraft(d=>({...d,[k]:v}));
 const label=(ns:string,code:string)=>catalog.find(c=>c.namespace===ns&&c.code===code)?.labelZh??code;
 const select=(key:string,title:string,options:[string,string][],counts?:Record<string,number>)=><Field label={title}><select value={draft[key]??''} onChange={e=>set(key,e.target.value)}><option value="">不限</option>{options.map(([code,label])=><option key={code} value={code}>{label}{counts?'（'+(counts[code]??0)+'）':''}</option>)}</select></Field>;
 const dictionary=(ns:string)=>catalog.filter(c=>c.namespace===ns&&c.status==='ACTIVE').map(c=>[c.code,c.labelZh] as [string,string]);
 return <section className="talent-directory" aria-label={surface==='candidate'?'候选找人':'统一人才目录'}>{surface==='library'&&<PageTitle overline="PEOPLE & TALENT" title="人才档案" description="按照片和当前资料找人，一个人保留同一份档案。" action={onCreate&&<button className="primary" onClick={onCreate}>＋ 新增人才</button>}/>}
 <form className="panel padded directory-filters" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(Object.fromEntries(Object.entries(draft).filter(([,v])=>v!=='')));}}><div className="form-grid">
 <Field label="搜索姓名或别名"><input maxLength={160} value={draft.q??''} onChange={e=>set('q',e.target.value)} placeholder="姓名、艺名、别名"/></Field>
 {select('mode','人物范围',[['ALL','全部人物'],['TALENT','人才'],['CONTACT','普通联系人']])}
 {select('role','职业',dictionary('role'),load.data?.facets.roles)}{select('gender','性别',['FEMALE','MALE','NON_BINARY','OTHER','UNKNOWN'].map(c=>[c,businessLabels[c]!] as [string,string]),load.data?.facets.genders)}
 {select('market','国模 / 外模',['DOMESTIC','INTERNATIONAL','UNCLASSIFIED'].map(c=>[c,businessLabels[c]!] as [string,string]),load.data?.facets.markets)}
 {select('experience','从业类型',['AMATEUR','PROFESSIONAL','UNSPECIFIED'].map(c=>[c,businessLabels[c]!] as [string,string]),load.data?.facets.experiences)}
 {select('location','城市',dictionary('city'),load.data?.facets.locations)}
 <Field label="年龄下限"><input type="number" min={0} max={130} value={draft.ageMin??''} onChange={e=>set('ageMin',e.target.value)}/></Field><Field label="年龄上限"><input type="number" min={0} max={130} value={draft.ageMax??''} onChange={e=>set('ageMax',e.target.value)}/></Field>
 <Field label="身高下限（厘米）"><input type="number" min={40} max={260} step="0.1" value={draft.heightMin??''} onChange={e=>set('heightMin',e.target.value)}/></Field><Field label="身高上限（厘米）"><input type="number" min={40} max={260} step="0.1" value={draft.heightMax??''} onChange={e=>set('heightMax',e.target.value)}/></Field>
 </div><details><summary>更多条件</summary><div className="form-grid">{select('nationality','国籍',dictionary('nationality'))}{select('style','风格标签',dictionary('roleStyle'))}{select('service','愿意参与的拍摄类型',dictionary('roleService'))}{select('language','工作语言',dictionary('language'))}{select('industryCode','作品行业',dictionary('industry'))}{select('workTypeCode','作品类型',dictionary('workType'))}{select('status','档案状态',[['DRAFT','草稿'],['ACTIVE','在库'],['ARCHIVED','归档']])}<label><input type="checkbox" checked={draft.ageUnknown==='true'} onChange={e=>{set('ageUnknown',e.target.checked?'true':'');if(e.target.checked){set('ageMin','');set('ageMax','');}}}/>只找年龄未知</label></div></details>
 <div className="detail-actions"><button type="submit" className="primary">组合找人</button><button type="button" onClick={()=>{setDraft({mode:'ALL'});setQuery({mode:'ALL'});setPage(1);}}>重置条件</button><button type="button" onClick={()=>setRefresh(x=>x+1)}>刷新</button></div><small className="muted">年龄范围须完整落在条件内；身高仅用当前已确认量尺。标签不代表既有经历。括号计数应用其他条件后按人数计算。</small></form>
 <ErrorBox error={load.error}/>{load.busy?<p>正在查询当前可见资料…</p>:load.data&&<><div className="directory-count"><strong>匹配 {load.data.total} 位</strong><span>本次已选 {selected.length} 位</span><button onClick={()=>setSelected([])}>清空选择</button></div><div className="people-grid photo-directory">{load.data.items.map(p=><article key={p.id} className="directory-card"><button className="person-card" onClick={()=>onOpen(p.id)}>{p.coverAssetId?<img className="directory-cover" loading="lazy" src={'/api/v1/assets/'+p.coverAssetId+'/preview'} alt={p.displayName+'的封面'}/>:<div className="directory-cover-placeholder">暂无封面照片</div>}<div className="directory-card-body"><div className="card-top"><h3>{p.displayName}</h3><Tag value={p.status}/></div><p>{p.roles.map(r=>label('role',r.roleCode)).join(' / ')||'普通联系人'}</p><p>{p.genderCode?businessLabels[p.genderCode]:'性别未知'} · {ageLabel(p.ageRange)}</p><p>{p.locations.map(l=>label('city',l.locationCode)).join(' / ')||'城市未知'} · {p.heightCm==null?'身高未知':p.heightCm+' cm'}</p><small>{p.roles.filter(r=>r.roleCode==='model').map(r=>businessLabels[r.castingMarketCode]+' · '+businessLabels[r.experienceCode]).join('')}</small></div></button><footer><label><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/>选择 {p.displayName}</label>{onPick&&<button onClick={()=>onPick(p)}>加入当前清单</button>}</footer></article>)}</div>{!load.data.items.length&&<Empty title="当前条件没有可见人才">可减少筛选条件或重置。未知值不会被当成符合；来源或权限失效的资料不计入结果。</Empty>}<Pager page={page} pageSize={20} total={load.data.total} setPage={setPage}/></>}</section>;
}
