import {useState} from 'react';
import {call,read} from './api.ts';
import {useAction,useLoad,ErrorBox,Field} from './ui.tsx';
import type {Receipt} from './dto.ts';
type ExposureRow={kind:'person'|'mediaAsset'|'mediaCollection'|'workCredit';id:string;field:string;label:string;revision:number;valueDigest?:string;status:'CLOSED'|'OPEN'|'UNAVAILABLE'|'RECHECK_REQUIRED';selectable:boolean};
type GrantView={id:string;revision:number;relation:string;state:string;rows:ExposureRow[]};
const states={CLOSED:'未开放',OPEN:'已开放',UNAVAILABLE:'来源或授权已失效',RECHECK_REQUIRED:'需要重新核对'};
const key=(r:ExposureRow)=>r.kind+':'+r.id+':'+r.field;
export function TalentHandoffPanel({personId}:{personId:string}){
 const [version,setVersion]=useState(0),[selected,setSelected]=useState<string[]>([]),[basis,setBasis]=useState(''),a=useAction();
 const data=useLoad(()=>read<{grants:GrantView[]}>('talent.handoff.get',{id:personId}),personId+':'+version);
 const groups={person:'基础资料',mediaAsset:'照片、视频及附件',mediaCollection:'模卡与作品集',workCredit:'本人案例与职业署名'};
 return <section className="panel padded talent-handoff"><h2>本人可见内容</h2><p>认领只确认人物关系。历史资料须逐项批准开放；开放案例只供本人查看，后续维护仍需本人真实同意。</p><button onClick={()=>{setSelected([]);setVersion(v=>v+1);}}>刷新归属与开放状态</button><ErrorBox error={a.error??data.error}/>{!data.data?.grants.length&&<p>尚无已确认的本人归属。请先邀请本人并审核归属申请。</p>}{data.data?.grants.map((g,index)=><section key={g.id} aria-label={'归属 '+(index+1)}><h3>{g.relation==='SELF'?'本人':'受托维护'} · {g.state==='ACTIVE'?'已认领':'授权已终止'}</h3>{Object.entries(groups).map(([kind,label])=><fieldset key={kind} disabled={a.busy||g.state!=='ACTIVE'}><legend>{label}</legend>{g.rows.filter(r=>r.kind===kind).map(r=><label className="check-chip" key={key(r)}><input type="checkbox" aria-label={r.label} disabled={!r.selectable} checked={selected.includes(g.id+':'+key(r))} onChange={e=>setSelected(old=>e.target.checked?[...old,g.id+':'+key(r)]:old.filter(k=>k!==g.id+':'+key(r)))}/>{r.label} · {states[r.status]}</label>)}{!g.rows.some(r=>r.kind===kind)&&<p>暂无可开放内容</p>}</fieldset>)}<Field label="本次开放或关闭依据"><textarea value={basis} onChange={e=>setBasis(e.target.value)} maxLength={2000}/></Field>{(['ALLOW','REVOKE'] as const).map(decision=><button key={decision} disabled={a.busy||g.state!=='ACTIVE'||basis.trim().length<4||!g.rows.some(r=>selected.includes(g.id+':'+key(r)))} onClick={()=>void a.run(async()=>{const rows=g.rows.filter(r=>selected.includes(g.id+':'+key(r)));await call<'talent.grant.exposure',Receipt>('talent.grant.exposure',{expectedRevision:g.revision,decision,fields:rows.filter(r=>r.kind==='person').map(r=>({field:r.field as 'displayName'|'aliases'|'intro',expectedValueDigest:r.valueDigest!})),assets:rows.filter(r=>r.kind==='mediaAsset').map(r=>({id:r.id,expectedRevision:r.revision})),collections:rows.filter(r=>r.kind==='mediaCollection').map(r=>({id:r.id,expectedRevision:r.revision})),credits:rows.filter(r=>r.kind==='workCredit').map(r=>({id:r.id,expectedRevision:r.revision})),approvalBasis:basis},{id:g.id});setSelected([]);setBasis('');setVersion(v=>v+1);})}>{decision==='ALLOW'?'批准开放所选内容':'关闭所选内容'}</button>)}</section>)}</section>;
}
