import {TalentMaintenanceHome} from './talent-maintenance-ui.tsx';
import {useEffect,useRef,useState} from 'react';
import type {TalentAccountMe as Me} from './dto.ts';
type Context={verifiedAccountId?:string|null;contextId:string;csrfToken:string;challenge?:{id:string;state:string;expiresAt:string}|null};
const messages:Record<string,string>={QUEUED:'验证码已排队',ACCEPTED:'发送服务已接收，请查看验证码',DELIVERED:'验证码已送达',UNKNOWN:'发送结果尚不确定，请先查看邮箱或短信。稍后可主动申请新验证码。',FAILED:'发送失败，可稍后重新申请',EXPIRED:'验证码已过期'};
async function request<T>(path:string,body?:unknown,csrf='',account=''):Promise<T>{
 const response=await fetch('/api/v1/portal'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-ONCE-Portal':'1','X-CSRF-Token':csrf,...(account?{'X-ONCE-Talent-Account':account}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
 const data=await response.json();if(!response.ok)throw new Error(data.error?.message??'请求未完成，请重试');return data as T;
}
export function TalentLogin(){
 const [invitationContext,setInvitationContext]=useState<string|null>(new URL(location.href).searchParams.get('invitation'));
 const keepUrl=(authContext?:string)=>{const u=new URL(location.href);u.hash='';if(authContext)u.searchParams.set('context',authContext);else u.searchParams.delete('context');history.replaceState(null,'',u.pathname+u.search);};
 const [me,setMe]=useState<Me|null>(null),[context,setContext]=useState<Context|null>(null),[kind,setKind]=useState<'EMAIL'|'PHONE'>('EMAIL'),[identity,setIdentity]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState('');const loaded=useRef(false);
 useEffect(()=>{if(loaded.current)return;loaded.current=true;void (async()=>{try{const fragment=new URLSearchParams(location.hash.slice(1));if(fragment.has('t')){const token=fragment.get('t'),invitationId=fragment.get('i');const clean=new URL(location.href);clean.hash='';for(const key of ['invitation','draft','context'])clean.searchParams.delete(key);setInvitationContext(null);history.replaceState(null,'',clean.pathname+clean.search);try{const r=await request<{contextId:string}>('/invitations/exchange',{invitationId,token});setInvitationContext(r.contextId);const u=new URL(location.href);u.searchParams.set('invitation',r.contextId);history.replaceState(null,'',u.pathname+u.search);}catch(e){setError(e instanceof Error?e.message:'邀请尚未确认，请重新打开邀请链接');}}setMe(await request<Me>('/me'));}catch{const id=new URL(location.href).searchParams.get('context');if(id&&/^[a-f0-9-]{36}$/.test(id))try{const c=await request<Context>('/auth/contexts/'+id);setContext(c);if(c.challenge)setStatus(messages[c.challenge.state]??'请输入验证码');}catch{keepUrl();}}finally{setBusy(false);}})();},[]);
 const run=async(work:()=>Promise<void>)=>{setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'操作未完成');}finally{setBusy(false);}};
 const start=async()=>{const c=await request<Context>('/auth/context',{purpose:'LOGIN'});setContext(c);keepUrl(c.contextId);return c;};
 return <main className="talent-login"><section className="panel padded"><p className="eyebrow">ONCE · 人才账号</p><h1>{me?'已登录':'登录人才账号'}</h1>{me?<><p>您的独立人才账号已登录。</p><TalentMaintenanceHome me={me} invitationContext={invitationContext}/><button disabled={busy} onClick={()=>void run(async()=>{await request('/auth/logout',{},me.csrfToken,me.talentAccountId);setMe(null);setContext(null);setCode('');setStatus('已退出登录');keepUrl();})}>退出登录</button></>:<><p>使用邮箱或手机号接收验证码。首次验证成功会建立人才账号。</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{const c=context??await start();const challenge=await request<{id:string;state:string;expiresAt:string}>('/auth/challenges',{contextId:c.contextId,purpose:'LOGIN',kind,identity},c.csrfToken);setContext({...c,challenge});setCode('');setStatus(messages[challenge.state]??'请查看验证码');});}}><label>联系方式类型<select value={kind} disabled={busy} onChange={e=>setKind(e.target.value as 'EMAIL'|'PHONE')}><option value="EMAIL">邮箱</option><option value="PHONE">手机号</option></select></label><label>{kind==='EMAIL'?'邮箱地址':'手机号（含国际区号）'}<input required type={kind==='EMAIL'?'email':'tel'} autoComplete={kind==='EMAIL'?'email':'tel'} maxLength={320} value={identity} disabled={busy} onChange={e=>setIdentity(e.target.value)} placeholder={kind==='EMAIL'?'name@example.com':'+8613800000000'}/></label><button disabled={busy}>{context?.challenge?'申请新验证码':'发送验证码'}</button></form>{context?.challenge&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{try{await request('/auth/verify',{contextId:context.contextId,challengeId:context.challenge!.id,purpose:'LOGIN',code},context.csrfToken);}catch(e){try{const current=await request<Me>('/me'),verified=await request<Context>('/auth/contexts/'+context.contextId);if(verified.verifiedAccountId!==current.talentAccountId)throw e;setMe(current);setCode('');keepUrl();return;}catch{throw e;}}setCode('');setMe(await request<Me>('/me'));keepUrl();});}}><label>六位验证码<input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} value={code} disabled={busy} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy}>验证并登录</button></form>}<p>刷新页面不会重新发送验证码；新验证码会使旧验证码失效。</p></>}{status&&<p role="status">{status}</p>}{error&&<p role="alert">{error}</p>}{busy&&<p aria-live="polite">正在处理…</p>}</section></main>;
}
