import {useState} from 'react';
import type {Me,CatalogItem} from './dto.ts';
import {read} from './api.ts';
import type {TalentDetail,TalentFact,TalentFactKind,TalentSchema} from './talent-dto.ts';
import {TALENT_SECTIONS,TALENT_LABELS} from './talent-fields.ts';
import {TalentFactEditor} from './talent-edit.tsx';
import {TalentFieldEvidence,TalentProposals,TalentEvidenceHistory} from './talent-evidence.tsx';
import {TalentReview,textValue} from './talent-ui.tsx';
import {ErrorBox,useLoad} from './ui.tsx';
export function TalentBasicSections({detail,me,catalog,onSaved}:{detail:TalentDetail;me:Me;catalog:CatalogItem[];onSaved:()=>void}){
 const [edit,setEdit]=useState<{kind:TalentFactKind;row?:TalentFact}|null>(null),[review,setReview]=useState<{kind:TalentFactKind;row:TalentFact;action:string}|null>(null),[proposal,setProposal]=useState<{kind:TalentFactKind;row:TalentFact;mode:'proposal'|'evidence'}|null>(null),[history,setHistory]=useState<{kind:TalentFactKind;ownerId:string}|null>(null),[proposals,setProposals]=useState(false);
 const schema=useLoad(()=>read<TalentSchema>('td2.schema'),'basic-schema'),canWrite=detail.canEdit&&detail.status!=='ARCHIVED',canReview=me.permissions.includes('sources.review');
 const saved=()=>{setEdit(null);setReview(null);setProposal(null);onSaved();};
 if(edit&&schema.data)return <TalentFactEditor {...edit} detail={detail} catalog={catalog} schema={schema.data} inline onClose={()=>setEdit(null)} onSaved={saved}/>;
 if(review)return <TalentReview {...review} detail={detail} onClose={()=>setReview(null)} onSaved={saved}/>;
 if(proposal&&schema.data)return <TalentFieldEvidence {...proposal} detail={detail} catalog={catalog} schema={schema.data} onClose={()=>setProposal(null)} onSaved={saved}/>;
 if(history)return <TalentEvidenceHistory {...history} onClose={()=>setHistory(null)}/>;
 if(proposals)return <TalentProposals detail={detail} me={me} onClose={()=>setProposals(false)} onSaved={onSaved}/>;
 const kinds:TalentFactKind[]=['personRoles','personLanguages','talentLocations','personCapabilities','castingProfiles','measurementSets','representations','personCredentials','adultEligibilities','translatorLanguagePairs','translatorServiceModes','personExternalRefs'];
 return <div className="basic-sections"><ErrorBox error={schema.error}/>{canReview&&<button onClick={()=>setProposals(true)}>查看待处理修改建议</button>}{schema.data&&kinds.filter(k=>detail.isTalent||detail.facts[k].length).filter(k=>!['castingProfiles','measurementSets','adultEligibilities'].includes(k)||detail.facts.personRoles.some(r=>r.usable&&['model','actor'].includes(String(r.roleCode)))||detail.facts[k].length).filter(k=>!k.startsWith('translator')||detail.facts.personRoles.some(r=>r.usable&&r.roleCode==='translator')||detail.facts[k].length).map(kind=>{const section=TALENT_SECTIONS[kind],rows=detail.facts[kind];return <details className="panel padded basic-section" key={kind} open={rows.length>0||['personRoles','personLanguages','talentLocations'].includes(kind)}><summary><strong>{section.title}</strong><span className="muted">{rows.length?rows.length+'条记录':'尚未填写'}</span></summary><div><div className="section-heading"><h2>{section.title}</h2>{canWrite&&kind!=='measurementSets'&&!(kind==='castingProfiles'&&rows.length)&&<button onClick={()=>setEdit({kind})}>新增{section.title}</button>}</div>{!rows.length&&<p className="muted">尚未填写</p>}{rows.map(row=><article className="basic-fact" key={row.id}><span className="tag">{TALENT_LABELS[String(row.status??row.state)]??'已记录'}</span>{!row.usable&&<span className="notice-inline">当前不可用于筛选</span>}<dl className="detail-grid">{section.fields.filter(f=>!f.proposalOnly||row.roleCode==='model').filter(f=>row[f.key]!==null&&row[f.key]!==undefined&&row[f.key]!=='').map(f=><div key={f.key}><dt>{f.label}</dt><dd>{row.unavailableFields.includes(f.key)?'当前不可读':textValue(f.key,row[f.key],detail,catalog,schema.data!)}</dd></div>)}</dl><div className="button-row">{canWrite&&!(kind==='measurementSets'&&row.status!=='DRAFT')&&<><button onClick={()=>setEdit({kind,row})}>编辑{section.title}</button><button onClick={()=>setProposal({kind,row,mode:'proposal'})}>补充新资料</button></>}{canReview&&canWrite&&kind==='measurementSets'&&row.status==='DRAFT'&&<button onClick={()=>setReview({kind,row,action:'confirm'})}>确认量尺</button>}{canReview&&canWrite&&kind==='adultEligibilities'&&row.status==='ACTIVE'&&<button onClick={()=>setReview({kind,row,action:'verify'})}>核验成年资格</button>}{canReview&&canWrite&&['personCredentials','personExternalRefs'].includes(kind)&&<><button onClick={()=>setReview({kind,row,action:'verify'})}>核验{section.title}</button><button onClick={()=>setReview({kind,row,action:'revoke'})}>撤销核验</button></>}{canWrite&&kind==='personCredentials'&&me.permissions.includes('sensitive.write')&&<button onClick={()=>setReview({kind,row,action:'identifier'})}>维护受限编号</button>}</div><details><summary>来源与依据</summary><div className="button-row">{canReview&&<button onClick={()=>setProposal({kind,row,mode:'evidence'})}>核对字段依据</button>}{me.permissions.includes('sources.read')&&me.permissions.includes('sensitive.read')&&<button onClick={()=>setHistory({kind,ownerId:row.id})}>查看依据历史</button>}</div></details></article>)}</div></details>;})}</div>;
}
