import {useState} from 'react';
import {call,read} from './api.ts';
import type {CatalogItem,Me,Page,Source} from './dto.ts';
import {ErrorBox,Field,Modal,Pager,useAction,useLoad} from './ui.tsx';
import {TALENT_VERSION,type TalentDetail,type TalentFact,type TalentFactKind,type TalentSchema} from './talent-dto.ts';
import {TALENT_LABELS,TALENT_SECTIONS} from './talent-fields.ts';
import {TalentSourceChoice,TalentValueInput,talentInputValue,outcomeUnknown} from './talent-edit.tsx';
export function TalentFieldEvidence({kind,row,detail,catalog,schema,mode,onClose,onSaved}:{kind:TalentFactKind;row:TalentFact;detail:TalentDetail;catalog:CatalogItem[];schema:TalentSchema;mode:'evidence'|'proposal';onClose:()=>void;onSaved:()=>void}) {
 const fields=TALENT_SECTIONS[kind].fields.filter(f=>!row.unavailableFields.includes(f.key)&&(mode==='evidence'||!f.immutable));
 const [fieldKey,setFieldKey]=useState(fields[0]?.key??''),[value,setValue]=useState(''),[source,setSource]=useState<Source|null>(null),[ack,setAck]=useState(false),action=useAction(),freeze=action.busy||outcomeUnknown(action.error),field=fields.find(f=>f.key===fieldKey);
 const close=()=>{if(freeze)return;if((source||value)&&!window.confirm('这次内容尚未提交，确定关闭？'))return;onClose();};
 return <Modal title={mode==='evidence'?'核验字段依据':'提交字段修改建议'} onClose={close} wide><form onSubmit={e=>{e.preventDefault();if(!source||!field||!ack)return;void action.run(async()=>{const input={schemaVersion:TALENT_VERSION,ownerKind:kind,ownerId:row.id,fieldPath:field.key,expectedRevision:row.revision,sourceId:source.id,sourceRevision:source.revision};if(mode==='evidence')await call('td2.evidence',input);else await call('td2.proposal.create',{...input,proposedValue:talentInputValue(field,value)});onSaved();});}}><div className="modal-body"><ErrorBox error={action.error}/><p className="notice">{mode==='evidence'?'核对所选字段与独立证据是否一致。不会代替成年资格或资质证明的专门核验。':'建议不会立即改写正式资料。经当前有权成员确认后才可能采用，冲突和已过期依据需重新核对。'}</p><fieldset disabled={freeze}><Field label="需要核对的字段"><select value={fieldKey} onChange={e=>{setFieldKey(e.target.value);setValue('');setAck(false);}}>{fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></Field><p>当前记录：{row[fieldKey]==null?'未确认':TALENT_LABELS[String(row[fieldKey])]??String(row[fieldKey])}</p>{mode==='proposal'&&field&&<TalentValueInput key={field.key} field={{...field,label:'建议的'+field.label}} value={value} onChange={setValue} detail={detail} catalog={catalog} schema={schema}/>}</fieldset><TalentSourceChoice value={source} onChange={setSource} disabled={freeze}/><fieldset disabled={freeze}><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>我已核对字段内容与本次依据</label></fieldset>{outcomeUnknown(action.error)&&<p className="notice">结果未知，请保留表单并原样重试。</p>}</div><footer className="modal-footer"><button type="button" disabled={freeze} onClick={close}>取消</button><button type="submit" className="primary" disabled={action.busy||!source||!field||!ack}>{outcomeUnknown(action.error)?'原样重试':mode==='evidence'?'确认字段依据':'提交建议'}</button></footer></form></Modal>;
}
interface Proposal {id:string;revision:number;state:string;fieldPath:string;proposedValue:unknown;createdAt:string;sourceId:string;[key:string]:unknown}
const ownerKeys:Record<TalentFactKind,string>={talentProfiles:'talentProfileId',personRoles:'personRoleId',personCapabilities:'personCapabilityId',personLanguages:'personLanguageId',talentLocations:'talentLocationId',castingProfiles:'castingProfileId',measurementSets:'measurementSetId',adultEligibilities:'adultEligibilityId',representations:'representationId',personExternalRefs:'personExternalRefId',personCredentials:'personCredentialId',translatorLanguagePairs:'translatorLanguagePairId',translatorServiceModes:'translatorServiceModeId',mediaCollections:'mediaCollectionId',mediaCollectionTags:'mediaCollectionTagId'};
export function TalentProposals({detail,me,onClose,onSaved}:{detail:TalentDetail;me:Me;onClose:()=>void;onSaved:()=>void}) {
 const [page,setPage]=useState(1),[selection,setSelection]=useState<{row:Proposal;decision:'APPLY'|'REJECT'}|null>(null),[ack,setAck]=useState(false),action=useAction(),freeze=action.busy||outcomeUnknown(action.error);
 const basis=useLoad(()=>selection?read<Source>('source.get',{id:selection.row.sourceId}):Promise.resolve(null),selection?.row.id??'none');
 const load=useLoad(()=>read<Page<Proposal>>('td2.proposal.list',{}, {personId:detail.id,page:String(page),pageSize:'10'}),detail.id+':'+page);
 return <Modal title="待审字段建议" onClose={()=>{if(!freeze)onClose();}} wide><div className="modal-body"><ErrorBox error={action.error??load.error}/>{load.busy?<p>正在读取可见建议…</p>:load.data?.items.map(row=>{const kind=(Object.keys(ownerKeys) as TalentFactKind[]).find(k=>row[ownerKeys[k]]);const label=kind?TALENT_SECTIONS[kind].fields.find(f=>f.key===row.fieldPath)?.label??row.fieldPath:row.fieldPath;return <article key={row.id} className="talent-fact"><h3>{kind?TALENT_SECTIONS[kind].title:'人物资料'} · {label}</h3><p>{Array.isArray(row.proposedValue)?row.proposedValue.join(' / '):row.proposedValue==null?'未确认':TALENT_LABELS[String(row.proposedValue)]??String(row.proposedValue)}</p><p>{row.state==='PENDING'?'待审核':row.state==='APPLIED'?'已采用':row.state==='REJECTED'?'已拒绝':'需要重新核对'}</p>{row.state==='PENDING'&&me.permissions.includes('records.write')&&<><button disabled={freeze} onClick={()=>{setSelection({row,decision:'APPLY'});setAck(false);}}>采用建议</button><button disabled={freeze} onClick={()=>{setSelection({row,decision:'REJECT'});setAck(false);}}>拒绝建议</button></>}</article>;})}{load.data&&!load.data.items.length&&<p>暂无当前可见的字段建议。</p>}{!freeze&&load.data&&<Pager page={page} pageSize={10} total={load.data.total} setPage={setPage}/>} {selection&&<form onSubmit={e=>{e.preventDefault();if(!ack)return;void action.run(async()=>{await call('td2.proposal.decide',{schemaVersion:TALENT_VERSION,expectedRevision:selection.row.revision,decision:selection.decision},{id:selection.row.id});onSaved();});}}><ErrorBox error={basis.error}/>{basis.data&&<div className="notice"><strong>建议依据：{basis.data.title}</strong><p className="pre-line">{basis.data.basisDescription}</p><p>有效期截止：{new Date(basis.data.validUntil).toLocaleString('zh-CN')}</p></div>}<fieldset disabled={freeze}><p>本次决定：{selection.decision==='APPLY'?'采用':'拒绝'}所选建议。依据或资料版本发生变化时，服务端会要求重新核对。</p><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>我已核对建议和依据</label></fieldset><button type="submit" className="primary" disabled={action.busy||!ack||basis.busy||!basis.data}>{outcomeUnknown(action.error)?'原样重试':'确认审核决定'}</button></form>}</div><footer className="modal-footer"><button disabled={freeze} onClick={onClose}>返回工作台</button></footer></Modal>;
}

export function TalentEvidenceHistory({ kind, ownerId, onClose }: { kind: TalentFactKind | 'person'; ownerId: string; onClose: () => void }) {
 const fields=kind==='person'?[{key:'displayName',label:'姓名'},{key:'intro',label:'简介'},{key:'aliases',label:'别名'}]:TALENT_SECTIONS[kind].fields;
 const [field,setField]=useState(fields[0]!.key),[page,setPage]=useState(1),[tick,setTick]=useState(0);
 const load=useLoad(()=>read<Page<import('./talent-dto.ts').TalentEvidenceRecord>>('td2.evidence.list',{}, {ownerKind:kind,ownerId,fieldPath:field,page:String(page),pageSize:'10'}),ownerId+':'+field+':'+page+':'+tick);
 return <Modal title="字段依据记录" wide onClose={onClose}><div className="modal-body"><p className="notice">只显示当前范围内可查的来源。历史核验不等于当前值仍有依据，也不能代替资质或成年资格的专门核验。</p><Field label="查看字段"><select value={field} onChange={e=>{setField(e.target.value);setPage(1);}}>{fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></Field><ErrorBox error={load.error}/>{load.busy?<p>正在核对来源与当前字段…</p>:load.data?.items.map(row=><article className="talent-fact" key={row.id}><h3>{row.source.title}</h3><p><strong>{row.supportsCurrentValue?'当前值有此依据':'历史记录，不能作为当前依据'}</strong></p><dl className="detail-grid"><div><dt>与当前字段值</dt><dd>{row.valueMatchesCurrent?'一致':'不一致，字段已有变化'}</dd></div><div><dt>来源状态</dt><dd>{row.source.current?'当前有效':'已暂停或过期'}</dd></div><div><dt>来源版本</dt><dd>记录时 {row.source.recordedRevision} / 当前 {row.source.currentRevision}{!row.source.revisionMatches?'，需要重新核对':''}</dd></div><div><dt>核验记录</dt><dd>{row.review?(row.review.origin==='ORIGINAL'?'原环境核验，未改记为当前账号':'当前环境核验'):'仅记录依据，尚未人工核验'}</dd></div></dl>{row.review?.reviewedAt&&<p>核验时间：{new Date(row.review.reviewedAt).toLocaleString('zh-CN',{hour12:false})}</p>}{row.review?.membershipId&&<details><summary>查看核验归属编号</summary><p>环境：{row.review.workspaceId}</p><p>核验成员：{row.review.membershipId}</p></details>}<small>记录于 {new Date(row.createdAt).toLocaleString('zh-CN',{hour12:false})}</small></article>)}{!load.busy&&load.data&&!load.data.items.length&&<p>这个字段暂无当前可见的依据记录。</p>}{load.data&&<Pager page={page} pageSize={10} total={load.data.total} setPage={setPage}/>}</div><footer className="modal-footer"><button onClick={onClose}>返回专业工作台</button><button disabled={load.busy} onClick={()=>setTick(t=>t+1)}>重新核对依据</button></footer></Modal>;
}
