import {useState} from 'react';
import {call} from './api.ts';
import {ErrorBox,Field,Modal,useAction} from './ui.tsx';
import {TALENT_VERSION,type TalentDetail,type TalentFact} from './talent-dto.ts';
import {TalentRelationChoice,outcomeUnknown} from './talent-edit.tsx';
interface Item {id:string;assetId:string;caption:string;featured:boolean;orderIndex:number;asset:{fileName:string}}
export function TalentCollectionEditor({detail,row,onClose,onSaved}:{detail:TalentDetail;row:TalentFact;onClose:()=>void;onSaved:()=>void}) {
 const items=(Array.isArray(row.items)?row.items:[]) as Item[];
 const [mode,setMode]=useState<'add'|'remove'|'order'>('add'),[assetId,setAssetId]=useState(''),[assetLabel,setAssetLabel]=useState(''),[caption,setCaption]=useState(''),[featured,setFeatured]=useState(false),[removeId,setRemoveId]=useState(''),[order,setOrder]=useState(items.map(i=>i.id)),[ack,setAck]=useState(false);
 const action=useAction(),freeze=action.busy||outcomeUnknown(action.error),dirty=assetId!==''||removeId!==''||order.join()!==items.map(i=>i.id).join();
 const close=()=>{if(freeze)return;if(dirty&&!window.confirm('尚未保存集合调整，确定关闭？'))return;onClose();};
 return <Modal title={'整理集合 · '+String(row.title)} onClose={close} wide><form onSubmit={e=>{e.preventDefault();if(!ack)return;void action.run(async()=>{const input={schemaVersion:TALENT_VERSION,expectedRevision:row.revision,expectedPersonRevision:detail.revision};if(mode==='add')await call('td2.collection.add',{...input,assetId,caption,featured},{id:row.id});else if(mode==='remove')await call('td2.collection.remove',{...input,itemId:removeId},{id:row.id});else await call('td2.collection.order',{...input,itemIds:order},{id:row.id});onSaved();});}}><div className="modal-body"><ErrorBox error={action.error}/><p className="notice">只调整此集合内的关联与顺序。移出集合不会删除原文件，也不影响它在其他集合或证明中的使用。</p><fieldset disabled={freeze}><nav className="talent-tabs" aria-label="集合操作">{(['add','remove','order'] as const).map((m,i)=><button type="button" key={m} aria-pressed={mode===m} onClick={()=>{setMode(m);setAck(false);}}>{['添加素材','移出素材','调整顺序'][i]}</button>)}</nav>
 {mode==='add'?<><p>{assetId?'已选：'+assetLabel:'请选择现有素材'}</p><TalentRelationChoice kind="asset" value={assetId} onChange={(id,label)=>{setAssetId(id);setAssetLabel(label);}}/><Field label="图片说明"><textarea value={caption} maxLength={1000} onChange={e=>setCaption(e.target.value)}/></Field><label><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/>作为推荐素材</label></>:<ol className="talent-collection-items">{order.map((id,index)=>{const item=items.find(i=>i.id===id)!;return <li key={id}><img className="private-preview" loading="lazy" src={'/api/v1/assets/'+item.assetId+'/preview'} alt={item.asset.fileName}/><div><strong>{item.asset.fileName}</strong><p>{item.caption||'未填写说明'}{item.featured?' · 推荐':''}</p>{mode==='remove'?<label><input type="radio" name="remove-item" checked={removeId===id} onChange={()=>setRemoveId(id)}/>移出此素材</label>:<><button type="button" disabled={index===0} aria-label={'上移 '+item.asset.fileName} onClick={()=>setOrder(o=>{const next=[...o];[next[index-1],next[index]]=[next[index]!,next[index-1]!];return next;})}>上移</button><button type="button" disabled={index===order.length-1} aria-label={'下移 '+item.asset.fileName} onClick={()=>setOrder(o=>{const next=[...o];[next[index+1],next[index]]=[next[index]!,next[index+1]!];return next;})}>下移</button></>}</div></li>;})}</ol>}
 <label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>我确认本次集合调整</label></fieldset>{outcomeUnknown(action.error)&&<p className="notice">结果未知，请原样重试核对同一笔操作。</p>}</div><footer className="modal-footer"><button type="button" disabled={freeze} onClick={close}>取消</button><button type="submit" className="primary" disabled={action.busy||!ack||(mode==='add'?!assetId:mode==='remove'?!removeId:!order.length)}>{outcomeUnknown(action.error)?'原样重试':'保存集合调整'}</button></footer></form></Modal>;
}
