import {TalentInvitationPanel} from './talent-review-ui.tsx';
import {useState} from 'react';
import {call,read} from './api.ts';
import type {Inputs} from './generated/requests.ts';
import type {CatalogItem,Me,Page,Receipt,Source} from './dto.ts';
import type {TalentDetail,TalentFact} from './talent-dto.ts';
import {ErrorBox,Field,Modal,PageTitle,Pager,useAction,useLoad,date as displayDate} from './ui.tsx';
import {outcomeUnknown} from './talent-edit.tsx';
import {MediaPanel} from './media-ui.tsx';
import {PersonProductionPanel} from './production-ui.tsx';
import {TALENT_LABELS} from './talent-fields.ts';
import {businessLabels,ageLabel} from './talent-directory.tsx';
import type {Selection} from './production-dto.ts';
type Update=Inputs['directory.talent.update'];
interface Photo{id:string;fileName:string;mime:string;state:string}
const profileOf=(d:TalentDetail)=>d.facts.talentProfiles.find(r=>r.status==='ACTIVE')??null;
function CoreForm({detail,source,me,catalog,onClose,onSaved}:{detail:TalentDetail;source:Source;me:Me;catalog:CatalogItem[];onClose:()=>void;onSaved:()=>void}){
 const profile=profileOf(detail),model=detail.facts.personRoles.find(r=>r.usable&&r.roleCode==='model'),city=detail.facts.talentLocations.find(r=>r.usable&&r.relationCode==='BASE');
 const [values,setValues]=useState<Record<string,unknown>>({genderCode:profile?.genderCode??null,birthPrecision:profile?.birthPrecision??'UNKNOWN',birthYear:profile?.birthYear??null,minAgeYears:profile?.minAgeYears??null,maxAgeYears:profile?.maxAgeYears??null,ageAsOfDate:profile?.ageAsOfDate??null,nationalityCodes:profile?.nationalityCodes??[],...(me.permissions.includes('sensitive.read')&&me.permissions.includes('sensitive.write')?{birthDate:profile?.birthDate??null}:{})});
 const [roles,setRoles]=useState<Record<string,unknown>>({castingMarketCode:model?.castingMarketCode??'UNCLASSIFIED',experienceCode:model?.experienceCode??'UNSPECIFIED',styleCodes:model?.styleCodes??[],serviceCodes:model?.serviceCodes??[]});
 const [location,setLocation]=useState(String(city?.locationCode??'')),[height,setHeight]=useState(''),[sizes,setSizes]=useState<Record<string,string>>({}),[date,setDate]=useState(''),[precision,setPrecision]=useState<'UNKNOWN'|'EXACT_DAY'|'APPROXIMATE'>('UNKNOWN'),[measure,setMeasure]=useState(false),[confirmMeasure,setConfirm]=useState(false);
 const action=useAction(),frozen=action.busy||outcomeUnknown(action.error),set=(k:string,v:unknown)=>setValues(d=>({...d,[k]:v}));
 const canBirth=me.permissions.includes('sensitive.write')&&me.permissions.includes('sensitive.read');
 const changeBirth=(v:string)=>setValues(d=>({...d,birthPrecision:v,birthYear:null,minAgeYears:null,maxAgeYears:null,ageAsOfDate:null,...(canBirth?{birthDate:null}:{})}));
 const chips=(ns:string,key:string,data:Record<string,unknown>,change:(r:Record<string,unknown>)=>void)=>catalog.filter(c=>c.namespace===ns&&(c.status==='ACTIVE'||(data[key] as string[]).includes(c.code))).map(c=><label className="check-chip" key={c.code}><input type="checkbox" checked={(data[key] as string[]).includes(c.code)} disabled={c.status!=='ACTIVE'&&!(data[key] as string[]).includes(c.code)} onChange={e=>change({...data,[key]:e.target.checked?[...(data[key] as string[]),c.code]:(data[key] as string[]).filter(x=>x!==c.code)})}/>{c.labelZh}{c.status!=='ACTIVE'?'（停用）':''}</label>);
 return <Modal title="补充核心资料" onClose={()=>{if(!frozen)onClose();}} wide><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{
  const profileValues={...values};if(!canBirth&&profile?.birthPrecision==='EXACT_DATE')for(const key of ['birthPrecision','birthYear','minAgeYears','maxAgeYears','ageAsOfDate'])delete profileValues[key];
  const original={genderCode:profile?.genderCode??null,birthPrecision:profile?.birthPrecision??'UNKNOWN',birthDate:profile?.birthDate??null,birthYear:profile?.birthYear??null,minAgeYears:profile?.minAgeYears??null,maxAgeYears:profile?.maxAgeYears??null,ageAsOfDate:profile?.ageAsOfDate??null,nationalityCodes:profile?.nationalityCodes??[]};
  const profilePatch=Object.fromEntries(Object.entries(profileValues).filter(([k,v])=>JSON.stringify(v)!==JSON.stringify(original[k as keyof typeof original])));
  const modelPatch=Object.fromEntries(Object.entries(roles).filter(([k,v])=>JSON.stringify(v)!==JSON.stringify(model?.[k])));
  if(!Object.keys(profilePatch).length&&!Object.keys(modelPatch).length&&location===String(city?.locationCode??'')&&!measure){onSaved();return;}
  const input:Update={schemaVersion:'once-talent-experience-v1',expectedRevision:detail.revision,sourceId:source.id,sourceRevision:source.revision,...(Object.keys(profilePatch).length?{profile:profilePatch}:{}),...(location!==String(city?.locationCode??'')?{locationCode:location||null}:{}),...(model&&Object.keys(modelPatch).length?{model:modelPatch}:{}),...(measure?{measurement:{heightCm:height===''?null:Number(height),...Object.fromEntries(Object.entries(sizes).map(([k,v])=>[k,v===''?null:k.endsWith('Cm')?Number(v):v])),measuredOn:precision==='UNKNOWN'?null:date,datePrecision:precision,supersedesId:(detail.facts.castingProfiles.find(r=>r.usable)?.currentMeasurementSetId as string|null)??null},confirmMeasurement:confirmMeasure}:{})};
  await call<'directory.talent.update',Receipt>('directory.talent.update',input,{id:detail.id});onSaved();
 });}}><div className="modal-body"><ErrorBox error={action.error}/><fieldset disabled={frozen}><div className="form-grid">
 <Field label="性别"><select value={String(values.genderCode??'')} onChange={e=>set('genderCode',e.target.value||null)}><option value="">未知</option>{['FEMALE','MALE','NON_BINARY','OTHER'].map(c=><option key={c} value={c}>{businessLabels[c]}</option>)}</select></Field>
 <Field label="出生信息精度" hint="只记录明确收到的资料；年龄区间不等于成年资格。"><select value={String(values.birthPrecision)} disabled={!canBirth&&profile?.birthPrecision==='EXACT_DATE'} onChange={e=>changeBirth(e.target.value)}>{['UNKNOWN',...(canBirth||profile?.birthPrecision==='EXACT_DATE'?['EXACT_DATE']:[]),'YEAR_ONLY','DECLARED_RANGE'].map(c=><option key={c} value={c}>{businessLabels[c]}</option>)}</select></Field>
 {values.birthPrecision==='EXACT_DATE'&&canBirth&&<Field label="出生日期（受限）"><input required type="date" value={String(values.birthDate??'')} onChange={e=>set('birthDate',e.target.value||null)}/></Field>}
 {values.birthPrecision==='YEAR_ONLY'&&<Field label="出生年份"><input required type="number" min={1900} max={new Date().getFullYear()} value={String(values.birthYear??'')} onChange={e=>set('birthYear',e.target.value===''?null:Number(e.target.value))}/></Field>}
 {values.birthPrecision==='DECLARED_RANGE'&&<><Field label="声明年龄下限"><input required type="number" min={0} max={130} value={String(values.minAgeYears??'')} onChange={e=>set('minAgeYears',e.target.value===''?null:Number(e.target.value))}/></Field><Field label="声明年龄上限"><input required type="number" min={0} max={130} value={String(values.maxAgeYears??'')} onChange={e=>set('maxAgeYears',e.target.value===''?null:Number(e.target.value))}/></Field><Field label="年龄声明日期"><input required type="date" value={String(values.ageAsOfDate??'')} onChange={e=>set('ageAsOfDate',e.target.value||null)}/></Field></>}
 <Field label="常驻城市"><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">未知</option>{catalog.filter(c=>c.namespace==='city'&&(c.status==='ACTIVE'||c.code===location)).map(c=><option key={c.code} value={c.code}>{c.labelZh}</option>)}</select></Field>
 {model&&<><Field label="国模 / 外模" hint="业务分类与国籍独立，不能从照片判断。"><select value={String(roles.castingMarketCode)} onChange={e=>setRoles(d=>({...d,castingMarketCode:e.target.value}))}>{['UNCLASSIFIED','DOMESTIC','INTERNATIONAL'].map(c=><option key={c} value={c}>{businessLabels[c]}</option>)}</select></Field><Field label="从业类型"><select value={String(roles.experienceCode)} onChange={e=>setRoles(d=>({...d,experienceCode:e.target.value}))}>{['UNSPECIFIED','AMATEUR','PROFESSIONAL'].map(c=><option key={c} value={c}>{businessLabels[c]}</option>)}</select></Field></>}
 <Field label="国籍声明" wide hint="没有明确声明时不选；业务分类不会自动填入国籍。"><div className="check-grid">{chips('nationality','nationalityCodes',values,setValues)}</div></Field>
 {model&&<><Field label="模特风格标签" wide><div className="check-grid">{chips('roleStyle','styleCodes',roles,setRoles)}</div></Field><Field label="愿意参与的拍摄类型" wide hint="意愿不等于已拍摄经历。"><div className="check-grid">{chips('roleService','serviceCodes',roles,setRoles)}</div></Field></>}
 </div>{model&&<><label><input type="checkbox" checked={measure} onChange={e=>setMeasure(e.target.checked)}/>新增一份量尺记录</label>{measure&&<div className="form-grid"><Field label="本次身高（厘米）"><input type="number" min={40} max={260} step="0.1" value={height} onChange={e=>setHeight(e.target.value)}/></Field>{[['bustCm','胸围（厘米）'],['waistCm','腰围（厘米）'],['hipsCm','臀围（厘米）']].map(([key,title])=><Field key={key} label={title!}><input type="number" min={20} max={250} step="0.1" value={sizes[key!]??''} onChange={e=>setSizes(s=>({...s,[key!]:e.target.value}))}/></Field>)}{[['shoe','鞋码',['EU','US','UK','CN']],['clothing','服装尺码',['INTL','EU','US','UK','CN']]].map(([key,title,systems])=><Field key={String(key)} label={String(title)}><input maxLength={30} value={sizes[key+'SizeValue']??''} onChange={e=>setSizes(s=>({...s,[key+'SizeValue']:e.target.value}))}/><select aria-label={title+'体系'} value={sizes[key+'SizeSystem']??''} onChange={e=>setSizes(s=>({...s,[key+'SizeSystem']:e.target.value}))}><option value="">体系未知</option>{(systems as string[]).map(c=><option key={c} value={c}>{c}</option>)}</select></Field>)}<Field label="量尺日期精度"><select value={precision} onChange={e=>{setPrecision(e.target.value as typeof precision);if(e.target.value==='UNKNOWN')setDate('');}}><option value="UNKNOWN">日期未知</option><option value="EXACT_DAY">准确日期</option><option value="APPROXIMATE">大约日期</option></select></Field>{precision!=='UNKNOWN'&&<Field label="量尺日期"><input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field>}{me.permissions.includes('sources.review')&&<label><input type="checkbox" checked={confirmMeasure} disabled={source.status!=='CONFIRMED'} onChange={e=>setConfirm(e.target.checked)}/>我已核对本次量尺，设为当前记录</label>}<p className="muted">已确认量尺不会原地覆盖，新记录保留历史。日期未知时保持为空；未确认记录不用于身高筛选。来源须先经明确核对，才能确认量尺。</p></div>}</>}</fieldset>{outcomeUnknown(action.error)&&<p role="status">结果尚不明确，原资料已冻结，请核对原提交。</p>}</div><footer className="modal-footer"><button type="button" disabled={frozen} onClick={onClose}>取消</button><button className="primary" type="submit" disabled={action.busy}>{action.busy?'正在保存…':outcomeUnknown(action.error)?'核对原提交':'保存核心资料'}</button></footer></form></Modal>;
}
export function TalentDirectoryDetail({id,me,catalog,onClose,onAdvanced,onProduction,refreshVersion=0}:{id:string;me:Me;catalog:CatalogItem[];onClose:()=>void;onAdvanced:()=>void;onProduction:(p:Selection)=>void;refreshVersion?:number}){
 const [tick,setTick]=useState(0),[photoTick,setPhotoTick]=useState(0),[edit,setEdit]=useState(false),[page,setPage]=useState(1),[cover,setCover]=useState<string|null|undefined>(undefined);const action=useAction(),frozen=action.busy||outcomeUnknown(action.error);
 const load=useLoad(()=>read<TalentDetail>('directory.talent.get',{id}),id+':'+tick+':'+refreshVersion),d=load.data,p=d?profileOf(d):null;
 const source=useLoad(()=>p&&me.permissions.includes('sources.read')?read<Source>('source.get',{id:p.sourceId}):Promise.resolve(null),String(p?.sourceId)+':'+tick+':'+refreshVersion);
 const photos=useLoad(()=>me.permissions.includes('assets.read')?read<Page<Photo>>('asset.list',{}, {personId:id,page:String(page),pageSize:'20'}):Promise.resolve(null),id+':'+page+':'+tick+':'+photoTick+':'+refreshVersion);
 const currentIds=new Set(d?.facts.castingProfiles.filter(r=>r.usable).map(r=>r.currentMeasurementSetId)??[]),currentMeasures=d?.facts.measurementSets.filter(r=>r.usable&&currentIds.has(r.id))??[];
 const label=(ns:string,code:unknown)=>catalog.find(c=>c.namespace===ns&&c.code===code)?.labelZh??String(code);
 const changed=()=>{setEdit(false);setCover(undefined);setTick(t=>t+1);};
 if(edit&&d&&source.data)return <CoreForm detail={d} source={source.data} me={me} catalog={catalog} onClose={()=>setEdit(false)} onSaved={changed}/>;
 return <section className="talent-main-detail" aria-label="人才主详情"><button onClick={onClose} disabled={frozen}>← 返回目录</button><ErrorBox error={load.error??action.error}/>{load.busy?<p>正在读取资料…</p>:d&&<><PageTitle overline="TALENT" title={d.displayName} description={d.intro||'简介待补充'} action={d.canEdit&&source.data?.current&&<button className="primary" onClick={()=>setEdit(true)}>补充核心资料</button>}/><div className="talent-main-overview">{p?.coverAssetId?<img className="main-cover" src={'/api/v1/assets/'+p.coverAssetId+'/preview'} alt={d.displayName+'的封面'}/>:<div className="main-cover directory-cover-placeholder">暂无封面照片</div>}<dl className="detail-grid"><div><dt>职业</dt><dd>{d.facts.personRoles.filter(r=>r.usable).map(r=>label('role',r.roleCode)).join(' / ')||'普通联系人'}</dd></div><div><dt>性别</dt><dd>{businessLabels[String(p?.genderCode)]??'未知'}</dd></div><div><dt>年龄</dt><dd>{ageLabel(d.ageRange??null)} · {businessLabels[String(p?.birthPrecision)]??'未知'}</dd></div><div><dt>国籍</dt><dd>{(p?.nationalityCodes as string[]??[]).map(c=>label('nationality',c)).join(' / ')||'未知'}</dd></div><div><dt>常驻城市</dt><dd>{d.facts.talentLocations.filter(r=>r.usable&&r.relationCode==='BASE').map(r=>label('city',r.locationCode)).join(' / ')||'未知'}</dd></div>{d.facts.personRoles.filter(r=>r.usable&&r.roleCode==='model').map(r=><div key={r.id}><dt>模特分类</dt><dd>{businessLabels[String(r.castingMarketCode)]??'未分类'} · {businessLabels[String(r.experienceCode)]??'未确认'}</dd></div>)}</dl></div>
 {me.permissions.includes('talent.invite')&&<TalentInvitationPanel personId={id}/>}<section className="panel padded"><h2>量尺</h2>{currentMeasures.map(r=><div key={r.id}><p>{r.heightCm==null?'身高未知':r.heightCm+' cm'} · {r.measuredOn==null?'量尺日期未知':String(r.measuredOn)+(r.datePrecision==='APPROXIMATE'?'（大约）':'')} · 已确认</p><p>{[['bustCm','胸围'],['waistCm','腰围'],['hipsCm','臀围']].map(([k,t])=>t+' '+(r[k!]==null?'未知':r[k!]+' cm')).join(' · ')}</p><p>鞋码：{r.shoeSizeValue==null?'未知':String(r.shoeSizeValue)+' '+String(r.shoeSizeSystem)} · 服装尺码：{r.clothingSizeValue==null?'未知':String(r.clothingSizeValue)+' '+String(r.clothingSizeSystem)}</p><small className="muted">收录时间：{r.reportedAt?displayDate(String(r.reportedAt)):'未知（旧记录未补造）'}。确认表示采用当前声明，不代表实际测量日期已核验。</small></div>)}{!currentMeasures.length&&<p>暂无当前已确认量尺。</p>}{d.facts.measurementSets.some(r=>r.status==='DRAFT')&&<p className="muted">有未确认量尺记录，尚不用于目录筛选。</p>}</section>
 <section className="panel padded"><h2>语言与选角资料</h2><p>工作语言：{d.facts.personLanguages.filter(r=>r.usable).map(r=>label('language',r.languageCode)).join(' / ')||'未知'}</p>{d.facts.castingProfiles.filter(r=>r.usable).map(r=><p key={r.id}>发色：{r.hairColorCode?TALENT_LABELS[String(r.hairColorCode)]??String(r.hairColorCode):'未知'} · 瞳色：{r.eyeColorCode?TALENT_LABELS[String(r.eyeColorCode)]??String(r.eyeColorCode):'未知'}</p>)}</section><section className="panel padded"><h2>风格与服务意愿</h2>{d.facts.personRoles.filter(r=>r.usable).map(r=><p key={r.id}>{label('role',r.roleCode)}：{(r.styleCodes as string[]??[]).map(c=>label('roleStyle',c)).join(' / ')||'风格待补充'}；{(r.serviceCodes as string[]??[]).map(c=>label('roleService',c)).join(' / ')||'服务意愿待补充'}</p>)}</section>
 {me.permissions.includes('assets.read')&&<section className="panel padded"><h2>照片</h2><ErrorBox error={photos.error}/><div className="detail-photos">{photos.data?.items.filter(a=>a.mime.startsWith('image/')&&a.state==='READY').map(a=><figure key={a.id}><img loading="lazy" src={'/api/v1/assets/'+a.id+'/preview'} alt={a.fileName}/><figcaption>{a.fileName}</figcaption>{d.canEdit&&source.data?.current&&<button disabled={frozen} onClick={()=>setCover(a.id)}>{p?.coverAssetId===a.id?'当前封面':'选作封面'}</button>}</figure>)}</div>{photos.data&&!photos.data.items.length&&<p>还没有照片。可在下方上传。</p>}{photos.data&&<Pager page={page} pageSize={20} total={photos.data.total} setPage={setPage}/>}<fieldset disabled={frozen}>{!!p?.coverAssetId&&d.canEdit&&<button onClick={()=>setCover(null)}>移除封面选择</button>}</fieldset>{cover!==undefined&&source.data&&<div className="notice"><p>{cover?'确认使用选中照片作为封面？':'确认移除当前封面选择？'}</p><button disabled={action.busy} onClick={()=>void action.run(async()=>{await call<'directory.talent.update',Receipt>('directory.talent.update',{schemaVersion:'once-talent-experience-v1',expectedRevision:d.revision,sourceId:source.data!.id,sourceRevision:source.data!.revision,profile:{coverAssetId:cover}},{id});changed();})}>{outcomeUnknown(action.error)?'核对原提交':'保存封面选择'}</button><button disabled={frozen} onClick={()=>setCover(undefined)}>取消</button></div>}{source.busy?<p role="status">正在核对素材来源…</p>:source.error?<ErrorBox error={source.error}/>:<MediaPanel key={id+':'+tick} me={me} personId={id} source={source.data??undefined} compact onReady={()=>setPhotoTick(t=>t+1)}/>}</section>}
 <PersonProductionPanel personId={id} onOpen={onProduction}/><details className="panel padded"><summary>高级管理：来源、依据、历史与权限</summary><p>按当前权限管理来源、字段依据、职业关系、历史资料和访问范围。</p><button onClick={onAdvanced} disabled={frozen}>打开高级管理</button></details><button onClick={()=>setTick(t=>t+1)} disabled={frozen}>刷新资料</button></>}</section>;
}
