import {DIRECTORY_DIMENSIONS,DIRECTORY_AGE_PRESETS} from '../../../packages/core/src/talent-directory-contract.ts';
import {readDirectoryState,saveDirectoryState,clearDirectoryMemory,directoryRequest,type DirectoryDraft,type CandidateContext} from './directory-state.ts';
export {clearDirectoryMemory};
import {useEffect,useState} from 'react';
import {call} from './api.ts';
import type {CatalogItem,Me,Page} from './dto.ts';
import {ErrorBox,Empty,Field,Pager,PageTitle,Tag,useLoad,Modal} from './ui.tsx';
import {MultiChoice,RangeFields} from './ux-controls.tsx';
import {BatchCandidateChoice} from './shortlist-batch-ui.tsx';
export interface DirectoryMatch {id:string;isTalent:boolean;displayName:string;status:string;revision:number;genderCode:string|null;nationalityCodes:string[];ageRange:{min:number;max:number;precision:string}|null;coverAssetId:string|null;heightCm:number|null;matchingRoleIds:string[];roles:Array<{id:string;roleCode:string;castingMarketCode:string;experienceCode:string}>;locations:Array<{locationCode:string;relationCode:string}>;languages:Array<{languageCode:string}>}
interface DirectoryPage extends Page<DirectoryMatch>{facets:Record<string,Record<string,number>>}
export const businessLabels:Record<string,string>={FEMALE:'女',MALE:'男',NON_BINARY:'非二元',OTHER:'其他',UNKNOWN:'未填写',DOMESTIC:'国模',INTERNATIONAL:'外模',UNCLASSIFIED:'未分类',AMATEUR:'素人',PROFESSIONAL:'专业',UNSPECIFIED:'未确认',YEAR_ONLY:'仅出生年份',EXACT_DATE:'完整出生日期',DECLARED_RANGE:'声明年龄范围'};
export const ageLabel=(age:DirectoryMatch['ageRange'])=>age?age.min===age.max?age.min+' 岁':age.min+'–'+age.max+' 岁':'年龄未填写';
const clean=(d:DirectoryDraft)=>Object.fromEntries(Object.entries(d).filter(([,v])=>v!==''&&(!Array.isArray(v)||v.length)));
const scrollPositions=new Map<string,number>();
window.addEventListener('once-session-expired',()=>scrollPositions.clear());
export function TalentDirectory({me,catalog,onOpen,onPick,tick=0,onCreate,surface='library',targetListId,onAdded,onViewList}:{me:Me;catalog:CatalogItem[];onOpen:(id:string)=>void;onPick?:(p:DirectoryMatch,context:CandidateContext)=>void;tick?:number;onCreate?:()=>void;surface?:'library'|'candidate';targetListId?:string;onAdded?:()=>void;onViewList?:(id:string)=>void}){
 const key=me.membershipId+':'+me.directoryStateScope+':'+surface,initial=readDirectoryState(surface);
 const [query,setQuery]=useState(initial.query),[draft,setDraft]=useState(initial.draft),[page,setPage]=useState(initial.page),[selected,setSelected]=useState(initial.selected),[refresh,setRefresh]=useState(0),[roleChoices,setRoleChoices]=useState(initial.roleChoices),[customAge,setCustomAge]=useState(false),[filters,setFilters]=useState(false),[layout,setLayout]=useState<'photo'|'list'>('photo'),[joining,setJoining]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{saveDirectoryState(surface,{query,draft,page,selected,roleChoices});},[key,query,draft,page,selected,roleChoices]);
 useEffect(()=>{const restore=()=>{const saved=readDirectoryState(surface);setQuery(saved.query);setDraft(saved.draft);setPage(saved.page);setSelected(saved.selected);setRoleChoices(saved.roleChoices);};window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore);},[surface]);
 const querySignature=JSON.stringify(query),draftChanged=JSON.stringify(clean(draft))!==querySignature;
 const load=useLoad(async()=>({...await call<'directory.talent.search',DirectoryPage>('directory.talent.search',{...directoryRequest(query),page,pageSize:20}),requestedQuery:querySignature}),JSON.stringify([query,page,tick,refresh]));
 const current=load.data?.requestedQuery===querySignature&&load.data.page===page&&!load.busy&&!load.error;
 useEffect(()=>{if(current&&load.data&&page>1&&!load.data.items.length)setPage(Math.max(1,Math.ceil(load.data.total/20)));},[load.data,page,current]);
 useEffect(()=>{if(current&&scrollPositions.has(key)){window.scrollTo(0,scrollPositions.get(key)!);scrollPositions.delete(key);}},[current,key]);
 const set=(k:string,v:string|string[])=>setDraft(d=>({...d,[k]:v}));
 const apply=(next=draft)=>{setPage(1);setQuery(clean(next));setRefresh(n=>n+1);setFilters(false);};
 const label=(ns:string,code:string)=>catalog.find(c=>c.namespace===ns&&c.code===code)?.labelZh??code;
 const dictionary=(ns:string)=>catalog.filter(c=>c.namespace===ns&&c.status==='ACTIVE').map(c=>[c.code,c.labelZh] as [string,string]);
 const choice=(field:string,title:string,options:[string,string][],counts?:Record<string,number>)=><MultiChoice title={title} value={Array.isArray(draft[field])?draft[field] as string[]:draft[field]?[String(draft[field])]:[]} onChange={v=>set(field,v)} options={options} counts={current?counts:undefined}/>;
 const preset=customAge?'custom':DIRECTORY_AGE_PRESETS.items.find(p=>String(p.min)===draft.ageMin&&String(p.max)===draft.ageMax)?.id??(draft.ageMin||draft.ageMax?'custom':'');
 const contextFor=(p:DirectoryMatch):CandidateContext=>{const role=p.matchingRoleIds.length===1?p.matchingRoleIds[0]:roleChoices[p.id];return role&&p.matchingRoleIds.includes(role)?{personId:p.id,personRoleId:role}:{personId:p.id,personRoleId:null,pendingRole:true};};
 const toggle=(p:DirectoryMatch,checked:boolean)=>{setNotice('');setSelected(ids=>{if(!checked)return ids.filter(s=>s.personId!==p.id);if(ids.some(s=>s.personId===p.id))return ids;if(ids.length>=200){setNotice('最多选择200项，请先处理已选人才。');return ids;}return [...ids,contextFor(p)];});};
 const open=(id:string)=>{scrollPositions.set(key,window.scrollY);onOpen(id);};
 const model=(Array.isArray(draft.role)?draft.role.includes('model'):draft.role==='model')||!draft.role||(Array.isArray(draft.role)&&!draft.role.length);
 const remove=(field:string,value?:string)=>{const next={...query};if(value&&Array.isArray(next[field]))next[field]=(next[field] as string[]).filter(c=>c!==value);else delete next[field];setDraft(next);apply(next);};
 const dimensionLabels:Record<string,[string,string]>={role:['职业','role'],gender:['性别',''],market:['分类',''],experience:['从业',''],location:['城市','city'],nationality:['国籍','nationality'],style:['风格','roleStyle'],service:['拍摄意愿','roleService'],language:['语言','language'],industryCode:['行业','industry'],workTypeCode:['作品类型','workType']};
 return <section className="talent-directory" aria-label={surface==='candidate'?'候选找人':'统一人才目录'}>{surface==='library'&&<PageTitle overline="人才" title="人才库" description="找人、补资料，或加入一次工作的候选清单。" action={onCreate&&<button className="primary" onClick={onCreate}>＋ 新增人才</button>}/>}
 <div className="view-tabs" aria-label="人物范围">{[['TALENT','人才'],['CONTACT','普通联系人'],['ALL','全部人物']].map(([mode,title])=><button key={mode} aria-pressed={(query.mode??'TALENT')===mode} onClick={()=>{const next={...draft,mode:mode!};setDraft(next);apply(next);}}>{title}</button>)}</div>
 <form className="panel directory-toolbar" onSubmit={e=>{e.preventDefault();apply();}}><Field label="搜索姓名或别名"><input maxLength={160} value={String(draft.q??'')} onChange={e=>set('q',e.target.value)} placeholder="搜索姓名、艺名、别名"/></Field>{choice('role','职业',dictionary('role'))}{choice('location','城市',dictionary('city'))}<button type="button" onClick={()=>setFilters(true)} aria-expanded={filters}>筛选条件</button><button type="submit" className="primary">搜索</button></form>
 {draftChanged&&<p className="draft-hint" role="status">筛选有修改尚未应用，下面仍是上一次查询结果。<button type="button" className="link-button" onClick={()=>apply()}>应用筛选</button></p>}
 <div className="applied-filters" aria-label="已生效条件">{Object.entries(query).filter(([k])=>k!=='mode').flatMap(([k,v])=>(Array.isArray(v)?v:[String(v)]).map(c=><button key={k+':'+c} type="button" onClick={()=>remove(k,Array.isArray(v)?c:undefined)}>{k==='q'?'姓名：'+c:dimensionLabels[k]?dimensionLabels[k]![0]+'：'+(businessLabels[c]??label(dimensionLabels[k]![1],c)):({ageMin:'年龄下限',ageMax:'年龄上限',heightMin:'身高下限',heightMax:'身高上限',ageUnknown:'年龄未填写',status:'状态'}[k]??k)+'：'+c}<span aria-hidden="true"> ×</span></button>))}{Object.keys(query).some(k=>k!=='mode')&&<button className="link-button" onClick={()=>{const next={mode:String(query.mode??'TALENT')};setDraft(next);apply(next);setCustomAge(false);}}>清除条件</button>}</div>
 <div className="directory-count"><strong>{current?'共 '+load.data!.total+' 位':load.error?'查询未完成':'正在查询…'}</strong><div className="button-row"><button disabled={!current||!me.permissions.includes('records.write')} onClick={()=>{const eligible=load.data!.items.filter(p=>p.isTalent!==false);if(selected.length+eligible.filter(p=>!selected.some(s=>s.personId===p.id)).length>200){setNotice('本页会超过200项选择上限，请减少选择。');return;}setSelected(ids=>[...ids,...eligible.filter(p=>!ids.some(s=>s.personId===p.id)).map(contextFor)]);}}>选中本页</button><button aria-pressed={layout==='photo'} onClick={()=>setLayout('photo')}>照片</button><button aria-pressed={layout==='list'} onClick={()=>setLayout('list')}>列表</button><button aria-label="刷新人才结果" onClick={()=>setRefresh(x=>x+1)}>刷新</button></div></div>
 <ErrorBox error={load.error}/>{notice&&<p className="notice" role="status">{notice}</p>}{load.busy&&<p role="status">正在读取当前可见资料…</p>}
 {current&&load.data&&<><div className={'people-grid photo-directory '+(layout==='list'?'directory-list':'')}>{load.data.items.map(p=><article key={p.id} className={'directory-card '+(selected.some(s=>s.personId===p.id)?'is-selected':'')}><button className="person-card" onClick={()=>open(p.id)}>{p.coverAssetId?<img className="directory-cover" loading="lazy" src={'/api/v1/assets/'+p.coverAssetId+'/preview'} alt={p.displayName+'的封面'}/>:<div className="directory-cover-placeholder">暂无封面照片</div>}<div className="directory-card-body"><div className="card-top"><h3>{p.displayName}</h3><Tag value={p.status}/></div><p>{p.roles.map(r=>label('role',r.roleCode)).join(' / ')||'普通联系人'}</p><p>{p.locations.map(l=>label('city',l.locationCode)).join(' / ')||'城市未填写'} · {p.heightCm==null?'身高未填写':p.heightCm+' cm'}</p><small>{p.genderCode?businessLabels[p.genderCode]:'性别未填写'} · {ageLabel(p.ageRange)}</small></div></button>{me.permissions.includes('records.write')&&p.isTalent!==false&&<footer><label><input type="checkbox" checked={selected.some(s=>s.personId===p.id)} onChange={e=>toggle(p,e.target.checked)}/>选择 {p.displayName}</label>{onPick&&!contextFor(p).pendingRole&&<button onClick={()=>onPick(p,contextFor(p))}>加入当前清单</button>}</footer>}</article>)}</div>{!load.data.items.length&&<Empty title="当前条件没有结果">减少筛选条件再试。未知资料不会被当成符合条件。</Empty>}<Pager page={page} pageSize={20} total={load.data.total} setPage={p=>{setPage(p);window.scrollTo(0,0);}}/></>}
 {!!selected.length&&<div className="selection-bar" aria-label="已选人才操作"><strong>已选 {new Set(selected.map(s=>s.personId)).size} 人</strong><span>{selected.length} 项 · 最多200项</span><button onClick={()=>setSelected([])}>取消选择</button><button className="primary" disabled={!current} onClick={()=>setJoining(true)}>加入候选清单</button></div>}
 {joining&&<BatchCandidateChoice selection={selected} catalog={catalog} initialListId={targetListId} onClose={()=>setJoining(false)} onDone={(id,summary,processedIds)=>{setJoining(false);setSelected(old=>old.filter(p=>!processedIds.includes(p.personId)));setNotice('已处理：新增 '+summary.added+' 项，已有 '+summary.existing+' 项。');onAdded?.();}} onViewList={onViewList}/>}
 {filters&&<Modal title="筛选人才" wide onClose={()=>setFilters(false)}><form onSubmit={e=>{e.preventDefault();apply();}}><div className="modal-body filter-body"><p>同一类条件可多选，满足任意一项即可；不同类条件同时生效。</p><div className="form-grid">{choice('role','职业',dictionary('role'),load.data?.facets.roles)}{choice('location','城市',dictionary('city'),load.data?.facets.locations)}{model&&<>{choice('gender','性别',['FEMALE','MALE','NON_BINARY','OTHER','UNKNOWN'].map(c=>[c,businessLabels[c]!] as [string,string]),load.data?.facets.genders)}{choice('market','国模 / 外模',['DOMESTIC','INTERNATIONAL','UNCLASSIFIED'].map(c=>[c,businessLabels[c]!] as [string,string]),load.data?.facets.markets)}{choice('experience','从业类型',['AMATEUR','PROFESSIONAL','UNSPECIFIED'].map(c=>[c,businessLabels[c]!] as [string,string]),load.data?.facets.experiences)}<Field label="年龄快捷筛选"><select value={preset} onChange={e=>{setCustomAge(e.target.value==='custom');const p=DIRECTORY_AGE_PRESETS.items.find(p=>p.id===e.target.value);setDraft(d=>({...d,ageMin:p?String(p.min):'',ageMax:p?String(p.max):'',ageUnknown:''}));}}><option value="">不限</option>{DIRECTORY_AGE_PRESETS.items.map(p=><option value={p.id} key={p.id}>{p.label}</option>)}<option value="custom">自定义范围</option></select></Field>{preset==='custom'&&<RangeFields title="年龄" limit={130} min={String(draft.ageMin??'')} max={String(draft.ageMax??'')} onMin={v=>set('ageMin',v)} onMax={v=>set('ageMax',v)}/>}<label><input type="checkbox" checked={draft.ageUnknown==='true'} onChange={e=>{setDraft(d=>({...d,ageUnknown:e.target.checked?'true':'',ageMin:'',ageMax:''}));setCustomAge(false);}}/>只找年龄未填写</label><RangeFields title="身高（厘米）" min={String(draft.heightMin??'')} max={String(draft.heightMax??'')} step="0.1" onMin={v=>set('heightMin',v)} onMax={v=>set('heightMax',v)}/>{choice('style','风格',dictionary('roleStyle'),load.data?.facets.styles)}{choice('service','拍摄意愿',dictionary('roleService'),load.data?.facets.services)}</>}{choice('nationality','国籍',dictionary('nationality'),load.data?.facets.nationalities)}{choice('language','工作语言',dictionary('language'),load.data?.facets.languages)}{choice('industryCode','作品行业',dictionary('industry'),load.data?.facets.industries)}{choice('workTypeCode','作品类型',dictionary('workType'),load.data?.facets.workTypes)}<Field label="档案状态"><select value={String(draft.status??'')} onChange={e=>set('status',e.target.value)}><option value="">不限</option><option value="DRAFT">草稿</option><option value="ACTIVE">在库</option><option value="ARCHIVED">已归档</option></select></Field></div><p className="muted">年龄范围须完整符合；身高采用当前已确认量尺。拍摄意愿不表示已有经历。</p></div><footer className="modal-footer"><button type="button" onClick={()=>{setDraft({mode:String(query.mode??'TALENT')});setCustomAge(false);}}>重置条件</button><button type="submit" className="primary">应用筛选</button></footer></form></Modal>}
 </section>;
}
