import {useState} from 'react';
import {call,read} from './api.ts';
import type {Me,Person} from './dto.ts';
import {ErrorBox,Empty,PageTitle,useLoad,date} from './ui.tsx';
import type {ReviewPage} from './review-workspace.tsx';
import {navigateDirectoryPath} from './directory-state.ts';
import {recentTalents} from './recent-talents.ts';
export function WorkspaceHome({me,onNavigate}:{me:Me;onNavigate:(key:string)=>void}){
 const [tick,setTick]=useState(0),tasks=useLoad(()=>call<'review.search',ReviewPage>('review.search',{view:'TODO',kind:'ALL',page:1,pageSize:5}),me.membershipId+':'+tick);
 const dashboard=useLoad(()=>read<{recentPeople:Person[];pendingJobs:number;failedJobs:number}>('dashboard.get'),me.membershipId+':'+tick);
 const ids=recentTalents(me),recent=useLoad(()=>ids.length?call<'shortlist.selection',{items:{id:string;displayName?:string;unavailable:boolean}[]}>('shortlist.selection',{personIds:ids}):Promise.resolve(null),ids.join(',')+':'+tick);
 const go=(path:string)=>{navigateDirectoryPath(path);window.dispatchEvent(new PopStateEvent('popstate'));};
 return <><PageTitle overline="工作空间" title="工作台" description={me.displayName+'，从待办或最近的资料继续工作。'} action={<button onClick={()=>setTick(t=>t+1)}>刷新</button>}/><div className="quick-start">{me.permissions.includes('records.write')&&<button className="primary" onClick={()=>go('/talents/new')}>＋ 新增人才</button>}<button onClick={()=>onNavigate('people')}>找人加入清单</button>{me.permissions.includes('records.write')&&<button onClick={()=>onNavigate('imports')}>导入资料</button>}</div><div className="home-columns"><section className="panel"><div className="panel-heading"><h2>待我处理</h2><button onClick={()=>onNavigate('review')}>全部任务</button></div><div className="padded"><ErrorBox error={tasks.error}/>{tasks.busy?<p role="status">正在核对待办…</p>:tasks.data?.items.length?<div className="home-tasks">{tasks.data.items.map(t=><button key={t.kind+':'+t.id} onClick={()=>go('/workspace/review/'+t.kind+'/'+t.id)}><strong>{t.title}</strong><p>{t.description}</p><small>{date(t.updatedAt)}</small></button>)}</div>:tasks.data&&<Empty title="没有待你处理的任务">可继续整理资料或查找人才。</Empty>}</div></section><section className="panel"><div className="panel-heading"><h2>最近打开</h2><small>本次会话</small></div><div className="padded"><ErrorBox error={recent.error}/>{recent.busy&&ids.length>0?<p>正在核对资料权限…</p>:recent.data?.items.some(i=>!i.unavailable)?<div className="home-tasks">{recent.data.items.filter(i=>!i.unavailable).map(i=><button key={i.id} onClick={()=>go('/talents/'+i.id)}><strong>{i.displayName}</strong><span>继续查看 →</span></button>)}</div>:<Empty title="尚未打开人才档案">进入人才库后，最近打开的资料会出现在这里。</Empty>}</div></section></div><section className="panel"><div className="panel-heading"><h2>最近入库</h2><button onClick={()=>onNavigate('people')}>进入人才库</button></div><div className="padded"><ErrorBox error={dashboard.error}/><div className="recent-grid">{!dashboard.busy&&dashboard.data?.recentPeople.map(p=><button key={p.id} onClick={()=>go('/talents/'+p.id)}><div className="avatar">{p.displayName.slice(0,1)}</div><strong>{p.displayName}</strong><small>{date(p.createdAt)}</small></button>)}</div></div></section>{dashboard.data?.failedJobs? <p className="notice">有 {dashboard.data.failedJobs} 个导入任务需要核对。<button onClick={()=>onNavigate('imports')}>查看逐行处理结果</button></p>:null}</>;
}
