import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn, spawnSync } from 'node:child_process';
import { createServer } from 'node:net';
import { PrismaClient } from '@prisma/client';
import { chromium } from 'playwright';

const raw=process.env.DATABASE_URL_TEST;assert.equal(process.env.ALLOW_BROWSER_TESTS,'yes');assert.ok(raw);const url=new URL(raw);assert.ok(['postgres:','postgresql:'].includes(url.protocol));assert.ok(['127.0.0.1','localhost','[::1]'].includes(url.hostname));assert.match(url.pathname,/^\/once_test_[a-z0-9_]+$/);assert.ok(url.username&&url.password&&!url.search&&!url.hash);
const prisma=new PrismaClient({datasources:{db:{url:raw}},log:[]}),tmp=mkdtempSync(join(tmpdir(),'once-search-')),password='Synthetic-'+randomBytes(20).toString('base64url')+'!';
const put=(name,text)=>{const path=join(tmp,name);writeFileSync(path,text,{mode:0o600});return path};
const env={...process.env,DATABASE_URL:raw,APP_ENV:'test',ACCESS_MODE:'INTERNAL',COOKIE_SECURE:'false',HOST:'127.0.0.1',CONTACT_KEY_FILE:put('contact.hex',randomBytes(32).toString('hex')),CSRF_KEY_FILE:put('csrf.hex',randomBytes(32).toString('hex')),RECOVERY_EPOCH_FILE:put('recovery.epoch',randomBytes(24).toString('hex')),BOOTSTRAP_LOGIN:'owner',BOOTSTRAP_NAME:'SR1合成管理员',BOOTSTRAP_PASSWORD_FILE:put('bootstrap.password',password)};
let api,browser,base;function run(command,args){const r=spawnSync(command,args,{env,encoding:'utf8',timeout:120000});assert.equal(r.status,0,command+' failed: '+(r.stderr??'').slice(-800));}
async function stop(child){if(!child||child.exitCode!==null||child.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{child.kill('SIGKILL');resolve()},5000);child.once('exit',()=>{clearTimeout(timer);resolve()});child.kill('SIGINT')})}
async function until(check){const end=Date.now()+30000;while(Date.now()<end){try{if(await check())return}catch{}await new Promise(r=>setTimeout(r,100))}throw new Error('SR1 readiness timeout')}
async function login(page){await page.goto(base,{waitUntil:'networkidle'});await page.locator('input[autocomplete=username]').fill('owner');await page.locator('input[autocomplete=current-password]').fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByRole('button',{name:/概览/}).waitFor()}
async function json(page,path){const r=await page.context().request.get(base+'/api/v1'+path);assert.equal(r.status(),200,path+': '+await r.text());return r.json()}
async function cmd(page,method,path,data,expected=200,key=randomUUID()){const me=await json(page,'/me');const r=await page.context().request.fetch(base+'/api/v1'+path,{method,data,headers:{Origin:base,'X-CSRF-Token':me.csrfToken,'Idempotency-Key':key}});assert.equal(r.status(),expected,method+' '+path+': '+await r.text());return r.json()}
try{
 const tables=await prisma.$queryRawUnsafe("SELECT table_name FROM information_schema.tables WHERE table_schema='public'");assert.equal(tables.length,0,'SR1 requires empty database');run('pnpm',['db:deploy']);
 const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));env.PORT=String(server.address().port);await new Promise(r=>server.close(r));base='http://127.0.0.1:'+env.PORT;env.APP_ORIGIN=base;run('node',['dist/apps/api/src/bootstrap.js']);api=spawn('node',['dist/apps/api/src/main.js'],{env,stdio:['ignore','pipe','pipe']});api.stdout.resume();api.stderr.resume();await until(async()=>(await fetch(base+'/health/ready')).status===200);browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});const page=await browser.newPage();await login(page);
 const source=title=>({title,type:'MANUAL',providerClaim:'SR1合成记录',basisMode:'INTERNAL_USE',basisDescription:'隔离自动化测试资料，不代表真实授权',validUntil:new Date(Date.now()+86400000*30).toISOString()});
 const a=(await cmd(page,'POST','/people',{displayName:'SR1家具模特A',roles:['model'],cityCode:'shenzhen',languageCodes:['en'],skillCodes:['lifestyle'],inlineSource:source('SR1人才A来源')},201)).resourceId;
 const b=(await cmd(page,'POST','/people',{displayName:'SR1家具模特B',roles:['model'],languageCodes:['en'],skillCodes:['lifestyle'],inlineSource:source('SR1人才B来源')},201)).resourceId;
 let pa=await json(page,'/people/'+a);for(const fieldPath of ['roles','cityCode','languageCodes','skillCodes']){await cmd(page,'POST','/field-evidence',{personId:a,expectedRevision:pa.revision,fieldPath,sourceId:pa.sourceId,sourceRevision:pa.source.revision});pa=await json(page,'/people/'+a)}
 const work=(await cmd(page,'POST','/works',{title:'SR1家具Lifestyle作品',description:'家具生活方式场景',origin:'EXTERNAL',originNote:'合成外部作品',inlineSource:source('SR1作品来源')},201)).resourceId;let wd=await json(page,'/works/'+work);await cmd(page,'POST','/works/'+work+'/credits',{expectedRevision:wd.revision,personId:a,roleCode:'model',note:'合成出镜'});
 const project=(await cmd(page,'POST','/projects',{title:'SR1家具实际项目',inlineSource:source('SR1项目来源')},201)).resourceId;let pd=await json(page,'/projects/'+project);await cmd(page,'POST','/projects/'+project+'/participants',{expectedRevision:pd.revision,personId:a,roleCode:'model',state:'ACTUAL',note:'合成现场实际参与'});
 await page.getByRole('button',{name:/人才档案/}).click();
 await page.getByLabel('角色',{exact:true}).selectOption('model');await page.getByLabel('城市',{exact:true}).selectOption('shenzhen');await page.getByLabel('工作语言',{exact:true}).selectOption('en');await page.getByLabel('技能 / 擅长类型',{exact:true}).selectOption('lifestyle');await page.getByLabel('参与作品关键词',{exact:true}).fill('家具');await page.getByLabel('作品制作归属',{exact:true}).selectOption('EXTERNAL');await page.getByLabel('核验时效',{exact:true}).selectOption('90');await page.locator('.search-check input[type=checkbox]').check();
 const waited=page.waitForResponse(r=>r.url().includes('/api/v1/people/search?')&&r.request().method()==='GET');await page.getByRole('button',{name:'应用检索条件',exact:true}).click();const response=await waited;assert.equal(response.status(),200,await response.text());
 await page.getByText('SR1家具模特A',{exact:true}).waitFor();assert.equal(await page.getByText('SR1家具模特B',{exact:true}).count(),0);assert.ok((await page.getByText('当前值有人工核验',{exact:false}).count())>=4);await page.getByText('实际项目：当前可见 1 个',{exact:true}).waitFor();await page.getByText('SR1家具Lifestyle作品',{exact:false}).waitFor();
 const data=await json(page,'/people/search?role=model&cityCode=shenzhen&languageCode=en&skillCode=lifestyle&workQ=%E5%AE%B6%E5%85%B7&workOrigin=EXTERNAL&actualProject=true&verifiedWithinDays=90');assert.equal(data.total,1);assert.equal(data.items[0].id,a);assert.equal(data.semantics.scoring,false);assert.deepEqual(data.semantics.unsupported,['availability','budget','nationality']);
 pa=await json(page,'/people/'+a);await cmd(page,'PATCH','/people/'+a,{expectedRevision:pa.revision,cityCode:null});const waited2=page.waitForResponse(r=>r.url().includes('/api/v1/people/search?')&&r.request().method()==='GET');await page.locator('.search-actions').getByRole('button',{name:'刷新',exact:true}).click();await waited2;await page.getByText('没有找到符合当前条件的资料',{exact:true}).waitFor();assert.equal((await json(page,'/people/search?cityCode=shenzhen')).items.some(x=>x.id===a),false);assert.equal((await json(page,'/people/search?q=SR1%E5%AE%B6%E5%85%B7%E6%A8%A1%E7%89%B9B')).items[0].match.unknownFields.includes('cityCode'),true);
 console.log('PASS SR1 browser: structured filters, current evidence, work/ACTUAL facts, unknown exclusion and explicit no-score semantics');
}finally{if(browser)await browser.close();await stop(api);await prisma.$disconnect();rmSync(tmp,{recursive:true,force:true})}
