import {registeredTemp} from '../../scripts/registered-temp.mjs';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdtempSync,mkdirSync,copyFileSync,readdirSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {PrismaClient} from '@prisma/client';
import {PrismaStore} from '../../apps/api/src/prisma-store.ts';
import {agentMediaScenario,agentMediaFixture,agentMediaFenceScenario,agentMediaRetentionScenario,agentMediaMergeScenario,agentMediaDeletionScenario,sampleBytes,samplePreview} from '../support/agent-media.ts';
import {RecoveryOps} from '../../packages/core/src/recovery.ts';
import {hashSecret} from '../../packages/core/src/crypto.ts';
const raw=process.env.DATABASE_URL_TEST;assert.equal(process.env.ALLOW_DB_TESTS,'yes');assert.ok(raw);const url=new URL(raw);assert.match(url.pathname,/^\/once_test_/);const db=new PrismaClient({datasources:{db:{url:raw}},log:[]}),store=new PrismaStore(db),tmp=registeredTemp().path,checks:string[]=[];
const run=(cmd:string,args:string[],u=raw)=>{const r=spawnSync(cmd,args,{env:{...process.env,DATABASE_URL:u},encoding:'utf8',timeout:180000});assert.equal(r.status,0,(r.stderr??'').slice(-2000));};
try{
 const variant=process.env.AGENT_MEDIA_VARIANT??'base';
 if(variant==='upgrade'){
  assert.equal((await db.$queryRawUnsafe<any[]>("SELECT tablename FROM pg_tables WHERE schemaname='public'")).length,0);copyFileSync('prisma/schema.prisma',join(tmp,'schema.prisma'));mkdirSync(join(tmp,'migrations'));copyFileSync('prisma/migrations/migration_lock.toml',join(tmp,'migrations/migration_lock.toml'));const names=readdirSync('prisma/migrations').filter(n=>/^\d/.test(n)).sort();for(const name of names.slice(0,72)){mkdirSync(join(tmp,'migrations',name));copyFileSync(join('prisma/migrations',name,'migration.sql'),join(tmp,'migrations',name,'migration.sql'));}run('pnpm',['exec','prisma','migrate','deploy','--schema',join(tmp,'schema.prisma')]);
  const {authFixture}=await import('../support/talent-auth.ts'),{result}=await import('../support/fixtures.ts'),f=await authFixture(store);f.app.config.ingestionEnabled=true;const member=await db.membership.findFirstOrThrow(),scope=await db.accessScope.findFirstOrThrow(),principal=await f.owner.raw('POST','/td2/principals',{schemaVersion:'once-talent-v2.1.0',displayName:'保留72文字Agent',scopeId:scope.id,defaultMaintainerMembershipId:member.id,permissionCodes:['ingestion.submit','ingestion.read.own'],expiresAt:'2026-11-01T00:00:00.000Z'});assert.equal(principal.status,201);const created=await f.app.handle({method:'POST',url:'/api/v1/ingestion/submissions',ip:'test',headers:{authorization:'Bearer '+result(principal).token,'idempotency-key':randomUUID(),'content-type':'application/json'},body:JSON.stringify({schemaVersion:'once-talent-experience-v1',externalSubmissionKey:'retained72',proposedPersonId:null,sourceDeclaration:{title:'保留72文字投稿',providerClaim:'合成保留主体',materialDescription:'保留迁移前已有真实机器投稿'}})});assert.equal(created.status,200,JSON.stringify(created.body));const before=await db.membership.findMany(),principals=await db.servicePrincipal.findMany(),roots=await db.talentSubmission.findMany();run('pnpm',['db:deploy']);assert.deepEqual(await db.membership.findMany(),before);assert.deepEqual(await db.servicePrincipal.findMany(),principals);assert.deepEqual(await db.talentSubmission.findMany(),roots);assert.equal(await db.mediaUpload.count(),0);checks.push('retained72-to74-keeps-internal-membership-existing-machine-credentials-and-submission-no-fake-uploads');
 }else if(variant==='delete'){checks.push(...await agentMediaDeletionScenario(store));}else if(variant==='merge'){checks.push(...await agentMediaMergeScenario(store));const relation=await db.personMedia.findFirstOrThrow({where:{usageState:'ADOPTED'}});await assert.rejects(db.$transaction(async t=>{await t.personMedia.update({where:{id:relation.id},data:{personRoleId:randomUUID()}});}));assert.equal((await db.personMedia.findUniqueOrThrow({where:{id:relation.id}})).personRoleId,relation.personRoleId);checks.push('deferred-exact-role-fk-still-rejects-invalid-role-at-commit');}else if(['draft1','draft30','withdraw-ttl','reject','partial','adopted'].includes(variant)){checks.push(...await agentMediaRetentionScenario(store,variant==='withdraw-ttl'?'withdraw':variant));}else if(variant==='quota'){
  const f=await agentMediaFixture(store),root=await f.draft();f.app.config.agentMediaAdmission!.principalRetainedBytes=100;const root2=await f.draft(),input=await f.createInput(root,'quota1'),input2=await f.createInput(root2,'quota2'),responses=await Promise.all([f.machine('POST','/ingestion/uploads',input),f.machine('POST','/ingestion/uploads',input2)]);assert.deepEqual(responses.map(r=>r.status).sort(),[201,429]);assert.equal(await db.mediaUpload.count(),1);checks.push('pg16-concurrent-upload-atomic-budget-one-reservation');
 }else if(variant!=='base'){checks.push(...await agentMediaFenceScenario(store,variant));}
 else{
  const {f,id,eid,payload,checks:c}=await agentMediaScenario(store);checks.push(...c);const u=await db.mediaUpload.findUniqueOrThrow({where:{id}});
  for(const data of [{actorId:f.m.id},{servicePrincipalId:randomUUID()},{talentAccountId:randomUUID()},{personId:(await db.person.findFirstOrThrow()).id},{servicePrincipalAuthorizationEpoch:99},{clientItemKey:'changed'},{receiveAuthorizationHash:'bad',receiveAuthorizationUntil:new Date() }])await assert.rejects(db.mediaUpload.update({where:{id},data}));checks.push('postgres-real-principal-xor-fk-null-person-immutable-epoch-origin-receive-hash');
  const relation=await db.personMedia.findFirstOrThrow({where:{assetId:eid}});await assert.rejects(db.personMedia.update({where:{id:relation.id},data:{personId:(await db.person.findFirstOrThrow()).id}}));await assert.rejects(db.mediaAsset.update({where:{id:eid},data:{usageState:'ADOPTED'}}));checks.push('postgres-no-prebinding-or-half-adoption');
  const adminUrl=new URL(raw);adminUrl.pathname='/postgres';const admin=new PrismaClient({datasources:{db:{url:adminUrl.href}},log:[]}),target=new URL(raw);target.pathname='/once_test_agent_media_restore_'+randomBytes(6).toString('hex');try{
   const rebuildUrl=new URL(raw);rebuildUrl.pathname='/once_test_agent_media_rebuild_'+randomBytes(6).toString('hex');await admin.$executeRawUnsafe('CREATE DATABASE "'+rebuildUrl.pathname.slice(1)+'"');run('pnpm',['db:deploy'],rebuildUrl.href);const rebuilt=new PrismaStore(new PrismaClient({datasources:{db:{url:rebuildUrl.href}},log:[]}));try{const {authFixture}=await import('../support/talent-auth.ts'),{JsonRebuild}=await import('../../packages/core/src/rebuild.ts'),{prepareRebuildMedia}=await import('../../scripts/rebuild-media.ts'),{inspectTalentIntegrity}=await import('../../packages/core/src/talent-v2-integrity.ts');const fixture=await authFixture(rebuilt);fixture.clock.value=f.clock.value;const json=new JsonRebuild(fixture.clock),actor=await rebuilt.transaction(tx=>json.actorFromTarget(tx,'owner')),input=join(tmp,'originals');mkdirSync(input,{mode:0o700});writeFileSync(join(input,id+'.original.bin'),sampleBytes);writeFileSync(join(input,id+'.preview.jpg'),samplePreview);const verified=await prepareRebuildMedia(payload,actor.workspaceId,{REBUILD_MEDIA_INPUT_DIR:input,REBUILD_MEDIA_TARGET_DIR:join(tmp,'rebuild-media')},true);await rebuilt.transaction(tx=>new JsonRebuild(fixture.clock,undefined,verified).apply(tx,actor,payload,{requestId:randomUUID(),ip:'test'}));assert.equal(await rebuilt.client.servicePrincipal.count(),0);assert.equal(await rebuilt.client.talentSubmission.count(),0);assert.equal(await rebuilt.client.talentAccount.count(),0);assert.equal(await rebuilt.client.talentAccessGrant.count(),0);const relation=await rebuilt.client.personMedia.findFirstOrThrow();assert.equal((relation.importedOrigin as any).principalKind,'MACHINE');assert.equal((relation.importedOrigin as any).servicePrincipalId,u.servicePrincipalId);assert.equal(relation.usageState,'ADOPTED');assert.equal(await rebuilt.client.mediaAsset.count(),1);assert.equal((await rebuilt.transaction(tx=>inspectTalentIntegrity(tx,actor.workspaceId,fixture.app.config.contactKey))).relationFailures,0);checks.push('actual-json-rebuild-verified-byte-hashes-formal-only-machine-provenance-no-live-auth');}finally{await rebuilt.close();}
   await admin.$executeRawUnsafe('CREATE DATABASE "'+target.pathname.slice(1)+'"');const pgEnv=(u:URL)=>({...process.env,PGHOST:u.hostname,PGPORT:u.port,PGUSER:decodeURIComponent(u.username),PGPASSWORD:decodeURIComponent(u.password),PGDATABASE:u.pathname.slice(1)});const dump=join(tmp,'media.dump');let p=spawnSync('pg_dump',['--format=custom','--file',dump],{env:pgEnv(url),encoding:'utf8',timeout:120000});assert.equal(p.status,0,'physical pg_dump failed');p=spawnSync('pg_restore',['--no-owner','--no-acl','--dbname',target.pathname.slice(1),dump],{env:pgEnv(target),encoding:'utf8',timeout:120000});assert.equal(p.status,0,(p.stderr??'').slice(-1000));const restored=new PrismaStore(new PrismaClient({datasources:{db:{url:target.href}},log:[]}));try{
    assert.equal((await restored.client.mediaAsset.findUniqueOrThrow({where:{id}})).usageState,'ADOPTED');assert.equal((await restored.client.mediaAsset.findUniqueOrThrow({where:{id:eid}})).usageState,'STAGED');const config={...f.app.config,accessMode:'MAINTENANCE' as const,dataEgressMode:'DISABLED' as const,dataCleanupMode:'DISABLED' as const,dataMergeMode:'DISABLED' as const,recoveryEpoch:randomBytes(24).toString('hex')},ops=new RecoveryOps(f.clock,config);await restored.transaction(async tx=>{const a=await ops.actorFromRestoredTarget(tx,'owner');await ops.prepare(tx,a,hashSecret(f.app.config.recoveryEpoch),{requestId:randomUUID(),ip:'test'});});assert.equal(await restored.client.servicePrincipal.count({where:{status:'ACTIVE'}}),0);assert.equal((await restored.client.mediaAsset.findUniqueOrThrow({where:{id}})).usageState,'ADOPTED');assert.equal(await restored.client.talentSubmission.count({where:{principalKind:'MACHINE',state:'DRAFT'}}),0);checks.push('actual-pg16-dump-restore-staged-adopted-preserved-old-auth-not-revived');
   }finally{await restored.close();}
  }finally{await admin.$disconnect();}
 }
 const version=await db.$queryRawUnsafe<any[]>('SELECT version()');assert.match(version[0].version,/PostgreSQL 16/);mkdirSync('artifacts/agent-media-pr04b',{recursive:true});writeFileSync('artifacts/agent-media-pr04b/postgres-'+variant+'.json',JSON.stringify({status:'POSTGRES_TESTED',database:version,checks},null,2)+'\n');console.log(JSON.stringify({checks}));
}finally{await store.close();rmSync(tmp,{recursive:true,force:true});}
