import {registeredTemp} from '../../scripts/registered-temp.mjs';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync,writeFileSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {PrismaClient} from '@prisma/client';
import {PrismaStore} from '../../apps/api/src/prisma-store.ts';
import {agentStructuresScenario,agentStructuresCounterexample,agentStructuresLifecycle,agentStructuresProtection,agentStructuresPartialIsolation,agentStructuresBasisRevocation} from '../support/agent-structures.ts';
import {RecoveryOps} from '../../packages/core/src/recovery.ts';
import {hashSecret} from '../../packages/core/src/crypto.ts';
const raw=process.env.DATABASE_URL_TEST;assert.equal(process.env.ALLOW_DB_TESTS,'yes');assert.ok(raw);const url=new URL(raw);assert.match(url.pathname,/^\/once_test_/);const db=new PrismaClient({datasources:{db:{url:raw}},log:[]}),store=new PrismaStore(db),variant=process.env.AGENT_STRUCTURES_VARIANT??'base',checks:string[]=[],tmp=registeredTemp().path;
const run=(cmd:string,args:string[],u=raw)=>{const r=spawnSync(cmd,args,{env:{...process.env,DATABASE_URL:u},encoding:'utf8',timeout:180000});assert.equal(r.status,0,'isolated database command failed');};
try{
 if(variant==='base'){const out=await agentStructuresScenario(store);checks.push(...out.checks);const item=await db.talentSubmissionItem.findFirstOrThrow({where:{kind:'COLLECTION'}});await assert.rejects(db.talentSubmissionItem.create({data:{...item,id:randomUUID(),clientItemKey:'late-collection'}}));const credit=await db.workCredit.findFirstOrThrow(),role=await db.personRole.findFirstOrThrow();await assert.rejects(db.workCredit.create({data:{...credit,id:randomUUID()}}));await assert.rejects(db.$transaction(tx=>tx.workCredit.update({where:{id:credit.id},data:{personRoleId:randomUUID()}})));checks.push('postgres-frozen-collection-insert-unique-exact-credit-role-FK');}
 else if(['lifecycle','long-basis'].includes(variant)){
  const adminUrl=new URL(raw);adminUrl.pathname='/postgres';const admin=new PrismaClient({datasources:{db:{url:adminUrl.href}},log:[]});const newUrl=(name:string)=>{const u=new URL(raw);u.pathname='/once_test_c_'+name+'_'+randomBytes(6).toString('hex');return u;};const rebuild=newUrl('rebuild'),restore=newUrl('restore');
  try{await admin.$executeRawUnsafe('CREATE DATABASE "'+rebuild.pathname.slice(1)+'"');run('pnpm',['db:deploy'],rebuild.href);const target=new PrismaStore(new PrismaClient({datasources:{db:{url:rebuild.href}},log:[]}));let out:Awaited<ReturnType<typeof agentStructuresLifecycle>>;try{out=await agentStructuresLifecycle(store,target,variant==='long-basis');}finally{await target.close();}checks.push(...out!.checks);
   const retained=await db.$queryRawUnsafe<any[]>('SELECT migration_name,checksum FROM _prisma_migrations ORDER BY migration_name'),rows=await db.talentSubmission.findMany(),collections=await db.mediaCollection.findMany(),credits=await db.workCredit.findMany();assert.equal(retained.length,74);run('pnpm',['db:deploy']);assert.deepEqual(await db.$queryRawUnsafe('SELECT migration_name,checksum FROM _prisma_migrations ORDER BY migration_name'),retained);assert.deepEqual(await db.talentSubmission.findMany(),rows);assert.deepEqual(await db.mediaCollection.findMany(),collections);assert.deepEqual(await db.workCredit.findMany(),credits);checks.push('fresh1-through74-and-retained74-no-op-byte-frozen-rows-preserved');
   await admin.$executeRawUnsafe('CREATE DATABASE "'+restore.pathname.slice(1)+'"');const pgEnv=(u:URL)=>({...process.env,PGHOST:u.hostname,PGPORT:u.port,PGUSER:decodeURIComponent(u.username),PGPASSWORD:decodeURIComponent(u.password),PGDATABASE:u.pathname.slice(1)}),dump=join(tmp,'structures.dump');let r=spawnSync('pg_dump',['--format=custom','--file',dump],{env:pgEnv(url),encoding:'utf8',timeout:120000});assert.equal(r.status,0,'physical dump failed');r=spawnSync('pg_restore',['--no-owner','--no-acl','--dbname',restore.pathname.slice(1),dump],{env:pgEnv(restore),encoding:'utf8',timeout:120000});assert.equal(r.status,0,'physical restore failed');const restored=new PrismaStore(new PrismaClient({datasources:{db:{url:restore.href}},log:[]}));try{
    assert.equal((await restored.client.mediaAsset.findUniqueOrThrow({where:{id:out!.f.photo}})).usageState,'ADOPTED');assert.equal((await restored.client.mediaAsset.findUniqueOrThrow({where:{id:out!.staged}})).usageState,'STAGED');assert.equal((await restored.client.workCredit.findUniqueOrThrow({where:{id:out!.credit.id}})).personRoleId,out!.credit.personRoleId);const restoredWorkItem=await restored.client.talentSubmissionItem.findFirstOrThrow({where:{submissionId:out!.f.root,kind:'WORK'}});assert.equal(restoredWorkItem.appliedId,out!.work.id);assert.notEqual(restoredWorkItem.appliedId,out!.credit.id);assert.equal((await restored.client.mediaCollection.findUniqueOrThrow({where:{id:out!.collection.id}})).coverAssetId,out!.f.photo);
    const config={...out!.f.app.config,accessMode:'MAINTENANCE' as const,dataEgressMode:'DISABLED' as const,dataCleanupMode:'DISABLED' as const,dataMergeMode:'DISABLED' as const,recoveryEpoch:randomBytes(24).toString('hex')},ops=new RecoveryOps(out!.f.clock,config);await restored.transaction(async tx=>{const a=await ops.actorFromRestoredTarget(tx,'owner');await ops.prepare(tx,a,hashSecret(out!.f.app.config.recoveryEpoch),{requestId:randomUUID(),ip:'test'});});assert.equal(await restored.client.servicePrincipal.count({where:{status:'ACTIVE'}}),0);assert.equal(await restored.client.talentSubmission.count({where:{principalKind:'MACHINE',state:'DRAFT'}}),0);assert.equal((await restored.client.mediaAsset.findUniqueOrThrow({where:{id:out!.f.photo}})).usageState,'ADOPTED');assert.equal((await restored.client.talentSubmissionItem.findUniqueOrThrow({where:{id:restoredWorkItem.id}})).appliedId,out!.work.id);checks.push('physical-restore-and-recovery-preserve-WORK-appliedId-as-Work-id-not-Credit');checks.push('actual-pg16-dump-restore-collections-cover-work-credits-staged-adopted-preserved-old-authorization-dead');
   }finally{await restored.close();}
  }finally{await admin.$disconnect();}
 }else if(variant==='formal-basis'){checks.push(...await agentStructuresBasisRevocation(store));}else if(variant==='partial-valid'){checks.push(...await agentStructuresPartialIsolation(store));}else if(['PERSON','MERGE'].includes(variant)){checks.push(...await agentStructuresProtection(store,variant as 'PERSON'|'MERGE'));}
 else{await agentStructuresCounterexample(store,variant);checks.push('postgres-counterexample-'+variant);}
 const version=await db.$queryRawUnsafe<any[]>('SELECT version()');assert.match(version[0].version,/PostgreSQL 16/);mkdirSync('artifacts/agent-structures-pr04c',{recursive:true});writeFileSync('artifacts/agent-structures-pr04c/postgres-'+variant+'.json',JSON.stringify({status:'POSTGRES_TESTED',database:version,checks},null,2)+'\n');console.log(JSON.stringify({checks}));
}finally{await store.close();rmSync(tmp,{recursive:true,force:true});}
