import {registeredTemp} from '../../scripts/registered-temp.mjs';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,copyFileSync,readdirSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {PrismaClient} from '@prisma/client';
import {MemoryStore} from '../support/memory-store.ts';
import {verifyTalentMaintenance} from '../support/talent-maintenance.ts';
import {result} from '../support/fixtures.ts';
const raw=process.env.DATABASE_URL_INGESTION_UPGRADE_TEST;assert.equal(process.env.ALLOW_DB_TESTS,'yes');assert.ok(raw);const u=new URL(raw);assert.ok(['localhost','127.0.0.1'].includes(u.hostname));assert.match(u.pathname,/^\/once_test_[a-z0-9_]+$/);const db=new PrismaClient({datasources:{db:{url:raw}},log:[]}),root=registeredTemp().path;
try{assert.equal((await db.$queryRawUnsafe<any[]>("SELECT tablename FROM pg_tables WHERE schemaname='public'")).length,0);const names=readdirSync('prisma/migrations').filter(x=>/^\d/.test(x)).sort();assert.equal(names[67],'202610010013_media_purge_plan_guard');copyFileSync('prisma/schema.prisma',join(root,'schema.prisma'));mkdirSync(join(root,'migrations'));copyFileSync('prisma/migrations/migration_lock.toml',join(root,'migrations/migration_lock.toml'));for(const name of names.slice(0,68)){mkdirSync(join(root,'migrations',name));copyFileSync(join('prisma/migrations',name,'migration.sql'),join(root,'migrations',name,'migration.sql'));}const deploy=(schema:string)=>{const r=spawnSync('pnpm',['exec','prisma','migrate','deploy','--schema',schema],{env:{...process.env,DATABASE_URL:raw},encoding:'utf8',timeout:120000});assert.equal(r.status,0,r.stderr);};deploy(join(root,'schema.prisma'));
 const memory=new MemoryStore(),{f}=await verifyTalentMaintenance(memory);await f.owner.login();const member=memory.rows('memberships')[0]!;const principal=await f.owner.raw('POST','/td2/principals',{schemaVersion:'once-talent-v2.1.0',displayName:'既有 TD2 机器凭证',scopeId:f.scopeId,defaultMaintainerMembershipId:member.id,permissionCodes:['records.read','talent.fact.write'],expiresAt:'2026-11-01T00:00:00.000Z'});assert.equal(principal.status,201,JSON.stringify(principal.body));const tables=['workspaces','users','memberships','scopes','scopeMembers','dictionary','sources','sourceHistory','people','talentProfiles','personRoles','talentAccounts','talentIdentities','talentSessions','talentAuthContexts','talentAuthChallenges','talentAuthDeliveries','talentInvitations','talentInvitationContexts','talentClaims','talentAccessGrants','talentConsents','talentSubmissions','talentSubmissionItems','sourceAttributions','sourceUseBases','servicePrincipals'] as const;
 await db.$transaction(async tx=>{await tx.$executeRawUnsafe('SET CONSTRAINTS ALL DEFERRED');for(const table of tables){const fields=await tx.$queryRawUnsafe<Array<{column_name:string}>>("SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1",table),allowed=new Set(fields.map(f=>f.column_name));for(const row of memory.rows(table)){const data=Object.fromEntries(Object.entries(row).filter(([key])=>allowed.has(key)));await tx.$executeRawUnsafe(`INSERT INTO "${table}" SELECT * FROM jsonb_populate_record(NULL::"${table}",$1::jsonb)`,JSON.stringify(data));}}},{timeout:30000});
 const before:Record<string,any[]>={};for(const table of tables)before[table]=await db.$queryRawUnsafe<any[]>(`SELECT * FROM "${table}" ORDER BY id`);deploy(resolve('prisma/schema.prisma'));await db.$disconnect();await db.$connect();for(const table of tables){const after=await db.$queryRawUnsafe<any[]>(`SELECT * FROM "${table}" ORDER BY id`);assert.equal(after.length,before[table]!.length);for(let i=0;i<after.length;i++)for(const [key,value]of Object.entries(before[table]![i]!))assert.deepEqual(after[i]![key],value,table+'.'+key);}
 assert.equal((await db.servicePrincipal.findUniqueOrThrow({where:{id:result(principal).resourceId}})).authorizationEpoch,1);assert.equal(await db.talentSubmission.count({where:{principalKind:'MACHINE'}}),0);assert.equal(await db.talentSubmission.count({where:{principalKind:'TALENT'}}),memory.rows('talentSubmissions').length);assert.equal(await db.sourceUseBasis.count({where:{basisKind:'INTERNAL_REVIEW'}}),0);mkdirSync('artifacts/agent-ingestion-pr04a',{recursive:true});writeFileSync('artifacts/agent-ingestion-pr04a/upgrade.json',JSON.stringify({status:'POSTGRES_TESTED',fromMigrations:68,toMigrations:names.length,checks:['retained-talent-account-claim-grant-submission-items-consent-attribution-basis-old-columns-identical','old-machine-key-version-credential-scope-permission-identity-unchanged-epoch-initialized-one','no-fabricated-machine-submission-or-internal-review-basis']},null,2)+'\n');console.log('PASS retained migration 68 upgrade to '+names.length);
}finally{await db.$disconnect();rmSync(root,{recursive:true,force:true});}
