import {ingestionExport,ingestionRebuild,ingestionLifecycle} from '../support/ingestion-lifecycle.ts';
import {RecoveryOps} from '../../packages/core/src/recovery.ts';
import {hashSecret} from '../../packages/core/src/crypto.ts';
import {spawnSync} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {PrismaStore} from '../../apps/api/src/prisma-store.ts';
import {verifyIngestion} from '../support/ingestion.ts';
import {mkdirSync,writeFileSync} from 'node:fs';
const raw=process.env.DATABASE_URL_INGESTION_TEST;assert.equal(process.env.ALLOW_DB_TESTS,'yes');assert.ok(raw);const u=new URL(raw);assert.ok(['localhost','127.0.0.1'].includes(u.hostname));assert.match(u.pathname,/^\/once_test_[a-z0-9_]+$/);
const db=new PrismaClient({datasources:{db:{url:raw}},log:[]}),store=new PrismaStore(db);
try{assert.equal(await db.workspace.count(),0);const verified=await verifyIngestion(store,async()=>{await db.$executeRawUnsafe(`CREATE FUNCTION once_ingestion_audit_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='ingestionReview.review' THEN RAISE EXCEPTION 'synthetic audit failure'; END IF; RETURN NEW; END; $$`);await db.$executeRawUnsafe(`CREATE TRIGGER once_ingestion_audit_fail BEFORE INSERT ON audits FOR EACH ROW EXECUTE FUNCTION once_ingestion_audit_fail()`);},async()=>{await db.$executeRawUnsafe(`DROP TRIGGER once_ingestion_audit_fail ON audits`);await db.$executeRawUnsafe(`DROP FUNCTION once_ingestion_audit_fail()`);});
 const {checks,id,basisId,servicePrincipalId}=verified;
 await assert.rejects(db.talentSubmission.update({where:{id},data:{principalKind:'TALENT'}}));await assert.rejects(db.talentSubmission.update({where:{id},data:{servicePrincipalId:crypto.randomUUID()}}));await assert.rejects(db.talentSubmission.update({where:{id},data:{consentId:crypto.randomUUID()}}));const root=await db.talentSubmission.findUniqueOrThrow({where:{id}});await assert.rejects(db.talentSubmission.create({data:{...root,id:crypto.randomUUID()}}));await assert.rejects(db.talentSubmission.create({data:{...root,id:crypto.randomUUID(),externalSubmissionKey:'bad-zero',servicePrincipalAuthorizationEpoch:0}}));await assert.rejects(db.talentSubmission.create({data:{...root,id:crypto.randomUUID(),externalSubmissionKey:'bad-null',servicePrincipalAuthorizationEpoch:null}}));await assert.rejects(db.talentSubmission.create({data:{...root,id:crypto.randomUUID(),externalSubmissionKey:'bad-pre-bind',state:'DRAFT'}}));checks.push('postgres-principal-xor-composite-fk-immutable-owner-unique-external-key-null-zero-and-prebinding-rejected');
 await assert.rejects(db.sourceUseBasis.update({where:{id:basisId},data:{consentRevision:0}}));await assert.rejects(db.sourceUseBasis.update({where:{id:basisId},data:{reviewerId:null}}));await assert.rejects(db.sourceUseBasis.update({where:{id:basisId},data:{reviewBasis:''}}));await assert.rejects(db.sourceUseBasis.update({where:{id:basisId},data:{basisKind:'TALENT_CONSENT',consentRevision:0}}));await assert.rejects(db.servicePrincipal.update({where:{id:servicePrincipalId},data:{authorizationEpoch:99}}));checks.push('postgres-typed-basis-no-fake-consent-zero-no-missing-reviewer-or-basis-no-unjustified-epoch');

 const payload=await ingestionExport(verified),adminUrl=new URL(raw);adminUrl.pathname='/postgres';const admin=new PrismaClient({datasources:{db:{url:adminUrl.toString()}},log:[]});const fresh=async(migrate:boolean)=>{const target=new URL(raw);target.pathname='/once_test_ingestion_'+randomBytes(6).toString('hex');await admin.$executeRawUnsafe(`CREATE DATABASE "${target.pathname.slice(1)}"`);if(migrate){const p=spawnSync('pnpm',['db:deploy'],{env:{...process.env,DATABASE_URL:target.toString()},encoding:'utf8',timeout:120000});assert.equal(p.status,0,p.stderr);}return target.toString();};
 try{const rebuildRaw=await fresh(true),rebuilt=new PrismaStore(new PrismaClient({datasources:{db:{url:rebuildRaw}},log:[]}));try{await ingestionRebuild(verified,rebuilt,payload);}finally{await rebuilt.close();}checks.push('postgres-real-business-json-rebuild-imported-internal-basis-no-principal-account-or-submission');
 const restoreRaw=await fresh(false),tmp=mkdtempSync(join(tmpdir(),'once-ingestion-restore-')),restored=new PrismaStore(new PrismaClient({datasources:{db:{url:restoreRaw}},log:[]}));const pgEnv=(raw:string)=>{const u=new URL(raw);return {...process.env,PGHOST:u.hostname,PGPORT:u.port,PGUSER:decodeURIComponent(u.username),PGPASSWORD:decodeURIComponent(u.password),PGDATABASE:u.pathname.slice(1)};};try{const dump=join(tmp,'snapshot.dump');let p=spawnSync('pg_dump',['--format=custom','--file',dump],{env:pgEnv(raw),encoding:'utf8',timeout:120000});assert.equal(p.status,0,p.stderr);p=spawnSync('pg_restore',['--no-owner','--no-acl','--dbname',new URL(restoreRaw).pathname.slice(1),dump],{env:pgEnv(restoreRaw),encoding:'utf8',timeout:120000});assert.equal(p.status,0,p.stderr);for(const table of ['talentSubmissions','talentSubmissionItems','servicePrincipals','sourceUseBases','sourceAttributions'] as const){const sort=(a:any[])=>a.sort((a,b)=>a.id.localeCompare(b.id));assert.deepEqual(sort(await restored.transaction(tx=>tx.find(table))),sort(await store.transaction(tx=>tx.find(table))));}const config={...verified.f.app.config,accessMode:'MAINTENANCE' as const,dataEgressMode:'DISABLED' as const,dataCleanupMode:'DISABLED' as const,dataMergeMode:'DISABLED' as const,recoveryEpoch:randomBytes(24).toString('hex')},ops=new RecoveryOps(verified.f.clock,config);await restored.transaction(async tx=>{const actor=await ops.actorFromRestoredTarget(tx,'owner');await ops.prepare(tx,actor,hashSecret(verified.f.app.config.recoveryEpoch),{requestId:randomUUID(),ip:'test'});});assert.equal(await restored.client.servicePrincipal.count({where:{status:'ACTIVE'}}),0);assert.equal(await restored.client.talentSubmission.count({where:{principalKind:'MACHINE',state:{in:['DRAFT','SUBMITTED']}}}),0);assert.ok(await restored.client.sourceUseBasis.count({where:{basisKind:'INTERNAL_REVIEW'}})>=2);checks.push('actual-pg-dump-restore-preserves-machine-provenance-recovery-revokes-principals-and-expires-drafts-without-reviving-auth');}finally{await restored.close();rmSync(tmp,{recursive:true,force:true});}
 }finally{await admin.$disconnect();}
 checks.push(...await ingestionLifecycle(verified));const erased=await db.talentSubmission.findUniqueOrThrow({where:{id}});assert.deepEqual(erased.sourceDeclaration,{erased:true});await assert.rejects(db.talentSubmission.update({where:{id},data:{sourceDeclaration:{title:'revive',providerClaim:'bad',materialDescription:'forbidden'}}}));checks.push('postgres-terminal-declaration-erasure-one-way-no-revival');
 mkdirSync('artifacts/agent-ingestion-pr04a',{recursive:true});writeFileSync('artifacts/agent-ingestion-pr04a/postgres.json',JSON.stringify({status:'POSTGRES_TESTED',database:await db.$queryRawUnsafe('SELECT version()'),checks},null,2)+'\n');console.log(JSON.stringify({checks}));
}finally{await store.close();}
