import {purgeRestoreScenario} from './media-purge-restore.ts';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {PrismaStore} from '../../apps/api/src/prisma-store.ts';
import {purgeRaceScenario,purgeLifecycleScenario,purgeRollbackScenario,purgeDeletionScenario,purgeBatchScenario,purgeDecisionScenario,uploadRetentionScenario} from '../support/media-purge.ts';
const url=process.env.DATABASE_URL_MEDIA_PURGE_TEST;assert.ok(process.env.ALLOW_DB_TESTS==='yes'&&url&&new URL(url).pathname.startsWith('/once_test_'));
const db=new PrismaClient({datasources:{db:{url}},log:[]}),store=new PrismaStore(db);
try{assert.equal(await db.workspace.count(),0);const variant=process.env.MEDIA_PURGE_VARIANT;const r=variant?.startsWith('retention-')?await uploadRetentionScenario(store,Number(variant.split('-')[1])):variant?.startsWith('ownership-')?await purgeDeletionScenario(store,false,variant.slice(10)):['partial','rejected'].includes(variant??'')?await purgeDecisionScenario(store,variant==='partial'):variant==='batch'?await purgeBatchScenario(store):variant?.startsWith('deletion-')?await purgeDeletionScenario(store,variant==='deletion-ttl'):variant==='restore'?await purgeRestoreScenario(store,db,url):variant==='rollback'?await purgeRollbackScenario(store):variant==='lifecycle'?await purgeLifecycleScenario(store):await purgeRaceScenario(store,variant==='purge-first');
 const p=await db.mediaPurgeIntent.findFirst();if(['retention-1','retention-30','deletion-explicit','ownership-slow'].includes(variant??''))assert.equal(p,null,'explicit ownership/active draft must not create a TTL intent');else assert.ok(p,'scenario must retain its purge evidence');if(p){await assert.rejects(db.mediaPurgeIntent.create({data:{...p,id:crypto.randomUUID()}}));await assert.rejects(db.mediaPurgeIntent.update({where:{id:p.id},data:{leaseToken:crypto.randomUUID(),leaseUntil:null}}));await assert.rejects(db.mediaPurgeIntent.update({where:{id:p.id},data:{assetId:crypto.randomUUID()}}));await assert.rejects(db.mediaPurgeIntent.update({where:{id:p.id},data:{state:'INVALID'}}));for(const plan of [[{part:'original'}],[{part:'original',bytes:null,hash:'a'.repeat(64),state:'MISSING'}],[{part:'original',bytes:100,hash:'a'.repeat(64),state:null}]]){const v=await db.$queryRaw<Array<{valid:boolean}>>`SELECT once_purge_object_plan_valid(${JSON.stringify(plan)}::jsonb) AS valid`;assert.equal(v[0]!.valid,false);}
 for(const objects of [[{part:'original'}],[{part:'original',bytes:100,hash:'a'.repeat(64),state:null}],[{...p.objects[0]!,hash:'f'.repeat(64)}]])await assert.rejects(db.mediaPurgeIntent.update({where:{id:p.id},data:{objects}}));}console.log(JSON.stringify({checks:[...r.checks,...(p?['PG unique-asset FK state-check lease-pair-check JSON-null-reject immutable-object-plan']:[])],variant}));
}finally{await store.close();}
