import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,mkdirSync,copyFileSync,readdirSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {PrismaClient} from '@prisma/client';
import {PrismaStore} from '../../apps/api/src/prisma-store.ts';
import {Commands} from '../../packages/core/src/commands.ts';
import {digest} from '../../packages/core/src/json.ts';
import {FakeClock} from '../support/fixtures.ts';
import type {Actor} from '../../packages/core/src/model.ts';
test('PR02a populated migration 55 preserves internal/machine receipts and system attribution',async()=>{
 assert.equal(process.env.ALLOW_TALENT_AUTH_DB_TESTS,'yes');const raw=process.env.DATABASE_URL_TALENT_AUTH_UPGRADE_TEST;assert.ok(raw);const u=new URL(raw);assert.ok(['localhost','127.0.0.1'].includes(u.hostname));assert.match(u.pathname,/^\/once_test_[a-z0-9_]+$/);assert.ok(u.username&&u.password&&!u.search&&!u.hash);const db=new PrismaClient({datasources:{db:{url:raw}},log:[]}),root=mkdtempSync(join(tmpdir(),'once-auth-upgrade-'));try{
 assert.equal((await db.$queryRawUnsafe<any[]>("SELECT tablename FROM pg_tables WHERE schemaname='public'")).length,0);const migrations=resolve('prisma/migrations'),names=readdirSync(migrations).filter(x=>/^\d/.test(x)).sort();const prior=names.filter(x=>x<'202610010001');assert.equal(prior.length,55);copyFileSync('prisma/schema.prisma',join(root,'schema.prisma'));mkdirSync(join(root,'migrations'));copyFileSync(join(migrations,'migration_lock.toml'),join(root,'migrations/migration_lock.toml'));for(const name of prior){mkdirSync(join(root,'migrations',name));copyFileSync(join(migrations,name,'migration.sql'),join(root,'migrations',name,'migration.sql'));}
 const deploy=(schema:string)=>{const r=spawnSync('pnpm',['exec','prisma','migrate','deploy','--schema',schema],{env:{...process.env,DATABASE_URL:raw},encoding:'utf8',timeout:120000});assert.equal(r.status,0,r.stderr);};deploy(join(root,'schema.prisma'));
 const workspaceId=randomUUID(),userId=randomUUID(),membershipId=randomUUID(),scopeId=randomUUID(),machineId=randomUUID(),clock=new FakeClock(),now=clock.now().toISOString(),base=(id=randomUUID())=>({id,workspaceId,createdAt:now,updatedAt:now,revision:1});
 const allowed=new Set(['workspaces','users','memberships','scopes','servicePrincipals','receipts','audits']);const insert=async(table:string,row:object)=>{assert.ok(allowed.has(table));await db.$executeRawUnsafe(`INSERT INTO "${table}" SELECT * FROM jsonb_populate_record(NULL::"${table}",$1::jsonb)`,JSON.stringify(row));};
 await insert('workspaces',{id:workspaceId,name:'合成认证升级',createdAt:now,recoveryEpoch:'synthetic-auth-upgrade-epoch'});await insert('users',{...base(userId),loginName:'owner',displayName:'合成管理员',passwordHash:null,status:'ACTIVE',sessionEpoch:1});await insert('memberships',{...base(membershipId),userId,role:'ADMIN',extraPermissions:[],status:'ACTIVE'});await insert('scopes',{...base(scopeId),name:'合成范围',mode:'WORKSPACE'});await insert('servicePrincipals',{...base(machineId),displayName:'合成机器',scopeId,permissionCodes:['records.read'],defaultMaintainerMembershipId:membershipId,credentialHash:null,keyVersion:1,expiresAt:null,recoveryEpoch:'synthetic-auth-upgrade-epoch',status:'REVOKED'});
 const key=randomUUID(),operation='synthetic.legacy.command',targetId=randomUUID(),input={synthetic:true};const results=[];
 for(const isMachine of [false,true]){const result={operationId:randomUUID(),resourceId:targetId,revision:7,state:'SUCCEEDED'};results.push(result);await insert('receipts',{...base(),actorId:isMachine?null:membershipId,servicePrincipalId:isMachine?machineId:null,operation,commandKey:key,requestDigest:digest({operation,targetId,input}),resourceKind:'person',resourceId:targetId,result});await insert('audits',{...base(),actorId:isMachine?null:membershipId,servicePrincipalId:isMachine?machineId:null,action:operation,resourceKind:'person',resourceId:targetId,changedFields:[],requestId:randomUUID()});}
 await insert('audits',{...base(),actorId:null,servicePrincipalId:null,action:'auth.logout',resourceKind:'session',resourceId:randomUUID(),changedFields:[],requestId:randomUUID()});const oldReceipts=await db.$queryRawUnsafe<any[]>('SELECT * FROM "receipts" ORDER BY id'),oldAudits=await db.$queryRawUnsafe<any[]>('SELECT * FROM "audits" ORDER BY id');deploy(resolve('prisma/schema.prisma'));await db.$disconnect();await db.$connect();
 for(const [table,before]of [['receipts',oldReceipts],['audits',oldAudits]] as const){const after=await db.$queryRawUnsafe<any[]>(`SELECT * FROM "${table}" ORDER BY id /* upgraded schema */`);assert.equal(after.length,before.length);for(let i=0;i<before.length;i++){for(const [key,value]of Object.entries(before[i]!))assert.deepEqual(after[i]![key],value);assert.equal(after[i]!.principalKind,before[i]!.servicePrincipalId?'MACHINE':before[i]!.actorId?'INTERNAL':'SYSTEM');}}
 const store=new PrismaStore(db),commands=new Commands(clock);for(const [index,isMachine]of [false,true].entries()){const actor:Actor={actorKind:isMachine?'MACHINE':'HUMAN',...(isMachine?{servicePrincipalId:machineId}:{}),workspaceId,userId,membershipId,role:'ADMIN',permissions:[],displayName:'合成',userEpoch:1,sessionId:'synthetic'};let authorized=false;const replay=await store.transaction(tx=>commands.execute(tx,actor,operation,key,targetId,input,'person',{requestId:randomUUID(),ip:'test'},async()=>{assert.fail('must replay legacy receipt');},async()=>{authorized=true;}));assert.equal(authorized,true);assert.deepEqual(replay,{...results[index],replayed:true});}
 mkdirSync('artifacts/talent-experience-pr02a',{recursive:true});writeFileSync('artifacts/talent-experience-pr02a/upgrade.json',JSON.stringify({status:'PASSED',fromMigrations:55,toMigrations:names.length,checks:['old-internal-machine-command-keys-and-results-preserved','system-audits-not-guessed-as-member','all-original-receipt-audit-fields-preserved','both-principals-replay-with-current-engine']},null,2)+'\n');
 }finally{await db.$disconnect();rmSync(root,{recursive:true,force:true});}
});
