import {workFinalizationScenario} from '../support/work-case-finalization.ts';
import assert from 'node:assert/strict';
import {PrismaClient} from '@prisma/client';
import {PrismaStore} from '../../apps/api/src/prisma-store.ts';
import {workCaseScenario,workCaseLifecycleScenario,workCaseEnrollScenario,workCaseExportScenario,workCaseProtectionScenario,workCaseSharedScenario} from '../support/work-cases.ts';
const url=process.env.DATABASE_URL_WORK_CASE_TEST;assert.ok(process.env.ALLOW_DB_TESTS==='yes'&&url&&new URL(url).pathname.startsWith('/once_test_'));
const db=new PrismaClient({datasources:{db:{url}},log:[]}),store=new PrismaStore(db);
try{assert.equal(await db.workspace.count(),0);if(['takeover','legacy'].includes(process.env.WORK_CASE_VARIANT??'')){console.log(JSON.stringify(await workFinalizationScenario(store,process.env.WORK_CASE_VARIANT==='legacy')));}else if(process.env.WORK_CASE_VARIANT==='shared'){console.log(JSON.stringify(await workCaseSharedScenario(store)));}else if(['PERSON','WORK','MERGE'].includes(process.env.WORK_CASE_VARIANT??'')){console.log(JSON.stringify(await workCaseProtectionScenario(store,process.env.WORK_CASE_VARIANT as 'PERSON'|'WORK'|'MERGE')));}else if(process.env.WORK_CASE_VARIANT==='export'){const targetUrl=process.env.DATABASE_URL_WORK_REBUILD_TEST;assert.ok(targetUrl);const target=new PrismaStore(new PrismaClient({datasources:{db:{url:targetUrl}},log:[]}));try{console.log(JSON.stringify(await workCaseExportScenario(store,target)));}finally{await target.close();}}else if(process.env.WORK_CASE_VARIANT==='lifecycle'){console.log(JSON.stringify(await workCaseLifecycleScenario(store)));}else if(process.env.WORK_CASE_VARIANT==='enroll'){console.log(JSON.stringify(await workCaseEnrollScenario(store)));}else{const {work,credit,asset}=await workCaseScenario(store);const row=await db.workCredit.findUniqueOrThrow({where:{id:credit.id}});await assert.rejects(db.workCredit.create({data:{...row,id:crypto.randomUUID()}}));await assert.rejects(db.workCredit.update({where:{id:credit.id},data:{personRoleId:crypto.randomUUID()}}));await assert.rejects(db.workCredit.update({where:{id:credit.id},data:{sourceId:null}}));await assert.rejects(db.work.update({where:{id:work.id},data:{coverEntryId:crypto.randomUUID()}}));const entry=await db.workAsset.findFirstOrThrow({where:{workId:work.id,assetId:asset}});await assert.rejects(db.workAsset.create({data:{...entry,id:crypto.randomUUID()}}));const original=await db.work.findUniqueOrThrow({where:{id:work.id}}),concurrent=await db.work.create({data:{...original,id:crypto.randomUUID(),coverEntryId:null,title:'并发署名约束合成案例'}});const writes=await Promise.allSettled([1,2].map(()=>db.workCredit.create({data:{...row,id:crypto.randomUUID(),workId:concurrent.id}})));assert.equal(writes.filter(r=>r.status==='fulfilled').length,1);assert.equal(writes.filter(r=>r.status==='rejected').length,1);
console.log('PR03D PostgreSQL: review atomicity, exact role/source FK, unique Credit/Asset, cover FK PASS');}}finally{await store.close();}
