import type {Actor,Clock,Config,Person,Source,Permission} from './model.ts';
import type {Tx} from './store.ts';
import type {MachineSubmission,TalentSubmissionItem} from './talent-maintenance-model.ts';
import {IngestionSchemas as S,INGESTION_VERSION,INGESTION_INPUT_VERSION,parseCandidate} from './ingestion-schema.ts';
import {MachineIdentity} from './talent-v2-machine.ts';
import {authorizationEpoch} from './machine-authorization.ts';
import {AppError,invariant,missing} from './errors.ts';
import {base,touch,cas,workspaceRow,page} from './helpers.ts';
import {digest} from './json.ts';
import {requirePermission,requireScope,scopeVisible,sourceFor,sourceCurrent,deletionBlocked,personAliasFor} from './policy.ts';
import {appendSourceHistory} from './source-history.ts';
import {TalentV2} from './talent-v2.ts';
import {td2PersonFor,loadTalentGraph,asRow,periodCurrent,insertFact,replaceFact} from './talent-v2-graph.ts';
import {TD2_FACTS,rowDefaults,type FactTable,type FactRow} from './talent-v2-schema.ts';
import {PROFILE_DEFAULTS,ROLE_DEFAULTS,validateDemographics} from './talent-demographics.ts';
const TEXT=['displayName','aliases','intro'];
const open=new Set(['DRAFT','SUBMITTED']);
export class Ingestion {
 clock:Clock;config:Config;
 constructor(clock:Clock,config:Config){this.clock=clock;this.config=config;}
 now(){return this.clock.now().toISOString();}
 until(days:number){return new Date(this.clock.now().getTime()+days*86400000).toISOString();}
 enabled(){invariant(this.config.ingestionEnabled===true,'INGESTION_DISABLED','外部摄取入口未开放',503);}
 async principal(tx:Tx,actor:Actor){this.enabled();invariant(actor.actorKind==='MACHINE'&&actor.servicePrincipalId,'MACHINE_REQUIRED','此入口仅接受机器主体',403);const p=await workspaceRow(tx,'servicePrincipals',actor.servicePrincipalId,actor.workspaceId);if(!p)missing();await this.currentPrincipal(tx,p.id,actor.workspaceId);return p;}
 async currentPrincipal(tx:Tx,id:string,workspaceId:string,s?:MachineSubmission){
  const p=await workspaceRow(tx,'servicePrincipals',id,workspaceId),w=await tx.get('workspaces',workspaceId);invariant(p&&p.status==='ACTIVE'&&!!p.expiresAt&&Date.parse(p.expiresAt)>this.clock.now().getTime()&&p.recoveryEpoch===this.config.recoveryEpoch&&w?.recoveryEpoch===this.config.recoveryEpoch&&this.config.accessMode==='INTERNAL','INGESTION_AUTHORIZATION_CHANGED','摄取主体已失效或进入恢复隔离',409);
  await new MachineIdentity(this.clock,this.config).validateMaintainer(tx,workspaceId,p.defaultMaintainerMembershipId,p.scopeId,p.permissionCodes as Permission[]);
  const scope=await workspaceRow(tx,'scopes',p.scopeId,workspaceId);invariant(scope,'INGESTION_AUTHORIZATION_CHANGED','接收范围已失效',409);
  invariant((!s||p.permissionCodes.includes('ingestion.submit'))&&(!s||authorizationEpoch(p)===s.servicePrincipalAuthorizationEpoch&&p.scopeId===s.scopeId&&p.defaultMaintainerMembershipId===s.maintainerId&&scope.revision===s.intakeScopeRevision&&s.recoveryEpoch===this.config.recoveryEpoch),'INGESTION_AUTHORIZATION_CHANGED','授权边界发生变化，请在当前授权下新建提交',409);return {p,scope};
 }
 async access(tx:Tx,actor:Actor,id:string,review=false,forFork=false){
  const raw=await workspaceRow(tx,'talentSubmissions',id,actor.workspaceId);if(!raw||raw.principalKind!=='MACHINE')missing();const s=raw as MachineSubmission;
  if(review){invariant(actor.actorKind!=='MACHINE','HUMAN_REVIEW_REQUIRED','审核需要内部人员',403);requirePermission(actor,'talent.review');await requireScope(tx,actor,s.scopeId);}
  else{const p=await this.principal(tx,actor);if(s.servicePrincipalId!==p.id)missing();}
  if(forFork){invariant(s.recoveryEpoch===this.config.recoveryEpoch,'INGESTION_AUTHORIZATION_CHANGED','恢复隔离后的旧草稿不可复用',409);const p=(await this.currentPrincipal(tx,s.servicePrincipalId,s.workspaceId)).p;const maintainer=await new MachineIdentity(this.clock,this.config).validateMaintainer(tx,s.workspaceId,p.defaultMaintainerMembershipId,p.scopeId,p.permissionCodes as Permission[]);await requireScope(tx,maintainer,s.scopeId);}else await this.currentPrincipal(tx,s.servicePrincipalId,s.workspaceId,s);return s;
 }
 async itemsFor(tx:Tx,s:MachineSubmission){return (await tx.find('talentSubmissionItems',{workspaceId:s.workspaceId,submissionId:s.id})).sort((a,b)=>a.clientItemKey.localeCompare(b.clientItemKey));}
 async targetBaseline(tx:Tx,workspaceId:string,id:string){
  const p=await workspaceRow(tx,'people',id,workspaceId);invariant(p&&p.status!=='ERASED'&&p.status!=='ARCHIVED'&&!await personAliasFor(tx,workspaceId,id)&&!await deletionBlocked(tx,workspaceId,'PERSON',id),'TARGET_REBASE_REQUIRED','建议目标已合并、删除或不可用于本次关联',409);
  const scope=await workspaceRow(tx,'scopes',p.scopeId,workspaceId);invariant(scope,'TARGET_REBASE_REQUIRED','建议目标范围已失效',409);
  const facts=[],sourceIds=new Set([p.sourceId]);for(const t of ['personRoles','talentProfiles','castingProfiles','measurementSets'] as const)for(const f of await tx.find(t,{workspaceId,personId:id})){facts.push({table:t,id:f.id,revision:f.revision});sourceIds.add(f.sourceId);}facts.sort((a,b)=>a.id.localeCompare(b.id));const sources=[];for(const id of [...sourceIds].sort()){const src=await workspaceRow(tx,'sources',id,workspaceId),scope=src?await workspaceRow(tx,'scopes',src.scopeId,workspaceId):null;sources.push({id,revision:src?.revision??null,protectionEpoch:src?.protectionEpoch??null,scopeId:src?.scopeId??null,scopeRevision:scope?.revision??null,current:!!src&&sourceCurrent(src,this.clock)});}
  return {personId:p.id,revision:p.revision,protectionEpoch:p.protectionEpoch,status:p.status,scopeId:p.scopeId,scopeRevision:scope.revision,facts,sources};
 }
 async checkTarget(tx:Tx,s:MachineSubmission){if(s.proposedPersonId)invariant(digest(await this.targetBaseline(tx,s.workspaceId,s.proposedPersonId))===digest(s.proposedTargetBaseline),'TARGET_REBASE_REQUIRED','建议目标已变化；须 fork 并重新冻结，不能静默改绑',409);}
 async create(tx:Tx,actor:Actor,input:unknown){const d=S.create.parse(input);invariant(d.sourceDeclaration.title.trim().length>0&&d.sourceDeclaration.providerClaim.trim().length>0&&d.sourceDeclaration.materialDescription.trim().length>=4,'SOURCE_DECLARATION_REQUIRED','请提供明确来源声明',422);const p=await this.principal(tx,actor),scope=(await this.currentPrincipal(tx,p.id,p.workspaceId)).scope;
  invariant(!(await tx.find('talentSubmissions',{workspaceId:actor.workspaceId,servicePrincipalId:p.id,externalSubmissionKey:d.externalSubmissionKey})).length,'EXTERNAL_SUBMISSION_KEY_EXISTS','外部提交键已使用，请读取原提交或使用新键',409);
  if(d.proposedPersonId)await this.targetBaseline(tx,actor.workspaceId,d.proposedPersonId);
  const s:MachineSubmission={...base(actor.workspaceId,this.clock),principalKind:'MACHINE',talentAccountId:null,consentId:null,claimId:null,grantId:null,personId:null,servicePrincipalId:p.id,externalSubmissionKey:d.externalSubmissionKey,proposedPersonId:d.proposedPersonId,proposedTargetBaseline:null,servicePrincipalAuthorizationEpoch:authorizationEpoch(p),intakeScopeRevision:scope.revision,maintainerId:p.defaultMaintainerMembershipId,sourceDeclaration:d.sourceDeclaration,reviewTargetDecision:null,scopeId:p.scopeId,schemaVersion:INGESTION_VERSION,state:'DRAFT',payloadDigest:null,forkedFromId:null,expiresAt:this.until(this.config.mediaRetention?.draft??90),submittedAt:null,decidedAt:null,decidedById:null,publicReason:'',protectionEpoch:1,recoveryEpoch:this.config.recoveryEpoch};await tx.insert('talentSubmissions',s);return s;
 }
 async save(tx:Tx,actor:Actor,id:string,input:unknown){const s=await this.access(tx,actor,id),d=S.items.parse(input);cas(s,d.expectedRevision);invariant(s.state==='DRAFT'&&Date.parse(s.expiresAt)>this.clock.now().getTime(),'SUBMISSION_FROZEN','提交已冻结或过期',409);const changes=d.items.map(parseCandidate),prior=await this.itemsFor(tx,s);invariant(new Set(changes.map(i=>i.clientItemKey)).size===changes.length,'ITEM_KEYS_INVALID','同一批请求不能重复条目键',422);const merged=new Map(prior.map(i=>[i.clientItemKey,i]));for(const i of changes)merged.set(i.clientItemKey,{...base(s.workspaceId,this.clock),submissionId:id,...i,targetId:null,baseline:{},state:'PENDING',appliedId:null});const items=[...merged.values()];invariant(items.length<=50,'ITEM_LIMIT','本批最多50个条目',422);await this.checkItems(tx,s,items);for(const i of changes){const old=prior.find(r=>r.clientItemKey===i.clientItemKey);if(old)await tx.replace('talentSubmissionItems',{...touch(old,this.clock),...i});else await tx.insert('talentSubmissionItems',merged.get(i.clientItemKey)!);}const next=touch(s,this.clock);await tx.replace('talentSubmissions',next);return next;}
 async checkItems(tx:Tx,s:MachineSubmission,items:{clientItemKey:string;kind:string;values:Record<string,unknown>;dependencyGroup:string;dependsOn:string[]}[]){
  for(const i of items){invariant(['IDENTITY_TEXT','ROLE','PROFILE','MEASUREMENT'].includes(i.kind),'CANDIDATE_KIND_INVALID','本轮只接受文字、职业和基础结构化事实',422);parseCandidate(i as Parameters<typeof parseCandidate>[0]);}
  const keys=new Set(items.map(i=>i.clientItemKey));invariant(keys.size===items.length&&items.length>0,'ITEM_KEYS_INVALID','条目键必须唯一且非空',422);for(const i of items)invariant(new Set(i.dependsOn).size===i.dependsOn.length&&i.dependsOn.every(k=>keys.has(k)&&k!==i.clientItemKey),'DEPENDENCY_INVALID','依赖必须指向本批其他条目',422);
  const visiting=new Set<string>(),visited=new Set<string>();const visit=(k:string)=>{invariant(!visiting.has(k),'DEPENDENCY_CYCLE','条目依赖不能成环',422);if(visited.has(k))return;visiting.add(k);for(const dep of items.find(i=>i.clientItemKey===k)!.dependsOn)visit(dep);visiting.delete(k);visited.add(k);};for(const k of keys)visit(k);
  invariant(items.filter(i=>i.kind==='PROFILE').length<=1&&items.filter(i=>i.kind==='MEASUREMENT').length<=1&&new Set(items.filter(i=>i.kind==='IDENTITY_TEXT').map(i=>i.values.field)).size===items.filter(i=>i.kind==='IDENTITY_TEXT').length&&new Set(items.filter(i=>i.kind==='ROLE').map(i=>i.values.roleCode)).size===items.filter(i=>i.kind==='ROLE').length,'DUPLICATE_FACT','同批不能重复提交同一字段或职业',422);
  for(const i of items){if(i.kind==='PROFILE'){validateDemographics({...PROFILE_DEFAULTS,...i.values},this.clock);for(const c of (i.values.nationalityCodes??[]) as string[])await this.dictionary(tx,s.workspaceId,'nationality',c);}if(i.kind==='ROLE'){for(const [key,ns]of [['roleCode','role'],['styleCodes','roleStyle'],['serviceCodes','roleService']]){const codes=key==='roleCode'?[String(i.values[key!])]:i.values[key!] as string[]??[];invariant(new Set(codes).size===codes.length,'DUPLICATE_CODE','代码不能重复',422);for(const c of codes)await this.dictionary(tx,s.workspaceId,ns!,c);}invariant(i.values.roleCode==='model'||(!i.values.castingMarketCode||i.values.castingMarketCode==='UNCLASSIFIED')&&(!i.values.experienceCode||i.values.experienceCode==='UNSPECIFIED'),'MODEL_ROLE_REQUIRED','模特分类不能用于其他职业',422);}
   if(i.kind==='MEASUREMENT'){invariant(Object.hasOwn(i.values,'measuredOn')&&Object.hasOwn(i.values,'datePrecision')&&(i.values.datePrecision==='UNKNOWN'?i.values.measuredOn===null:typeof i.values.measuredOn==='string'),'MEASUREMENT_DATE_PRECISION','未知量尺时间必须明确为 null + UNKNOWN',422);invariant(i.values.measuredOn===null||String(i.values.measuredOn)<=this.now().slice(0,10),'MEASUREMENT_FUTURE','不能使用未来量尺日期',422);}
  }
 }
 async dictionary(tx:Tx,w:string,namespace:string,code:string){invariant((await tx.find('dictionary',{workspaceId:w,namespace:namespace as "role",code,status:'ACTIVE'})).length>0,'DICTIONARY_CODE_INVALID','候选代码未登记或已停用',422);}
 payload(s:MachineSubmission,items:TalentSubmissionItem[]){return digest({sourceDeclaration:s.sourceDeclaration,proposedPersonId:s.proposedPersonId,baseline:s.proposedTargetBaseline,items:items.map(i=>({key:i.clientItemKey,kind:i.kind,values:i.values,group:i.dependencyGroup,dependsOn:i.dependsOn}))});}
 async validate(tx:Tx,actor:Actor,id:string,input:unknown){const s=await this.access(tx,actor,id);cas(s,S.revision.parse(input).expectedRevision);invariant(s.state==='DRAFT'&&Date.parse(s.expiresAt)>this.clock.now().getTime(),'SUBMISSION_FROZEN','提交已冻结或过期',409);await this.checkItems(tx,s,await this.itemsFor(tx,s));if(s.proposedPersonId)await this.targetBaseline(tx,s.workspaceId,s.proposedPersonId);return {valid:true,mode:s.proposedPersonId?'EXISTING':'NEW'};}
 async submit(tx:Tx,actor:Actor,id:string,input:unknown){await this.validate(tx,actor,id,input);const s=await this.access(tx,actor,id),next={...touch(s,this.clock),proposedTargetBaseline:s.proposedPersonId?await this.targetBaseline(tx,s.workspaceId,s.proposedPersonId):null,state:'SUBMITTED',submittedAt:this.now(),expiresAt:this.until(this.config.mediaRetention?.submitted??180)};next.payloadDigest=this.payload(next,await this.itemsFor(tx,s));await tx.replace('talentSubmissions',next);return next;}
 async withdraw(tx:Tx,actor:Actor,id:string,input:unknown){const s=await this.access(tx,actor,id);cas(s,S.revision.parse(input).expectedRevision);invariant(open.has(s.state),'SUBMISSION_CLOSED','提交已经关闭',409);const next={...touch(s,this.clock),state:'WITHDRAWN',expiresAt:this.until(this.config.mediaRetention?.withdrawn??7)};await tx.replace('talentSubmissions',next);return next;}
 async fork(tx:Tx,actor:Actor,id:string,input:unknown){const s=await this.access(tx,actor,id,false,true),d=S.fork.parse(input);cas(s,d.expectedRevision);invariant(!s.sourceDeclaration.erased,'SUBMISSION_ERASED','原材料已按保留期限清理，不能复活；请新建提交',409);const n=await this.create(tx,actor,{schemaVersion:INGESTION_INPUT_VERSION,externalSubmissionKey:d.externalSubmissionKey,proposedPersonId:s.proposedPersonId,sourceDeclaration:s.sourceDeclaration});n.forkedFromId=s.id;await tx.replace('talentSubmissions',n);for(const i of await this.itemsFor(tx,s))await tx.insert('talentSubmissionItems',{...i,...base(s.workspaceId,this.clock),submissionId:n.id,state:'PENDING',appliedId:null,baseline:{}});return n;}
 async dto(tx:Tx,s:MachineSubmission,reviewer?:Actor){const p=(await tx.get('servicePrincipals',s.servicePrincipalId))!;let target:Record<string,unknown>|null=null,rebaseRequired=false;if(reviewer&&s.proposedPersonId){try{await this.checkTarget(tx,s);const row=await td2PersonFor(tx,reviewer,s.proposedPersonId);target={id:row.id,displayName:(await loadTalentGraph(tx,reviewer,this.clock,[row.id])).get(row.id).displayName,scopeId:row.scopeId};}catch(e){if(e instanceof AppError&&['TARGET_REBASE_REQUIRED','NOT_FOUND','SCOPE_FORBIDDEN','FORBIDDEN'].includes(e.code))rebaseRequired=true;else throw e;}}
  return {id:s.id,revision:s.revision,state:s.state,mode:s.proposedPersonId?'EXISTING':'NEW',externalSubmissionKey:s.externalSubmissionKey,principalName:p.displayName,sourceDeclaration:s.sourceDeclaration,proposedPersonId:s.proposedPersonId,personId:s.personId,publicReason:s.publicReason,items:(await this.itemsFor(tx,s)).map(i=>({clientItemKey:i.clientItemKey,kind:i.kind,values:reviewer&&i.kind==='PROFILE'&&!reviewer.permissions.includes('sensitive.read')?Object.fromEntries(Object.entries(i.values).filter(([k])=>k!=='birthDate')):i.values,unavailableFields:reviewer&&i.kind==='PROFILE'&&Object.hasOwn(i.values,'birthDate')&&!reviewer.permissions.includes('sensitive.read')?['birthDate']:[],dependencyGroup:i.dependencyGroup,dependsOn:i.dependsOn,state:i.state})),...(reviewer?{target,rebaseRequired}:{} )};}
 async list(tx:Tx,actor:Actor,query:Record<string,string>){this.enabled();invariant(actor.actorKind!=='MACHINE','HUMAN_REVIEW_REQUIRED','审核需要内部人员',403);requirePermission(actor,'talent.review');const out=[];for(const raw of await tx.find('talentSubmissions',{workspaceId:actor.workspaceId,principalKind:'MACHINE'})){if(!await scopeVisible(tx,actor,raw.scopeId))continue;out.push(await this.dto(tx,raw as MachineSubmission,actor));}return page(out,query);}
 async review(tx:Tx,actor:Actor,id:string,input:unknown){this.enabled();const s=await this.access(tx,actor,id,true);invariant(!['APPROVED','PARTIALLY_APPROVED','REJECTED'].includes(s.state),'SUBMISSION_CLOSED','本批提交已处理',409);const d=S.review.parse(input);invariant(d.reviewBasis.trim().length>=4,'REVIEW_BASIS_REQUIRED','请记录真实内部审核依据',422);cas(s,d.expectedRevision);invariant(s.state==='SUBMITTED'&&Date.parse(s.expiresAt)>this.clock.now().getTime(),'SUBMISSION_CLOSED','提交已失效或已处理',409);const items=await this.itemsFor(tx,s);invariant(s.payloadDigest===this.payload(s,items),'SUBMISSION_DIGEST_MISMATCH','冻结内容已变化',409);await this.checkTarget(tx,s);await this.checkItems(tx,s,items);
  const accepted=new Set(d.acceptedKeys);invariant(accepted.size===d.acceptedKeys.length&&d.acceptedKeys.every(k=>items.some(i=>i.clientItemKey===k)),'ITEM_SELECTION_INVALID','条目选择不正确',422);for(const i of items)if(accepted.has(i.clientItemKey))invariant(items.filter(j=>j.dependencyGroup===i.dependencyGroup).every(j=>accepted.has(j.clientItemKey))&&i.dependsOn.every(k=>accepted.has(k)),'DEPENDENCY_GROUP_INCOMPLETE','相关条目必须整组采纳',422);
  invariant((d.decision==='REJECT')===!accepted.size,'REVIEW_DECISION_INVALID','拒绝不能采纳条目，采纳必须明确目标决定',422);let person:Person|null=null;
  if(accepted.size){requirePermission(actor,'records.write');requirePermission(actor,'sources.review');invariant(Date.parse(d.validUntil)>this.clock.now().getTime()&&Date.parse(d.validUntil)<=this.clock.now().getTime()+365*86400000,'BASIS_EXPIRY_INVALID','内部使用依据必须有未来一年内的明确期限',422);
   if(s.proposedPersonId){invariant(d.decision==='LINK_EXISTING'&&d.targetPersonId===s.proposedPersonId&&d.formalScopeId===undefined,'EXACT_TARGET_REQUIRED','必须明确关联冻结的同一目标；不能改目标或范围',422);person=await td2PersonFor(tx,actor,s.proposedPersonId);}else{invariant(d.decision==='CREATE_NEW'&&!!d.formalScopeId&&d.targetPersonId===undefined,'FORMAL_SCOPE_REQUIRED','新建须由审核人明确选择正式范围',422);await requireScope(tx,actor,d.formalScopeId);invariant(TEXT.every(f=>items.some(i=>i.kind==='IDENTITY_TEXT'&&i.values.field===f&&accepted.has(i.clientItemKey)))&&items.some(i=>i.kind==='ROLE'&&accepted.has(i.clientItemKey)),'MINIMUM_IDENTITY_REQUIRED','新建须明确采纳姓名、别名、简介和至少一个职业',422);}
   const source:Source={...base(s.workspaceId,this.clock),scopeId:person?.scopeId??d.formalScopeId!,maintainerId:actor.membershipId,title:String(s.sourceDeclaration.title),type:'TEXT',providerClaim:String(s.sourceDeclaration.providerClaim),textPayload:'',basisMode:'INTERNAL_USE',basisDescription:d.reviewBasis,validFrom:this.now(),validUntil:d.validUntil,internalUseUntil:d.validUntil,status:'CONFIRMED',protectionEpoch:1,reviewedBy:actor.membershipId,reviewedAt:this.now()};await tx.insert('sources',source);await appendSourceHistory(tx,actor,source,'CREATED',this.clock);
   const attr={...base(s.workspaceId,this.clock),principalKind:'MACHINE' as const,sourceId:source.id,submissionId:s.id,servicePrincipalId:s.servicePrincipalId,talentAccountId:null,consentId:null,reviewerId:actor.membershipId,materialDescription:String(s.sourceDeclaration.materialDescription)};await tx.insert('sourceAttributions',attr);await tx.insert('sourceUseBases',{...base(s.workspaceId,this.clock),basisKind:'INTERNAL_REVIEW',sourceId:source.id,consentId:null,consentRevision:null,submissionId:s.id,sourceAttributionId:attr.id,servicePrincipalId:s.servicePrincipalId,reviewerId:actor.membershipId,reviewBasis:d.reviewBasis,purpose:'INTERNAL_DIRECTORY',fieldScope:[...new Set(items.filter(i=>accepted.has(i.clientItemKey)).flatMap(i=>i.kind==='IDENTITY_TEXT'?[String(i.values.field)]:Object.keys(i.values).map(k=>i.kind.toLowerCase()+'.'+k)))],state:'ACTIVE',validUntil:d.validUntil});
   const chosen=items.filter(i=>accepted.has(i.clientItemKey));if(chosen.some(i=>i.kind==='PROFILE'&&Object.hasOwn(i.values,'birthDate'))){requirePermission(actor,'sensitive.read');requirePermission(actor,'sensitive.write');}if(!person){person={...base(s.workspaceId,this.clock),sourceId:source.id,scopeId:source.scopeId,maintainerId:actor.membershipId,displayName:'',aliases:[],intro:'',roles:[],languageCodes:[],skillCodes:[],cityCode:null,heightCm:null,status:'ACTIVE',protectionEpoch:1};for(const i of chosen.filter(i=>i.kind==='IDENTITY_TEXT'))Object.assign(person,{[String(i.values.field)]:i.values.value});await tx.insert('people',person);}else{person=touch(person,this.clock);for(const i of chosen.filter(i=>i.kind==='IDENTITY_TEXT'))Object.assign(person,{[String(i.values.field)]:i.values.value});await tx.replace('people',person);}
   const td2=new TalentV2(this.clock,this.config);await td2.evidenceFor(tx,actor,'person',asRow(person),chosen.filter(i=>i.kind==='IDENTITY_TEXT').map(i=>String(i.values.field)),source.id,source.revision,true);
   const profile=chosen.find(i=>i.kind==='PROFILE'),existing=(await tx.find('talentProfiles',{workspaceId:s.workspaceId,personId:person.id}))[0];if(profile||!existing)await this.applyFact(tx,actor,td2,'talentProfiles',person,source,profile?.values??{},existing as unknown as FactRow|undefined);
   for(const i of chosen.filter(i=>i.kind==='ROLE')){const roleHistory=await tx.find('personRoles',{workspaceId:s.workspaceId,personId:person.id,roleCode:String(i.values.roleCode),status:'ACTIVE'}),existingRole=roleHistory.find(r=>periodCurrent(asRow(r),this.clock));await this.applyFact(tx,actor,td2,'personRoles',person,source,{...(!existingRole&&roleHistory.length?{validFrom:this.now()}:{}),...i.values},existingRole as unknown as FactRow|undefined);}
   const measure=chosen.find(i=>i.kind==='MEASUREMENT');if(measure){const m=await this.applyFact(tx,actor,td2,'measurementSets',person,source,measure.values);const c=(await tx.find('castingProfiles',{workspaceId:s.workspaceId,personId:person.id}))[0];await this.applyFact(tx,actor,td2,'castingProfiles',person,source,{currentMeasurementSetId:m.id},c as unknown as FactRow|undefined);}
  }
  for(const i of items)await tx.replace('talentSubmissionItems',{...touch(i,this.clock),state:accepted.has(i.clientItemKey)?'APPLIED':'REJECTED',appliedId:accepted.has(i.clientItemKey)?person!.id:null});const next={...touch(s,this.clock),personId:person?.id??null,reviewTargetDecision:d.decision,state:!accepted.size?'REJECTED':accepted.size===items.length?'APPROVED':'PARTIALLY_APPROVED',decidedAt:this.now(),decidedById:actor.membershipId,publicReason:d.publicReason,expiresAt:this.until(this.config.mediaRetention?.decided??30)};await tx.replace('talentSubmissions',next);return next;
 }
 async applyFact(tx:Tx,actor:Actor,td2:TalentV2,table:FactTable,p:Person,source:Source,values:Record<string,unknown>,old?:FactRow){if(table==='castingProfiles'&&old){const origin=await sourceFor(tx,actor,old.sourceId,this.clock,false);const proof=await tx.find('evidence',{workspaceId:p.workspaceId,castingProfileId:old.id});await td2.evidenceFor(tx,actor,table,old,Object.keys(TD2_FACTS.castingProfiles.fields).filter(k=>!proof.some(e=>e.fieldPath===k)),origin.id,origin.revision);}
 const row:FactRow=old?{...touch(old,this.clock),...(table==='castingProfiles'?{sourceId:source.id}:{}),...values}:{...base(p.workspaceId,this.clock),personId:p.id,sourceId:source.id,...rowDefaults(table),...(table==='talentProfiles'?{...PROFILE_DEFAULTS,internalSummary:'',status:'ACTIVE'}:table==='personRoles'?{...ROLE_DEFAULTS,status:'ACTIVE'}:table==='measurementSets'?{status:'CONFIRMED',reportedAt:this.now()}:{}),...values};await td2.validate(tx,actor,table,row);if(old)await replaceFact(tx,table,row);else await insertFact(tx,table,row);await td2.evidenceFor(tx,actor,table,row,(old?Object.keys(values):Object.keys(rowDefaults(table))).filter(k=>Object.hasOwn(TD2_FACTS[table].fields,k)),source.id,source.revision,true);return row;}
 async schema(tx:Tx,actor:Actor){await this.principal(tx,actor);return {schemaVersion:INGESTION_INPUT_VERSION,ingestionVersion:INGESTION_VERSION,factVersion:'once-talent-v2.1.0',create:S.create.json,items:S.items.json,measurementDate:'UNKNOWN requires measuredOn=null',supportedKinds:['IDENTITY_TEXT','ROLE','PROFILE','MEASUREMENT'],mediaEnabled:false};}
 async dictionaries(tx:Tx,actor:Actor){await this.principal(tx,actor);return {items:(await tx.find('dictionary',{workspaceId:actor.workspaceId,status:'ACTIVE'})).filter(d=>['role','nationality','roleStyle','roleService'].includes(d.namespace)).map(d=>({namespace:d.namespace,code:d.code,labelZh:d.labelZh,labelEn:d.labelEn}))};}
}
