import { ExportSchemas as ES } from './export-validation.ts';
import { ShortlistSchemas as SS } from './shortlist-validation.ts';
import { ProductionSchemas as PS } from './production-validation.ts';
import { MediaSchemas } from './media-validation.ts';
import type { Permission } from './model.ts';
import { Schemas, type Schema } from './validation.ts';
export interface RouteDefinition {
    method: 'GET' | 'POST' | 'PATCH' | 'PUT';
    path: string;
    operation: string;
    mode: 'AUTH' | 'READ' | 'COMMAND' | 'SECRET' | 'BINARY';
    permission?: Permission;
    schema?: Schema<unknown>;
}
export const ROUTES: RouteDefinition[] = [
    { method: 'GET', path: '/works', operation: 'work.list', mode: 'READ', permission: 'records.read' },
    { method: 'POST', path: '/works', operation: 'work.create', mode: 'COMMAND', permission: 'records.write', schema: PS.workCreate },
    { method: 'GET', path: '/works/{id}', operation: 'work.get', mode: 'READ', permission: 'records.read' },
    { method: 'PATCH', path: '/works/{id}', operation: 'work.update', mode: 'COMMAND', permission: 'records.write', schema: PS.workPatch },
    { method: 'POST', path: '/works/{id}/assets', operation: 'work.assetAdd', mode: 'COMMAND', permission: 'records.write', schema: PS.workAsset },
    { method: 'POST', path: '/works/{id}/assets/remove', operation: 'work.assetRemove', mode: 'COMMAND', permission: 'records.write', schema: PS.remove },
    { method: 'POST', path: '/works/{id}/assets/reorder', operation: 'work.reorder', mode: 'COMMAND', permission: 'records.write', schema: PS.order },
    { method: 'POST', path: '/works/{id}/credits', operation: 'work.creditAdd', mode: 'COMMAND', permission: 'records.write', schema: PS.credit },
    { method: 'POST', path: '/works/{id}/credits/remove', operation: 'work.creditRemove', mode: 'COMMAND', permission: 'records.write', schema: PS.remove },
    { method: 'GET', path: '/projects', operation: 'project.list', mode: 'READ', permission: 'records.read' },
    { method: 'POST', path: '/projects', operation: 'project.create', mode: 'COMMAND', permission: 'records.write', schema: PS.projectCreate },
    { method: 'GET', path: '/projects/{id}', operation: 'project.get', mode: 'READ', permission: 'records.read' },
    { method: 'PATCH', path: '/projects/{id}', operation: 'project.update', mode: 'COMMAND', permission: 'records.write', schema: PS.projectPatch },
    { method: 'POST', path: '/projects/{id}/participants', operation: 'project.participantAdd', mode: 'COMMAND', permission: 'records.write', schema: PS.participant },
    { method: 'POST', path: '/projects/{id}/participants/update', operation: 'project.participantUpdate', mode: 'COMMAND', permission: 'records.write', schema: PS.participantPatch },
    { method: 'POST', path: '/projects/{id}/participants/remove', operation: 'project.participantRemove', mode: 'COMMAND', permission: 'records.write', schema: PS.remove },
    { method: 'POST', path: '/projects/{id}/works', operation: 'project.workLink', mode: 'COMMAND', permission: 'records.write', schema: PS.projectWork },
    { method: 'POST', path: '/projects/{id}/works/remove', operation: 'project.workRemove', mode: 'COMMAND', permission: 'records.write', schema: PS.remove },
    { method: 'GET', path: '/people/{id}/production', operation: 'person.production', mode: 'READ', permission: 'records.read' },
    { method: 'POST', path: '/uploads', operation: 'upload.create', mode: 'COMMAND', permission: 'assets.upload', schema: MediaSchemas.create },
    { method: 'GET', path: '/uploads', operation: 'upload.list', mode: 'READ', permission: 'records.read' },
    { method: 'GET', path: '/uploads/{id}', operation: 'upload.get', mode: 'READ', permission: 'records.read' },
    { method: 'PUT', path: '/uploads/{id}/content', operation: 'upload.content', mode: 'BINARY', permission: 'assets.upload' },
    { method: 'POST', path: '/uploads/{id}/renew', operation: 'upload.renew', mode: 'COMMAND', permission: 'assets.upload', schema: MediaSchemas.revision },
    { method: 'POST', path: '/uploads/{id}/complete', operation: 'upload.complete', mode: 'COMMAND', permission: 'assets.upload', schema: MediaSchemas.revision },
    { method: 'POST', path: '/uploads/{id}/cancel', operation: 'upload.cancel', mode: 'COMMAND', permission: 'records.read', schema: MediaSchemas.revision },
    { method: 'GET', path: '/assets', operation: 'asset.list', mode: 'READ', permission: 'assets.read' },
    { method: 'GET', path: '/assets/{id}', operation: 'asset.get', mode: 'READ', permission: 'assets.read' },
    { method: 'GET', path: '/assets/{id}/preview', operation: 'asset.preview', mode: 'BINARY', permission: 'assets.read' },
    { method: 'POST', path: '/assets/{id}/quarantine', operation: 'asset.quarantine', mode: 'COMMAND', permission: 'sources.review', schema: MediaSchemas.revision },
    { method: 'GET', path: '/auth/csrf', operation: 'auth.csrf', mode: 'AUTH' },
    { method: 'POST', path: '/auth/login', operation: 'auth.login', mode: 'AUTH', schema: Schemas.login },
    { method: 'POST', path: '/auth/activate', operation: 'auth.activate', mode: 'AUTH', schema: Schemas.activate },
    { method: 'POST', path: '/auth/logout', operation: 'auth.logout', mode: 'AUTH', schema: Schemas.empty },
    { method: 'POST', path: '/auth/change-password', operation: 'auth.changePassword', mode: 'AUTH', schema: Schemas.password },
    { method: 'GET', path: '/me', operation: 'identity.me', mode: 'READ' },
    { method: 'GET', path: '/dashboard', operation: 'dashboard.get', mode: 'READ', permission: 'records.read' },
    { method: 'GET', path: '/catalog', operation: 'catalog.list', mode: 'READ', permission: 'records.read' },
    { method: 'POST', path: '/catalog/items', operation: 'catalog.create', mode: 'COMMAND', permission: 'catalog.manage', schema: Schemas.dictionaryCreate },
    { method: 'PATCH', path: '/catalog/items/{id}', operation: 'catalog.update', mode: 'COMMAND', permission: 'catalog.manage', schema: Schemas.dictionaryPatch },
    { method: 'GET', path: '/memberships', operation: 'member.list', mode: 'READ', permission: 'members.manage' },
    { method: 'POST', path: '/memberships', operation: 'member.create', mode: 'SECRET', permission: 'members.manage', schema: Schemas.memberCreate },
    { method: 'POST', path: '/memberships/{id}/disable', operation: 'member.disable', mode: 'COMMAND', permission: 'members.manage', schema: Schemas.revision },
    { method: 'PATCH', path: '/memberships/{id}/permissions', operation: 'member.permissions', mode: 'COMMAND', permission: 'members.manage', schema: Schemas.memberPermissions },
    { method: 'POST', path: '/memberships/{id}/reset-access', operation: 'member.resetAccess', mode: 'SECRET', permission: 'members.manage', schema: Schemas.revision },
    { method: 'GET', path: '/scopes', operation: 'scope.list', mode: 'READ', permission: 'records.read' },
    { method: 'POST', path: '/scopes', operation: 'scope.create', mode: 'COMMAND', permission: 'members.manage', schema: Schemas.scopeCreate },
    { method: 'PATCH', path: '/records/{kind}/{id}/scope', operation: 'record.scope', mode: 'COMMAND', permission: 'members.manage', schema: Schemas.recordScope },
    { method: 'GET', path: '/sources', operation: 'source.list', mode: 'READ', permission: 'sources.read' },
    { method: 'POST', path: '/sources', operation: 'source.create', mode: 'COMMAND', permission: 'sources.write', schema: Schemas.sourceCreate },
    { method: 'GET', path: '/sources/{id}/history', operation: 'source.history', mode: 'READ', permission: 'sources.review' },
    { method: 'GET', path: '/sources/{id}', operation: 'source.get', mode: 'READ', permission: 'sources.read' },
    { method: 'PATCH', path: '/sources/{id}', operation: 'source.update', mode: 'COMMAND', permission: 'sources.write', schema: Schemas.sourcePatch },
    { method: 'POST', path: '/sources/{id}/review', operation: 'source.review', mode: 'COMMAND', permission: 'sources.review', schema: Schemas.sourceReview },
    { method: 'POST', path: '/sources/{id}/suspend', operation: 'source.suspend', mode: 'COMMAND', permission: 'sources.review', schema: Schemas.suspend },
    { method: 'GET', path: '/people/{id}/handoff-recipients', operation: 'handoff.recipients', mode: 'READ', permission: 'records.write' },
    { method: 'POST', path: '/people/{id}/handoffs', operation: 'handoff.create', mode: 'COMMAND', permission: 'records.write', schema: Schemas.handoffCreate },
    { method: 'GET', path: '/handoffs', operation: 'handoff.list', mode: 'READ', permission: 'records.read' },
    { method: 'GET', path: '/handoffs/{id}', operation: 'handoff.get', mode: 'READ', permission: 'records.read' },
    { method: 'POST', path: '/handoffs/{id}/accept', operation: 'handoff.accept', mode: 'COMMAND', permission: 'records.read', schema: Schemas.revision },
    { method: 'POST', path: '/handoffs/{id}/decline', operation: 'handoff.decline', mode: 'COMMAND', permission: 'records.read', schema: Schemas.revision },
    { method: 'POST', path: '/handoffs/{id}/revoke', operation: 'handoff.revoke', mode: 'COMMAND', permission: 'records.read', schema: Schemas.revision },
    { method: 'GET', path: '/people', operation: 'person.list', mode: 'READ', permission: 'records.read' },
    { method: 'POST', path: '/people', operation: 'person.create', mode: 'COMMAND', permission: 'records.write', schema: Schemas.personCreate },
    { method: 'GET', path: '/people/{id}', operation: 'person.get', mode: 'READ', permission: 'records.read' },
    { method: 'PATCH', path: '/people/{id}', operation: 'person.update', mode: 'COMMAND', permission: 'records.write', schema: Schemas.personPatch },
    { method: 'GET', path: '/people/{id}/contacts', operation: 'contact.get', mode: 'READ', permission: 'sensitive.read' },
    { method: 'PUT', path: '/people/{id}/contacts', operation: 'contact.replace', mode: 'COMMAND', permission: 'sensitive.write', schema: Schemas.contacts },
    { method: 'POST', path: '/field-evidence', operation: 'evidence.confirm', mode: 'COMMAND', permission: 'sources.review', schema: Schemas.evidence },
    { method: 'POST', path: '/imports/preview', operation: 'import.preview', mode: 'COMMAND', permission: 'records.write', schema: Schemas.importPreview },
    { method: 'GET', path: '/imports/{id}', operation: 'import.get', mode: 'READ', permission: 'records.write' },
    { method: 'POST', path: '/imports/{id}/commit', operation: 'import.commit', mode: 'COMMAND', permission: 'records.write', schema: Schemas.importCommit },
    { method: 'GET', path: '/jobs', operation: 'job.list', mode: 'READ', permission: 'records.write' },
    { method: 'POST', path: '/jobs/{id}/resume', operation: 'job.resume', mode: 'COMMAND', permission: 'records.write', schema: Schemas.revision },
    { method: 'GET', path: '/jobs/{id}', operation: 'job.get', mode: 'READ', permission: 'records.write' },
    { method: 'GET', path: '/audit-events', operation: 'audit.list', mode: 'READ', permission: 'audit.read' },
    { method: 'GET', path: '/use-permissions', operation: 'usePermission.list', mode: 'READ', permission: 'sources.read' },
    { method: 'POST', path: '/use-permissions', operation: 'usePermission.create', mode: 'COMMAND', permission: 'sources.review', schema: ES.permissionCreate },
    { method: 'POST', path: '/use-permissions/{id}/revoke', operation: 'usePermission.revoke', mode: 'COMMAND', permission: 'sources.review', schema: ES.permissionRevoke },
    { method: 'GET', path: '/exports', operation: 'export.list', mode: 'READ', permission: 'data.export' },
    { method: 'POST', path: '/exports', operation: 'export.create', mode: 'COMMAND', permission: 'data.export', schema: ES.create },
    { method: 'GET', path: '/exports/{id}', operation: 'export.get', mode: 'READ', permission: 'data.export' },
    { method: 'POST', path: '/exports/{id}/download', operation: 'export.download', mode: 'READ', permission: 'data.export', schema: ES.download },
    { method: 'GET', path: '/talent-search', operation: 'talent.search', mode: 'READ', permission: 'records.read' },
    { method: 'GET', path: '/shortlists', operation: 'shortlist.list', mode: 'READ', permission: 'records.read' },
    { method: 'POST', path: '/shortlists', operation: 'shortlist.create', mode: 'COMMAND', permission: 'records.write', schema: SS.create },
    { method: 'GET', path: '/shortlists/{id}', operation: 'shortlist.get', mode: 'READ', permission: 'records.read' },
    { method: 'PATCH', path: '/shortlists/{id}', operation: 'shortlist.update', mode: 'COMMAND', permission: 'records.write', schema: SS.patch },
    { method: 'POST', path: '/shortlists/{id}/items', operation: 'shortlist.itemAdd', mode: 'COMMAND', permission: 'records.write', schema: SS.itemAdd },
    { method: 'POST', path: '/shortlists/{id}/items/update', operation: 'shortlist.itemUpdate', mode: 'COMMAND', permission: 'records.write', schema: SS.itemPatch },
    { method: 'POST', path: '/shortlists/{id}/items/remove', operation: 'shortlist.itemRemove', mode: 'COMMAND', permission: 'records.write', schema: SS.remove },
    { method: 'POST', path: '/shortlists/{id}/items/reorder', operation: 'shortlist.reorder', mode: 'COMMAND', permission: 'records.write', schema: SS.order },
];
