import {mediaExposure} from './talent-media-exposure.ts';
import {AppError} from './errors.ts';
import {collectionAssetFor,validateCollectionDraft,submissionCollectionPlan,applyCollection,portalCollections} from './media-collections.ts';
import {checkSubmissionMedia,adoptSubmissionMedia,syncMediaRetention} from './media-adoption.ts';
import {TalentMediaSchemas,MEDIA_CONSENT_VERSION} from './media-validation.ts';
import type {Actor,Clock,Config,Person,Source,RequestMeta} from './model.ts';
import type {TalentActor} from './talent-auth-model.ts';
import type {Tx} from './store.ts';
import type {TalentInvitation,TalentClaim,TalentAccessGrant,TalentSubmission,Exposure} from './talent-maintenance-model.ts';
import {MaintenanceSchemas as S,TEXT_FIELDS,MAINTENANCE_VERSION,CONSENT_VERSION,type TextItem} from './talent-maintenance-schema.ts';
import {base,touch,cas,workspaceRow,audit} from './helpers.ts';
import {invariant,missing} from './errors.ts';
import {digest} from './json.ts';
import {randomSecret,equalSecret} from './crypto.ts';
import {normalizeTalentIdentity,talentHash} from './talent-auth.ts';
import {requirePermission,requireScope,scopeVisible,sourceCurrent,deletionBlocked,personAliasFor} from './policy.ts';
import {td2PersonFor,loadTalentGraph,asRow} from './talent-v2-graph.ts';
import {ageRange,PROFILE_DEFAULTS,ROLE_DEFAULTS} from './talent-demographics.ts';
import {TalentV2} from './talent-v2.ts';
import {appendSourceHistory} from './source-history.ts';
const day=86400000;
export const TALENT_MAINTENANCE_LIMITS=Object.freeze({claimDays:7,enrollDays:30,enrollUses:100,admissionDays:7,draftDays:90,submittedDays:180,decidedDays:30,withdrawnDays:7,consentDays:365,activeDraftsPerAccount:100});
const L=TALENT_MAINTENANCE_LIMITS;
export class TalentMaintenance {
 clock:Clock;config:Config;
 constructor(clock:Clock,config:Config){this.clock=clock;this.config=config;}
 now(){return this.clock.now().toISOString();}
 until(days:number){return new Date(this.clock.now().getTime()+days*day).toISOString();}
 human(actor:Actor,permission:'talent.invite'|'talent.review'){invariant(actor.actorKind!=='MACHINE','HUMAN_REVIEW_REQUIRED','此操作需要内部人员',403);requirePermission(actor,permission);}
 async account(tx:Tx,workspaceId:string,id:string){const a=await workspaceRow(tx,'talentAccounts',id,workspaceId),w=await tx.get('workspaces',workspaceId);invariant(a?.status==='ACTIVE'&&this.config.accessMode==='INTERNAL'&&w?.recoveryEpoch===this.config.recoveryEpoch,'NOT_FOUND','内容不可访问',404);return a;}
 async person(tx:Tx,workspaceId:string,id:string){const p=await workspaceRow(tx,'people',id,workspaceId);if(!p||p.status==='ERASED'||p.status==='ARCHIVED'||await deletionBlocked(tx,workspaceId,'PERSON',id)||await personAliasFor(tx,workspaceId,id))missing();return p;}
 async invitation(tx:Tx,actor:Actor,id:string){this.human(actor,'talent.invite');const r=await workspaceRow(tx,'talentInvitations',id,actor.workspaceId);if(!r)missing();await requireScope(tx,actor,r.scopeId);if(r.targetPersonId)await td2PersonFor(tx,actor,r.targetPersonId);return r;}
 liveInvitation(r:TalentInvitation){invariant(r.state==='ACTIVE'&&Date.parse(r.expiresAt)>this.clock.now().getTime()&&r.recoveryEpoch===this.config.recoveryEpoch,'INVITATION_UNAVAILABLE','邀请已失效，请联系邀请人',409);}
 async createInvitation(tx:Tx,actor:Actor,input:unknown){this.human(actor,'talent.invite');const d=S.invitation.parse(input);await requireScope(tx,actor,d.scopeId);const scope=(await tx.get('scopes',d.scopeId))!;invariant(scope.mode==='RESTRICTED','INTAKE_SCOPE_REQUIRED','加入申请须进入限定审核范围',422);if(d.targetPersonId)await td2PersonFor(tx,actor,d.targetPersonId);
 invariant(d.purpose==='CLAIM'?!!d.targetPersonId&&!d.maxUses:!d.targetPersonId&&!d.recipient&&!d.recipientKind,'INVITATION_SHAPE','邀请用途与目标不一致',422);invariant(!!d.recipient===!!d.recipientKind,'IDENTITY_REQUIRED','收件人类型与标识须同时提供',422);invariant(new Set(d.exposureFields).size===d.exposureFields.length,'DUPLICATE_FIELD','展示字段不能重复',422);
 const c=this.config.talentAuth;invariant(c?.enabled,'PORTAL_DISABLED','人才入口未配置',503);const r:TalentInvitation={...base(actor.workspaceId,this.clock),purpose:d.purpose,targetPersonId:d.targetPersonId??null,scopeId:d.scopeId,maintainerId:actor.membershipId,recipientHash:d.recipient&&d.recipientKind?talentHash(c.identityKey,d.recipientKind,actor.workspaceId+':'+normalizeTalentIdentity(d.recipientKind,d.recipient)):null,recipientKind:d.recipientKind??null,state:'DRAFT',tokenHash:null,secretVersion:0,expiresAt:this.until(d.purpose==='CLAIM'?L.claimDays:L.enrollDays),maxUses:d.purpose==='CLAIM'?1:d.maxUses??L.enrollUses,usedCount:0,reservedCount:0,recoveryEpoch:this.config.recoveryEpoch,exposureFields:d.exposureFields};await tx.insert('talentInvitations',r);return r;}
 async issue(tx:Tx,actor:Actor,id:string,input:unknown,meta:RequestMeta){const d=S.revision.parse(input),r=await this.invitation(tx,actor,id);cas(r,d.expectedRevision);invariant(['DRAFT','ACTIVE'].includes(r.state)&&Date.parse(r.expiresAt)>this.clock.now().getTime()&&r.recoveryEpoch===this.config.recoveryEpoch,'INVITATION_CLOSED','邀请不能重新签发',409);const token=randomSecret(),next={...touch(r,this.clock),state:'ACTIVE',secretVersion:r.secretVersion+1,tokenHash:talentHash(this.config.talentAuth!.sessionKey,'invitation',r.id+':'+(r.secretVersion+1)+':'+token)};await tx.replace('talentInvitations',next);await audit(tx,actor,actor.workspaceId,'talent.invitation.issue','talentInvitation',id,[],meta,this.clock);return {id,revision:next.revision,url:this.config.origin+'/talent/claim#i='+id+'&t='+token};}
 async revokeInvitation(tx:Tx,actor:Actor,id:string,input:unknown){const r=await this.invitation(tx,actor,id);cas(r,S.revision.parse(input).expectedRevision);const n={...touch(r,this.clock),state:'REVOKED',tokenHash:null};await tx.replace('talentInvitations',n);await this.releaseReservations(tx,actor.workspaceId);return n;}
 async exchange(tx:Tx,workspaceId:string,browser:string,input:unknown){const d=S.exchange.parse(input),r=await workspaceRow(tx,'talentInvitations',d.invitationId,workspaceId);invariant(r&&browser&&r.tokenHash&&equalSecret(r.tokenHash,talentHash(this.config.talentAuth!.sessionKey,'invitation',r.id+':'+r.secretVersion+':'+d.token)),'INVITATION_UNAVAILABLE','邀请不可用',404);this.liveInvitation(r);const browserHash=talentHash(this.config.talentAuth!.sessionKey,'browser',browser);invariant((await tx.find('talentInvitationContexts',{workspaceId,browserHash})).filter(x=>Date.parse(x.expiresAt)>this.clock.now().getTime()).length<20,'CONTEXT_LIMIT','打开的邀请过多，请稍后再试',429);const context={...base(workspaceId,this.clock),invitationId:r.id,browserHash,secretVersion:r.secretVersion,recoveryEpoch:this.config.recoveryEpoch,expiresAt:new Date(Math.min(Date.parse(r.expiresAt),this.clock.now().getTime()+30*60000)).toISOString()};await tx.insert('talentInvitationContexts',context);return {contextId:context.id,purpose:r.purpose,expiresAt:context.expiresAt};}
 async context(tx:Tx,workspaceId:string,browser:string,id:string){const r=await workspaceRow(tx,'talentInvitationContexts',id,workspaceId);invariant(r&&browser&&equalSecret(r.browserHash,talentHash(this.config.talentAuth!.sessionKey,'browser',browser))&&r.recoveryEpoch===this.config.recoveryEpoch&&Date.parse(r.expiresAt)>this.clock.now().getTime(),'CONTEXT_INVALID','邀请上下文已失效，请重新打开邀请',404);const inv=await workspaceRow(tx,'talentInvitations',r.invitationId,workspaceId);invariant(inv&&inv.secretVersion===r.secretVersion,'INVITATION_UNAVAILABLE','邀请已更新，请使用新链接',409);this.liveInvitation(inv);return inv;}
 async releaseReservations(tx:Tx,workspaceId:string){for(const claim of await tx.find('talentClaims',{workspaceId,reserved:true})){const i=await tx.get('talentInvitations',claim.invitationId);if(i&&(Date.parse(claim.admissionUntil)<=this.clock.now().getTime()||i.state!=='ACTIVE'||Date.parse(i.expiresAt)<=this.clock.now().getTime()||claim.recoveryEpoch!==this.config.recoveryEpoch)){await tx.replace('talentClaims',{...touch(claim,this.clock),reserved:false});await tx.replace('talentInvitations',{...touch(i,this.clock),reservedCount:i.reservedCount-1});}}}
 async recipient(tx:Tx,inv:TalentInvitation,accountId:string){if(inv.recipientHash)invariant((await tx.find('talentIdentities',{workspaceId:inv.workspaceId,talentAccountId:accountId})).some(i=>i.kind===inv.recipientKind&&i.identityHash===inv.recipientHash),'RECIPIENT_MISMATCH','当前账号与指定收件人不符，请切换账号',403);}
 async claim(tx:Tx,actor:TalentActor,browser:string,input:unknown){const d=S.claim.parse(input);await this.account(tx,actor.workspaceId,actor.talentAccountId);await this.releaseReservations(tx,actor.workspaceId);const inv=await this.context(tx,actor.workspaceId,browser,d.contextId);await this.recipient(tx,inv,actor.talentAccountId);invariant(d.relation!=='SELF'||d.applicantKey==='SELF','APPLICANT_KEY_INVALID','本人申请使用固定标识',422);if(d.relation==='SELF')invariant(!(await tx.find('talentAccessGrants',{workspaceId:actor.workspaceId,talentAccountId:actor.talentAccountId,relation:'SELF',state:'ACTIVE'})).length,'SELF_ALREADY_BOUND','您已有本人档案，请进入我的资料',409);
 const previous=(await tx.find('talentClaims',{workspaceId:actor.workspaceId,talentAccountId:actor.talentAccountId,state:'PENDING',kind:inv.purpose,relation:d.relation,applicantKey:d.applicantKey})).find(x=>inv.purpose==='ENROLL'||x.invitationId===inv.id);if(previous)return previous;
 invariant(inv.usedCount+inv.reservedCount<inv.maxUses,'INVITATION_FULL','本次加入名额已满',409);if(inv.targetPersonId)await this.person(tx,actor.workspaceId,inv.targetPersonId);
 const r:TalentClaim={...base(actor.workspaceId,this.clock),invitationId:inv.id,talentAccountId:actor.talentAccountId,targetPersonId:inv.targetPersonId,scopeId:inv.scopeId,kind:inv.purpose,relation:d.relation,applicantKey:d.applicantKey,state:'PENDING',admissionUntil:new Date(Math.min(Date.parse(inv.expiresAt),this.clock.now().getTime()+L.admissionDays*day)).toISOString(),reserved:inv.purpose==='ENROLL',adultDeclared:d.adultDeclared,ownershipBasis:'',recoveryEpoch:this.config.recoveryEpoch,decidedById:null,decidedAt:null};await tx.insert('talentClaims',r);if(r.reserved)await tx.replace('talentInvitations',{...touch(inv,this.clock),reservedCount:inv.reservedCount+1});return r;}
 async ownClaim(tx:Tx,actor:TalentActor,id:string,active=false){await this.account(tx,actor.workspaceId,actor.talentAccountId);const r=await workspaceRow(tx,'talentClaims',id,actor.workspaceId);if(!r||r.talentAccountId!==actor.talentAccountId)missing();if(active){invariant(r.state==='PENDING'&&r.recoveryEpoch===this.config.recoveryEpoch&&Date.parse(r.admissionUntil)>this.clock.now().getTime()&&(r.kind!=='ENROLL'||r.reserved),'ADMISSION_EXPIRED','申请名额已到期，请重新取得邀请并续办',409);const inv=(await tx.get('talentInvitations',r.invitationId))!;this.liveInvitation(inv);}return r;}
 async renew(tx:Tx,actor:TalentActor,browser:string,id:string,input:unknown){const d=S.renew.parse(input);await this.releaseReservations(tx,actor.workspaceId);const r=await this.ownClaim(tx,actor,id);cas(r,d.expectedRevision);invariant(r.kind==='ENROLL'&&r.state==='PENDING','CLAIM_CLOSED','此申请不能续办',409);const inv=await this.context(tx,actor.workspaceId,browser,d.contextId);invariant(inv.purpose==='ENROLL'&&inv.scopeId===r.scopeId,'INVITATION_SCOPE_MISMATCH','请使用相同审核范围的加入邀请',409);invariant(!r.reserved,'ADMISSION_ACTIVE','当前申请仍有效',409);invariant(inv.usedCount+inv.reservedCount<inv.maxUses,'INVITATION_FULL','名额已满',409);const n={...touch(r,this.clock),invitationId:inv.id,reserved:true,recoveryEpoch:this.config.recoveryEpoch,admissionUntil:new Date(Math.min(Date.parse(inv.expiresAt),this.clock.now().getTime()+L.admissionDays*day)).toISOString()};await tx.replace('talentClaims',n);await tx.replace('talentInvitations',{...touch(inv,this.clock),reservedCount:inv.reservedCount+1});return n;}
 async grant(tx:Tx,workspaceId:string,accountId:string,id:string){await this.account(tx,workspaceId,accountId);const g=await workspaceRow(tx,'talentAccessGrants',id,workspaceId);if(!g||g.talentAccountId!==accountId||g.state!=='ACTIVE'||g.recoveryEpoch!==this.config.recoveryEpoch||!g.actions.includes('TEXT_MAINTAIN'))missing();const claim=await workspaceRow(tx,'talentClaims',g.claimId,workspaceId);if(!claim||claim.state!=='APPROVED'||claim.talentAccountId!==accountId||claim.targetPersonId!==g.personId)missing();await this.person(tx,workspaceId,g.personId);return g;}
 async exposure(tx:Tx,actor:Actor,p:Person,fields:string[]):Promise<Exposure[]>{const graph=await loadTalentGraph(tx,actor,this.clock,[p.id]);const out:Exposure[]=[];for(const field of fields){if(!graph.fieldReadable('person',asRow(p),field))continue;const evidence=(await tx.find('evidence',{workspaceId:actor.workspaceId,personId:p.id,fieldPath:field})).find(e=>e.valueDigest===digest(asRow(p)[field])&&graph.sourceUsable(e.sourceId)&&graph.source(e.sourceId)?.revision===e.sourceRevision);const s=evidence?graph.source(evidence.sourceId):graph.source(p.sourceId);if(s&&graph.sourceUsable(s.id))out.push({kind:'person',targetId:p.id,field,valueDigest:digest(asRow(p)[field]),sourceId:s.id,sourceRevision:s.revision});}return out;}
 async approveClaim(tx:Tx,actor:Actor,r:TalentClaim,p:Person,basis:string,guardian:boolean){await this.account(tx,actor.workspaceId,r.talentAccountId);await requireScope(tx,actor,r.scopeId);await requireScope(tx,actor,p.scopeId);await this.person(tx,actor.workspaceId,p.id);const inv=(await tx.get('talentInvitations',r.invitationId))!;this.liveInvitation(inv);await this.recipient(tx,inv,r.talentAccountId);invariant(r.state==='PENDING'&&Date.parse(r.admissionUntil)>this.clock.now().getTime()&&r.recoveryEpoch===this.config.recoveryEpoch&&(r.kind!=='ENROLL'||r.reserved),'ADMISSION_EXPIRED','申请已失效',409);
 if(r.relation==='SELF'){invariant(r.adultDeclared,'ADULT_DECLARATION_REQUIRED','未知年龄须先由本人明确成年声明，未成年人须经确认监护人维护',409);const profiles=await tx.find('talentProfiles',{workspaceId:actor.workspaceId,personId:p.id});for(const pr of profiles){const age=ageRange(asRow(pr),this.now().slice(0,10));invariant(!age||age.min>=18,'GUARDIAN_REQUIRED','该档案可能未满18岁，需要监护授权',409);}invariant(!(await tx.find('talentAccessGrants',{workspaceId:actor.workspaceId,relation:'SELF',state:'ACTIVE'})).some(g=>g.personId===p.id||g.talentAccountId===r.talentAccountId),'SELF_ALREADY_BOUND','本人维护关系已存在',409);}else invariant(guardian,'GUARDIAN_PROOF_REQUIRED','监护或代理关系须独立核实',409);
 const nextClaim={...touch(r,this.clock),targetPersonId:p.id,state:'APPROVED',reserved:false,ownershipBasis:basis,decidedById:actor.membershipId,decidedAt:this.now()};await tx.replace('talentClaims',nextClaim);
 const g:TalentAccessGrant={...base(actor.workspaceId,this.clock),talentAccountId:r.talentAccountId,personId:p.id,claimId:r.id,relation:r.relation,state:'ACTIVE',actions:['TEXT_MAINTAIN'],authorizationEpoch:1,selfExposureManifest:await this.exposure(tx,actor,p,inv.exposureFields),approvedById:actor.membershipId,approvalBasis:basis,recoveryEpoch:this.config.recoveryEpoch};await tx.insert('talentAccessGrants',g);const used=inv.usedCount+1;await tx.replace('talentInvitations',{...touch(inv,this.clock),usedCount:used,reservedCount:inv.reservedCount-(r.reserved?1:0),state:inv.purpose==='CLAIM'?'CLAIMED':used===inv.maxUses?'EXHAUSTED':'ACTIVE',tokenHash:inv.purpose==='CLAIM'?null:inv.tokenHash});return {claim:nextClaim,grant:g};}
 async decideClaim(tx:Tx,actor:Actor,id:string,input:unknown){this.human(actor,'talent.review');const d=S.decideClaim.parse(input),r=await workspaceRow(tx,'talentClaims',id,actor.workspaceId);if(!r)missing();await requireScope(tx,actor,r.scopeId);cas(r,d.expectedRevision);invariant(r.state==='PENDING','CLAIM_CLOSED','申请已处理',409);if(d.decision==='REJECT'){if(r.reserved){const inv=(await tx.get('talentInvitations',r.invitationId))!;await tx.replace('talentInvitations',{...touch(inv,this.clock),reservedCount:inv.reservedCount-1});}const n={...touch(r,this.clock),state:'REJECTED',reserved:false,decidedAt:this.now(),decidedById:actor.membershipId,ownershipBasis:d.ownershipBasis};await tx.replace('talentClaims',n);return n;}invariant(r.kind==='CLAIM'&&r.targetPersonId,'ENROLL_SUBMISSION_REQUIRED','通用加入须在资料审核时一次完成绑定',409);const p=await td2PersonFor(tx,actor,r.targetPersonId);return (await this.approveClaim(tx,actor,r,p,d.ownershipBasis,d.guardianConfirmed)).claim;}
 async profile(tx:Tx,actor:TalentActor,personId:string){const row=(await tx.find('talentAccessGrants',{workspaceId:actor.workspaceId,talentAccountId:actor.talentAccountId,personId,state:'ACTIVE'}))[0];if(!row)missing();const g=await this.grant(tx,actor.workspaceId,actor.talentAccountId,row.id),p=await this.person(tx,actor.workspaceId,personId),fields:Record<string,unknown>={};for(const e of g.selfExposureManifest){if(e.kind!=='person'||e.targetId!==p.id||!TEXT_FIELDS.includes(e.field as typeof TEXT_FIELDS[number])||e.valueDigest!==digest(asRow(p)[e.field]))continue;const s=await workspaceRow(tx,'sources',e.sourceId,actor.workspaceId);if(s&&s.revision===e.sourceRevision&&sourceCurrent(s,this.clock)&&!await deletionBlocked(tx,actor.workspaceId,'SOURCE',s.id))fields[e.field]=asRow(p)[e.field];}return {personId,grantId:g.id,relation:g.relation,fields};}
 async revokeGrant(tx:Tx,actor:Actor,id:string,input:unknown){this.human(actor,'talent.review');const g=await workspaceRow(tx,'talentAccessGrants',id,actor.workspaceId);if(!g)missing();await td2PersonFor(tx,actor,g.personId);cas(g,S.revision.parse(input).expectedRevision);const n={...touch(g,this.clock),state:'REVOKED',authorizationEpoch:g.authorizationEpoch+1,selfExposureManifest:[]};await tx.replace('talentAccessGrants',n);return n;}
 validateItems(items:TextItem[]){invariant(new Set(items.map(i=>i.clientItemKey)).size===items.length&&new Set(items.map(i=>i.field)).size===items.length,'DUPLICATE_ITEM','条目键和字段不能重复',422);const by=new Map(items.map(i=>[i.clientItemKey,i]));for(const i of items){invariant(i.field==='aliases'?i.aliases!==undefined&&i.text===undefined:i.text!==undefined&&i.aliases===undefined,'TEXT_ITEM_INVALID','文字字段格式不正确',422);if(i.field==='displayName')invariant(!!i.text?.trim()&&i.text.length<=120,'NAME_REQUIRED','姓名须为1–120字',422);invariant(new Set(i.dependsOn).size===i.dependsOn.length,'DUPLICATE_DEPENDENCY','依赖不能重复',422);const seen=new Set<string>();const visit=(key:string)=>{invariant(key!==i.clientItemKey&&!seen.has(key),'DEPENDENCY_CYCLE','依赖不能形成循环',422);const other=by.get(key);invariant(other,'DEPENDENCY_MISSING','依赖条目不存在',422);seen.add(key);for(const parent of other.dependsOn)visit(parent);seen.delete(key);};for(const key of i.dependsOn)visit(key);}}
 async submissionAccess(tx:Tx,actor:TalentActor,id:string,write=false){await this.account(tx,actor.workspaceId,actor.talentAccountId);const s=await workspaceRow(tx,'talentSubmissions',id,actor.workspaceId);if(!s||s.talentAccountId!==actor.talentAccountId||Date.parse(s.expiresAt)<=this.clock.now().getTime())missing();if(s.personId){if(!s.grantId)missing();const g=await this.grant(tx,actor.workspaceId,actor.talentAccountId,s.grantId);if(g.personId!==s.personId)missing();}else {if(!s.claimId)missing();await this.ownClaim(tx,actor,s.claimId,write);}if(write)invariant(s.recoveryEpoch===this.config.recoveryEpoch,'RECOVERY_REVIEW_REQUIRED','恢复后须重新建立申请',409);return s;}
 async putItems(tx:Tx,s:TalentSubmission,items:TextItem[]){this.validateItems(items);const p=s.personId?await this.person(tx,s.workspaceId,s.personId):null;const previous=await tx.find('talentSubmissionItems',{workspaceId:s.workspaceId,submissionId:s.id,kind:'IDENTITY_TEXT'});for(const r of previous)await tx.remove('talentSubmissionItems',r.id);for(const i of items)await tx.insert('talentSubmissionItems',{...base(s.workspaceId,this.clock),submissionId:s.id,clientItemKey:i.clientItemKey,kind:'IDENTITY_TEXT',targetId:p?.id??null,values:{field:i.field,value:i.field==='aliases'?i.aliases:i.text},baseline:previous.find(r=>r.values.field===i.field)?.baseline??(p?{valueDigest:digest(p[i.field]),protectionEpoch:p.protectionEpoch}:{}),dependencyGroup:i.dependencyGroup,dependsOn:i.dependsOn,state:'PENDING',appliedId:null});}
 async draftCapacity(tx:Tx,actor:TalentActor){invariant((await tx.find('talentSubmissions',{workspaceId:actor.workspaceId,talentAccountId:actor.talentAccountId})).filter(s=>['DRAFT','SUBMITTED'].includes(s.state)&&Date.parse(s.expiresAt)>this.clock.now().getTime()).length<L.activeDraftsPerAccount,'SUBMISSION_LIMIT','未结束的草稿或提交过多，请先处理已有记录',429);}
 async createDraft(tx:Tx,actor:TalentActor,input:unknown){const d=S.createDraft.parse(input);invariant(d.consentAccepted&&!!d.grantId!==!!d.claimId,'CONSENT_CONTEXT_REQUIRED','请选择本人授权或加入申请，并明确同意内部使用',422);await this.account(tx,actor.workspaceId,actor.talentAccountId);let personId:string|null=null,scopeId:string,claimId:string|null=null;if(d.grantId){const g=await this.grant(tx,actor.workspaceId,actor.talentAccountId,d.grantId);personId=g.personId;scopeId=(await this.person(tx,actor.workspaceId,personId)).scopeId;}else{const c=await this.ownClaim(tx,actor,d.claimId!,true);invariant(c.kind==='ENROLL','ENROLL_REQUIRED','定向认领须先获得维护授权',409);scopeId=c.scopeId;claimId=c.id;}
 await this.draftCapacity(tx,actor);
 const consent={...base(actor.workspaceId,this.clock),talentAccountId:actor.talentAccountId,personId,claimId,purpose:'INTERNAL_DIRECTORY',textVersion:CONSENT_VERSION,fieldScope:[...TEXT_FIELDS],state:'ACTIVE',validUntil:this.until(L.consentDays),revokedAt:null};await tx.insert('talentConsents',consent);
 const s:TalentSubmission={...base(actor.workspaceId,this.clock),talentAccountId:actor.talentAccountId,personId,claimId,grantId:d.grantId??null,consentId:consent.id,scopeId,schemaVersion:MAINTENANCE_VERSION,state:'DRAFT',payloadDigest:null,forkedFromId:null,expiresAt:this.until(L.draftDays),submittedAt:null,decidedAt:null,decidedById:null,publicReason:'',protectionEpoch:personId?(await tx.get('people',personId))!.protectionEpoch:0,recoveryEpoch:this.config.recoveryEpoch};await tx.insert('talentSubmissions',s);await this.putItems(tx,s,d.items);return s;}
 async mediaConsent(tx:Tx,actor:TalentActor,id:string,input:unknown){const d=TalentMediaSchemas.consent.parse(input),s=await this.submissionAccess(tx,actor,id,true);cas(s,d.expectedRevision);invariant(s.state==='DRAFT'&&d.accepted,'MEDIA_CONSENT_REQUIRED','请明确同意本批媒体内部使用',409);const c=(await tx.get('talentConsents',s.consentId))!;invariant(c.state==='ACTIVE'&&Date.parse(c.validUntil)>this.clock.now().getTime(),'CONSENT_REQUIRED','使用同意已失效',409);const mediaConsent={...c,...base(s.workspaceId,this.clock),textVersion:MEDIA_CONSENT_VERSION,fieldScope:[...TEXT_FIELDS,'media']};await tx.insert('talentConsents',mediaConsent);const n={...touch(s,this.clock),consentId:mediaConsent.id};await tx.replace('talentSubmissions',n);await syncMediaRetention(tx,n,this.clock);return n;}
 async saveDraft(tx:Tx,actor:TalentActor,id:string,input:unknown){const d=S.saveDraft.parse(input),s=await this.submissionAccess(tx,actor,id,true);cas(s,d.expectedRevision);invariant(s.state==='DRAFT','SUBMISSION_IMMUTABLE','已提交内容不能原地修改，请复制为新草稿',409);await this.putItems(tx,s,d.items);const n={...touch(s,this.clock),expiresAt:this.until(L.draftDays)};await tx.replace('talentSubmissions',n);await syncMediaRetention(tx,n,this.clock);return n;}
 async submissionAction(tx:Tx,actor:TalentActor,id:string,input:unknown,action:'submit'|'withdraw'|'fork'){const s=await this.submissionAccess(tx,actor,id,action!=='withdraw'),d=S.revision.parse(input);cas(s,d.expectedRevision);const items=await tx.find('talentSubmissionItems',{workspaceId:actor.workspaceId,submissionId:id});if(action==='fork'){await this.draftCapacity(tx,actor);invariant(s.state!=='DRAFT'&&s.state!=='SUBMITTED','SUBMISSION_OPEN','请先完成或撤回本次提交',409);const consent=await tx.get('talentConsents',s.consentId);invariant(consent?.state==='ACTIVE'&&Date.parse(consent.validUntil)>this.clock.now().getTime(),'CONSENT_REQUIRED','请重新同意并创建草稿',409);const n={...s,...base(s.workspaceId,this.clock),state:'DRAFT',payloadDigest:null,forkedFromId:s.id,expiresAt:this.until(L.draftDays),submittedAt:null,decidedAt:null,decidedById:null,publicReason:''};await tx.insert('talentSubmissions',n);await this.putItems(tx,n,items.filter(i=>i.kind==='IDENTITY_TEXT'&&(s.state==='APPROVED'||i.state!=='APPLIED')).map(i=>({clientItemKey:i.clientItemKey,field:i.values.field as TextItem['field'],...(i.values.field==='aliases'?{aliases:i.values.value as string[],text:undefined}:{text:i.values.value as string,aliases:undefined}),dependencyGroup:i.dependencyGroup,dependsOn:i.dependsOn.filter(k=>items.some(other=>other.clientItemKey===k&&(s.state==='APPROVED'||other.state!=='APPLIED')))})));return n;}
 invariant(action==='submit'?s.state==='DRAFT':['DRAFT','SUBMITTED'].includes(s.state),'SUBMISSION_CLOSED','本次提交已经处理',409);if(action==='submit'){await checkSubmissionMedia(tx,s,this.clock,this.config);for(const item of items.filter(i=>i.kind==='COLLECTION'))await validateCollectionDraft(tx,s,submissionCollectionPlan(item),this.clock,this.config);invariant(items.length>0,'EMPTY_SUBMISSION','没有可提交内容',422);const c=await tx.get('talentConsents',s.consentId);invariant(c?.state==='ACTIVE'&&Date.parse(c.validUntil)>this.clock.now().getTime(),'CONSENT_REQUIRED','使用同意已失效',409);}const n={...touch(s,this.clock),state:action==='submit'?'SUBMITTED':'WITHDRAWN',payloadDigest:action==='submit'?digest(items.map(i=>({key:i.clientItemKey,values:i.values,baseline:i.baseline,group:i.dependencyGroup,dependsOn:i.dependsOn})).sort((a,b)=>a.key.localeCompare(b.key))):s.payloadDigest,submittedAt:action==='submit'?this.now():s.submittedAt,expiresAt:this.until(action==='submit'?L.submittedDays:L.withdrawnDays)};await tx.replace('talentSubmissions',n);await syncMediaRetention(tx,n,this.clock);return n;}
 async submissionDto(tx:Tx,s:TalentSubmission,internal:Actor|false=false){const items=await tx.find('talentSubmissionItems',{workspaceId:s.workspaceId,submissionId:s.id});const c=(await tx.get('talentConsents',s.consentId))!;const uploads=await tx.find('uploads',{workspaceId:s.workspaceId,submissionId:s.id});const media=[];for(const u of uploads){const a=await tx.get('assets',u.id);media.push({id:u.id,fileName:u.fileName,mime:u.mime,state:u.state,revision:u.revision,assetRevision:a?.revision??null,usageState:a?.usageState??null,errorCode:u.errorCode});}const person=internal&&s.personId?await td2PersonFor(tx,internal,s.personId):null;const graph=person&&internal?await loadTalentGraph(tx,internal,this.clock,[person.id]):null;
 const collectionAssets=[];if(internal&&s.personId)for(const i of items.filter(i=>i.kind==='COLLECTION'))for(const ref of submissionCollectionPlan(i).items){if(ref.referenceKind!=='EXISTING_ADOPTED_ASSET_REFERENCE')continue;try{const a=await collectionAssetFor(tx,internal,{personId:s.personId,personRoleId:submissionCollectionPlan(i).personRoleId,collectionTypeCode:submissionCollectionPlan(i).collectionTypeCode},ref.assetId,this.clock);collectionAssets.push({id:a.id,fileName:a.fileName,mime:a.mime});}catch(e){if(!(e instanceof AppError)||![404,422].includes(e.status))throw e;}}
 const currentCollection=(id:string|null)=>{const view:any=person&&graph?graph.get(person.id):null,c=view?.facts.mediaCollections.find((c:any)=>c.id===id);return c?{...c,tagCodes:view!.facts.mediaCollectionTags.filter((t:any)=>t.collectionId===id&&t.usable).map((t:any)=>t.tagCode)}:null;};return {collectionAssets,media,id:s.id,revision:s.revision,personId:s.personId,claimId:s.claimId,grantId:s.grantId,state:s.state,expiresAt:s.expiresAt,publicReason:s.publicReason,consent:{id:c.id,revision:c.revision,state:c.state,textVersion:c.textVersion,validUntil:c.validUntil},items:items.map(i=>({clientItemKey:i.clientItemKey,kind:i.kind,field:i.values.field,value:i.values.value,...(i.kind==='MEDIA'?{assetId:i.values.assetId}:{}),...(i.kind==='COLLECTION'?{collection:i.values,appliedId:i.appliedId,...(internal?{currentCollection:currentCollection(i.targetId)}:{})}:{}),state:i.state,dependencyGroup:i.dependencyGroup,dependsOn:i.dependsOn,...(internal?{baseline:i.baseline,...(person&&graph?.fieldReadable('person',asRow(person),String(i.values.field))?{currentValue:asRow(person)[String(i.values.field)]}: {})}: {})}))};}
 async internalSubmission(tx:Tx,actor:Actor,id:string){this.human(actor,'talent.review');const s=await workspaceRow(tx,'talentSubmissions',id,actor.workspaceId);if(!s)missing();await requireScope(tx,actor,s.scopeId);for(const u of await tx.find('uploads',{workspaceId:s.workspaceId,submissionId:s.id}))await requireScope(tx,actor,u.scopeId);if(s.personId)await td2PersonFor(tx,actor,s.personId);return s;}
 async review(tx:Tx,actor:Actor,id:string,input:unknown){const s=await this.internalSubmission(tx,actor,id),d=S.review.parse(input);invariant(!['APPROVED','PARTIALLY_APPROVED','REJECTED'].includes(s.state),'SUBMISSION_CLOSED','本次提交已经处理',409);cas(s,d.expectedRevision);invariant(s.state==='SUBMITTED'&&Date.parse(s.expiresAt)>this.clock.now().getTime()&&s.recoveryEpoch===this.config.recoveryEpoch,'SUBMISSION_CLOSED','提交已失效或已处理',409);await this.account(tx,s.workspaceId,s.talentAccountId);const items=await tx.find('talentSubmissionItems',{workspaceId:s.workspaceId,submissionId:id});invariant(s.payloadDigest===digest(items.map(i=>({key:i.clientItemKey,values:i.values,baseline:i.baseline,group:i.dependencyGroup,dependsOn:i.dependsOn})).sort((a,b)=>a.key.localeCompare(b.key))),'SUBMISSION_DIGEST_MISMATCH','冻结内容不一致',409);const accepted=new Set(d.acceptedKeys);invariant(accepted.size===d.acceptedKeys.length&&d.acceptedKeys.every(k=>items.some(i=>i.clientItemKey===k)),'ITEM_SELECTION_INVALID','审核条目选择不正确',422);for(const i of items)if(accepted.has(i.clientItemKey))invariant(items.filter(x=>x.dependencyGroup===i.dependencyGroup).every(x=>accepted.has(x.clientItemKey))&&i.dependsOn.every(k=>accepted.has(k)),'DEPENDENCY_GROUP_INCOMPLETE','有关联的条目须整组采纳',422);
 let p:Person|null=s.personId?await this.person(tx,s.workspaceId,s.personId):null,g:TalentAccessGrant|null=null;const consent=(await tx.get('talentConsents',s.consentId))!;if(p){g=await this.grant(tx,s.workspaceId,s.talentAccountId,s.grantId!);invariant(g.personId===p.id,'NOT_FOUND','内容不可访问',404);}else await this.ownClaim(tx,{actorKind:'TALENT',workspaceId:s.workspaceId,talentAccountId:s.talentAccountId,sessionId:'',sessionEpoch:0},s.claimId!,true);
 for(const item of items.filter(i=>i.kind==='COLLECTION'&&accepted.has(i.clientItemKey)))await validateCollectionDraft(tx,s,submissionCollectionPlan(item),this.clock,this.config);
 const appliedCollections=new Map<string,string>();
 if(accepted.size){requirePermission(actor,'records.write');requirePermission(actor,'sources.review');invariant(consent.state==='ACTIVE'&&Date.parse(consent.validUntil)>this.clock.now().getTime(),'CONSENT_REQUIRED','本人内部使用同意已失效',409);
 if(p&&items.some(i=>i.kind==='IDENTITY_TEXT'&&accepted.has(i.clientItemKey)&&(i.baseline.protectionEpoch!==p!.protectionEpoch||i.baseline.valueDigest!==digest(asRow(p)[String(i.values.field)])))){const stale={...touch(s,this.clock),state:'NEEDS_REBASE'};await tx.replace('talentSubmissions',stale);return stale;}
 if(!p){invariant(!!d.targetPersonId!==!!d.createPerson&&d.ownershipBasis,'ENROLL_DECISION_REQUIRED','请明确新建或同档绑定，并记录独立归属依据',422);invariant(TEXT_FIELDS.every(f=>items.some(i=>i.values.field===f&&accepted.has(i.clientItemKey))),'MINIMUM_IDENTITY_REQUIRED','首次加入须明确采纳姓名、别名和简介（可为空），不能复制旧隐藏资料',422);if(d.targetPersonId)p=await td2PersonFor(tx,actor,d.targetPersonId);}
 const source:Source={...base(s.workspaceId,this.clock),scopeId:p?.scopeId??s.scopeId,maintainerId:actor.membershipId,title:items.some(i=>i.kind==='MEDIA')?'人才本人文字与媒体提交':'人才本人文字提交',type:'TEXT',providerClaim:'人才账号提供，经内部人员采纳',textPayload:'',basisMode:'INTERNAL_USE',basisDescription:'本人明确同意 INTERNAL_DIRECTORY，文本版本 '+consent.textVersion,validFrom:this.now(),validUntil:consent.validUntil,internalUseUntil:consent.validUntil,status:'CONFIRMED',protectionEpoch:1,reviewedBy:actor.membershipId,reviewedAt:this.now()};await tx.insert('sources',source);await appendSourceHistory(tx,actor,source,'CREATED',this.clock);
 if(!p){p={...base(s.workspaceId,this.clock),sourceId:source.id,scopeId:s.scopeId,maintainerId:actor.membershipId,displayName:'',aliases:[],intro:'',roles:[],languageCodes:[],skillCodes:[],cityCode:null,heightCm:null,status:'ACTIVE',protectionEpoch:1};for(const i of items)if(i.kind==='IDENTITY_TEXT'&&accepted.has(i.clientItemKey))Object.assign(p,{[String(i.values.field)]:i.values.value});await tx.insert('people',p);await tx.insert('talentProfiles',{...base(s.workspaceId,this.clock),personId:p.id,sourceId:source.id,...PROFILE_DEFAULTS,internalSummary:'',status:'ACTIVE'});await tx.insert('personRoles',{...base(s.workspaceId,this.clock),personId:p.id,sourceId:source.id,...ROLE_DEFAULTS,roleCode:'model',validFrom:null,validUntil:null,status:'ACTIVE'});}
 else {const n={...touch(p,this.clock)};for(const i of items)if(i.kind==='IDENTITY_TEXT'&&accepted.has(i.clientItemKey))Object.assign(n,{[String(i.values.field)]:i.values.value});p=n;await tx.replace('people',p);}
 const td2=new TalentV2(this.clock,this.config);await td2.evidenceFor(tx,actor,'person',asRow(p),items.filter(i=>i.kind==='IDENTITY_TEXT'&&accepted.has(i.clientItemKey)).map(i=>String(i.values.field)),source.id,source.revision,true);
 await tx.replace('talentConsents',{...consent,personId:p.id});await tx.insert('sourceAttributions',{...base(s.workspaceId,this.clock),sourceId:source.id,submissionId:s.id,talentAccountId:s.talentAccountId,consentId:consent.id,reviewerId:actor.membershipId,materialDescription:'服务器文字草稿冻结提交 '+s.id});await tx.insert('sourceUseBases',{...base(s.workspaceId,this.clock),sourceId:source.id,consentId:consent.id,consentRevision:consent.revision,purpose:'INTERNAL_DIRECTORY',fieldScope:[...new Set(items.filter(i=>accepted.has(i.clientItemKey)).map(i=>['MEDIA','COLLECTION'].includes(i.kind)?'media':String(i.values.field)))],state:'ACTIVE',validUntil:consent.validUntil});
 await adoptSubmissionMedia(tx,actor,s,p,source,items.filter(i=>i.kind==='MEDIA'&&accepted.has(i.clientItemKey)),this.clock,this.config);
 for(const item of items.filter(i=>i.kind==='COLLECTION'&&accepted.has(i.clientItemKey))){const row=await applyCollection(tx,actor,p,source,submissionCollectionPlan(item),this.clock,this.config);appliedCollections.set(item.clientItemKey,row.id);}
 if(!s.personId){const claim=(await tx.get('talentClaims',s.claimId!))!;g=(await this.approveClaim(tx,actor,claim,p,d.ownershipBasis!,d.guardianConfirmed??false)).grant;}
 if(g){const fields=new Set(items.filter(i=>i.kind==='IDENTITY_TEXT'&&accepted.has(i.clientItemKey)).map(i=>String(i.values.field)));const manifest=g.selfExposureManifest.filter(e=>e.kind!=='person'||!fields.has(e.field));for(const field of fields)manifest.push({kind:'person',targetId:p.id,field,valueDigest:digest(asRow(p)[field]),sourceId:source.id,sourceRevision:source.revision});for(const item of items.filter(i=>accepted.has(i.clientItemKey)&&['MEDIA','COLLECTION'].includes(i.kind))){const kind=item.kind==='MEDIA'?'mediaAsset':'mediaCollection',target=item.kind==='MEDIA'?String(item.values.assetId):appliedCollections.get(item.clientItemKey)!;const e=await mediaExposure(tx,g,kind,target,this.clock,this.config);for(let n=manifest.length-1;n>=0;n--)if(manifest[n]!.kind===kind&&manifest[n]!.targetId===target)manifest.splice(n,1);manifest.push({...e,approvedById:actor.membershipId,approvedAt:this.now(),approvalBasis:'本人提交 '+s.id+' 经内部审核采纳'});}await tx.replace('talentAccessGrants',{...touch(g,this.clock),selfExposureManifest:manifest});}
 }
 for(const i of items)await tx.replace('talentSubmissionItems',{...touch(i,this.clock),state:accepted.has(i.clientItemKey)?'APPLIED':'REJECTED',appliedId:accepted.has(i.clientItemKey)?(i.kind==='MEDIA'?String(i.values.assetId):i.kind==='COLLECTION'?appliedCollections.get(i.clientItemKey)!:p!.id):null});const next={...touch(s,this.clock),personId:p?.id??s.personId,grantId:g?.id??s.grantId,state:accepted.size===0?'REJECTED':accepted.size===items.length?'APPROVED':'PARTIALLY_APPROVED',publicReason:d.publicReason,decidedAt:this.now(),decidedById:actor.membershipId,expiresAt:this.until(L.decidedDays)};await tx.replace('talentSubmissions',next);await syncMediaRetention(tx,next,this.clock);if(!accepted.size&&!s.personId&&s.claimId){
 const c=(await tx.get('talentClaims',s.claimId))!;
 if(c.reserved){const inv=(await tx.get('talentInvitations',c.invitationId))!;await tx.replace('talentInvitations',{...touch(inv,this.clock),reservedCount:inv.reservedCount-1});}
 await tx.replace('talentClaims',{...touch(c,this.clock),reserved:false,state:'REJECTED',decidedAt:next.decidedAt,decidedById:actor.membershipId,ownershipBasis:d.ownershipBasis??`ENROLL Submission ${s.id} 全部拒绝：${d.publicReason||'本次提交未获采纳，未建立归属授权。'}`});
 }return next;
 }
 async revokeConsent(tx:Tx,actor:TalentActor,id:string,input:unknown){await this.account(tx,actor.workspaceId,actor.talentAccountId);const c=await workspaceRow(tx,'talentConsents',id,actor.workspaceId);if(!c||c.talentAccountId!==actor.talentAccountId)missing();cas(c,S.revision.parse(input).expectedRevision);const n={...touch(c,this.clock),state:'REVOKED',revokedAt:this.now()};await tx.replace('talentConsents',n);for(const b of await tx.find('sourceUseBases',{workspaceId:actor.workspaceId,consentId:id})){await tx.replace('sourceUseBases',{...touch(b,this.clock),state:'REVOKED'});const source=(await tx.get('sources',b.sourceId))!; // Keep source revision/history intact: the independent purpose protection changes immediately.
 await tx.replace('sources',{...source,internalUseUntil:this.now(),protectionEpoch:source.protectionEpoch+1});}return n;}
 async internalList(tx:Tx,actor:Actor,kind:'invitation'|'claim'|'submission'){this.human(actor,kind==='invitation'?'talent.invite':'talent.review');const rows=kind==='invitation'?await tx.find('talentInvitations',{workspaceId:actor.workspaceId}):kind==='claim'?await tx.find('talentClaims',{workspaceId:actor.workspaceId}):await tx.find('talentSubmissions',{workspaceId:actor.workspaceId});const out=[];for(const r of rows){if(!await scopeVisible(tx,actor,r.scopeId))continue;const personId=kind==='submission'?(r as TalentSubmission).personId:(r as TalentClaim|TalentInvitation).targetPersonId;if(personId){try{await td2PersonFor(tx,actor,personId);}catch(e){if((e as {status?:number}).status===404)continue;throw e;}}if(kind==='submission'){try{await this.internalSubmission(tx,actor,r.id);}catch(e){if((e as {status?:number}).status===404)continue;throw e;}}out.push(kind==='submission'?await this.submissionDto(tx,r as TalentSubmission,actor):kind==='invitation'?{id:r.id,revision:r.revision,purpose:(r as TalentInvitation).purpose,state:r.state,expiresAt:(r as TalentInvitation).expiresAt,targetPersonId:(r as TalentInvitation).targetPersonId}:{id:r.id,revision:r.revision,state:r.state,kind:(r as TalentClaim).kind,relation:(r as TalentClaim).relation,targetPersonId:(r as TalentClaim).targetPersonId,adultDeclared:(r as TalentClaim).adultDeclared});}return {items:out};}
 async portalRead(tx:Tx,actor:TalentActor,operation:string,id:string,browser:string){if(operation==='portal.invitation.inspect'){const i=await this.context(tx,actor.workspaceId,browser,id);return {purpose:i.purpose,expiresAt:i.expiresAt,recipientRestricted:!!i.recipientHash};}if(operation==='portal.collection.list')return portalCollections(tx,actor,id,this.clock,this.config);if(operation==='portal.profile.get')return this.profile(tx,actor,id);if(operation==='portal.profile.list'){const out=[];for(const g of await tx.find('talentAccessGrants',{workspaceId:actor.workspaceId,talentAccountId:actor.talentAccountId,state:'ACTIVE'})){try{out.push(await this.profile(tx,actor,g.personId));}catch(e){if((e as {status?:number}).status!==404)throw e;}}return {items:out};}if(operation==='portal.claim.list')return {items:(await tx.find('talentClaims',{workspaceId:actor.workspaceId,talentAccountId:actor.talentAccountId})).map(c=>({id:c.id,revision:c.revision,kind:c.kind,relation:c.relation,state:c.state,admissionUntil:c.admissionUntil,reserved:c.reserved}))};if(operation==='portal.submission.get')return this.submissionDto(tx,await this.submissionAccess(tx,actor,id));const out=[];for(const s of await tx.find('talentSubmissions',{workspaceId:actor.workspaceId,talentAccountId:actor.talentAccountId})){try{await this.submissionAccess(tx,actor,s.id);out.push(await this.submissionDto(tx,s));}catch(e){if((e as {status?:number}).status!==404)throw e;}}return {items:out};}
}
