import {isolateTalentMaintenance,inspectTalentMaintenance,cleanupTalentMaintenance} from './talent-maintenance-lifecycle.ts';
import {digest} from './json.ts';
import {createHmac,randomInt} from 'node:crypto';
import {domainToASCII} from 'node:url';
import type {Clock,Config,RequestMeta} from './model.ts';
import type {AuthProvider,AuthPurpose,TalentActor,TalentAuthChallenge,TalentAuthConfig,TalentIdentityKind} from './talent-auth-model.ts';
import type {Store,Tx} from './store.ts';
import {audit,base,touch} from './helpers.ts';
import {invariant} from './errors.ts';
import {csrfFor,decryptContact,encryptContact,equalSecret,randomSecret} from './crypto.ts';
export function normalizeTalentIdentity(kind:TalentIdentityKind,input:string):string {
 const value=input.trim();
 if(kind==='PHONE') {invariant(/^\+[1-9][0-9]{7,14}$/.test(value),'IDENTITY_INVALID','手机号须包含国际区号，如 +8613800000000',400);return value;}
 const parts=value.split('@');const local=parts[0]??'',domain=domainToASCII(parts[1]??'').toLowerCase();
 invariant(parts.length===2&&local.length<=64&&/^[A-Za-z0-9!#$%&'*+\-/=?^_`{|}~.]+$/.test(local)&&!local.startsWith('.')&&!local.endsWith('.')&&!local.includes('..')&&domain.length<=253&&domain.includes('.')&&domain.split('.').every(x=>/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/.test(x)),'IDENTITY_INVALID','请输入有效邮箱',400);
 // v1: local-part case is preserved; only DNS domain is case-insensitive. No provider-specific alias folding.
 return local+'@'+domain;
}
export const talentHash=(key:Buffer,purpose:string,value:string)=>createHmac('sha256',key).update('once:talent:v1:'+purpose+':'+value).digest('hex');
const live=(c:TalentAuthChallenge,now:number)=>!['CONSUMED','EXPIRED','FAILED'].includes(c.state)&&Date.parse(c.expiresAt)>now;
export class TalentAuth {
 store:Store;config:Config;clock:Clock;provider?:AuthProvider;
 constructor(store:Store,config:Config,clock:Clock,provider?:AuthProvider){this.store=store;this.config=config;this.clock=clock;this.provider=provider;}
 settings():TalentAuthConfig {const c=this.config.talentAuth;invariant(c?.enabled,'PORTAL_DISABLED','人才登录暂未开放',503);return c;}
 async workspace(tx:Tx){this.settings();const rows=await tx.find('workspaces');const w=rows[0];invariant(rows.length===1&&w&&this.config.accessMode==='INTERNAL'&&w.recoveryEpoch===this.config.recoveryEpoch,'MAINTENANCE','系统处于维护或恢复隔离状态',503);const binding=talentHash(this.settings().identityKey,'key-binding',w.id);invariant((await tx.find('talentAccounts',{workspaceId:w.id})).every(a=>a.identityKeyDigest===binding),'TALENT_KEY_MISMATCH','人才认证密钥与现有账号不匹配，请由维护人员核对恢复密钥',503);return w;}
 async rate(tx:Tx,workspaceId:string,key:string,max:number,ms:number){const c=this.settings(),id=talentHash(c.identityKey,'rate',workspaceId+':'+key),old=await tx.get('rateBuckets',id),now=this.clock.now().getTime();invariant(!old||Date.parse(old.until)<=now||old.count<max,'RATE_LIMITED','操作过于频繁，请稍后再试',429);const r={id,workspaceId,count:old&&Date.parse(old.until)>now?old.count+1:1,until:old&&Date.parse(old.until)>now?old.until:new Date(now+ms).toISOString()};if(old)await tx.replace('rateBuckets',r);else await tx.insert('rateBuckets',r);}
 async context(browser:string,purpose:AuthPurpose,meta:RequestMeta){const c=this.settings();return this.store.transaction(async tx=>{const w=await this.workspace(tx);await this.rate(tx,w.id,'context:'+meta.ip,30,3600000);const browserHash=talentHash(c.sessionKey,'browser',browser);const rows=await tx.find('talentAuthContexts',{workspaceId:w.id,browserHash});invariant(rows.filter(x=>Date.parse(x.expiresAt)>this.clock.now().getTime()&&x.recoveryEpoch===this.config.recoveryEpoch).length<5,'CONTEXT_LIMIT','请先完成现有认证或等待上下文过期',429);const row={...base(w.id,this.clock),browserHash,purpose,recoveryEpoch:this.config.recoveryEpoch,expiresAt:new Date(this.clock.now().getTime()+c.contextMs).toISOString()};await tx.insert('talentAuthContexts',row);return {contextId:row.id,expiresAt:row.expiresAt,csrfToken:csrfFor(browser,c.csrfKey)};});}
 async getContext(tx:Tx,browser:string,id:string,purpose?:AuthPurpose){const c=this.settings(),w=await this.workspace(tx),row=await tx.get('talentAuthContexts',id);invariant(row&&row.workspaceId===w.id&&equalSecret(row.browserHash,talentHash(c.sessionKey,'browser',browser))&&row.recoveryEpoch===this.config.recoveryEpoch&&Date.parse(row.expiresAt)>this.clock.now().getTime()&&(!purpose||purpose===row.purpose),'CONTEXT_INVALID','认证上下文已失效，请重新开始',401);return row;}
 async contextStatus(browser:string,id:string){return this.store.transaction(async tx=>{const row=await this.getContext(tx,browser,id);const challenges=(await tx.find('talentAuthChallenges',{workspaceId:row.workspaceId,contextId:id})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id));const ch=challenges.find(x=>live(x,this.clock.now().getTime()));const consumed=challenges.find(x=>x.state==='CONSUMED');const identity=consumed?(await tx.find('talentIdentities',{workspaceId:row.workspaceId,kind:consumed.kind,identityHash:consumed.identityHash}))[0]:null;return {contextId:id,purpose:row.purpose,csrfToken:csrfFor(browser,this.settings().csrfKey),verifiedAccountId:identity?.talentAccountId??null,challenge:ch?{id:ch.id,state:ch.state,expiresAt:ch.expiresAt}:null};});}
 async createChallenge(browser:string,input:{contextId:string;purpose:AuthPurpose;kind:TalentIdentityKind;identity:string},meta:RequestMeta){
 const c=this.settings(),identity=normalizeTalentIdentity(input.kind,input.identity),code=String(randomInt(0,1000000)).padStart(6,'0');
 const result=await this.store.transaction(async tx=>{const context=await this.getContext(tx,browser,input.contextId,input.purpose);invariant(input.purpose==='LOGIN','PURPOSE_UNAVAILABLE','此认证用途尚未开放',400);const identityHash=talentHash(c.identityKey,input.kind,context.workspaceId+':'+identity),now=this.clock.now().getTime();
 const old=await tx.find('talentAuthChallenges',{workspaceId:context.workspaceId,identityHash,kind:input.kind,purpose:input.purpose});invariant(!old.some(x=>now-Date.parse(x.createdAt)<c.resendMs),'RESEND_TOO_SOON','请稍后再申请新验证码',429);
 await this.rate(tx,context.workspaceId,'identity-hour:'+identityHash,c.identityHourly,3600000);await this.rate(tx,context.workspaceId,'identity-day:'+identityHash,c.identityDaily,86400000);await this.rate(tx,context.workspaceId,'ip:'+meta.ip,c.ipHourly,3600000);await this.rate(tx,context.workspaceId,'workspace-hour',c.workspaceHourly,3600000);await this.rate(tx,context.workspaceId,'workspace-day',c.workspaceDaily,86400000);
 // Latest challenge for this identity/purpose OR this context replaces the old one, across tabs.
 const related=await tx.find('talentAuthChallenges',{workspaceId:context.workspaceId});for(const ch of related.filter(x=>(x.identityHash===identityHash&&x.kind===input.kind&&x.purpose===input.purpose)||x.contextId===context.id)){if(!['CONSUMED','EXPIRED','FAILED'].includes(ch.state))await this.expire(tx,ch);}
 const row:TalentAuthChallenge={...base(context.workspaceId,this.clock),contextId:context.id,kind:input.kind,identityHash,purpose:input.purpose,codeHash:null,state:'QUEUED',attempts:0,recoveryEpoch:this.config.recoveryEpoch,expiresAt:new Date(Math.min(now+c.challengeMs,Date.parse(context.expiresAt))).toISOString(),consumedAt:null};row.codeHash=talentHash(c.codeKey,'code',row.id+':'+code);
 await tx.insert('talentAuthChallenges',row);await tx.insert('talentAuthDeliveries',{...base(context.workspaceId,this.clock),challengeId:row.id,state:'QUEUED',encryptedPayload:encryptContact(JSON.stringify({recipient:identity,code}),c.messageKey,row.id),providerRequestKey:randomSecret(),expiresAt:row.expiresAt});
 return {id:row.id,state:row.state,expiresAt:row.expiresAt};});
 await this.dispatch(result.id);return this.store.transaction(async tx=>{const ch=await tx.get('talentAuthChallenges',result.id);return {...result,state:ch!.state};});
 }
 private async expire(tx:Tx,ch:TalentAuthChallenge){await tx.replace('talentAuthChallenges',{...touch(ch,this.clock),state:'EXPIRED',codeHash:null});for(const d of await tx.find('talentAuthDeliveries',{workspaceId:ch.workspaceId,challengeId:ch.id}))await tx.replace('talentAuthDeliveries',{...touch(d,this.clock),encryptedPayload:null,state:d.state==='UNKNOWN'?'UNKNOWN':'EXPIRED'});}
 async dispatch(challengeId:string){const c=this.settings();const send=await this.store.transaction(async tx=>{await this.workspace(tx);const ch=await tx.get('talentAuthChallenges',challengeId);if(!ch)return null;const d=(await tx.find('talentAuthDeliveries',{workspaceId:ch.workspaceId,challengeId}))[0];if(!d||d.state!=='QUEUED'||!d.encryptedPayload)return null;if(!live(ch,this.clock.now().getTime())||ch.recoveryEpoch!==this.config.recoveryEpoch){await this.expire(tx,ch);return null;}const payload=JSON.parse(decryptContact(d.encryptedPayload,c.messageKey,ch.id)) as {recipient:string;code:string};
 // Persist uncertainty before leaving the transaction. Crash/retry can never send this delivery twice.
 await tx.replace('talentAuthDeliveries',{...touch(d,this.clock),state:'UNKNOWN',encryptedPayload:null});await tx.replace('talentAuthChallenges',{...touch(ch,this.clock),state:'UNKNOWN'});return {requestKey:d.providerRequestKey,kind:ch.kind,recipient:payload.recipient,code:payload.code,expiresAt:ch.expiresAt};});
 if(!send)return;let state:'ACCEPTED'|'DELIVERED'|'FAILED'|'UNKNOWN'='UNKNOWN';try{state=await this.provider?.send(send)??'FAILED';}catch{state='UNKNOWN';}
 await this.store.transaction(async tx=>{const ch=await tx.get('talentAuthChallenges',challengeId);if(!ch||ch.state!=='UNKNOWN'||ch.recoveryEpoch!==this.config.recoveryEpoch)return;const w=await tx.get('workspaces',ch.workspaceId);if(this.config.accessMode!=='INTERNAL'||w?.recoveryEpoch!==this.config.recoveryEpoch||Date.parse(ch.expiresAt)<=this.clock.now().getTime()){await this.expire(tx,ch);return;}const d=(await tx.find('talentAuthDeliveries',{workspaceId:ch.workspaceId,challengeId}))[0]!;await tx.replace('talentAuthDeliveries',{...touch(d,this.clock),state,encryptedPayload:null});await tx.replace('talentAuthChallenges',{...touch(ch,this.clock),state,codeHash:state==='FAILED'?null:ch.codeHash});});
 }
 async verify(browser:string,input:{contextId:string;challengeId:string;purpose:AuthPurpose;code:string},meta:RequestMeta){const c=this.settings(),token=randomSecret();const outcome=await this.store.transaction(async tx=>{const ctx=await this.getContext(tx,browser,input.contextId,input.purpose);const ch=await tx.get('talentAuthChallenges',input.challengeId);invariant(ch&&ch.contextId===ctx.id&&ch.workspaceId===ctx.workspaceId&&ch.purpose===input.purpose&&ch.recoveryEpoch===this.config.recoveryEpoch,'CHALLENGE_INVALID','验证码无效或已失效',401);invariant(input.purpose==='LOGIN','PURPOSE_UNAVAILABLE','此认证用途尚未开放',400);
 if(!live(ch,this.clock.now().getTime())||ch.attempts>=c.maxAttempts)return null;
 if(!ch.codeHash||!equalSecret(ch.codeHash,talentHash(c.codeKey,'code',ch.id+':'+input.code))){const attempts=ch.attempts+1;await tx.replace('talentAuthChallenges',{...touch(ch,this.clock),attempts,state:attempts>=c.maxAttempts?'FAILED':ch.state,codeHash:attempts>=c.maxAttempts?null:ch.codeHash});return null;}
 let identity=(await tx.find('talentIdentities',{workspaceId:ch.workspaceId,kind:ch.kind,identityHash:ch.identityHash}))[0];let account=identity?await tx.get('talentAccounts',identity.talentAccountId):null;
 if(account&&account.status!=='ACTIVE')return null;
 if(!identity){account={...base(ch.workspaceId,this.clock),identityKeyDigest:talentHash(c.identityKey,'key-binding',ch.workspaceId),status:'ACTIVE',sessionEpoch:1};await tx.insert('talentAccounts',account);identity={...base(ch.workspaceId,this.clock),talentAccountId:account.id,kind:ch.kind,identityHash:ch.identityHash,encryptedValue:null,verifiedAt:this.clock.now().toISOString()};await tx.insert('talentIdentities',identity);}
 invariant(account,'ACCOUNT_INVALID','账号不可用',401);const now=this.clock.now().getTime();const session={...base(ch.workspaceId,this.clock),talentAccountId:account.id,tokenHash:talentHash(c.sessionKey,'session',token),sessionEpoch:account.sessionEpoch,recoveryEpoch:this.config.recoveryEpoch,idleUntil:new Date(now+c.idleMs).toISOString(),absoluteUntil:new Date(now+c.absoluteMs).toISOString(),revokedAt:null};await tx.insert('talentSessions',session);await tx.replace('talentAuthChallenges',{...touch(ch,this.clock),state:'CONSUMED',codeHash:null,consumedAt:this.clock.now().toISOString()});for(const d of await tx.find('talentAuthDeliveries',{workspaceId:ch.workspaceId,challengeId:ch.id}))await tx.replace('talentAuthDeliveries',{...touch(d,this.clock),encryptedPayload:null,state:'CONSUMED'});
 const actor:TalentActor={actorKind:'TALENT',workspaceId:account.workspaceId,talentAccountId:account.id,sessionEpoch:account.sessionEpoch,sessionId:session.id};await audit(tx,actor,actor.workspaceId,'talent.auth.login','talentAccount',account.id,[],meta,this.clock);return actor;});invariant(outcome,'CHALLENGE_INVALID','验证码无效或已失效',401);return {token,actor:outcome};}
 async authenticate(tx:Tx,token:string):Promise<TalentActor>{const c=this.settings(),w=await this.workspace(tx);invariant(token.length>=32&&token.length<=100,'TALENT_SESSION_INVALID','请重新登录',401);const s=(await tx.find('talentSessions',{workspaceId:w.id,tokenHash:talentHash(c.sessionKey,'session',token)}))[0],now=this.clock.now().getTime();invariant(s&&!s.revokedAt&&Date.parse(s.idleUntil)>now&&Date.parse(s.absoluteUntil)>now&&s.recoveryEpoch===this.config.recoveryEpoch,'TALENT_SESSION_INVALID','请重新登录',401);const a=await tx.get('talentAccounts',s.talentAccountId);invariant(a&&a.workspaceId===w.id&&a.status==='ACTIVE'&&a.sessionEpoch===s.sessionEpoch,'TALENT_SESSION_INVALID','请重新登录',401);await tx.replace('talentSessions',{...s,idleUntil:new Date(Math.min(now+c.idleMs,Date.parse(s.absoluteUntil))).toISOString()});return {actorKind:'TALENT',workspaceId:a.workspaceId,talentAccountId:a.id,sessionEpoch:a.sessionEpoch,sessionId:s.id};}
 async logout(tx:Tx,actor:TalentActor,meta:RequestMeta){const s=await tx.get('talentSessions',actor.sessionId);if(s)await tx.replace('talentSessions',{...touch(s,this.clock),revokedAt:this.clock.now().toISOString()});await audit(tx,actor,actor.workspaceId,'talent.auth.logout','talentAccount',actor.talentAccountId,[],meta,this.clock);}
}
export async function isolateTalentAuth(tx:Tx,workspaceId:string,clock:Clock,accountId?:string,erase=false){
 await isolateTalentMaintenance(tx,workspaceId,clock,accountId,erase);
 const accounts=await tx.find('talentAccounts',{workspaceId,...(accountId?{id:accountId}:{})});const ids=new Set(accounts.map(x=>x.id));
 for(const a of accounts)await tx.replace('talentAccounts',{...touch(a,clock),sessionEpoch:a.sessionEpoch+1,...(accountId?{status:erase?'ERASED' as const:'DISABLED' as const}:{})});
 for(const s of await tx.find('talentSessions',{workspaceId}))if(ids.has(s.talentAccountId))await tx.replace('talentSessions',{...touch(s,clock),revokedAt:clock.now().toISOString()});
 const identities=await tx.find('talentIdentities',{workspaceId});const hashes=new Set(identities.filter(i=>ids.has(i.talentAccountId)).map(i=>i.identityHash));
 for(const ch of await tx.find('talentAuthChallenges',{workspaceId}))if(!accountId||hashes.has(ch.identityHash)){await tx.replace('talentAuthChallenges',{...touch(ch,clock),state:ch.state==='CONSUMED'?'CONSUMED':'EXPIRED',codeHash:null});for(const d of await tx.find('talentAuthDeliveries',{workspaceId,challengeId:ch.id}))await tx.replace('talentAuthDeliveries',{...touch(d,clock),state:d.state==='UNKNOWN'?'UNKNOWN':'EXPIRED',encryptedPayload:null});}
 if(erase)for(const i of identities.filter(i=>ids.has(i.talentAccountId)))await tx.replace('talentIdentities',{...touch(i,clock),encryptedValue:null});
}

/** Purges expired encrypted delivery payloads without sending anything, including after crashes. */
export async function cleanupTalentAuth(tx:Tx,clock:Clock){
 await cleanupTalentMaintenance(tx,clock);
 const now=clock.now().getTime();
 for(const ch of await tx.find('talentAuthChallenges'))if(Date.parse(ch.expiresAt)<=now&&(ch.codeHash||!['EXPIRED','CONSUMED','FAILED'].includes(ch.state)))await tx.replace('talentAuthChallenges',{...touch(ch,clock),codeHash:null,state:ch.state==='CONSUMED'?'CONSUMED':'EXPIRED'});
 for(const d of await tx.find('talentAuthDeliveries'))if(Date.parse(d.expiresAt)<=now&&d.encryptedPayload)await tx.replace('talentAuthDeliveries',{...touch(d,clock),encryptedPayload:null,state:d.state==='UNKNOWN'?'UNKNOWN':'EXPIRED'});
}

/** Recovery evidence is a digest/count summary, never an authentication export. */
export async function inspectTalentAuth(tx:Tx,workspaceId:string){
 const accounts=await tx.find('talentAccounts',{workspaceId}),identities=await tx.find('talentIdentities',{workspaceId}),sessions=await tx.find('talentSessions',{workspaceId}),contexts=await tx.find('talentAuthContexts',{workspaceId}),challenges=await tx.find('talentAuthChallenges',{workspaceId}),deliveries=await tx.find('talentAuthDeliveries',{workspaceId});
 const ids=new Set(accounts.map(a=>a.id)),ctx=new Map(contexts.map(c=>[c.id,c])),challengeIds=new Set(challenges.map(c=>c.id)),blockers:string[]=[];
 if(identities.some(i=>!ids.has(i.talentAccountId))||sessions.some(s=>!ids.has(s.talentAccountId))||challenges.some(c=>ctx.get(c.contextId)?.purpose!==c.purpose)||deliveries.some(d=>!challengeIds.has(d.challengeId)))blockers.push('TALENT_AUTH_RELATION_INVALID');
 if(sessions.some(s=>!s.revokedAt))blockers.push('TALENT_SESSION_ACTIVE');
 if(challenges.some(c=>c.codeHash||!['CONSUMED','EXPIRED','FAILED'].includes(c.state)))blockers.push('TALENT_CHALLENGE_ACTIVE');
 if(deliveries.some(d=>d.encryptedPayload))blockers.push('TALENT_DELIVERY_PAYLOAD_RETAINED');
 const maintenance=await inspectTalentMaintenance(tx,workspaceId);blockers.push(...maintenance.blockers);
 const groups=[accounts,identities,sessions,contexts,challenges,deliveries].map(rows=>[...rows].sort((a,b)=>a.id.localeCompare(b.id)));
 return {accountCount:accounts.length,identityCount:identities.length,sessionCount:sessions.length,challengeCount:challenges.length,graphDigest:digest({groups,maintenance}),blockers};
}
