import type {RouteDefinition} from './routes.ts';
import {MaintenanceSchemas as S} from './talent-maintenance-schema.ts';
export const TALENT_MAINTENANCE_ROUTES:RouteDefinition[]=[
 {method:'POST',path:'/talent-invitations',operation:'talent.invitation.create',mode:'COMMAND',permission:'talent.invite',schema:S.invitation},
 {method:'GET',path:'/talent-invitations',operation:'talent.invitation.list',mode:'READ',permission:'talent.invite'},
 {method:'POST',path:'/talent-invitations/{id}/issue',operation:'talent.invitation.issue',mode:'SECRET',permission:'talent.invite',schema:S.revision},
 {method:'POST',path:'/talent-invitations/{id}/revoke',operation:'talent.invitation.revoke',mode:'COMMAND',permission:'talent.invite',schema:S.revision},
 {method:'GET',path:'/talent-claims',operation:'talent.claim.list',mode:'READ',permission:'talent.review'},
 {method:'POST',path:'/talent-claims/{id}/decide',operation:'talent.claim.decide',mode:'COMMAND',permission:'talent.review',schema:S.decideClaim},
 {method:'POST',path:'/talent-grants/{id}/revoke',operation:'talent.grant.revoke',mode:'COMMAND',permission:'talent.review',schema:S.revision},
 {method:'GET',path:'/talent-submissions',operation:'talent.submission.list',mode:'READ',permission:'talent.review'},
 {method:'GET',path:'/talent-submissions/{id}',operation:'talent.submission.get',mode:'READ',permission:'talent.review'},
 {method:'POST',path:'/talent-submissions/{id}/decide',operation:'talent.submission.decide',mode:'COMMAND',permission:'talent.review',schema:S.review},
 {method:'POST',path:'/portal/invitations/exchange',operation:'portal.invitation.exchange',mode:'AUTH',schema:S.exchange},
 {method:'GET',path:'/portal/invitations/{id}',operation:'portal.invitation.inspect',mode:'READ'},
 {method:'POST',path:'/portal/claims',operation:'portal.claim.create',mode:'COMMAND',schema:S.claim},
 {method:'GET',path:'/portal/claims',operation:'portal.claim.list',mode:'READ'},
 {method:'POST',path:'/portal/claims/{id}/renew-admission',operation:'portal.claim.renew',mode:'COMMAND',schema:S.renew},
 {method:'GET',path:'/portal/profiles',operation:'portal.profile.list',mode:'READ'},
 {method:'GET',path:'/portal/profiles/{id}',operation:'portal.profile.get',mode:'READ'},
 {method:'POST',path:'/portal/submissions',operation:'portal.submission.create',mode:'COMMAND',schema:S.createDraft},
 {method:'GET',path:'/portal/submissions',operation:'portal.submission.list',mode:'READ'},
 {method:'GET',path:'/portal/submissions/{id}',operation:'portal.submission.get',mode:'READ'},
 {method:'PATCH',path:'/portal/submissions/{id}',operation:'portal.submission.save',mode:'COMMAND',schema:S.saveDraft},
 {method:'POST',path:'/portal/submissions/{id}/submit',operation:'portal.submission.submit',mode:'COMMAND',schema:S.revision},
 {method:'POST',path:'/portal/submissions/{id}/withdraw',operation:'portal.submission.withdraw',mode:'COMMAND',schema:S.revision},
 {method:'POST',path:'/portal/submissions/{id}/fork',operation:'portal.submission.fork',mode:'COMMAND',schema:S.revision},
 {method:'POST',path:'/portal/consents/{id}/revoke',operation:'portal.consent.revoke',mode:'COMMAND',schema:S.revision},
];
