import {requireExposureBasis} from './talent-exposure-basis.ts';
import {requireWorkConsent} from './work-consent.ts';
import type {Actor,Clock,Config,Person,Source} from './model.ts';
import type {Work,WorkCredit} from './production-model.ts';
import type {TalentActor} from './talent-auth-model.ts';
import type {TalentSubmission,TalentSubmissionItem,TalentAccessGrant,Exposure} from './talent-maintenance-model.ts';
import type {Tx} from './store.ts';
import {v,uuid,revision,code,type Parsed} from './validation.ts';
import {base,touch,cas,workspaceRow} from './helpers.ts';
import {AppError,invariant,missing} from './errors.ts';
import {sourceCurrent,sourceFor,deletionBlocked} from './policy.ts';
import {periodCurrent} from './talent-v2-graph.ts';
import {TalentMaintenance} from './talent-maintenance.ts';
import {validateCollectionDraft,collectionAssetFor,portalCollections,talentFormalAsset} from './media-collections.ts';
import {workFor,visibleOrNull} from './production-policy.ts';
import {ROLE_DEFAULTS} from './talent-demographics.ts';
import {syncMediaRetention} from './media-adoption.ts';
import {digest} from './json.ts';
import {workPlanSchema,WorkCaseSchemas,type WorkPlan,type WorkDecision} from './work-case-schema.ts';
export {workPlanSchema,WorkCaseSchemas};
export type {WorkPlan,WorkDecision};
export function caseFacts(w:Work){return {id:w.id,sourceId:w.sourceId,scopeId:w.scopeId,title:w.title,description:w.description,caseDate:w.caseDate??null,datePrecision:w.datePrecision??'UNKNOWN',location:w.location??'',industryCode:w.industryCode,workTypeCodes:w.workTypeCodes,brandDisplayName:w.brandDisplayName??'',origin:w.origin,status:w.status};}
export function validateCaseDate(p:Pick<WorkPlan,'caseDate'|'datePrecision'>){const d=p.caseDate;let ok=false;switch(p.datePrecision){case 'UNKNOWN':ok=d===null;break;case 'YEAR':ok=!!d&&/^\d{4}$/.test(d);break;case 'MONTH':ok=!!d&&/^\d{4}-(0[1-9]|1[0-2])$/.test(d);break;case 'DAY':ok=!!d&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;break;case 'APPROXIMATE':ok=!!d?.trim();}invariant(ok,'WORK_DATE_INVALID','请按精度填写时间；未知时间须留空',422);}
async function source(tx:Tx,workspaceId:string,id:string,clock:Clock){const s=await workspaceRow(tx,'sources',id,workspaceId);if(!s||!sourceCurrent(s,clock)||await deletionBlocked(tx,workspaceId,'SOURCE',id))missing();await requireExposureBasis(tx,s,clock);return s;}
export async function exactCreditCurrent(tx:Tx,c:WorkCredit,clock:Clock){if(!c.personRoleId)return true;const r=await workspaceRow(tx,'personRoles',c.personRoleId,c.workspaceId);if(!r||r.personId!==c.personId||r.roleCode!==c.roleCode||r.status!=='ACTIVE'||!periodCurrent(r as unknown as Record<string,unknown>,clock)||!c.sourceId)return false;return !!await visibleOrNull(async()=>{await source(tx,c.workspaceId,r.sourceId,clock);return source(tx,c.workspaceId,c.sourceId!,clock);});}
export async function workExposure(tx:Tx,g:TalentAccessGrant,creditId:string,clock:Clock,config:Config,consentId?:string):Promise<Exposure>{const consent=await requireWorkConsent(tx,g.workspaceId,g.talentAccountId,consentId,g.personId,clock).catch(e=>{if(e instanceof AppError&&e.code==='WORK_CONSENT_REQUIRED')missing();throw e;});const m=new TalentMaintenance(clock,config);await m.grant(tx,g.workspaceId,g.talentAccountId,g.id);const p=await m.person(tx,g.workspaceId,g.personId),c=await workspaceRow(tx,'workCredits',creditId,g.workspaceId);if(!c||c.personId!==p.id||!c.personRoleId||!await exactCreditCurrent(tx,c,clock))missing();const w=await workspaceRow(tx,'works',c.workId,g.workspaceId);if(!w||w.status!=='ACTIVE'||await deletionBlocked(tx,g.workspaceId,'WORK',w.id))missing();await requireExposureBasis(tx,await source(tx,g.workspaceId,w.sourceId,clock),clock,['work']);const s=await source(tx,g.workspaceId,c.sourceId!,clock);await requireExposureBasis(tx,s,clock,['work']);return {consentId:consent.id,kind:'workCredit',targetId:c.id,field:'OWN_WORK_CASE',sourceId:s.id,sourceRevision:s.revision,valueDigest:digest({grantId:g.id,account:g.talentAccountId,authorizationEpoch:g.authorizationEpoch,consentId:consent.id,consentRevision:consent.revision,protection:p.protectionEpoch,credit:c,work:caseFacts(w)})};}
/** Internal approval opens the exact existing case for reading. It never represents Talent WorkConsent. */
export async function reviewedWorkExposure(tx:Tx,g:TalentAccessGrant,creditId:string,clock:Clock,config:Config):Promise<Exposure>{
 const m=new TalentMaintenance(clock,config);await m.grant(tx,g.workspaceId,g.talentAccountId,g.id);const p=await m.person(tx,g.workspaceId,g.personId),c=await workspaceRow(tx,'workCredits',creditId,g.workspaceId);
 if(!c||c.personId!==p.id||!c.personRoleId||!c.sourceId||!await exactCreditCurrent(tx,c,clock))missing();
 const w=await workspaceRow(tx,'works',c.workId,g.workspaceId);if(!w||w.status!=='ACTIVE'||await deletionBlocked(tx,g.workspaceId,'WORK',w.id))missing();
 await requireExposureBasis(tx,await source(tx,g.workspaceId,w.sourceId,clock),clock,['work']);const basis=await source(tx,g.workspaceId,c.sourceId,clock);await requireExposureBasis(tx,basis,clock,['work']);
 return {kind:'workCredit',targetId:c.id,field:'OWN_WORK_CASE',sourceId:basis.id,sourceRevision:basis.revision,valueDigest:digest({version:'internally-approved-case-exposure-v1',grantId:g.id,account:g.talentAccountId,authorizationEpoch:g.authorizationEpoch,protection:p.protectionEpoch,credit:c,work:caseFacts(w)})};
}
export async function currentWorkExposure(tx:Tx,g:TalentAccessGrant,e:Exposure,clock:Clock,config:Config){
 if(e.consentId)return workExposure(tx,g,e.targetId,clock,config,e.consentId);
 if(!e.approvedById||!e.approvedAt||!e.approvalBasis?.trim())missing();
 return reviewedWorkExposure(tx,g,e.targetId,clock,config);
}
async function ownCredit(tx:Tx,actor:TalentActor,personId:string,workId:string,clock:Clock,config:Config){const g=(await tx.find('talentAccessGrants',{workspaceId:actor.workspaceId,talentAccountId:actor.talentAccountId,personId,state:'ACTIVE'}))[0];if(!g)missing();for(const e of g.selfExposureManifest.filter(e=>e.kind==='workCredit')){const c=await workspaceRow(tx,'workCredits',e.targetId,actor.workspaceId);if(!c||c.workId!==workId)continue;const current=await visibleOrNull(()=>currentWorkExposure(tx,g,e,clock,config));if(current&&current.valueDigest===e.valueDigest&&current.sourceId===e.sourceId&&current.sourceRevision===e.sourceRevision)return c;}missing();}
export async function validateWorkDraft(tx:Tx,s:TalentSubmission,p:WorkPlan,clock:Clock,config:Config,baseline?:Record<string,unknown>){await requireWorkConsent(tx,s.workspaceId,s.talentAccountId,s.consentId,s.personId,clock);validateCaseDate(p);invariant(p.title.trim().length>0,'TITLE_REQUIRED','请填写案例标题',422);invariant(p.mode==='LINK_EXISTING_WORK'||!p.targetWorkId,'WORK_MODE_INVALID','新建案例不能指定已有作品',422);invariant(!!p.targetWorkId===!!p.expectedWorkRevision,'WORK_REVISION_REQUIRED','已有案例需要版本',422);if(s.personId)invariant(p.personRoleId&&!p.declaredRoleCode,'WORK_ROLE_REQUIRED','请选择当前人物的明确职业',422);else {invariant(!p.personRoleId&&p.declaredRoleCode,'WORK_ROLE_REQUIRED','未绑定申请请声明自己的职业',422);invariant((await tx.find('dictionary',{workspaceId:s.workspaceId,namespace:'role',code:p.declaredRoleCode!,status:'ACTIVE'})).length>0,'ROLE_UNAVAILABLE','职业已停用或不存在',422);}
 for(const [ns,codes] of [['industry',p.industryCode?[p.industryCode]:[]],['workType',p.workTypeCodes]] as const){invariant(new Set(codes).size===codes.length,'DUPLICATE_CODE','类型不能重复',422);for(const code of codes)invariant((await tx.find('dictionary',{workspaceId:s.workspaceId,namespace:ns,code,status:'ACTIVE'})).length>0,'CODE_UNAVAILABLE','行业或类型不可用',422);}
 if(p.targetWorkId){if(baseline?.creditId){const c=await workspaceRow(tx,'workCredits',String(baseline.creditId),s.workspaceId);invariant(c&&c.revision===baseline.creditRevision,'WORK_CREDIT_NEEDS_REBASE','本人署名已被修改，请重新核对',409);}if(baseline?.workFactsDigest){const target=await workspaceRow(tx,'works',p.targetWorkId,s.workspaceId);invariant(target&&digest(caseFacts(target))===baseline.workFactsDigest,'WORK_NEEDS_REBASE','目标案例事实已变更，请重新核对',409);}invariant(s.personId,'WORK_EXPOSURE_REQUIRED','未绑定申请不能引用已有案例',422);await ownCredit(tx,{actorKind:'TALENT',workspaceId:s.workspaceId,talentAccountId:s.talentAccountId,sessionId:'',sessionEpoch:0},s.personId,p.targetWorkId,clock,config);}
 // Same submission media protocol and current Grant/Claim checks as Collections, without creating a Collection.
 return validateCollectionDraft(tx,s,{clientItemKey:p.clientItemKey,targetCollectionId:null,expectedCollectionRevision:null,personRoleId:p.personRoleId,collectionTypeCode:'PORTFOLIO',title:p.title,isCurrent:false,coverAssetId:p.coverAssetId,tagCodes:[],items:p.items.map(i=>({...i,caption:'',featured:false}))},clock,config);
}
export async function saveWorkDrafts(tx:Tx,actor:TalentActor,id:string,input:unknown,clock:Clock,config:Config){const d=WorkCaseSchemas.draft.parse(input),s=await new TalentMaintenance(clock,config).submissionAccess(tx,actor,id,true);cas(s,d.expectedRevision);invariant(s.state==='DRAFT','SUBMISSION_IMMUTABLE','提交后不能修改案例',409);invariant(new Set(d.works.map(w=>w.clientItemKey)).size===d.works.length,'DUPLICATE_ITEM','案例条目键重复',422);const before=await tx.find('talentSubmissionItems',{workspaceId:s.workspaceId,submissionId:id}),plans=[];for(const p of d.works){invariant(!before.some(i=>i.kind!=='WORK'&&i.clientItemKey===p.clientItemKey),'DUPLICATE_ITEM','条目键已使用',422);const dependsOn=await validateWorkDraft(tx,s,p,clock,config),w=p.targetWorkId?await tx.get('works',p.targetWorkId):null;if(w)cas(w,p.expectedWorkRevision!);const credit=w?(await tx.find('workCredits',{workspaceId:s.workspaceId,workId:w.id,personId:s.personId!,personRoleId:p.personRoleId!}))[0]:null;plans.push({p,dependsOn,baseline:w?{workRevision:w.revision,workFactsDigest:digest(caseFacts(w)),...(credit?{creditId:credit.id,creditRevision:credit.revision}:{})}:{}});}for(const i of before.filter(i=>i.kind==='WORK'))await tx.remove('talentSubmissionItems',i.id);for(const {p,dependsOn,baseline} of plans)await tx.insert('talentSubmissionItems',{...base(s.workspaceId,clock),submissionId:id,clientItemKey:p.clientItemKey,kind:'WORK',targetId:p.targetWorkId,values:p,baseline,dependencyGroup:p.clientItemKey,dependsOn,state:'PENDING',appliedId:null});const n={...touch(s,clock),expiresAt:new Date(clock.now().getTime()+90*86400000).toISOString()};await tx.replace('talentSubmissions',n);await syncMediaRetention(tx,n,clock);return n;}
export async function applyWorkCase(tx:Tx,actor:Actor,person:Person,sourceRow:Source,item:TalentSubmissionItem,decision:WorkDecision,clock:Clock,originNoteOverride?:string){const p=workPlanSchema.parse(item.values);invariant(decision.clientItemKey===p.clientItemKey,'WORK_DECISION_REQUIRED','每个案例须明确审核动作',422);let role=p.personRoleId?await workspaceRow(tx,'personRoles',p.personRoleId,actor.workspaceId):null;if(!role){invariant(p.declaredRoleCode,'WORK_ROLE_REQUIRED','职业不可用',422);role=(await tx.find('personRoles',{workspaceId:actor.workspaceId,personId:person.id,roleCode:p.declaredRoleCode,status:'ACTIVE'}))[0]??null;if(!role){role={...base(actor.workspaceId,clock),personId:person.id,sourceId:sourceRow.id,...ROLE_DEFAULTS,roleCode:p.declaredRoleCode,validFrom:null,validUntil:null,status:'ACTIVE'};await tx.insert('personRoles',role);}}
 invariant(role.personId===person.id&&role.status==='ACTIVE'&&periodCurrent(role as unknown as Record<string,unknown>,clock),'WORK_ROLE_INVALID','案例职业不属于当前人物或已失效',409);await sourceFor(tx,actor,role.sourceId,clock);
 let w:Work;
 if(decision.decision==='LINK_EXISTING'){invariant(decision.targetWorkId&&decision.expectedWorkRevision,'WORK_TARGET_REQUIRED','请明确已有案例及版本',422);w=await workFor(tx,actor,decision.targetWorkId,clock);invariant(w.status==='ACTIVE','WORK_UNAVAILABLE','目标案例不可用',409);cas(w,decision.expectedWorkRevision);if(p.targetWorkId){invariant(p.targetWorkId===w.id,'WORK_TARGET_CHANGED','请重新提交目标案例',409);invariant(item.baseline.workFactsDigest===digest(caseFacts(w)),'WORK_NEEDS_REBASE','目标案例的依赖事实已变更，请重新核对',409);}}
 else {invariant(!decision.targetWorkId&&!decision.expectedWorkRevision&&!p.targetWorkId,'WORK_DECISION_INVALID','已有案例的署名维护不能改为新建',422);w={...base(actor.workspaceId,clock),sourceId:sourceRow.id,scopeId:person.scopeId,maintainerId:actor.membershipId,title:p.title.trim(),description:p.description,caseDate:p.caseDate,datePrecision:p.datePrecision,location:p.location,brandDisplayName:p.brandDisplayName,industryCode:p.industryCode,workTypeCodes:p.workTypeCodes,origin:'EXTERNAL',originNote:originNoteOverride??'本人声明外部案例，经内部审核；'+decision.basis,status:'ACTIVE',coverEntryId:null};await tx.insert('works',w);}
 const old=(await tx.find('workCredits',{workspaceId:actor.workspaceId,workId:w.id,personId:person.id,roleCode:role.roleCode}))[0];
 if(old){
  invariant(decision.decision==='LINK_EXISTING','DUPLICATE_WORK_CREDIT','该人物职业已有署名',409);
  invariant(old.personRoleId&&old.sourceId,'WORK_CREDIT_UPGRADE_REQUIRED','旧署名须由内部人员明确升级精确职业和来源后再接手',409);
  invariant(old.personRoleId===role.id&&await exactCreditCurrent(tx,old,clock),'WORK_CREDIT_UNAVAILABLE','已有署名职业或来源已失效',409);await sourceFor(tx,actor,old.sourceId,clock);
  return {work:w,credit:old};
 }
 const credit:WorkCredit={...base(actor.workspaceId,clock),workId:w.id,personId:person.id,personRoleId:role.id,sourceId:sourceRow.id,roleCode:role.roleCode,note:p.creditNote};await tx.insert('workCredits',credit);
 // LINK is an attribution/exposure decision, never an edit of shared Work media or facts.
 if(decision.decision==='LINK_EXISTING')return {work:w,credit};
 const entries=await tx.find('workAssets',{workspaceId:actor.workspaceId,workId:w.id});for(const ref of p.items){const a=await collectionAssetFor(tx,actor,{personId:person.id,personRoleId:role.id,collectionTypeCode:'PORTFOLIO'},ref.assetId,clock);if(p.coverAssetId===a.id)invariant(a.mime.startsWith('image/'),'WORK_COVER_INVALID','封面须为图片',422);if(!entries.some(e=>e.assetId===a.id)){invariant(entries.length<30,'WORK_ITEM_LIMIT','单案例最多30项素材',422);const e={...base(actor.workspaceId,clock),workId:w.id,assetId:a.id,position:entries.length};await tx.insert('workAssets',e);entries.push(e);}}
 // A link approval never edits shared facts, cover or existing placements.
 if(decision.decision==='CREATE_NEW'){w={...w,coverEntryId:entries.find(e=>e.assetId===p.coverAssetId)?.id??null};await tx.replace('works',w);}return {work:w,credit};
}
export async function portalWorkCases(tx:Tx,actor:TalentActor,personId:string,clock:Clock,config:Config){const pool=await portalCollections(tx,actor,personId,clock,config),g=(await tx.get('talentAccessGrants',pool.grantId))!,works=[];for(const e of g.selfExposureManifest.filter(e=>e.kind==='workCredit')){const current=await visibleOrNull(()=>currentWorkExposure(tx,g,e,clock,config));if(!current||current.valueDigest!==e.valueDigest||current.sourceRevision!==e.sourceRevision||current.sourceId!==e.sourceId)continue;const credit=(await tx.get('workCredits',e.targetId))!,w=(await tx.get('works',credit.workId))!,items=[];for(const entry of (await tx.find('workAssets',{workspaceId:actor.workspaceId,workId:w.id})).sort((a,b)=>a.position-b.position)){const f=await visibleOrNull(()=>talentFormalAsset(tx,actor,entry.assetId,clock,config));if(f&&f.relation.personId===personId&&(!f.relation.personRoleId||f.relation.personRoleId===credit.personRoleId))items.push({id:entry.id,assetId:f.asset.id,fileName:f.asset.fileName,mime:f.asset.mime,position:entry.position});}const {sourceId:_,scopeId:__,...facts}=caseFacts(w);works.push({...facts,revision:w.revision,credit:{id:credit.id,personRoleId:credit.personRoleId,roleCode:credit.roleCode,note:credit.note},coverAssetId:items.find(i=>i.id===w.coverEntryId&&i.mime.startsWith('image/'))?.assetId??null,items});}return {personId,roles:pool.roles,assets:pool.assets,works};}
