import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {fixture,member,result} from '../support/fixtures.ts';
import {batchScenario,caseScenario,uxTalent,uxChoice,uxList,uxEntry} from '../support/admin-ux.ts';
import {expectResponse as ok} from '../support/talent-v2-maintenance.ts';
import {MemoryStore} from '../support/memory-store.ts';
import {maintenanceFixture} from '../support/talent-maintenance.ts';
test('admin UX batch command validates the whole selection, returns numeric outcomes and supports readonly recovery',async()=>{await batchScenario(await fixture());});
test('admin UX batch audit failure rolls back all items and can replay the exact original request',async()=>{const f=await fixture(),t=await uxTalent(f,'合成审计回滚'),p=(await uxChoice(f,[t.id]))[0],list=await uxList(f),key=randomUUID(),input={expectedRevision:1,entries:[uxEntry(p)]};f.store.failNextAudit=true;assert.equal((await f.owner.cmd('POST',`/shortlists/${list}/batch`,input,key)).status,500);assert.equal(f.store.rows('shortlistItems').length,0);ok(await f.owner.cmd('POST',`/shortlists/${list}/batch`,input,key),200);assert.equal(f.store.rows('shortlistItems').length,1);});
test('admin UX recovery and batch writes remain bound to current actor, scope and permission',async()=>{const f=await fixture(),s=await batchScenario(f),viewer=await member(f,'uxviewer','VIEWER');assert.deepEqual(ok(await viewer.client.raw('POST','/commands/inspect',{operation:'shortlist.batchAdd',commandKey:s.key}),200),{found:false});assert.equal((await viewer.client.cmd('POST',`/shortlists/${s.list}/batch`,{expectedRevision:s.receipt.revision,entries:[]})).status,403);const privateOwner=await member(f,'uxprivate'),t=await uxTalent(f,'不得泄露的私有姓名',['model'],privateOwner.client);assert.deepEqual((await uxChoice(f,[t.id]))[0],{id:t.id,unavailable:true});const root=f.store.rows('shortlists').find(l=>l.id===s.list)!;await f.store.transaction(tx=>tx.replace('shortlists',{...root,scopeId:randomUUID()}));assert.equal((await f.owner.raw('POST','/commands/inspect',{operation:'shortlist.batchAdd',commandKey:s.key})).status,404);const history=ok(await f.owner.raw('GET','/commands'),200);assert.equal(JSON.stringify(history).includes(s.key),false);assert.equal(history.items.some((r:any)=>r.result.resourceId===s.list),false);});
test('admin UX new case keeps exact attribution and validates all media before writes',async()=>{await caseScenario(await fixture());});
test('admin UX source review TODO/SENT/DONE counts follow the active participant and cannot leak private objects',async()=>{const f=await fixture(),editor=await member(f,'uxtaskeditor'),reviewer=await member(f,'uxtaskreviewer','REVIEWER'),t=await uxTalent(f,'合成私有审核名称',['model'],editor.client),options=ok(await editor.client.raw('GET',`/people/${t.id}/source-review-options`),200),scope=f.store.rows('scopes').find(s=>s.mode==='WORKSPACE')!;
 const task=ok(await editor.client.cmd('POST',`/people/${t.id}/source-reviews`,{expectedRevision:options.revision,expectedSourceRevision:options.sourceRevision,reviewerId:reviewer.id,publisherId:f.membershipId,targetScopeId:scope.id,expiresAt:'2026-09-25T00:00:00.000Z',acknowledgeLimitedAccess:true}),201).resourceId;
 const list=(c:typeof f.owner,view='TODO')=>c.raw('POST','/review/search',{view,kind:'ALL',page:1,pageSize:20});
 const todo=ok(await list(reviewer.client),200);assert.equal(todo.total,1);assert.equal(JSON.stringify(todo).includes('合成私有审核名称'),false);assert.equal(ok(await list(editor.client,'SENT'),200).total,1);assert.equal(ok(await list(f.owner),200).total,0);
 ok(await reviewer.client.cmd('POST',`/source-reviews/${task}/accept`,{expectedRevision:1}),200);assert.match(JSON.stringify(ok(await list(reviewer.client),200)),/合成私有审核名称/);ok(await reviewer.client.cmd('POST',`/source-reviews/${task}/review`,{expectedRevision:2,basisDescription:'合成内部团队使用依据',validUntil:'2026-12-31T00:00:00.000Z'}),200);assert.equal(ok(await list(f.owner),200).total,1);assert.equal(ok(await list(reviewer.client,'SENT'),200).total,1);
 ok(await f.owner.cmd('POST',`/source-reviews/${task}/publish`,{expectedRevision:3,confirmScope:true}),200);assert.equal(ok(await list(f.owner,'DONE'),200).total,1);assert.equal(ok(await list(editor.client,'DONE'),200).total,1);assert.equal(result(await list(reviewer.client)).counts.TODO,0);
 });
for(const state of ['EXPIRED','INVALIDATED'] as const)test('admin UX '+state+' claim has consistent list/detail eligibility and can be explicitly rejected',async()=>{
 const f=await maintenanceFixture(new MemoryStore());
 const inv=ok(await f.owner.cmd('POST','/talent-invitations',{purpose:'CLAIM',targetPersonId:f.personId,scopeId:f.scopeId,exposureFields:['displayName']}),200).resourceId;
 const issue=ok(await f.owner.raw('POST','/talent-invitations/'+inv+'/issue',{expectedRevision:1}),200),token=new URLSearchParams(new URL(issue.url).hash.slice(1)).get('t');
 const context=ok(await f.a.client.raw('POST','/portal/invitations/exchange',{invitationId:inv,token},{'x-once-portal':'1'}),200).contextId;
 const claim=ok(await f.a.client.raw('POST','/portal/claims',{contextId:context,relation:'SELF',applicantKey:'SELF',adultDeclared:true},{'x-once-talent-account':f.a.accountId,'idempotency-key':randomUUID()}),200).resourceId;
 const list=(view:string)=>f.owner.raw('POST','/review/search',{view,kind:'CLAIM',page:1,pageSize:20}),detail=()=>f.owner.raw('GET','/review/CLAIM/'+claim);
 assert.equal(ok(await list('TODO'),200).items[0].state,'PENDING');assert.equal(ok(await detail(),200).canApprove,true);
 if(state==='EXPIRED'){f.clock.advance(31*86400000);ok(await f.owner.login(),200);}else ok(await f.owner.cmd('POST','/talent-invitations/'+inv+'/revoke',{expectedRevision:issue.revision}),200);
 assert.equal(ok(await list('TODO'),200).total,0);const closed=ok(await list('DONE'),200);assert.equal(closed.total,1);assert.equal(closed.items[0].state,state);
 const unavailable=ok(await detail(),200);assert.equal(unavailable.state,state);assert.equal(unavailable.canApprove,false);assert.equal(unavailable.canReject,true);
 const before=f.store.rows('talentClaims')[0]!,grants=f.store.rows('talentAccessGrants').length;
 assert.equal((await f.owner.cmd('POST','/talent-claims/'+claim+'/decide',{expectedRevision:before.revision,decision:'APPROVE',ownershipBasis:'合成已失效申请不得批准',guardianConfirmed:false})).status,409);
 assert.equal(f.store.rows('talentAccessGrants').length,grants);assert.deepEqual(f.store.rows('talentClaims')[0],before);
 ok(await f.owner.cmd('POST','/talent-claims/'+claim+'/decide',{expectedRevision:before.revision,decision:'REJECT',ownershipBasis:'明确拒绝合成失效申请',guardianConfirmed:false}),200);
 const rejected=ok(await detail(),200);assert.equal(rejected.state,'REJECTED');assert.equal(rejected.canApprove,false);assert.equal(rejected.canReject,false);assert.equal(ok(await list('DONE'),200).items[0].state,'REJECTED');
});
