import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseTable,mapTable,initialMapping} from '../../apps/admin-web/src/table-import-parser.ts';
import {toggleReviewGroup} from '../../apps/admin-web/src/review-selection.ts';
const catalog=[{namespace:'role',code:'model',labelZh:'模特',status:'ACTIVE'},{namespace:'role',code:'actor',labelZh:'演员',status:'ACTIVE'},{namespace:'city',code:'shenzhen',labelZh:'深圳',status:'ACTIVE'}] as any;
test('table import handles quoted delimiters, BOM, escaped quotes, embedded newlines and exact mappings',()=>{const t=parseTable('\uFEFF姓名,职业,城市\r\n"林,禾",模特,深圳\r\n"王""晨\n二",演员,深圳');assert.deepEqual(t.rows,[['林,禾','模特','深圳'],['王"晨\n二','演员','深圳']]);const rows=mapTable(t,initialMapping(t.headers),catalog);assert.equal(rows[0]!.roles[0],'model');assert.equal(rows[0]!.cityCode,'shenzhen');assert.deepEqual(rows[0]!.issues,[]);const tab=parseTable('姓名\t职业\n林禾\t模特、演员');assert.deepEqual(mapTable(tab,initialMapping(tab.headers),catalog)[0]!.roles,['model','actor']);assert.equal(parseTable('"姓名\t备注",职业\n林禾,模特').headers[0],'姓名\t备注');});
test('table import preserves unknown and duplicate facts for correction without guessing or merging',()=>{const t=parseTable('姓名,职业,城市,类型\n林禾,网红模特,深圳市,人才\n林禾,模特,深圳,人才\n联系人,演员,深圳,普通联系人'),rows=mapTable(t,initialMapping(t.headers),catalog);assert.equal(rows[0]!.roles[0],'网红模特');assert.equal(rows[0]!.cityCode,'深圳市');assert.ok(rows[0]!.issues.some(s=>s.includes('同名')));assert.ok(rows[0]!.issues.some(s=>s.includes('职业无法对应')));assert.ok(rows[2]!.issues.some(s=>s.includes('只导入姓名')));assert.throws(()=>mapTable(t,{...initialMapping(t.headers),roles:'0'},catalog),/同时/);assert.throws(()=>mapTable(t,{...initialMapping(t.headers),roles:'99'},catalog),/失效/);});
test('table import rejects oversized batches and invalid table structure with actionable errors',()=>{for(const input of ['姓名,姓名\na,b','姓名,职业\n林禾','姓名,职业\n"林禾,模特','姓名,职业\n"林禾"xx,模特'])assert.throws(()=>parseTable(input));assert.throws(()=>parseTable('姓名\n'+Array(101).fill('林禾').join('\n')),/100行/);assert.throws(()=>parseTable('a'.repeat(262145)),/256KB/);});
test('review group selection closes transitive dependencies and deselection removes dependent groups',()=>{const items=[{clientItemKey:'name',dependencyGroup:'identity',dependsOn:[]},{clientItemKey:'intro',dependencyGroup:'identity',dependsOn:[]},{clientItemKey:'media',dependencyGroup:'media',dependsOn:['name']},{clientItemKey:'work',dependencyGroup:'work',dependsOn:['media']}];const selected=toggleReviewGroup(items,[],'work',true);assert.deepEqual(new Set(selected),new Set(['name','intro','media','work']));assert.deepEqual(toggleReviewGroup(items,selected,'name',false),[]);assert.deepEqual(new Set(toggleReviewGroup(items,selected,'media',false)),new Set(['name','intro']));});
