import test from 'node:test';
import {MemoryStore} from '../support/memory-store.ts';
import {agentMediaScenario,agentMediaFenceScenario} from '../support/agent-media.ts';
test('MACHINE upload ownership, atomic adoption and formal authorization transition',async()=>{await agentMediaScenario(new MemoryStore());});
for(const change of ['quota','missing','permission','scope','scopeRevision','revoke','maintainer','disable','recovery','withdraw'])test('MACHINE upload fencing '+change,async()=>{await agentMediaFenceScenario(new MemoryStore(),change);});
import {agentMediaRetentionScenario} from '../support/agent-media.ts';
for(const mode of ['draft1','draft30','withdraw','reject','partial','adopted'])test('MACHINE retention/purge '+mode,async()=>{await agentMediaRetentionScenario(new MemoryStore(),mode);});
import assert from 'node:assert/strict';
import {agentMediaFixture,sampleHash} from '../support/agent-media.ts';
import {loadAgentMediaAdmission,AGENT_MEDIA_ENV} from '../../apps/api/src/media/agent-admission-config.ts';
import {AGENT_MEDIA_CEILINGS} from '../../packages/core/src/agent-media.ts';
test('MACHINE quota env is complete, independently bounded and never implicit',()=>{assert.equal(loadAgentMediaAdmission({}),undefined);assert.throws(()=>loadAgentMediaAdmission({AGENT_MEDIA_SUBMISSION_FILES:'10'}));const env=Object.fromEntries(Object.entries(AGENT_MEDIA_ENV).map(([k,v])=>[v,String(AGENT_MEDIA_CEILINGS[k as keyof typeof AGENT_MEDIA_CEILINGS])]));assert.deepEqual(loadAgentMediaAdmission(env),AGENT_MEDIA_CEILINGS);for(const bad of ['0','NaN','1.2','101'])assert.throws(()=>loadAgentMediaAdmission({...env,AGENT_MEDIA_HOURLY_UPLOADS:bad}));});
test('MACHINE receive authorization is one-time, expiring and bytes-bound',async()=>{const f=await agentMediaFixture(new MemoryStore()),s=await f.draft(),u=await f.create(s,'nonce'),actor=await f.actor(),auth=await f.authorize(u.resourceId);await assert.rejects(f.store.transaction(tx=>f.app.media.beginReceive(tx,actor,u.resourceId,101,auth.receiveToken)));await assert.rejects(f.store.transaction(tx=>f.app.media.beginReceive(tx,actor,u.resourceId,100,'a'.repeat(43))));f.clock.advance(61000);await assert.rejects(f.store.transaction(tx=>f.app.media.beginReceive(tx,actor,u.resourceId,100,auth.receiveToken)));const renewed=await f.authorize(u.resourceId),received=await f.store.transaction(tx=>f.app.media.beginReceive(tx,actor,u.resourceId,100,renewed.receiveToken));await assert.rejects(f.store.transaction(tx=>f.app.media.beginReceive(tx,actor,u.resourceId,100,renewed.receiveToken)));await assert.rejects(f.store.transaction(tx=>f.app.media.finishReceive(tx,actor,u.resourceId,received.receiveToken!,100,'0'.repeat(64))));await f.store.transaction(tx=>f.app.media.finishReceive(tx,actor,u.resourceId,received.receiveToken!,100,sampleHash));});
test('MACHINE text+media review uses one measurement report timestamp on an advancing real clock',async()=>{const f=await agentMediaFixture(new MemoryStore()),s=await f.draft(),id=await f.ready(s,'timed');await f.submit(s);const input=await f.review(s);const original=f.clock.now.bind(f.clock);f.clock.now=()=>{f.clock.advance(1);return original();};await f.expect(f.owner.cmd('POST','/ingestion-review/submissions/'+s+'/review',input));const row=(await f.store.transaction(tx=>tx.find('measurementSets')))[0]!;assert.equal(row.reportedAt,row.createdAt);assert.equal(row.createdAt,row.updatedAt);assert.equal(row.measuredOn,null);assert.equal((await f.store.transaction(tx=>tx.get('assets',id)))!.usageState,'ADOPTED');});
import {agentMediaMergeScenario} from '../support/agent-media.ts';
test('MACHINE media actual merge keeps STAGED unbound and moves only formal relationships',async()=>{await agentMediaMergeScenario(new MemoryStore());});

import {agentMediaDeletionScenario} from '../support/agent-media.ts';
test('MACHINE media Person deletion blocks staged and formal bytes without premature capacity release',async()=>{await agentMediaDeletionScenario(new MemoryStore());});
