import test from 'node:test';
import assert from 'node:assert/strict';
import {MemoryStore} from '../support/memory-store.ts';
import {stagingFixture,unitReady} from '../support/media-staging.ts';
import {MediaPurgeWorker} from '../../apps/api/src/media/purge-worker.ts';
import {PURGE_LIMITS} from '../../packages/core/src/media-purge-model.ts';
async function setup(){const store=new MemoryStore(),f=await stagingFixture(store),id=await unitReady(f);f.app.config.dataCleanupMode='INTERNAL_APPROVED';return {...f,id,store};}
async function due(f:Awaited<ReturnType<typeof setup>>){const r=f.store.rows('personMedia')[0]!;f.clock.advance(Date.parse(r.retainUntil!)-f.clock.now().getTime());}
test('PR03E exact deadline, independent READY lifecycle and physical confirmation quota',async()=>{const f=await setup(),r=f.store.rows('personMedia')[0]!;f.clock.advance(Date.parse(r.retainUntil!)-f.clock.now().getTime()-1);assert.equal(await f.app.mediaPurge.claim(),null);f.clock.advance(1);const c=await f.app.mediaPurge.claim();assert.ok(c);assert.equal(f.store.rows('assets')[0]!.state,'READY');await f.app.mediaPurge.beginDelete(c);assert.equal(f.store.rows('assets')[0]!.usageState,'RETIRED');assert.equal(f.store.rows('uploads')[0]!.purgedAt,null);await f.app.mediaPurge.objectResult(c,'original','MISSING');await f.app.mediaPurge.objectResult(c,'preview','UNKNOWN');await assert.rejects(f.app.mediaPurge.finalize(c));assert.equal(f.store.rows('uploads')[0]!.expectedBytes,100);await f.app.mediaPurge.objectResult(c,'preview','MISSING');await f.app.mediaPurge.finalize(c);assert.equal(f.store.rows('uploads')[0]!.expectedBytes,0);assert.ok(f.store.rows('uploads')[0]!.purgedAt);assert.equal(f.store.rows('assets')[0]!.state,'ERASED');assert.equal(await f.app.mediaPurge.claim(),null);});
test('PR03E two owners, crash lease fencing and UNKNOWN reconciliation',async()=>{const f=await setup();await due(f);const claims=await Promise.all([f.app.mediaPurge.claim(),f.app.mediaPurge.claim()]);assert.equal(claims.filter(Boolean).length,1);const old=claims.find(Boolean)!;await f.app.mediaPurge.beginDelete(old);await f.app.mediaPurge.objectResult(old,'original','UNKNOWN');f.clock.advance(PURGE_LIMITS.leaseMs);const c=await f.app.mediaPurge.claim();assert.ok(c);await assert.rejects(f.app.mediaPurge.finalize(old));const objects=new Set(['original','preview']),calls:string[]=[];const worker=new MediaPurgeWorker(f.app,{purgeOwnedNamespace:async()=>{},statPurgeObject:async r=>objects.has(r.part)?'EXISTS':'MISSING',deleteImmutableObject:async r=>{calls.push(r.part);objects.delete(r.part);}});await worker.process(c,new AbortController().signal);assert.deepEqual(calls,['original','preview']);assert.equal(f.store.rows('mediaPurgeIntents')[0]!.state,'ERASED');});
test('PR03E confirmed deletion with audit rollback stays unreadable and retains quota until retry',async()=>{const f=await setup();await due(f);const c=(await f.app.mediaPurge.claim())!;await f.app.mediaPurge.beginDelete(c);await f.app.mediaPurge.objectResult(c,'original','MISSING');await f.app.mediaPurge.objectResult(c,'preview','MISSING');f.store.failNextAudit=true;await assert.rejects(f.app.mediaPurge.finalize(c));assert.equal(f.store.rows('assets')[0]!.usageState,'RETIRED');assert.equal(f.store.rows('uploads')[0]!.purgedAt,null);await f.app.mediaPurge.finalize(c);assert.equal(f.store.rows('assets')[0]!.state,'ERASED');});
test('PR03E DELETE timeout preserves UNKNOWN and backoff; next HEAD missing finalizes',async()=>{const f=await setup();await due(f);const objects=new Set(['original','preview']);const worker=new MediaPurgeWorker(f.app,{purgeOwnedNamespace:async()=>{},statPurgeObject:async r=>objects.has(r.part)?'EXISTS':'MISSING',deleteImmutableObject:async r=>{objects.delete(r.part);throw new Error('network unknown');}});await worker.cycle(new AbortController().signal,true);assert.equal(f.store.rows('mediaPurgeIntents')[0]!.state,'DELETE_UNKNOWN');assert.equal(f.store.rows('uploads')[0]!.expectedBytes,100);assert.equal(await f.app.mediaPurge.claim(),null);f.clock.advance(PURGE_LIMITS.retryMs);await worker.cycle(new AbortController().signal,true);assert.equal(f.store.rows('assets')[0]!.state,'ERASED');});
import {purgeRaceScenario,purgeLifecycleScenario} from '../support/media-purge.ts';
for(const first of [true,false])test('PR03E real review command vs purge '+first,async()=>{await purgeRaceScenario(new MemoryStore(),first);});
test('PR03E full withdrawal lifecycle',async()=>{await purgeLifecycleScenario(new MemoryStore());});
import {loadMediaRetention} from '../../packages/core/src/media-retention.ts';
import {syncMediaRetention} from '../../packages/core/src/media-adoption.ts';
import {formalMediaDependency,assertMediaNotPurging} from '../../packages/core/src/media-purge.ts';
test('PR03E retention config can only tighten',()=>{assert.deepEqual(loadMediaRetention({}),{draft:90,submitted:180,decided:30,withdrawn:7});assert.equal(loadMediaRetention({MEDIA_RETENTION_DRAFT_DAYS:'1'}).draft,1);for(const v of ['91','0','Infinity','-1','1.5',''])assert.throws(()=>loadMediaRetention({MEDIA_RETENTION_DRAFT_DAYS:v}));});
for(const state of ['DRAFT','SUBMITTED','REJECTED','PARTIALLY_APPROVED','APPROVED','WITHDRAWN','EXPIRED'])test('PR03E retention '+state,async()=>{const f=await setup(),days=state==='DRAFT'?90:state==='SUBMITTED'?180:state==='WITHDRAWN'?7:state==='EXPIRED'?0:30;await f.store.transaction(async tx=>{const s=(await tx.get('talentSubmissions',f.submissionId))!;const n={...s,state,expiresAt:new Date(f.clock.now().getTime()+days*86400000).toISOString()};await tx.replace('talentSubmissions',n);await syncMediaRetention(tx,n,f.clock);});if(days){f.clock.advance(days*86400000-1);assert.equal(await f.app.mediaPurge.claim(),null);f.clock.advance(1);}assert.ok(await f.app.mediaPurge.claim());});
test('PR03E formal source or any placement prevents purge even after usage retirement',async()=>{const f=await setup();await due(f);const original=f.store.rows('assets')[0]!;for(const table of ['workAssets','mediaCollectionItems','shortlistItemAssets'] as const){await f.store.transaction(async tx=>{await tx.insert(table,{id:crypto.randomUUID(),workspaceId:original.workspaceId,assetId:f.id} as any);assert.equal(await formalMediaDependency(tx,original),true);});assert.equal(await f.app.mediaPurge.claim(),null);await f.store.transaction(async tx=>{for(const r of await tx.find(table,{assetId:f.id}))await tx.remove(table,r.id);});}await f.store.transaction(async tx=>{const r=(await tx.find('personMedia',{assetId:f.id}))[0]!;await tx.replace('personMedia',{...r,sourceId:f.sourceId,usageState:'RETIRED'});});assert.equal(await f.app.mediaPurge.claim(),null);});
test('PR03E cleanup fence, recovery epoch and data gates',async()=>{const f=await setup();await due(f);const c=(await f.app.mediaPurge.claim())!;await f.store.transaction(tx=>assertMediaNotPurging(tx,f.id));await f.app.mediaPurge.beginDelete(c);await assert.rejects(f.store.transaction(tx=>assertMediaNotPurging(tx,f.id)));f.app.config.recoveryEpoch='different-recovery-epoch';await assert.rejects(f.app.mediaPurge.heartbeat(c));f.app.config.dataCleanupMode='DISABLED';assert.equal(await f.app.mediaPurge.claim(),null);});
test('PR03E maintenance status and reconciliation require internal maintenance permission',async()=>{const f=await setup();assert.equal((await f.a.client.raw('POST','/media-purge/reconcile',{},f.headers())).status,403);const owner=await f.store.transaction(tx=>f.app.identity.authenticate(tx,f.owner.jar.once_session!));await assert.rejects(f.store.transaction(tx=>f.app.mediaPurge.overview(tx,{...owner,role:'EDITOR',permissions:['records.read']})));const before=await f.expect(f.owner.raw('GET','/media-purge/status'));assert.equal(before.pending,0);const key=crypto.randomUUID(),first=await f.expect(f.owner.cmd('POST','/media-purge/reconcile',{},key)),again=await f.expect(f.owner.cmd('POST','/media-purge/reconcile',{},key));assert.equal(first.operationId,again.operationId);assert.equal(again.replayed,true);});

import {purgeRollbackScenario} from '../support/media-purge.ts';
test('PR03E final-audit-fault recovery contract',async()=>{await purgeRollbackScenario(new MemoryStore());});

import {purgeDeletionScenario} from '../support/media-purge.ts';
for(const ttlFirst of [true,false])test('PR03E explicit deletion competition '+ttlFirst,async()=>{await purgeDeletionScenario(new MemoryStore(),ttlFirst);});

import {purgeBatchScenario} from '../support/media-purge.ts';
test('PR03E bounded scheduler with transient dependencies',async()=>{await purgeBatchScenario(new MemoryStore());});

import {purgeDecisionScenario} from '../support/media-purge.ts';
for(const partial of [true,false])test('PR03E actual decision retention '+partial,async()=>{await purgeDecisionScenario(new MemoryStore(),partial);});
test('PR03E write-ahead failure never starts DELETE or claims confirmation',async()=>{const f=await setup();await due(f);const c=(await f.app.mediaPurge.claim())!;let io=0;await new MediaPurgeWorker(f.app,{purgeOwnedNamespace:async()=>{io++;},statPurgeObject:async()=>{io++;return 'MISSING';},deleteImmutableObject:async()=>{io++;}},{writeAhead:async()=>{throw new Error('journal offline');},committed:async()=>{throw new Error('not committed');},aborted:async()=>{throw new Error('not aborted');}}).process(c,new AbortController().signal);assert.equal(io,0);assert.equal(f.store.rows('mediaPurgeIntents')[0]!.state,'CLAIMED');assert.equal(f.store.rows('assets')[0]!.usageState,'STAGED');});
