import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { fixture, member, createPerson, result, Client } from '../support/fixtures.ts';
import { MEDIA_LIMITS as L } from '../../packages/core/src/media-model.ts';
import { assetFor } from '../../packages/core/src/media.ts';
import type { Actor } from '../../packages/core/src/model.ts';
import type { Tx } from '../../packages/core/src/store.ts';
const hash = 'a'.repeat(64), previewHash = 'b'.repeat(64);
async function setup() { const f = await fixture(); f.app.config.mediaEnabled = true; return f; }
type F = Awaited<ReturnType<typeof setup>>;
async function as<T>(f: F, c: Client, fn: (tx: Tx, a: Actor) => Promise<T>) { return f.store.transaction(async (tx) => fn(tx, await f.app.identity.authenticate(tx, c.jar.once_session!))); }
async function make(f: F, c = f.owner) {
    const p = await createPerson(c, '图片合成人才', true);
    const person = f.store.rows('people').find(r => r.id === p)!;
    const s = f.store.rows('sources').find(r => r.id === person.sourceId)!;
    const input = { sourceId: s.id, expectedSourceRevision: s.revision, personId: p, fileName: 'synthetic.png', mime: 'image/png', expectedBytes: 12, sha256: hash };
    const created = await c.cmd('POST', '/uploads', input);
    assert.equal(created.status, 201, JSON.stringify(created.body));
    return { input, id: result(created).resourceId as string, p, s };
}
async function receive(f: F, id: string, c = f.owner) { const u = await as(f, c, (tx, a) => f.app.media.beginReceive(tx, a, id, 12)); await as(f, c, (tx, a) => f.app.media.finishReceive(tx, a, id, u.receiveToken!, 12, hash)); }
async function queue(f: F, id: string, c = f.owner) { await receive(f, id, c); const u = f.store.rows('uploads').find(u => u.id === id)!; const r = await c.cmd('POST', '/uploads/' + id + '/complete', { expectedRevision: u.revision }); assert.equal(r.status, 202, JSON.stringify(r.body)); }
async function ready(f: F, id: string, c = f.owner) { await queue(f, id, c); const claim = (await f.app.media.claim())!; assert.equal(claim.id, id); await f.app.media.finish(claim, { mime: 'image/png', sha256: hash, bytes: 12, width: 4, height: 3, previewBytes: 20, previewHash }); return claim; }
const rejectsCode = (code: string) => (e: unknown) => !!e && typeof e === 'object' && 'code' in e && e.code === code;
test('M1 disabled provider rejects creation; no hidden memory storage', async () => { const f = await setup(); f.app.config.mediaEnabled = false; const r = await f.owner.cmd('POST', '/uploads', { sourceId: randomUUID(), expectedSourceRevision: 1, fileName: 'x.png', mime: 'image/png', expectedBytes: 12, sha256: hash }); assert.equal(r.status, 503); assert.equal(f.store.rows('uploads').length, 0); });
test('M1 upload create same-key replay consumes one reservation and minimal receipts', async () => { const f = await setup(), m = await make(f), key = randomUUID(); const a = await f.owner.cmd('POST', '/uploads', m.input, key), b = await f.owner.cmd('POST', '/uploads', m.input, key); assert.equal(a.status, 201); assert.equal(b.status, 201); assert.equal(result(a).resourceId, result(b).resourceId); assert.equal(f.store.rows('uploads').length, 2); assert.ok(!JSON.stringify(b.body).includes(hash)); });
test('M1 strict MIME, filename, size and unknown field input fail without writes', async () => { const f = await setup(), m = await make(f); for (const patch of [{ mime: 'image/svg+xml' }, { expectedBytes: 30000001 }, { fileName: '../x.png' }, { fileName: 'x\u0000.png' }, { originalPublic: true }, { sha256: 'x' }]) {
    const r = await f.owner.cmd('POST', '/uploads', { ...m.input, ...patch });
    assert.equal(r.status, 400, JSON.stringify(r.body));
} assert.equal(f.store.rows('uploads').length, 1); });
test('M1 actor active reservation cap includes expired rows until worker expiry', async () => { const f = await setup(), m = await make(f); assert.equal((await f.owner.cmd('POST', '/uploads', m.input)).status, 201); assert.equal((await f.owner.cmd('POST', '/uploads', m.input)).status, 201); assert.equal((await f.owner.cmd('POST', '/uploads', m.input)).status, 429); f.clock.advance(L.uploadMs + 1); assert.equal((await f.owner.cmd('POST', '/uploads', m.input)).status, 429); await f.app.media.expire(); assert.equal((await f.owner.cmd('POST', '/uploads', m.input)).status, 201); });
test('M1 source CAS and person/source mismatch denied', async () => { const f = await setup(), m = await make(f), n = await make(f); assert.equal((await f.owner.cmd('POST', '/uploads', { ...m.input, expectedSourceRevision: 999 })).status, 409); assert.equal((await f.owner.cmd('POST', '/uploads', { ...m.input, personId: n.p })).status, 422); });
test('M1 private upload metadata and bytes require owning/native scope; administrator is not bypass', async () => { const f = await setup(), editor = await member(f, 'media_owner'), m = await make(f, editor.client); assert.equal((await f.owner.raw('GET', '/uploads/' + m.id)).status, 404); assert.equal((await f.owner.cmd('POST', '/uploads', m.input)).status, 404); await ready(f, m.id, editor.client); assert.equal((await f.owner.raw('GET', '/assets/' + m.id)).status, 404); assert.equal(result(await f.owner.raw('GET', '/assets')).total, 0); });
test('M1 receive is one-shot and cannot overwrite UPLOADED bytes', async () => { const f = await setup(), m = await make(f); await receive(f, m.id); await assert.rejects(as(f, f.owner, (tx, a) => f.app.media.beginReceive(tx, a, m.id, 12)), rejectsCode('UPLOAD_NOT_OPEN')); assert.equal(f.store.rows('uploads')[0]!.state, 'UPLOADED'); });
test('M1 length mismatch does not claim reservation', async () => { const f = await setup(), m = await make(f); await assert.rejects(as(f, f.owner, (tx, a) => f.app.media.beginReceive(tx, a, m.id, 11)), rejectsCode('UPLOAD_SIZE_MISMATCH')); assert.equal(f.store.rows('uploads')[0]!.state, 'OPEN'); });
test('M1 digest mismatch never marks file uploaded', async () => { const f = await setup(), m = await make(f); const u = await as(f, f.owner, (tx, a) => f.app.media.beginReceive(tx, a, m.id, 12)); await assert.rejects(as(f, f.owner, (tx, a) => f.app.media.finishReceive(tx, a, m.id, u.receiveToken!, 12, previewHash)), rejectsCode('UPLOAD_DIGEST_MISMATCH')); assert.equal(f.store.rows('uploads')[0]!.state, 'RECEIVING'); });
test('M1 complete same-key unknown response replays original 202 without a second job', async () => { const f = await setup(), m = await make(f); await receive(f, m.id); const input = { expectedRevision: f.store.rows('uploads')[0]!.revision }, key = randomUUID(); const first = await f.owner.cmd('POST', '/uploads/' + m.id + '/complete', input, key); assert.equal(first.status, 202); const a = await f.app.media.claim(); assert.ok(a); const replay = await f.owner.cmd('POST', '/uploads/' + m.id + '/complete', input, key); assert.equal(replay.status, 202); assert.equal(result(replay).replayed, true); assert.equal(f.store.rows('uploads').length, 1); assert.equal(await f.app.media.claim(), null); });
test('M1 late receive cannot revive cancellation', async () => { const f = await setup(), m = await make(f); const u = await as(f, f.owner, (tx, a) => f.app.media.beginReceive(tx, a, m.id, 12)); assert.equal((await f.owner.cmd('POST', '/uploads/' + m.id + '/cancel', { expectedRevision: u.revision })).status, 200); await assert.rejects(as(f, f.owner, (tx, a) => f.app.media.finishReceive(tx, a, m.id, u.receiveToken!, 12, hash))); assert.equal(f.store.rows('uploads')[0]!.state, 'CANCELLED'); });
test('M1 worker lease replacement denies stale result and gives unique final identity', async () => { const f = await setup(), m = await make(f); await queue(f, m.id); const old = (await f.app.media.claim())!; f.clock.advance(L.leaseMs + 1); const fresh = (await f.app.media.claim())!; assert.notEqual(old.leaseToken, fresh.leaseToken); await assert.rejects(f.app.media.finish(old, { mime: 'image/png', sha256: hash, bytes: 12, width: 1, height: 1, previewBytes: 20, previewHash }), rejectsCode('MEDIA_LEASE_LOST')); await f.app.media.finish(fresh, { mime: 'image/png', sha256: hash, bytes: 12, width: 1, height: 1, previewBytes: 20, previewHash }); assert.equal(f.store.rows('assets').length, 1); assert.equal(f.store.rows('assets')[0]!.objectToken, fresh.leaseToken); });
test('M1 two workers cannot concurrently claim one upload', async () => { const f = await setup(), m = await make(f); await queue(f, m.id); const claims = await Promise.all([f.app.media.claim(), f.app.media.claim()]); assert.equal(claims.filter(Boolean).length, 1); });
test('M1 worker cannot publish after source edits', async () => { const f = await setup(), m = await make(f); await queue(f, m.id); const c = (await f.app.media.claim())!; assert.equal((await f.owner.cmd('PATCH', '/sources/' + m.s.id, { expectedRevision: m.s.revision, title: '已重新整理' })).status, 200); await assert.rejects(f.app.media.finish(c, { mime: 'image/png', sha256: hash, bytes: 12, width: 1, height: 1, previewBytes: 20, previewHash }), rejectsCode('MEDIA_CONTEXT_CHANGED')); assert.equal(f.store.rows('assets').length, 0); });
test('M1 cancel during decode denies publication without removing others', async () => { const f = await setup(), m = await make(f); await queue(f, m.id); const c = (await f.app.media.claim())!; assert.equal((await f.owner.cmd('POST', '/uploads/' + m.id + '/cancel', { expectedRevision: c.revision })).status, 200); await assert.rejects(f.app.media.finish(c, { mime: 'image/png', sha256: hash, bytes: 12, width: 1, height: 1, previewBytes: 20, previewHash })); assert.equal(f.store.rows('assets').length, 0); });
test('M1 preview DTO never exposes storage path, token, original URL or digest', async () => { const f = await setup(), m = await make(f); await ready(f, m.id); const r = await f.owner.raw('GET', '/assets/' + m.id); assert.equal(r.status, 200); assert.deepEqual(Object.keys(result(r)).sort(), ['id', 'sourceId', 'personId', 'fileName', 'mime', 'bytes', 'width', 'height', 'state', 'revision', 'createdAt'].sort()); });
test('M1 quarantine denies next preview but preserves explicit asset state', async () => { const f = await setup(), m = await make(f); await ready(f, m.id); assert.equal((await f.owner.cmd('POST', '/assets/' + m.id + '/quarantine', { expectedRevision: 1 })).status, 200); await assert.rejects(as(f, f.owner, (tx, a) => f.app.media.preview(tx, a, m.id, { requestId: randomUUID(), ip: 'synthetic' })), rejectsCode('NOT_FOUND')); assert.equal(result(await f.owner.raw('GET', '/assets/' + m.id)).state, 'QUARANTINED'); });
test('M1 source suspension hides ready assets immediately', async () => { const f = await setup(), m = await make(f); await ready(f, m.id); const s = f.store.rows('sources').find(s => s.id === m.s.id)!; assert.equal((await f.owner.cmd('POST', '/sources/' + s.id + '/suspend', { expectedRevision: s.revision, reason: '合成暂停' })).status, 200); assert.equal((await f.owner.raw('GET', '/assets/' + m.id)).status, 404); assert.equal(result(await f.owner.raw('GET', '/assets')).total, 0); });
test('M1 renewed OPEN session remains one reservation and caps renewal count', async () => { const f = await setup(), m = await make(f); for (let i = 0; i < 2; i++) {
    const u = f.store.rows('uploads')[0]!;
    assert.equal((await f.owner.cmd('POST', '/uploads/' + m.id + '/renew', { expectedRevision: u.revision })).status, 200);
} assert.equal((await f.owner.cmd('POST', '/uploads/' + m.id + '/renew', { expectedRevision: f.store.rows('uploads')[0]!.revision })).status, 409); assert.equal(f.store.rows('uploads').length, 1); });
test('M1 maintenance or recovery mismatch prevents cleanup and processing', async () => { const f = await setup(), m = await make(f); await f.owner.cmd('POST', '/uploads/' + m.id + '/cancel', { expectedRevision: 1 }); f.clock.advance(L.cleanupMs + 1); f.app.config.accessMode = 'MAINTENANCE'; await assert.rejects(f.app.media.expire(), rejectsCode('MAINTENANCE')); await assert.rejects(f.app.media.purgeAllowed(m.id), rejectsCode('MAINTENANCE')); assert.equal(f.store.rows('uploads')[0]!.purgedAt, null); });
test('M1 only aged failed/cancelled sessions can be purged; READY never eligible', async () => { const f = await setup(), m = await make(f), n = await make(f); await ready(f, m.id); await f.owner.cmd('POST', '/uploads/' + n.id + '/cancel', { expectedRevision: 1 }); await assert.rejects(f.app.media.purgeAllowed(n.id)); f.clock.advance(L.cleanupMs + 1); const due = await f.app.media.expire(); assert.deepEqual(due.map(u => u.id), [n.id]); await f.app.media.purgeAllowed(n.id); await f.app.media.markPurged(n.id); assert.ok(f.store.rows('uploads').find(u => u.id === n.id)!.purgedAt); await assert.rejects(f.app.media.purgeAllowed(m.id)); });
test('M1 failed receive remains bounded and cannot be automatically sent again', async () => { const f = await setup(), m = await make(f); const c = await as(f, f.owner, (tx, a) => f.app.media.beginReceive(tx, a, m.id, 12)); await f.app.media.failReceive(m.id, c.receiveToken!); await f.app.media.failReceive(m.id, c.receiveToken!); assert.equal(f.store.rows('uploads')[0]!.revision, 3); await assert.rejects(as(f, f.owner, (tx, a) => f.app.media.beginReceive(tx, a, m.id, 12))); });
test('M1 accepted basic profile handoff does not grant its media or sources', async () => {
    const f = await setup(), sender = await member(f, 'm1sender'), recipient = await member(f, 'm1recipient'), m = await make(f, sender.client);
    await ready(f, m.id, sender.client);
    const p = f.store.rows('people').find(p => p.id === m.p)!;
    const offered = await sender.client.cmd('POST', '/people/' + m.p + '/handoffs', { recipientId: recipient.id, purpose: 'EDIT', expectedRevision: p.revision, expectedSourceRevision: m.s.revision, expiresAt: new Date(f.clock.now().getTime() + 3600000).toISOString(), acknowledgeLimitedAccess: true });
    assert.equal(offered.status, 201, JSON.stringify(offered.body));
    const id = result(offered).resourceId;
    assert.equal((await recipient.client.cmd('POST', '/handoffs/' + id + '/accept', { expectedRevision: 1 })).status, 200);
    assert.equal((await recipient.client.raw('GET', '/people/' + m.p)).status, 200);
    assert.equal((await recipient.client.raw('GET', '/assets/' + m.id)).status, 404);
    assert.equal((await recipient.client.cmd('POST', '/uploads', m.input)).status, 404);
});
