import test from 'node:test';import assert from 'node:assert/strict';
import {realpath,mkdtemp,mkdir,writeFile,chmod,rm,symlink,stat} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {LocalMediaProvider} from '../../apps/api/src/media/local-provider.ts';import {CosMediaProvider} from '../../apps/api/src/media/cos-provider.ts';
const signal=()=>new AbortController().signal;
async function fixture(){const root=await mkdtemp(join(await realpath(tmpdir()),'once-purge-')),local=await LocalMediaProvider.create(root),bytes=Buffer.from('immutable original'),ref={uploadId:randomUUID(),objectToken:randomUUID(),part:'original' as const,bytes:bytes.length,hash:createHash('sha256').update(bytes).digest('hex')};const dir=local.work(ref.uploadId,ref.objectToken);await mkdir(dir,{recursive:true,mode:0o700});await writeFile(join(dir,'original.bin'),bytes,{mode:0o400});return {root,local,bytes,ref,dir};}
test('PR03E local exact immutable deletion, missing is idempotent',async()=>{const f=await fixture();try{assert.equal(await f.local.statPurgeObject(f.ref,signal()),'EXISTS');await f.local.deleteImmutableObject(f.ref,signal());assert.equal(await f.local.statPurgeObject(f.ref,signal()),'MISSING');await f.local.deleteImmutableObject(f.ref,signal());}finally{await rm(f.root,{recursive:true,force:true});}});
test('PR03E local mismatch, symlink and path escape reject without touching target',async()=>{const f=await fixture();try{await assert.rejects(f.local.deleteImmutableObject({...f.ref,hash:'0'.repeat(64)},signal()));await assert.rejects(f.local.statPurgeObject({...f.ref,uploadId:'../../outside'},signal()));await rm(join(f.dir,'original.bin'));await writeFile(join(f.root,'protected'),f.bytes,{mode:0o400});await symlink(join(f.root,'protected'),join(f.dir,'original.bin'));await assert.rejects(f.local.deleteImmutableObject(f.ref,signal()));assert.equal((await stat(join(f.root,'protected'))).size,f.bytes.length);await rm(f.dir,{recursive:true});await symlink(f.root,f.dir);await assert.rejects(f.local.statPurgeObject(f.ref,signal()));}finally{await rm(f.root,{recursive:true,force:true});}});
for(const mode of ['success','404','unknown','redirect','identity'] as const)test('PR03E controlled COS '+mode,async()=>{const f=await fixture();let exists=true,deleted=0;const cos:any={getBucketAcl:async()=>({ACL:'private'}),getBucketVersioning:async()=>({}),getBucketPolicy:async()=>({Policy:{}}),headObject:async()=>{if(!exists)throw {statusCode:404};return {statusCode:mode==='redirect'?302:200,headers:{'content-length':String(mode==='identity'?999:f.bytes.length)},ETag:'"fixed"'};},getObject:async({Output}:any)=>{Output.write(f.bytes);Output.end();return {statusCode:200};},deleteObject:async()=>{deleted++;exists=false;if(mode==='unknown')throw new Error('timeout result unknown');if(mode==='404')throw {statusCode:404};return {statusCode:204};}};const provider=new CosMediaProvider(f.root,cos,{Bucket:'synthetic-123',Region:'ap-test'},'private');try{if(['redirect','identity'].includes(mode)){await assert.rejects(provider.deleteImmutableObject(f.ref,signal()));assert.equal(deleted,0);}else if(mode==='unknown'){await assert.rejects(provider.deleteImmutableObject(f.ref,signal()));assert.equal(await provider.statPurgeObject(f.ref,signal()),'EXISTS');await provider.deleteImmutableObject(f.ref,signal());assert.equal(await provider.statPurgeObject(f.ref,signal()),'MISSING');assert.equal(deleted,1);}else{await provider.deleteImmutableObject(f.ref,signal());assert.equal(await provider.statPurgeObject(f.ref,signal()),'MISSING');assert.equal(deleted,1);}}finally{await rm(f.root,{recursive:true,force:true});}});
test('PR03E exclusive upload namespace removes bounded abandoned copies but rejects unknown names',async()=>{const f=await fixture();try{await f.local.deleteImmutableObject(f.ref,signal());const abandoned=f.local.work(f.ref.uploadId,randomUUID());await mkdir(abandoned,{mode:0o700});await writeFile(join(abandoned,'original.bin'),f.bytes,{mode:0o400});await writeFile(join(abandoned,'unowned-secret'),f.bytes);await assert.rejects(f.local.purgeOwnedNamespace(f.ref,signal()));assert.equal((await stat(join(abandoned,'original.bin'))).size,f.bytes.length);await rm(join(abandoned,'unowned-secret'));await f.local.purgeOwnedNamespace(f.ref,signal());await assert.rejects(stat(f.local.group(f.ref.uploadId)),{code:'ENOENT'});}finally{await rm(f.root,{recursive:true,force:true});}});
test('PR03E COS exclusive namespace rejects redirect and unknown keys before deletion',async()=>{for(const mode of ['redirect','unknown-key']){const f=await fixture();let deletes=0;await f.local.deleteImmutableObject(f.ref,signal());const sdk:any={getBucketAcl:async()=>({ACL:'private'}),getBucketVersioning:async()=>({}),getBucketPolicy:async()=>({Policy:{}}),getBucket:async()=>({statusCode:mode==='redirect'?302:200,IsTruncated:'false',Contents:mode==='unknown-key'?[{Key:'private/uploads/'+f.ref.uploadId+'/arbitrary-unowned-file'}]:[]}),deleteObject:async()=>{deletes++;return {statusCode:204};}};try{await assert.rejects(new CosMediaProvider(f.root,sdk,{Bucket:'synthetic-123',Region:'ap-test'},'private').purgeOwnedNamespace(f.ref,signal()));assert.equal(deletes,0);}finally{await rm(f.root,{recursive:true,force:true});}}});
