/** WP1 domain/HTTP regression uses MemoryStore, not a database or actual files. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { fixture, member, createPerson, sourceInput, result, Client } from '../support/fixtures.ts';
import { AppError } from '../../packages/core/src/errors.ts';
import { visibleOrNull } from '../../packages/core/src/production-policy.ts';
import { base } from '../../packages/core/src/helpers.ts';
type F = Awaited<ReturnType<typeof fixture>>;
async function ok(p: ReturnType<Client['raw']>, status = 200) { const r = await p; assert.equal(r.status, status, JSON.stringify(r.body)); return result(r); }
async function root(f: F, kind: 'works' | 'projects' = 'works', c = f.owner, more: Record<string, unknown> = {}) { return (await ok(c.cmd('POST', '/' + kind, { title: kind === 'works' ? '合成作品' : '合成项目', inlineSource: sourceInput(c !== f.owner), ...more }), 201)).resourceId as string; }
async function detail(c: Client, path: string) { return ok(c.raw('GET', path)); }
async function mutate(c: Client, path: string, suffix: string, body: Record<string, unknown>) { const r = await detail(c, path); return ok(c.cmd(suffix ? 'POST' : 'PATCH', path + suffix, { expectedRevision: r.revision, ...body })); }
async function image(f: F, c = f.owner, personId?: string) {
    f.app.config.mediaEnabled = true;
    const pid = personId ?? await createPerson(c, '图片资料人才', c !== f.owner), p = f.store.rows('people').find(x => x.id === pid)!, s = f.store.rows('sources').find(x => x.id === p.sourceId)!;
    const hash = 'a'.repeat(64), id = (await ok(c.cmd('POST', '/uploads', { sourceId: s.id, personId: pid, expectedSourceRevision: s.revision, fileName: 'synthetic.png', mime: 'image/png', expectedBytes: 12, sha256: hash }), 201)).resourceId;
    const as = <T>(fn: (tx: any, actor: any) => Promise<T>) => f.store.transaction(async (tx) => fn(tx, await f.app.identity.authenticate(tx, c.jar.once_session!)));
    const u = await as((tx, a) => f.app.media.beginReceive(tx, a, id, 12));
    await as((tx, a) => f.app.media.finishReceive(tx, a, id, u.receiveToken!, 12, hash));
    const current = f.store.rows('uploads').find(x => x.id === id)!;
    await ok(c.cmd('POST', '/uploads/' + id + '/complete', { expectedRevision: current.revision }), 202);
    const claim = (await f.app.media.claim())!;
    assert.equal(claim.id, id);
    await f.app.media.finish(claim, { mime: 'image/png', sha256: hash, bytes: 12, width: 2, height: 3, previewBytes: 10, previewHash: 'b'.repeat(64) });
    return { id: id as string, pid, sourceId: s.id };
}
async function suspend(f: F, id: string) { const s = f.store.rows('sources').find(x => x.id === id)!; return ok(f.owner.cmd('POST', '/sources/' + id + '/suspend', { expectedRevision: s.revision, reason: '合成测试停止使用' })); }
for (const kind of ['works', 'projects'] as const) {
    test('WP1 ' + kind + ' creates source/root/receipt atomically without files or commercial objects', async () => { const f = await fixture(), key = randomUUID(), input = { title: '初稿', inlineSource: sourceInput() }; const a = await ok(f.owner.cmd('POST', '/' + kind, input, key), 201), b = await ok(f.owner.cmd('POST', '/' + kind, input, key), 201); assert.equal(a.resourceId, b.resourceId); assert.equal(b.replayed, true); assert.equal(f.store.rows(kind).length, 1); assert.equal(f.store.rows('sources').length, 1); assert.equal(f.store.rows('assets').length, 0); assert.equal(f.store.rows('people').length, 0); assert.equal(f.store.rows(kind)[0]!.maintainerId, f.membershipId); assert.equal(f.store.rows(kind)[0]!.status, 'DRAFT'); });
    test('WP1 ' + kind + ' private source does not grant administrator or colleagues access, counts or audit identities', async () => { const f = await fixture(), ed = await member(f, 'editor'), id = await root(f, kind, ed.client); assert.equal((await f.owner.raw('GET', '/' + kind + '/' + id)).status, 404); assert.equal((await detail(f.owner, '/' + kind)).total, 0); assert.ok(!(await detail(f.owner, '/audit-events')).items.some((x: any) => x.resourceId === id)); assert.equal((await detail(ed.client, '/' + kind + '/' + id)).maintainerId, ed.id); });
    test('WP1 ' + kind + ' expiry and suspended source block fresh reads and same-key replay', async () => { const f = await fixture(), id = await root(f, kind), path = '/' + kind + '/' + id, key = randomUUID(), body = { expectedRevision: 1, title: '修改标题' }; await ok(f.owner.cmd('PATCH', path, body, key)); await suspend(f, f.store.rows(kind)[0]!.sourceId); assert.equal((await f.owner.raw('GET', path)).status, 404); assert.equal((await f.owner.cmd('PATCH', path, body, key)).status, 404); assert.equal(f.store.rows(kind)[0]!.revision, 2); });
    test('WP1 ' + kind + ' rejects forged owner/scope, invalid root and cross-workspace source', async () => { const f = await fixture(); for (const patch of [{ maintainerId: f.membershipId }, { scopeId: randomUUID() }, { status: 'ACTIVE' }, { title: '  ' }, { sourceId: randomUUID() }]) {
        const r = await f.owner.cmd('POST', '/' + kind, { title: '原始标题', inlineSource: sourceInput(), ...patch });
        assert.ok(r.status >= 400);
    } assert.equal(f.store.rows(kind).length, 0); assert.equal(f.store.rows('sources').length, 0); });
    test('WP1 ' + kind + ' archives are readable but require separate unarchive before editing', async () => { const f = await fixture(), id = await root(f, kind), path = '/' + kind + '/' + id; await mutate(f.owner, path, '', { status: 'ARCHIVED' }); assert.equal((await detail(f.owner, path)).canEdit, false); assert.equal((await f.owner.cmd('PATCH', path, { expectedRevision: 2, title: '不得写入' })).status, 409); assert.equal((await f.owner.cmd('PATCH', path, { expectedRevision: 2, status: 'DRAFT', title: '也不能夹带' })).status, 409); await ok(f.owner.cmd('PATCH', path, { expectedRevision: 2, status: 'DRAFT' })); await mutate(f.owner, path, '', { title: '恢复后编辑' }); });
    test('WP1 ' + kind + ' audit failure rolls back inline source, root and receipt', async () => { const f = await fixture(), before = structuredClone(f.store.data); f.store.failNextAudit = true; assert.equal((await f.owner.cmd('POST', '/' + kind, { title: '不能半成功', inlineSource: sourceInput() })).status, 500); for (const t of ['works', 'projects', 'sources', 'sourceHistory', 'receipts'] as const)
        assert.deepEqual(f.store.data[t], before[t]); });
}
test('WP1 ONCE attribution requires explicit basis; uploader never becomes a credit', async () => { const f = await fixture(); assert.equal((await f.owner.cmd('POST', '/works', { title: '冒充作品', origin: 'ONCE', inlineSource: sourceInput() })).status, 422); const id = await root(f, 'works', f.owner, { origin: 'ONCE', originNote: '合成测试：团队负责拍摄制作' }); assert.deepEqual((await detail(f.owner, '/works/' + id)).credits, []); assert.equal(f.store.rows('projectParticipants').length, 0); });
test('WP1 order/cover updates are whole-work CAS, same-key replay and exact permutations', async () => { const f = await fixture(), id = await root(f), path = '/works/' + id, a = await image(f), b = await image(f); await mutate(f.owner, path, '/assets', { assetId: a.id }); await mutate(f.owner, path, '/assets', { assetId: b.id }); const w = await detail(f.owner, path), ids = w.items.map((e: any) => e.id), key = randomUUID(), body = { expectedRevision: w.revision, entryIds: ids.slice().reverse(), coverEntryId: ids[1] }; await ok(f.owner.cmd('POST', path + '/assets/reorder', body, key)); assert.equal((await ok(f.owner.cmd('POST', path + '/assets/reorder', body, key))).replayed, true); const now = await detail(f.owner, path); assert.equal(now.items[0].asset.id, b.id); assert.equal(now.items[0].isCover, true); assert.equal(now.revision, w.revision + 1); assert.equal((await f.owner.cmd('POST', path + '/assets/reorder', body)).status, 409); for (const entryIds of [[ids[0], ids[0]], [randomUUID(), ids[1]], [ids[0]]])
    assert.equal((await f.owner.cmd('POST', path + '/assets/reorder', { ...body, expectedRevision: now.revision, entryIds })).status, 409); });
test('WP1 cover and child IDs from another work cannot be used, removed or reordered', async () => { const f = await fixture(), a = await root(f), b = await root(f), img = await image(f); await mutate(f.owner, '/works/' + a, '/assets', { assetId: img.id }); await mutate(f.owner, '/works/' + b, '/assets', { assetId: img.id }); const wa = await detail(f.owner, '/works/' + a), wb = await detail(f.owner, '/works/' + b); assert.equal((await f.owner.cmd('POST', '/works/' + a + '/assets/remove', { expectedRevision: wa.revision, entryId: wb.items[0].id })).status, 404); assert.equal((await f.owner.cmd('POST', '/works/' + a + '/assets/reorder', { expectedRevision: wa.revision, entryIds: [wa.items[0].id], coverEntryId: wb.items[0].id })).status, 422); assert.equal(f.store.rows('workAssets').length, 2); });
test('WP1 active work requires usable image; removal clears last cover without deleting asset', async () => { const f = await fixture(), id = await root(f), path = '/works/' + id, img = await image(f); assert.equal((await f.owner.cmd('PATCH', path, { expectedRevision: 1, status: 'ACTIVE' })).status, 422); await mutate(f.owner, path, '/assets', { assetId: img.id }); await mutate(f.owner, path, '', { status: 'ACTIVE' }); const w = await detail(f.owner, path); await mutate(f.owner, path, '/assets/remove', { entryId: w.items[0].id }); assert.equal(f.store.rows('works')[0]!.status, 'DRAFT'); assert.equal(f.store.rows('works')[0]!.coverEntryId, null); assert.equal(f.store.rows('assets').length, 1); });
test('WP1 disabled/missing/foreign assets fail linking without changing the parent', async () => { const f = await fixture(), id = await root(f), img = await image(f), path = '/works/' + id; await ok(f.owner.cmd('POST', '/assets/' + img.id + '/quarantine', { expectedRevision: 1 })); for (const assetId of [img.id, randomUUID()])
    assert.equal((await f.owner.cmd('POST', path + '/assets', { expectedRevision: 1, assetId })).status, 404); assert.equal(f.store.rows('works')[0]!.revision, 1); });
test('WP1 source suspension redacts asset identity while local reference can be removed', async () => { const f = await fixture(), id = await root(f), img = await image(f), path = '/works/' + id; await mutate(f.owner, path, '/assets', { assetId: img.id }); await suspend(f, img.sourceId); const w = await detail(f.owner, path); assert.equal(w.items[0].asset, null); assert.ok(!JSON.stringify(w).includes(img.id)); assert.ok(!JSON.stringify(w).includes('synthetic.png')); await mutate(f.owner, path, '/assets/remove', { entryId: w.items[0].id }); assert.equal(f.store.rows('assets').length, 1); });
test('WP1 multi-role credits have one person, no duplicate pair, no generated participation', async () => { const f = await fixture(), id = await root(f), pid = await createPerson(f.owner), path = '/works/' + id; for (const roleCode of ['photographer', 'editor'])
    await mutate(f.owner, path, '/credits', { personId: pid, roleCode, note: '合成真实贡献说明' }); const w = await detail(f.owner, path); assert.equal(w.credits.length, 2); assert.equal((await f.owner.cmd('POST', path + '/credits', { expectedRevision: w.revision, personId: pid, roleCode: 'editor', note: '' })).status, 409); const prod = await detail(f.owner, '/people/' + pid + '/production'); assert.equal(prod.works.total, 1); assert.equal(prod.actualProjectCount, 0); assert.equal(f.store.rows('projectParticipants').length, 0); });
test('WP1 credit source loss redacts person, role and note; other credentials do not bypass it', async () => { const f = await fixture(), id = await root(f), pid = await createPerson(f.owner), path = '/works/' + id; await mutate(f.owner, path, '/credits', { personId: pid, roleCode: 'model', note: 'PRIVATE_NOTE' }); await suspend(f, f.store.rows('people')[0]!.sourceId); const w = await detail(f.owner, path); assert.deepEqual(w.credits.map((c: any) => ({ person: c.person, roleCode: c.roleCode, note: c.note })), [{ person: null, roleCode: null, note: null }]); assert.ok(!JSON.stringify(w).includes(pid)); assert.ok(!JSON.stringify(w).includes('PRIVATE_NOTE')); });
test('WP1 H1 acceptance does not confer credit, project participation or production-history access', async () => { const f = await fixture(), ed = await member(f, 'sender'), other = await member(f, 'receiver'), pid = await createPerson(ed.client, '私有人才', true), p = f.store.rows('people')[0]!, s = f.store.rows('sources')[0]!; const handoff = await ok(ed.client.cmd('POST', '/people/' + pid + '/handoffs', { recipientId: other.id, purpose: 'EDIT', expectedRevision: p.revision, expectedSourceRevision: s.revision, expiresAt: new Date(f.clock.now().getTime() + 3600000).toISOString(), acknowledgeLimitedAccess: true }), 201); await ok(other.client.cmd('POST', '/handoffs/' + handoff.resourceId + '/accept', { expectedRevision: 1 })); assert.equal((await other.client.raw('GET', '/people/' + pid)).status, 200); const work = await root(f, 'works', other.client), project = await root(f, 'projects', other.client); assert.equal((await other.client.raw('GET', '/people/' + pid + '/production')).status, 404); assert.equal((await other.client.cmd('POST', '/works/' + work + '/credits', { expectedRevision: 1, personId: pid, roleCode: 'model', note: '' })).status, 404); assert.equal((await other.client.cmd('POST', '/projects/' + project + '/participants', { expectedRevision: 1, personId: pid, roleCode: 'model', state: 'NOMINATED', note: '' })).status, 404); });
test('WP1 only ACTUAL contributes to distinct visible project count, with correctable facts', async () => { const f = await fixture(), id = await root(f, 'projects'), path = '/projects/' + id, pid = await createPerson(f.owner); await mutate(f.owner, path, '/participants', { personId: pid, roleCode: 'photographer', state: 'NOMINATED', note: '' }); let p = await detail(f.owner, path); for (const state of ['CONFIRMED', 'ACTUAL']) {
    await mutate(f.owner, path, '/participants/update', { entryId: p.participants[0].id, state, note: '合成拍摄于现场已实际完成' });
    assert.equal((await detail(f.owner, '/people/' + pid + '/production')).actualProjectCount, state === 'ACTUAL' ? 1 : 0);
} await mutate(f.owner, path, '/participants', { personId: pid, roleCode: 'editor', state: 'ACTUAL', note: '合成剪辑任务已完成' }); assert.equal((await detail(f.owner, '/people/' + pid + '/production')).actualProjectCount, 1); await mutate(f.owner, path, '', { status: 'COMPLETED', reviewNote: '仅内部复盘' }); assert.equal((await detail(f.owner, '/people/' + pid + '/production')).actualProjectCount, 1); p = await detail(f.owner, path); for (const e of p.participants)
    await mutate(f.owner, path, '/participants/update', { entryId: e.id, state: 'NOMINATED', note: '更正错误记录' }); assert.equal((await detail(f.owner, '/people/' + pid + '/production')).actualProjectCount, 0); });
test('WP1 ACTUAL needs evidence note; participant updates reject wrong parent, stale CAS and spoofed IDs', async () => { const f = await fixture(), a = await root(f, 'projects'), b = await root(f, 'projects'), pid = await createPerson(f.owner), path = '/projects/' + a; assert.equal((await f.owner.cmd('POST', path + '/participants', { expectedRevision: 1, personId: pid, roleCode: 'model', state: 'ACTUAL', note: '   ' })).status, 422); await mutate(f.owner, path, '/participants', { personId: pid, roleCode: 'model', state: 'NOMINATED', note: '' }); const entryId = (await detail(f.owner, path)).participants[0].id; assert.equal((await f.owner.cmd('POST', '/projects/' + b + '/participants/update', { expectedRevision: 1, entryId, state: 'ACTUAL', note: '合成已完成拍摄' })).status, 404); assert.equal((await f.owner.cmd('POST', path + '/participants/update', { expectedRevision: 1, entryId, state: 'CONFIRMED', note: '' })).status, 409); assert.equal((await f.owner.cmd('POST', path + '/participants/update', { expectedRevision: 2, entryId, state: 'CONFIRMED', note: '', personId: randomUUID() })).status, 400); });
test('WP1 EXTERNAL delivery/reference changes do not rewrite ownership, attribution or personnel', async () => { const f = await fixture(), w = await root(f, 'works', f.owner, { origin: 'EXTERNAL' }), p = await root(f, 'projects'), path = '/projects/' + p; await mutate(f.owner, path, '/works', { workId: w, relation: 'REFERENCE' }); const entryId = (await detail(f.owner, path)).works[0].id; await mutate(f.owner, path, '/works', { workId: w, relation: 'DELIVERABLE' }); const r = await detail(f.owner, path); assert.equal(r.works.length, 1); assert.equal(r.works[0].id, entryId); assert.equal(r.works[0].work.origin, 'EXTERNAL'); assert.equal(f.store.rows('works')[0]!.revision, 1); assert.equal(f.store.rows('projectParticipants').length, 0); assert.equal(f.store.rows('workCredits').length, 0); assert.equal((await detail(f.owner, '/works/' + w)).projects[0].relation, 'DELIVERABLE'); });
test('WP1 hidden linked works and participants reveal neither identity nor note and can be detached', async () => { const f = await fixture(), w = await root(f), p = await root(f, 'projects'), pid = await createPerson(f.owner), path = '/projects/' + p; await mutate(f.owner, path, '/works', { workId: w, relation: 'REFERENCE' }); await mutate(f.owner, path, '/participants', { personId: pid, roleCode: 'model', state: 'ACTUAL', note: 'PRIVATE_PROJECT_NOTE' }); await suspend(f, f.store.rows('works')[0]!.sourceId); await suspend(f, f.store.rows('people')[0]!.sourceId); const r = await detail(f.owner, path); assert.equal(r.works[0].work, null); assert.equal(r.works[0].relation, null); assert.equal(r.participants[0].person, null); for (const text of [w, pid, 'PRIVATE_PROJECT_NOTE'])
    assert.ok(!JSON.stringify(r).includes(text)); await mutate(f.owner, path, '/works/remove', { entryId: r.works[0].id }); await mutate(f.owner, path, '/participants/remove', { entryId: r.participants[0].id }); assert.equal(f.store.rows('works').length, 1); assert.equal(f.store.rows('people').length, 1); });
test('WP1 inactive dictionary role remains visible but new credit/participant is denied', async () => { const f = await fixture(), w = await root(f), p = await root(f, 'projects'), pid = await createPerson(f.owner); await mutate(f.owner, '/works/' + w, '/credits', { personId: pid, roleCode: 'model', note: '' }); await mutate(f.owner, '/projects/' + p, '/participants', { personId: pid, roleCode: 'model', state: 'NOMINATED', note: '' }); const d = f.store.rows('dictionary').find(d => d.namespace === 'role' && d.code === 'model')!; await ok(f.owner.cmd('PATCH', '/catalog/items/' + d.id, { expectedRevision: d.revision, status: 'INACTIVE' })); const participation = (await detail(f.owner, '/projects/' + p)).participants[0]; await mutate(f.owner, '/projects/' + p, '/participants/update', { entryId: participation.id, state: 'CONFIRMED', note: '旧角色仍可据实更正' }); assert.equal((await detail(f.owner, '/works/' + w)).credits[0].roleCode, 'model'); const p2 = await root(f, 'projects'); assert.equal((await f.owner.cmd('POST', '/projects/' + p2 + '/participants', { expectedRevision: 1, personId: pid, roleCode: 'model', state: 'NOMINATED', note: '' })).status, 422); });
test('WP1 root/child/audit/receipt rollback together on failed credit command then same key succeeds', async () => { const f = await fixture(), w = await root(f), pid = await createPerson(f.owner), key = randomUUID(), body = { expectedRevision: 1, personId: pid, roleCode: 'model', note: '不能半成功' }; const n = f.store.rows('receipts').length; f.store.failNextAudit = true; assert.equal((await f.owner.cmd('POST', '/works/' + w + '/credits', body, key)).status, 500); assert.equal(f.store.rows('workCredits').length, 0); assert.equal(f.store.rows('works')[0]!.revision, 1); assert.equal(f.store.rows('receipts').length, n); await ok(f.owner.cmd('POST', '/works/' + w + '/credits', body, key)); assert.equal(f.store.rows('workCredits').length, 1); });
test('WP1 viewer cannot mutate visible root, and current permissions apply before replay', async () => { const f = await fixture(), v = await member(f, 'viewer', 'VIEWER'), w = await root(f); await detail(v.client, '/works/' + w); assert.equal((await v.client.cmd('PATCH', '/works/' + w, { expectedRevision: 1, title: '不能改' })).status, 403); });
test('WP1 stable pagination, explicit filters, hidden projects excluded from production count', async () => { const f = await fixture(), ed = await member(f, 'editor'), pid = await createPerson(f.owner), p = await root(f, 'projects', ed.client); await mutate(ed.client, '/projects/' + p, '/participants', { personId: pid, roleCode: 'model', state: 'ACTUAL', note: '合成已实际参加' }); assert.equal((await detail(f.owner, '/people/' + pid + '/production')).actualProjectCount, 0); assert.equal((await detail(ed.client, '/people/' + pid + '/production')).actualProjectCount, 1); for (const path of ['/works?bad=1', '/works?status=WRONG', '/projects?pageSize=101', '/people/' + pid + '/production?hidden=1'])
    assert.equal((await f.owner.raw('GET', path)).status, 400); });
test('WP1 storage failures must not masquerade as redacted dependencies', async () => { await assert.rejects(visibleOrNull(async () => { throw new AppError(503, 'STORE_BUSY', 'synthetic'); }), /synthetic/); assert.equal(await visibleOrNull(async () => { throw new AppError(404, 'NOT_FOUND', 'hidden'); }), null); });
