import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { fixture, member, createPerson, sourceInput, result, type Client } from '../support/fixtures.ts';

type F = Awaited<ReturnType<typeof fixture>>;
async function ok(p: ReturnType<Client['raw']>, status=200){const r=await p;assert.equal(r.status,status,JSON.stringify(r.body));return result(r);}
async function project(f:F,c=f.owner,title='SL1合成项目'){return (await ok(c.cmd('POST','/projects',{title,inlineSource:sourceInput(c!==f.owner)}),201)).resourceId as string;}
async function shortlist(f:F,projectId:string,c=f.owner,title='SL1候选清单'){return (await ok(c.cmd('POST','/shortlists',{projectId,title,brief:'内部选角与制作资源候选'}),201)).resourceId as string;}
async function detail(c:Client,id:string){return ok(c.raw('GET','/shortlists/'+id));}
async function work(f:F,title='SL1参考作品'){return (await ok(f.owner.cmd('POST','/works',{title,origin:'EXTERNAL',originNote:'合成外部作品',inlineSource:sourceInput()}),201)).resourceId as string;}

 test('SL1 shortlist is project-bound internal data and does not create participation', async()=>{const f=await fixture(),pid=await project(f),sid=await shortlist(f,pid);const d=await detail(f.owner,sid);assert.equal(d.project.id,pid);assert.equal(d.status,'DRAFT');assert.deepEqual(d.people,[]);assert.equal(f.store.rows('projectParticipants').length,0);});

test('SL1 people can be added, annotated, prioritized and reordered without becoming ACTUAL', async()=>{const f=await fixture(),pid=await project(f),sid=await shortlist(f,pid),a=await createPerson(f.owner,'候选A'),b=await createPerson(f.owner,'候选B');let d=await detail(f.owner,sid);await ok(f.owner.cmd('POST','/shortlists/'+sid+'/people',{expectedRevision:d.revision,personId:a,groupLabel:'欧美女模',state:'PRIORITY',note:'适合家具生活方式'}));d=await detail(f.owner,sid);await ok(f.owner.cmd('POST','/shortlists/'+sid+'/people',{expectedRevision:d.revision,personId:b,groupLabel:'备选',state:'CANDIDATE',note:''}));d=await detail(f.owner,sid);assert.deepEqual(d.people.map((x:any)=>x.person.displayName),['候选A','候选B']);await ok(f.owner.cmd('POST','/shortlists/'+sid+'/people/reorder',{expectedRevision:d.revision,entryIds:d.people.map((x:any)=>x.id).reverse()}));d=await detail(f.owner,sid);assert.deepEqual(d.people.map((x:any)=>x.person.displayName),['候选B','候选A']);const e=d.people[1];await ok(f.owner.cmd('POST','/shortlists/'+sid+'/people/update',{expectedRevision:d.revision,entryId:e.id,state:'CONTACTED',note:'已内部记录联系进度，不表示档期确认'}));assert.equal(f.store.rows('projectParticipants').length,0);assert.equal((await detail(f.owner,sid)).people[1].state,'CONTACTED');});

test('SL1 same person/work cannot be duplicated and wrong-parent entry cannot be removed', async()=>{const f=await fixture(),pid=await project(f),a=await shortlist(f,pid),b=await shortlist(f,pid),person=await createPerson(f.owner),w=await work(f);let d=await detail(f.owner,a);await ok(f.owner.cmd('POST','/shortlists/'+a+'/people',{expectedRevision:d.revision,personId:person}));d=await detail(f.owner,a);assert.equal((await f.owner.cmd('POST','/shortlists/'+a+'/people',{expectedRevision:d.revision,personId:person})).status,409);await ok(f.owner.cmd('POST','/shortlists/'+a+'/works',{expectedRevision:d.revision,workId:w,note:'风格参考'}));const da=await detail(f.owner,a),db=await detail(f.owner,b);assert.equal((await f.owner.cmd('POST','/shortlists/'+b+'/people/remove',{expectedRevision:db.revision,entryId:da.people[0].id})).status,404);assert.equal((await f.owner.cmd('POST','/shortlists/'+a+'/works',{expectedRevision:da.revision,workId:w})).status,409);});

test('SL1 records changedSinceAdded when underlying person changes', async()=>{const f=await fixture(),pid=await project(f),sid=await shortlist(f,pid),person=await createPerson(f.owner,'变更前');let d=await detail(f.owner,sid);await ok(f.owner.cmd('POST','/shortlists/'+sid+'/people',{expectedRevision:d.revision,personId:person}));assert.equal((await detail(f.owner,sid)).people[0].changedSinceAdded,false);const p=result(await f.owner.raw('GET','/people/'+person));await ok(f.owner.cmd('PATCH','/people/'+person,{expectedRevision:p.revision,displayName:'变更后'}));d=await detail(f.owner,sid);assert.equal(d.people[0].person.displayName,'变更后');assert.equal(d.people[0].changedSinceAdded,true);});

test('SL1 hidden candidate becomes a placeholder without leaking identity or note', async()=>{const f=await fixture(),pid=await project(f),sid=await shortlist(f,pid),person=await createPerson(f.owner,'即将隐藏');let d=await detail(f.owner,sid);await ok(f.owner.cmd('POST','/shortlists/'+sid+'/people',{expectedRevision:d.revision,personId:person,note:'敏感候选备注'}));const p=f.store.rows('people').find(x=>x.id===person)!,s=f.store.rows('sources').find(x=>x.id===p.sourceId)!;await ok(f.owner.cmd('POST','/sources/'+s.id+'/suspend',{expectedRevision:s.revision,reason:'合成停止使用'}));d=await detail(f.owner,sid);assert.equal(d.people[0].person,null);assert.equal(d.people[0].note,null);assert.equal(JSON.stringify(d).includes('即将隐藏'),false);assert.equal(JSON.stringify(d).includes('敏感候选备注'),false);});

test('SL1 shortlist visibility follows project scope; admin has no restricted-scope bypass', async()=>{const f=await fixture(),ed=await member(f,'sl-editor'),pid=await project(f,ed.client,'私有项目'),sid=await shortlist(f,pid,ed.client,'私有候选');assert.equal((await f.owner.raw('GET','/shortlists/'+sid)).status,404);assert.equal((await ok(f.owner.raw('GET','/shortlists'))).total,0);assert.equal((await detail(ed.client,sid)).title,'私有候选');});

test('SL1 archive blocks child edits and requires a separate restore command', async()=>{const f=await fixture(),pid=await project(f),sid=await shortlist(f,pid),person=await createPerson(f.owner);let d=await detail(f.owner,sid);await ok(f.owner.cmd('PATCH','/shortlists/'+sid,{expectedRevision:d.revision,status:'ARCHIVED'}));d=await detail(f.owner,sid);assert.equal(d.canEdit,false);assert.equal((await f.owner.cmd('POST','/shortlists/'+sid+'/people',{expectedRevision:d.revision,personId:person})).status,409);assert.equal((await f.owner.cmd('PATCH','/shortlists/'+sid,{expectedRevision:d.revision,status:'DRAFT',title:'夹带修改'})).status,409);await ok(f.owner.cmd('PATCH','/shortlists/'+sid,{expectedRevision:d.revision,status:'DRAFT'}));});

test('SL1 idempotent add replay never creates a second entry', async()=>{const f=await fixture(),pid=await project(f),sid=await shortlist(f,pid),person=await createPerson(f.owner),d=await detail(f.owner,sid),key=randomUUID(),body={expectedRevision:d.revision,personId:person,state:'CANDIDATE' as const};await ok(f.owner.cmd('POST','/shortlists/'+sid+'/people',body,key));const replay=await ok(f.owner.cmd('POST','/shortlists/'+sid+'/people',body,key));assert.equal(replay.replayed,true);assert.equal(f.store.rows('shortlistPeople').length,1);});
