import test from 'node:test';
import {MemoryStore} from '../support/memory-store.ts';
import {verifyTalentMaintenance} from '../support/talent-maintenance.ts';
test('PR02b invitation, grant, account-bound reads, draft, batch review and consent',async()=>{await verifyTalentMaintenance(new MemoryStore());});
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {reviewRollbackScenario} from '../support/talent-maintenance.ts';
import {result} from '../support/fixtures.ts';
import {isolateTalentAuth,inspectTalentAuth} from '../../packages/core/src/talent-auth.ts';
import {revokePersonMaintenance,maintenanceSnapshot} from '../../packages/core/src/talent-maintenance-lifecycle.ts';
test('PR02b review audit rollback, source expiry, revocation and recovery isolation',async()=>{
 const store=new MemoryStore(),{f,grantId,items}=await verifyTalentMaintenance(store);
 const {a,id,headers}=await reviewRollbackScenario(f,grantId,items,async()=>{store.failNextAudit=true;},async()=>{});
 const source=await store.transaction(tx=>tx.get('sources',f.sourceId));assert.ok(source);assert.equal((await f.owner.cmd('POST','/sources/'+source.id+'/suspend',{expectedRevision:source.revision,reason:'合成旧来源暂停'})).status,200);
 const list=await f.owner.raw('GET','/people?q=Anna%20self');assert.equal(list.status,200);assert.ok(result(list).items.some((p:{id:string})=>p.id===f.personId),'old directory uses independent identity evidence when origin unavailable');
 const g=(await store.transaction(tx=>tx.get('talentAccessGrants',grantId)))!;assert.equal((await f.owner.cmd('POST','/talent-grants/'+g.id+'/revoke',{expectedRevision:g.revision})).status,200);
 assert.equal((await a.client.raw('GET','/portal/profiles/'+f.personId,undefined,headers)).status,404);assert.equal((await a.client.raw('GET','/portal/submissions/'+id,undefined,headers)).status,404);
 const workspace=(await store.transaction(tx=>tx.find('workspaces')))[0]!;await store.transaction(tx=>isolateTalentAuth(tx,workspace.id,f.clock));const inspect=await store.transaction(tx=>inspectTalentAuth(tx,workspace.id));assert.deepEqual(inspect.blockers,[]);assert.equal((await a.client.raw('GET','/portal/me')).status,401);
});
test('PR02b lifecycle erases server mirrors and revokes both merge roots without transferring accounts',async()=>{const store=new MemoryStore(),{f}=await verifyTalentMaintenance(store);const workspace=(await store.transaction(tx=>tx.find('workspaces')))[0]!;const people=await store.transaction(tx=>tx.find('people'));await store.transaction(tx=>revokePersonMaintenance(tx,workspace.id,people.map(p=>p.id),f.clock,true));const graph=await store.transaction(tx=>maintenanceSnapshot(tx,workspace.id));assert.ok(graph.data.talentAccessGrants!.every(g=>g.state!=='ACTIVE'));assert.ok(graph.data.talentSubmissionItems!.filter(i=>(i.values as {erased?:boolean}).erased).length>=6);assert.ok(!JSON.stringify(graph.data.talentSubmissionItems!.filter(i=>(i.values as {erased?:boolean}).erased)).includes('Anna self'));});
import {exportMaintenance} from '../support/talent-maintenance.ts';
import {fixture} from '../support/fixtures.ts';
import {JsonRebuild} from '../../packages/core/src/rebuild.ts';
test('PR02b real business export and JSON rebuild preserve purpose provenance without restoring accounts or grants',async()=>{const store=new MemoryStore(),{f}=await verifyTalentMaintenance(store),payload=await exportMaintenance(f);const target=await fixture();target.clock.value=f.clock.value;const rebuild=new JsonRebuild(target.clock),actor=await target.store.transaction(tx=>rebuild.actorFromTarget(tx,'owner'));await target.store.transaction(tx=>rebuild.apply(tx,actor,payload,{requestId:randomUUID(),ip:'test'}));const basis=target.store.rows('sourceUseBases')[0]!;assert.equal(basis.consentId,null);assert.equal(basis.importedBasis!.providerAccountId,f.b.accountId);assert.equal(target.store.rows('talentAccounts').length,0);assert.equal(target.store.rows('talentAccessGrants').length,0);assert.equal(target.store.rows('sources')[0]!.internalUseUntil,basis.validUntil);});
import {maintenanceMergeDelete} from '../support/talent-maintenance.ts';
test('PR02b actual Person merge and deletion include external grants and server mirrors',async()=>{const {f}=await verifyTalentMaintenance(new MemoryStore());await maintenanceMergeDelete(f);});
import {maintenanceReviewBoundaries} from '../support/talent-maintenance.ts';
test('PR02b per-field conflict, partial batch and fork preserve approved facts',async()=>{const {f,grantId}=await verifyTalentMaintenance(new MemoryStore());await maintenanceReviewBoundaries(f,grantId);});
import {maintenanceGuardianBoundaries} from '../support/talent-maintenance.ts';
test('PR02b unknown age and known minors require explicit relationship review',async()=>{const {f}=await verifyTalentMaintenance(new MemoryStore());await maintenanceGuardianBoundaries(f);});
