import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {configuredAuthProvider} from '../../apps/api/src/talent-auth-provider.ts';
import {testAuthConfig,authFixture,challenge,loginTalent} from '../support/talent-auth.ts';
import {MemoryStore} from '../support/memory-store.ts';
import {cleanupTalentAuth,inspectTalentAuth,isolateTalentAuth} from '../../packages/core/src/talent-auth.ts';
import {Client} from '../support/fixtures.ts';
test('HTTP notification gateway distinguishes accepted, delivered and unknown without retry',async()=>{let calls=0,mode='accepted';const server=createServer(async(req,res)=>{calls++;let raw='';for await(const c of req)raw+=c;const input=JSON.parse(raw);if(mode==='reset'){req.socket.destroy();return;}if(mode==='timeout')return;if(mode==='redirect'){res.writeHead(307,{Location:'/again'});res.end();return;}res.setHeader('Content-Type','application/json');res.end(JSON.stringify({requestKey:input.requestKey,state:mode==='delivered'?'DELIVERED':mode==='bad'?'SENT':'ACCEPTED'}));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));try{const config=testAuthConfig();config.endpoint='http://127.0.0.1:'+(server.address() as {port:number}).port;config.timeoutMs=80;const p=configuredAuthProvider(config)!;const input={requestKey:'synthetic-request',kind:'EMAIL' as const,recipient:'synthetic@example.com',code:'135790',expiresAt:new Date().toISOString()};for(const [m,want] of [['accepted','ACCEPTED'],['delivered','DELIVERED'],['bad','UNKNOWN'],['reset','UNKNOWN'],['timeout','UNKNOWN'],['redirect','UNKNOWN']]){mode=m!;const n=calls;assert.equal(await p.send(input),want);assert.equal(calls,n+1);}}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});
test('identity rate cumulative across explicit challenges; workspace and IP ceilings',async()=>{const f=await authFixture(new MemoryStore());const one=await challenge(f,'rate@example.com');for(let i=1;i<5;i++){f.clock.advance(60001);assert.equal((await one.client.raw('POST','/portal/auth/challenges',{contextId:one.input.contextId,purpose:'LOGIN',kind:'EMAIL',identity:'rate@example.com'})).status,200);}f.clock.advance(60001);assert.equal((await one.client.raw('POST','/portal/auth/challenges',{contextId:one.input.contextId,purpose:'LOGIN',kind:'EMAIL',identity:'rate@example.com'})).status,429);
 f.app.config.talentAuth!.ipHourly=5;const c=new Client(f.app);const context=await c.raw('POST','/portal/auth/context',{purpose:'LOGIN'},{'x-once-portal':'1'});c.csrf=(context.body as any).csrfToken;assert.equal((await c.raw('POST','/portal/auth/challenges',{contextId:(context.body as any).contextId,purpose:'LOGIN',kind:'EMAIL',identity:'different@example.com'})).status,429);
 f.app.config.talentAuth!.ipHourly=20;f.app.config.talentAuth!.workspaceDaily=5;assert.equal((await c.raw('POST','/portal/auth/challenges',{contextId:(context.body as any).contextId,purpose:'LOGIN',kind:'EMAIL',identity:'different@example.com'})).status,429);
});
test('expired challenge cleanup removes queued ciphertext and never sends',async()=>{const store=new MemoryStore(),f=await authFixture(store),a=await challenge(f,'cleanup@example.com');const row=store.rows('talentAuthDeliveries')[0]!;await store.transaction(tx=>tx.replace('talentAuthDeliveries',{...row,state:'QUEUED',encryptedPayload:'synthetic-abandoned-encrypted-value'}));const before=f.sent.length;f.clock.advance(600001);await store.transaction(tx=>cleanupTalentAuth(tx,f.clock));assert.equal(store.rows('talentAuthDeliveries')[0]!.encryptedPayload,null);assert.equal(store.rows('talentAuthChallenges')[0]!.codeHash,null);await f.app.portal.auth.dispatch(a.input.challengeId);assert.equal(f.sent.length,before);});
test('account erasure retains only minimal identity tombstone and revokes sessions',async()=>{const store=new MemoryStore(),f=await authFixture(store),a=await loginTalent(f,'erase@example.com');const r=await f.owner.cmd('POST','/talent-accounts/'+a.accountId+'/erase',{expectedRevision:1});assert.equal(r.status,200);assert.equal(store.rows('talentAccounts')[0]!.status,'ERASED');assert.equal(store.rows('talentIdentities')[0]!.encryptedValue,null);assert.equal((await a.client.raw('GET','/portal/me')).status,401);});
test('changed identity lookup key fails closed rather than creating a duplicate account',async()=>{const store=new MemoryStore(),f=await authFixture(store),a=await loginTalent(f,'key@example.com');f.app.config.talentAuth!.identityKey=f.app.config.talentAuth!.codeKey;assert.equal((await a.client.raw('GET','/portal/me')).status,503);const before=store.rows('talentAccounts').length;assert.equal((await new Client(f.app).raw('POST','/portal/auth/context',{purpose:'LOGIN'},{'x-once-portal':'1'})).status,503);assert.equal(store.rows('talentAccounts').length,before);});
test('PHONE challenge verifies into independent talent identity and account',async()=>{const store=new MemoryStore(),f=await authFixture(store),c=await challenge(f,'+8613800000000',undefined,'PHONE');assert.equal(f.sent[0]!.kind,'PHONE');assert.equal((await c.client.raw('POST','/portal/auth/verify',c.input)).status,200);assert.equal(store.rows('talentIdentities')[0]!.kind,'PHONE');assert.equal(store.rows('users').length,1);assert.equal(store.rows('memberships').length,1);});

test('recovery inspection blocks live talent credentials and binds all new state',async()=>{const store=new MemoryStore(),f=await authFixture(store),a=await loginTalent(f,'inspection@example.com');const workspaceId=store.rows('workspaces')[0]!.id;const active=await store.transaction(tx=>inspectTalentAuth(tx,workspaceId));assert.ok(active.blockers.includes('TALENT_SESSION_ACTIVE'));await store.transaction(tx=>isolateTalentAuth(tx,workspaceId,f.clock));const isolated=await store.transaction(tx=>inspectTalentAuth(tx,workspaceId));assert.deepEqual(isolated.blockers,[]);assert.notEqual(active.graphDigest,isolated.graphDigest);assert.ok(!JSON.stringify(isolated).includes(a.token));});
