import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import type {Store} from '../../packages/core/src/store.ts';
import {authFixture} from './talent-auth.ts';
import {result,Client} from './fixtures.ts';
import {candidateItems} from './ingestion.ts';
import {AGENT_MEDIA_CEILINGS} from '../../packages/core/src/agent-media.ts';
import {base} from '../../packages/core/src/helpers.ts';
import {FaultStore} from './fault-store.ts';
import {AppError} from '../../packages/core/src/errors.ts';
import {loadTalentGraph} from '../../packages/core/src/talent-v2-graph.ts';
import {transferFormalAsset} from '../../packages/core/src/media-transfer.ts';
export const samplePreview=Buffer.alloc(50,9),samplePreviewHash=createHash('sha256').update(samplePreview).digest('hex');
export const sampleBytes=Buffer.alloc(100,7),sampleHash=createHash('sha256').update(sampleBytes).digest('hex');
export async function agentMediaFixture(inner:Store){
 const store=new FaultStore(inner),f=await authFixture(store);Object.assign(f.app.config,{ingestionEnabled:true,mediaEnabled:true,agentMediaEnabled:true,agentMediaAdmission:{...AGENT_MEDIA_CEILINGS}});
 const expect=async(p:Promise<any>,status=200)=>{const r=await p;assert.equal(r.status,status,JSON.stringify(r.body));return result(r);};
 const m=(await store.transaction(tx=>tx.find('memberships')))[0]!,w=m.workspaceId;
 const intake=await expect(f.owner.cmd('POST','/scopes',{name:'机器媒体接收',membershipIds:[m.id]}),201),formal=await expect(f.owner.cmd('POST','/scopes',{name:'机器媒体正式范围',membershipIds:[m.id]}),201);
 const permissions=['ingestion.schema.read','ingestion.submit','ingestion.read.own','ingestion.withdraw.own','ingestion.media.upload'];
 const principal=await expect(f.owner.raw('POST','/td2/principals',{schemaVersion:'once-talent-v2.1.0',displayName:'机器媒体合成主体',scopeId:intake.resourceId,defaultMaintainerMembershipId:m.id,permissionCodes:permissions,expiresAt:'2026-11-01T00:00:00.000Z'}),201);let token=principal.token as string;
 const request=(method:string,path:string,body?:unknown,key=randomUUID())=>({method,url:'/api/v1'+path,ip:'192.0.2.44',headers:{authorization:'Bearer '+token,'content-type':'application/json','idempotency-key':key},body:JSON.stringify(body??{})});
 const machine=(method:string,path:string,body?:unknown,key=randomUUID())=>f.app.handle(request(method,path,body,key));
 const actor=()=>f.app.ingestionAuthenticated(request('GET','/ingestion/schema'),'ingestion.read.own',async(_,a)=>a);
 const revision=async(id:string)=>(await store.transaction(tx=>tx.get('talentSubmissions',id)))!.revision;
 const draft=async(name=randomUUID(),target:string|null=null)=>{const d=await expect(machine('POST','/ingestion/submissions',{schemaVersion:'once-talent-experience-v1',externalSubmissionKey:name,proposedPersonId:target,sourceDeclaration:{title:'机器真实媒体',providerClaim:'合成提供者',materialDescription:'受控媒体测试材料'}}));await expect(machine('POST','/ingestion/submissions/'+d.resourceId+'/items',{expectedRevision:1,items:candidateItems}));return d.resourceId as string;};
 const createInput=async(id:string,key=randomUUID(),extra={})=>({context:{kind:'AGENT_SUBMISSION',submissionId:id},expectedSubmissionRevision:await revision(id),clientItemKey:key,roleCandidateKey:'role',fileName:'machine.jpg',mime:'image/jpeg',expectedBytes:100,sha256:sampleHash,...extra});
 const create=async(id:string,key=randomUUID(),extra={})=>expect(machine('POST','/ingestion/uploads',await createInput(id,key,extra)),201);
 const authorize=async(id:string)=>{const u=(await store.transaction(tx=>tx.get('uploads',id)))!;return expect(machine('POST','/ingestion/uploads/'+id+'/receive-authorizations',{expectedRevision:u.revision}));};
 const queue=async(id:string)=>{const auth=await authorize(id),a=await actor(),u=await store.transaction(tx=>f.app.media.beginReceive(tx,a,id,100,auth.receiveToken));await store.transaction(tx=>f.app.media.finishReceive(tx,a,id,u.receiveToken!,100,sampleHash));const n=(await store.transaction(tx=>tx.get('uploads',id)))!;await expect(machine('POST','/ingestion/uploads/'+id+'/complete',{expectedRevision:n.revision}),202);return u;};
 const ready=async(root:string,key=randomUUID())=>{const u=await create(root,key);await queue(u.resourceId);const c=await f.app.media.claim();assert.equal(c?.id,u.resourceId);await f.app.media.finish(c!,{bytes:100,sha256:sampleHash,mime:'image/jpeg',width:10,height:10,previewBytes:50,previewHash:samplePreviewHash});return u.resourceId as string;};
 const submit=async(id:string)=>expect(machine('POST','/ingestion/submissions/'+id+'/submit',{expectedRevision:await revision(id)}));
 const review=async(id:string,keys?:string[],target?:string)=>({expectedRevision:await revision(id),acceptedKeys:keys??(await store.transaction(tx=>tx.find('talentSubmissionItems',{submissionId:id}))).map(i=>i.clientItemKey),decision:keys?.length===0?'REJECT':target?'LINK_EXISTING':'CREATE_NEW',...(keys?.length===0?{}:target?{targetPersonId:target}:{formalScopeId:formal.resourceId}),reviewBasis:'真实合成内部审核来源依据',validUntil:'2026-12-01T00:00:00.000Z',publicReason:'本批审核'});
 return {...f,store,expect,m,w,intake,formal,principal,permissions,request,machine,actor,revision,draft,createInput,create,authorize,queue,ready,submit,review,setToken(t:string){token=t;}};
}
export async function agentMediaScenario(inner:Store){
 const f=await agentMediaFixture(inner),checks:string[]=[],root=await f.draft('new-media'),key=randomUUID(),input=await f.createInput(root,'jpeg'),first=await f.expect(f.machine('POST','/ingestion/uploads',input,key),201),replay=await f.expect(f.machine('POST','/ingestion/uploads',input,key),201);assert.equal(first.resourceId,replay.resourceId);assert.equal((await f.store.transaction(tx=>tx.find('uploads'))).length,1);checks.push('response-lost-original-key-one-upload-one-quota');
 await f.expect(f.machine('POST','/ingestion/uploads',{...input,assetId:randomUUID()}),400);await f.expect(f.machine('POST','/ingestion/uploads',{...input,url:'https://example.invalid/asset'}),400);await f.expect(f.machine('POST','/ingestion/submissions/'+root+'/items',{expectedRevision:await f.revision(root),items:[{clientItemKey:'foreign',kind:'MEDIA',values:{assetId:randomUUID()},dependencyGroup:'foreign',dependsOn:[]}]}),400);checks.push('no-existing-asset-url-or-client-media-reference');
 const rotated=await f.expect(f.owner.raw('POST','/td2/principals/'+f.principal.resourceId+'/rotate',{schemaVersion:'once-talent-v2.1.0',expectedRevision:1}));f.setToken(rotated.token);await f.queue(first.resourceId);const claim=await f.app.media.claim();assert.equal(claim?.id,first.resourceId);await f.app.media.heartbeat(claim!);assert.equal(await f.app.media.claim(),null);await f.app.media.finish(claim!,{bytes:100,sha256:sampleHash,mime:'image/jpeg',width:10,height:10,previewBytes:50,previewHash:samplePreviewHash});checks.push('token-rotation-keeps-upload-lease-and-stable-uploader');
 const id=first.resourceId,a=(await f.store.transaction(tx=>tx.get('assets',id)))!,u=(await f.store.transaction(tx=>tx.get('uploads',id)))!,r=(await f.store.transaction(tx=>tx.find('personMedia',{assetId:id})))[0]!;
 assert.equal(u.actorId,null);assert.equal(u.personId,null);assert.equal(a.personId,null);assert.equal(r.personId,null);assert.equal(r.sourceId,null);assert.equal(a.usageState,'STAGED');const currentActor=await f.actor();await f.store.transaction(tx=>f.app.media.staged(tx,currentActor,id));
 const other=await f.expect(f.owner.raw('POST','/td2/principals',{schemaVersion:'once-talent-v2.1.0',displayName:'其他机器',scopeId:f.intake.resourceId,defaultMaintainerMembershipId:f.m.id,permissionCodes:f.permissions,expiresAt:'2026-11-01T00:00:00.000Z'}),201);const ownActor=await f.actor();await assert.rejects(f.store.transaction(tx=>f.app.media.staged(tx,{...ownActor,servicePrincipalId:other.resourceId},id)));checks.push('new-unbound-machine-upload-staged-owner-isolation');
 const employee=async(name:string,scope:string)=>{const x=await f.expect(f.owner.raw('POST','/memberships',{loginName:name,displayName:name,role:'ADMIN',extraPermissions:[]}),201),c=new Client(f.app);await f.expect(c.activate(x.activationToken));await f.expect(c.login(name));await f.store.transaction(tx=>tx.insert('scopeMembers',{...base(f.w,f.clock),scopeId:scope,membershipId:x.membershipId}));return c;};
 const intake=await employee('machine-intake',f.intake.resourceId),formal=await employee('machine-formal',f.formal.resourceId);
 const readAs=(c:Client)=>f.app.authenticated({method:'GET',url:'/api/v1/talent-staged-assets/'+id+'/preview',ip:'test',headers:{cookie:Object.entries(c.jar).map(([k,v])=>k+'='+v).join('; ')}},'talent.review',(tx,actor)=>f.app.media.staged(tx,actor,id));
 await readAs(intake);await assert.rejects(readAs(formal));await f.expect(f.owner.raw('GET','/assets/'+id),404);assert.ok(!(await f.expect(f.owner.raw('GET','/assets'))).items.some((a:any)=>a.id===id));await assert.rejects(f.store.transaction(tx=>transferFormalAsset(tx,a)));checks.push('intake-required-staged-hidden-from-formal-and-business-export');
 await f.submit(root);await f.expect(f.machine('POST','/ingestion/uploads',await f.createInput(root,'late')),409);
 const body=await f.review(root),snap=()=>f.store.transaction(async tx=>({assets:await tx.find('assets'),relations:await tx.find('personMedia'),sources:await tx.find('sources'),roots:await tx.find('talentSubmissions'),items:await tx.find('talentSubmissionItems'),receipts:await tx.find('receipts'),audits:await tx.find('audits')}));
 for(const failure of ['audits','receipts']){const before=await snap();f.store.afterInsert=(table)=>{if(table===failure)throw new AppError(503,'SYNTHETIC_FAULT','atomic fault');};await f.expect(f.owner.cmd('POST','/ingestion-review/submissions/'+root+'/review',body),503);f.store.afterInsert=null;assert.deepEqual(await snap(),before);}checks.push('text-media-review-audit-and-receipt-fault-atomic');
 const rk=randomUUID();await f.expect(f.owner.cmd('POST','/ingestion-review/submissions/'+root+'/review',body,rk));await f.expect(f.owner.cmd('POST','/ingestion-review/submissions/'+root+'/review',body,rk));const adopted=(await f.store.transaction(tx=>tx.get('assets',id)))!,relation=(await f.store.transaction(tx=>tx.find('personMedia',{assetId:id})))[0]!;assert.equal(adopted.id,a.id);assert.equal(adopted.sha256,a.sha256);assert.equal(adopted.sourceId,null);assert.equal(adopted.usageState,'ADOPTED');assert.ok(relation.personRoleId);assert.equal((await f.store.transaction(tx=>tx.get('uploads',id)))!.servicePrincipalId,u.servicePrincipalId);
 await f.expect(formal.raw('GET','/assets/'+id));await f.expect(intake.raw('GET','/assets/'+id),404);await assert.rejects(f.store.transaction(tx=>f.app.media.staged(tx,ownActor,id)));checks.push('same-asset-role-source-atomic-adoption-formal-scope-replaces-intake');
 const payload=await exportAgentMedia(f,id,relation.personId!,relation.sourceId!);assert.equal(payload.manifest.talent.assets.length,1);assert.equal(payload.manifest.talent.assets[0].relation.origin.servicePrincipalId,u.servicePrincipalId);checks.push('actual-business-export-adopted-only-machine-provenance-no-live-principal');
 const existing=await f.draft('existing-media',relation.personId),eid=await f.ready(existing,'existing-jpeg');assert.equal((await f.store.transaction(tx=>tx.get('assets',eid)))!.personId,null);assert.equal((await f.store.transaction(tx=>tx.find('personMedia',{assetId:eid})))[0]!.personId,null);checks.push('proposed-existing-person-never-prebinds-media');
 const p=(await f.store.transaction(tx=>tx.get('servicePrincipals',f.principal.resourceId)))!;await f.expect(f.owner.cmd('POST','/td2/principals/'+p.id+'/revoke',{schemaVersion:'once-talent-v2.1.0',expectedRevision:p.revision}));await f.expect(formal.raw('GET','/assets/'+id));const source=(await f.store.transaction(tx=>tx.get('sources',relation.sourceId!)))!;await f.expect(f.owner.cmd('POST','/sources/'+source.id+'/suspend',{expectedRevision:source.revision,reason:'内部正式来源依据撤回测试'}));await f.expect(formal.raw('GET','/assets/'+id),404);checks.push('agent-revoke-does-not-revoke-formal-basis-source-withdrawal-does');
 return {f,id,eid,root,checks,payload};
}
export async function agentMediaFenceScenario(inner:Store,change:string){
 const f=await agentMediaFixture(inner),root=await f.draft(),created=await f.create(root,'fenced'),auth=await f.authorize(created.resourceId),actor=await f.actor();
 if(change==='quota'){f.app.config.agentMediaAdmission!.principalRetainedBytes=100;const r=await Promise.all([f.machine('POST','/ingestion/uploads',await f.createInput(root,'q1')),f.machine('POST','/ingestion/uploads',await f.createInput(root,'q2'))]);assert.deepEqual(r.map(r=>r.status),[429,429]);return ['atomic-machine-quota-no-talent-borrow'];}
 if(change==='missing'){f.app.config.agentMediaAdmission=undefined;await f.expect(f.machine('POST','/ingestion/uploads',await f.createInput(root,'q')),503);return ['missing-machine-quota-fail-closed'];}
 await f.store.transaction(tx=>f.app.media.beginReceive(tx,actor,created.resourceId,100,auth.receiveToken));const received=(await f.store.transaction(tx=>tx.get('uploads',created.resourceId)))!;await f.store.transaction(tx=>f.app.media.finishReceive(tx,actor,received.id,received.receiveToken!,100,sampleHash));const done=(await f.store.transaction(tx=>tx.get('uploads',received.id)))!;await f.expect(f.machine('POST','/ingestion/uploads/'+done.id+'/complete',{expectedRevision:done.revision}),202);const lease=await f.app.media.claim();assert.ok(lease);
 if(change==='recovery')f.app.config.recoveryEpoch=randomUUID();else if(change==='scopeRevision')await f.store.transaction(async tx=>{const s=(await tx.get('scopes',f.intake.resourceId))!;await tx.replace('scopes',{...s,revision:s.revision+1});});else if(change==='withdraw')await f.expect(f.machine('POST','/ingestion/submissions/'+root+'/withdraw',{expectedRevision:await f.revision(root)}));else if(change==='disable')await f.store.transaction(async tx=>{const m=(await tx.get('memberships',f.m.id))!,u=(await tx.get('users',m.userId))!;await tx.replace('users',{...u,status:'DISABLED'});});else if(change==='revoke')await f.expect(f.owner.cmd('POST','/td2/principals/'+f.principal.resourceId+'/revoke',{schemaVersion:'once-talent-v2.1.0',expectedRevision:1}));else if(change==='maintainer'){const other=await f.expect(f.owner.raw('POST','/memberships',{loginName:'next-maintainer',displayName:'next-maintainer',role:'ADMIN',extraPermissions:[]}),201);const c=new Client(f.app);await f.expect(c.activate(other.activationToken));await f.store.transaction(tx=>tx.insert('scopeMembers',{...base(f.w,f.clock),scopeId:f.intake.resourceId,membershipId:other.membershipId}));await f.expect(f.owner.cmd('POST','/td2/principals/'+f.principal.resourceId+'/authorization',{expectedRevision:1,scopeId:f.intake.resourceId,defaultMaintainerMembershipId:other.membershipId,permissionCodes:f.permissions}));}else await f.expect(f.owner.cmd('POST','/td2/principals/'+f.principal.resourceId+'/authorization',{expectedRevision:1,scopeId:change==='scope'?f.formal.resourceId:f.intake.resourceId,defaultMaintainerMembershipId:f.m.id,permissionCodes:change==='permission'?['ingestion.read.own']:f.permissions}));
 await assert.rejects(f.app.media.heartbeat(lease!));await assert.rejects(f.app.media.finish(lease!,{bytes:100,sha256:sampleHash,mime:'image/jpeg',width:10,height:10,previewBytes:50,previewHash:samplePreviewHash}));assert.equal((await f.store.transaction(tx=>tx.get('assets',done.id))),null);return ['worker-heartbeat-finish-fenced-'+change];
}
export async function agentMediaRetentionScenario(inner:Store,mode:string){
 const f=await agentMediaFixture(inner);if(mode==='draft1'||mode==='draft30')f.app.config.mediaRetention={draft:mode==='draft1'?1:30,submitted:180,decided:30,withdrawn:7};const root=await f.draft(),id=await f.ready(root,'retained');
 const current=await f.store.transaction(tx=>tx.get('talentSubmissions',root));if(mode.startsWith('draft'))assert.ok(Date.parse(current!.expiresAt)<=f.clock.now().getTime()+f.app.config.mediaRetention!.draft*86400000);
 if(mode==='withdraw')await f.expect(f.machine('POST','/ingestion/submissions/'+root+'/withdraw',{expectedRevision:await f.revision(root)}));
 if(['reject','partial','adopted'].includes(mode)){await f.submit(root);const keys=mode==='reject'?[]:mode==='partial'?candidateItems.map(i=>i.clientItemKey):undefined;await f.expect(f.owner.cmd('POST','/ingestion-review/submissions/'+root+'/review',await f.review(root,keys)));}
 const relation=(await f.store.transaction(tx=>tx.find('personMedia',{assetId:id})))[0]!,u=(await f.store.transaction(tx=>tx.get('uploads',id)))!;if(mode==='adopted'){assert.equal(relation.retainUntil,null);f.clock.advance(200*86400000);assert.equal(await f.app.mediaPurge.claim(),null);return ['adopted-formal-dependency-no-ttl'];}
 const days=mode==='withdraw'?7:mode==='reject'||mode==='partial'?30:f.app.config.mediaRetention?.draft??90;assert.equal(relation.retainUntil,new Date(f.clock.now().getTime()+days*86400000).toISOString());f.clock.advance(days*86400000-1);assert.equal(await f.app.mediaPurge.claim(),null);f.clock.advance(1);const claims=await Promise.all([f.app.mediaPurge.claim(),f.app.mediaPurge.claim()]);assert.equal(claims.filter(Boolean).length,1);const lease=claims.find(Boolean)!;await f.app.mediaPurge.beginDelete(lease);await f.app.mediaPurge.objectResult(lease,'original','UNKNOWN');await f.app.mediaPurge.objectResult(lease,'preview','MISSING');await assert.rejects(f.app.mediaPurge.finalize(lease));assert.equal((await f.store.transaction(tx=>tx.get('uploads',id)))!.expectedBytes,u.expectedBytes);assert.equal((await f.store.transaction(tx=>tx.get('uploads',id)))!.purgedAt,null);await f.app.mediaPurge.objectResult(lease,'original','MISSING');await f.app.mediaPurge.finalize(lease);assert.equal((await f.store.transaction(tx=>tx.get('uploads',id)))!.expectedBytes,0);assert.equal(await f.app.mediaPurge.claim(),null);return ['machine-retention-'+mode,'purge-unknown-holds-quota-confirmed-releases-once'];
}
async function exportAgentMedia(f:Awaited<ReturnType<typeof agentMediaFixture>>,id:string,personId:string,sourceId:string){
 const sf=['source.title','source.type','source.providerClaim','source.basisMode','source.basisDescription','source.validFrom','source.validUntil','source.status'],pf=['person.displayName','person.aliases','person.intro','person.status','person.td2.talentProfiles','person.td2.personRoles','person.identityEvidence'],refs:string[]=[];
 for(const [subjectKind,subjectId,fields] of [['SOURCE',sourceId,[...sf,...pf.filter(k=>k!=='person.status'),'media.originals']],['PERSON',personId,pf],['ASSET',id,['media.originals']]] as const)refs.push((await f.expect(f.owner.cmd('POST','/use-permissions',{subjectKind,subjectId,sourceId,fields:[...fields],validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成机器媒体正式导出依据'}),201)).resourceId);
 const job=await f.expect(f.owner.cmd('POST','/exports',{format:'JSON',selectedIds:{people:[personId],works:[],projects:[]},fields:[...sf,...pf,'media.originals'],usePermissionRefs:refs}),202),claim=await f.app.exports.claim();assert.ok(claim);await f.app.exports.process(claim);const d=await f.expect(f.owner.raw('POST','/exports/'+job.resourceId+'/download',{}));for(const key of ['credentialHash','receiveAuthorizationHash','receiveToken','authorizationEpoch'])assert.ok(!JSON.stringify(d.payload).includes('"'+key+'"'));return d.payload;
}
export async function agentMediaMergeScenario(inner:Store){
 const f=await agentMediaFixture(inner),root=await f.draft(),adopted=await f.ready(root,'adopted');await f.submit(root);await f.expect(f.owner.cmd('POST','/ingestion-review/submissions/'+root+'/review',await f.review(root)));const duplicate=(await f.store.transaction(tx=>tx.get('talentSubmissions',root)))!.personId!,pending=await f.draft('merge-pending',duplicate),staged=await f.ready(pending,'staged');
 const {sourceInput}=await import('./fixtures.ts'),source=await f.expect(f.owner.cmd('POST','/sources',{...sourceInput(),scopeId:f.formal.resourceId}),201),canonical=await f.expect(f.owner.cmd('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',originSourceId:source.resourceId,sourceRevision:1,displayName:'合成媒体合并主档'}),201),{mergeInput,mergePreview}=await import('./talent-v2-merge.ts'),preview=await mergePreview(f.store,f.owner,canonical.resourceId,duplicate);assert.equal(preview.complete,true,JSON.stringify(preview.blockers));await f.expect(f.owner.cmd('POST','/people/merge',{...mergeInput(preview),professionalConflicts:preview.professional.conflicts.map((c:any)=>({table:c.table,canonicalId:c.canonicalId,duplicateId:c.duplicateId,choice:c.choices.includes('RETAIN_DUPLICATE_HISTORY')?'RETAIN_DUPLICATE_HISTORY':'KEEP_CANONICAL_ACTIVE'}))}));const rows=await f.store.transaction(tx=>tx.find('personMedia'));assert.equal(rows.find(r=>r.assetId===adopted)!.personId,canonical.resourceId);assert.equal(rows.find(r=>r.assetId===staged)!.personId,null);assert.equal((await f.store.transaction(tx=>tx.get('uploads',adopted)))!.personId,null);assert.equal((await f.store.transaction(tx=>tx.get('assets',adopted)))!.sha256,sampleHash);await f.expect(f.owner.raw('GET','/assets/'+adopted));const actor=await f.actor();await assert.rejects(f.store.transaction(tx=>f.app.media.staged(tx,actor,staged)));
 const {inspectTalentIntegrity}=await import('../../packages/core/src/talent-v2-integrity.ts');const report=await f.store.transaction(tx=>inspectTalentIntegrity(tx,f.w,f.app.config.contactKey));assert.equal(report.relationFailures,0,JSON.stringify(report));return ['actual-merge-moves-adopted-only-staged-never-transferred-origin-hash-kept','machine-merge-integrity-clean'];
}

export async function agentMediaDeletionScenario(inner:Store){
 const f=await agentMediaFixture(inner),root=await f.draft(),adopted=await f.ready(root,'adopted');await f.submit(root);await f.expect(f.owner.cmd('POST','/ingestion-review/submissions/'+root+'/review',await f.review(root)));const person=(await f.store.transaction(async tx=>tx.get('people',(await tx.get('talentSubmissions',root))!.personId!)))!,pending=await f.draft('delete-pending',person.id),staged=await f.ready(pending,'staged'),actor=await f.actor();
 const input={targetKind:'PERSON',targetId:person.id,expectedRevision:person.revision},preview=await f.expect(f.owner.raw('POST','/deletion-requests/preview',input));assert.equal(preview.complete,true,JSON.stringify(preview.unresolved));const deletion=await f.expect(f.owner.cmd('POST','/deletion-requests',{...input,previewDigest:preview.previewDigest,reason:'合成：删除阻断机器暂存与正式读取'}),201);await f.expect(f.owner.cmd('POST','/deletion-requests/'+deletion.resourceId+'/block',{expectedRevision:1,previewDigest:preview.previewDigest,acknowledgeBlock:true}));await assert.rejects(f.store.transaction(tx=>f.app.media.staged(tx,actor,staged)));await f.expect(f.owner.raw('GET','/assets/'+adopted),404);for(const id of [staged,adopted]){const upload=(await f.store.transaction(tx=>tx.get('uploads',id)))!;assert.equal(upload.purgedAt,null);assert.equal(upload.expectedBytes,100);}return ['actual-person-deletion-block-denies-machine-staged-and-adopted-capacity-not-released'];
}
