import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {Store} from '../../packages/core/src/store.ts';
import {agentMediaFixture,sampleHash,samplePreviewHash} from './agent-media.ts';
import {AppError} from '../../packages/core/src/errors.ts';
import {base,touch} from '../../packages/core/src/helpers.ts';
export const collectionCandidate=(key='portfolio',type='PORTFOLIO',media='photo')=>({clientItemKey:key,kind:'COLLECTION',values:{roleCandidateKey:'role',collectionTypeCode:type,title:'Agent 作品集',isCurrent:true,coverMediaCandidateKey:type==='SHOWREEL'||type==='INTRO_VIDEO'?null:media,tagCodes:['COMMERCIAL'],items:[{mediaCandidateKey:media,caption:'受控素材说明',featured:true}]},dependencyGroup:key,dependsOn:['role',media]});
export const workCandidate=(key='work',media='photo')=>({clientItemKey:key,kind:'WORK',values:{roleCandidateKey:'role',title:'外部同名案例',description:'结构化外部案例事实',caseDate:null,datePrecision:'UNKNOWN',location:'深圳',brandDisplayName:'合成品牌',industryCode:null,workTypeCodes:[],creditNote:'本人担任模特的提供者候选说明',coverMediaCandidateKey:media,items:[{mediaCandidateKey:media}]},dependencyGroup:key,dependsOn:['role',media]});
export async function agentStructuresFixture(inner:Store){
 const f=await agentMediaFixture(inner),root=await f.draft(),photo=await f.ready(root,'photo');
 const save=async(items:unknown[],id=root,status=200)=>f.expect(f.machine('POST','/ingestion/submissions/'+id+'/items',{expectedRevision:await f.revision(id),items}),status);
 const add=async(id=root)=>save([collectionCandidate(),workCandidate()],id);
 const body=async(id=root,target?:string)=>({...await f.review(id,undefined,target),collectionDecisions:[{clientItemKey:'portfolio',targetCollectionId:null,expectedCollectionRevision:null}],workDecisions:[{clientItemKey:'work',decision:'CREATE_EXTERNAL_WORK',targetWorkId:null,expectedWorkRevision:null,basis:'明确采纳外部结构化案例依据'}]});
 const review=async(input:any,key=randomUUID(),status=200,id=root)=>f.expect(f.owner.cmd('POST','/ingestion-review/submissions/'+id+'/review',input,key),status);
 const snapshot=()=>f.store.transaction(async tx=>Object.fromEntries(await Promise.all(['people','sources','sourceAttributions','sourceUseBases','evidence','assets','personMedia','mediaCollections','mediaCollectionItems','mediaCollectionTags','works','workAssets','workCredits','personRoles','talentSubmissions','talentSubmissionItems','receipts','audits'].map(async t=>[t,await tx.find(t as any)]))));
 return {...f,root,photo,save,add,body,review,snapshot};
}
export async function agentStructuresScenario(inner:Store){
 const f=await agentStructuresFixture(inner),checks:string[]=[];
 await f.add();await f.submit(f.root);const input=await f.body();
 for(const table of ['receipts','audits']){const before=await f.snapshot();f.store.afterInsert=t=>{if(t===table)throw new AppError(503,'SYNTHETIC_FAULT','structured review rollback');};await f.review(input,randomUUID(),503);f.store.afterInsert=null;assert.deepEqual(await f.snapshot(),before);}checks.push('collection-work-media-person-source-receipt-audit-all-rollback');
 const key=randomUUID();await f.review(input,key);await f.review(input,key);await f.review(input,randomUUID(),409);const first=await f.snapshot(),person=first.people[0],collection=first.mediaCollections[0],work=first.works[0],credit=first.workCredits[0];assert.equal(first.talentSubmissionItems.find((i:any)=>i.submissionId===f.root&&i.kind==='WORK').appliedId,work.id);assert.notEqual(work.id,credit.id);assert.equal(first.talentSubmissionItems.find((i:any)=>i.submissionId===f.root&&i.kind==='COLLECTION').appliedId,collection.id);assert.equal(first.talentSubmissionItems.find((i:any)=>i.submissionId===f.root&&i.kind==='MEDIA').appliedId,f.photo);assert.equal(first.talentSubmissionItems.find((i:any)=>i.submissionId===f.root&&i.kind==='ROLE').appliedId,collection.personRoleId);assert.equal(work.origin,'EXTERNAL');assert.equal(work.scopeId,person.scopeId);assert.equal(work.sourceId,collection.sourceId);assert.equal(credit.personRoleId,collection.personRoleId);assert.equal(first.workAssets[0].assetId,f.photo);assert.equal(first.mediaCollectionItems[0].assetId,f.photo);assert.equal(first.assets[0].usageState,'ADOPTED');assert.equal(first.assets[0].sha256,sampleHash);assert.equal(first.sourceUseBases[0].basisKind,'INTERNAL_REVIEW');assert.ok(first.sourceUseBases[0].fieldScope.includes('collection'));assert.ok(first.sourceUseBases[0].fieldScope.includes('work'));checks.push('stable-key-collection-work-exact-role-real-adoption-one-source-one-transaction-original-key-replay');
 const linked=await f.draft('link-existing',person.id),newPhoto=await f.ready(linked,'photo');await f.save([collectionCandidate(),workCandidate()],linked);await f.submit(linked);const linkInput=await f.body(linked,person.id);linkInput.collectionDecisions[0]={clientItemKey:'portfolio',targetCollectionId:collection.id,expectedCollectionRevision:collection.revision};linkInput.workDecisions[0]={clientItemKey:'work',decision:'LINK_EXISTING_WORK',targetWorkId:work.id,expectedWorkRevision:work.revision,basis:'明确关联已有案例，仅接手精确署名'};
 const before=await f.snapshot();await f.review(linkInput,randomUUID(),200,linked);const after=await f.snapshot();assert.deepEqual(after.works,before.works);assert.deepEqual(after.workAssets,before.workAssets);assert.deepEqual(after.workCredits,before.workCredits);assert.equal(after.mediaCollections.length,1);assert.equal(after.mediaCollections[0].id,collection.id);assert.equal(after.mediaCollections[0].revision,collection.revision+1);assert.equal(after.mediaCollectionTags[0].sourceId,after.mediaCollections[0].sourceId);assert.notEqual(after.mediaCollectionTags[0].sourceId,before.mediaCollectionTags[0].sourceId);assert.equal(after.mediaCollectionItems[0].assetId,newPhoto);assert.equal(after.assets.find((a:any)=>a.id===f.photo).usageState,'ADOPTED');assert.equal(after.workCredits[0].id,credit.id);assert.equal(after.talentSubmissionItems.find((i:any)=>i.submissionId===linked&&i.kind==='WORK').appliedId,work.id);assert.notEqual(after.talentSubmissionItems.find((i:any)=>i.submissionId===linked&&i.kind==='WORK').appliedId,credit.id);checks.push('CREATE-and-LINK-WORK-appliedId-is-Work-id-exact-credit-id-source-note-preserved-Collection-MEDIA-ROLE-unchanged','explicit-existing-collection-update-no-duplicate-removal-keeps-asset','LINK-new-media-adopted-independently-no-work-facts-cover-assets-credit-id-source-note-change');
 // LINK a different newly reviewed Person/Role: create only a new exact Credit, retaining the shared Work and its placements.
 const freshPerson=await f.draft('link-new-exact-credit'),freshPhoto=await f.ready(freshPerson,'photo');await f.save([workCandidate()],freshPerson);await f.submit(freshPerson);const freshDecision=await f.body(freshPerson);freshDecision.collectionDecisions=[];freshDecision.workDecisions=[{clientItemKey:'work',decision:'LINK_EXISTING_WORK',targetWorkId:work.id,expectedWorkRevision:work.revision,basis:'明确新增另一人物精确职业署名，作品和素材不变'}];const preCredit=await f.snapshot();await f.review(freshDecision,randomUUID(),200,freshPerson);const withCredit=await f.snapshot(),freshRoot=withCredit.talentSubmissions.find((r:any)=>r.id===freshPerson),freshCredit=withCredit.workCredits.find((r:any)=>r.workId===work.id&&r.personId===freshRoot.personId),freshItem=withCredit.talentSubmissionItems.find((i:any)=>i.submissionId===freshPerson&&i.kind==='WORK');assert.ok(freshCredit);assert.equal(withCredit.workCredits.length,preCredit.workCredits.length+1);assert.equal(freshItem.appliedId,work.id);assert.notEqual(freshItem.appliedId,freshCredit.id);assert.deepEqual(withCredit.works,preCredit.works);assert.deepEqual(withCredit.workAssets,preCredit.workAssets);assert.deepEqual(withCredit.workCredits.find((c:any)=>c.id===credit.id),credit);assert.equal(freshCredit.personRoleId,withCredit.personRoles.find((r:any)=>r.personId===freshRoot.personId&&r.roleCode==='model').id);checks.push('LINK-new-exact-Credit-WORK-appliedId-remains-selected-Work-id-shared-facts-cover-placements-preserved');
 const sameTitle=await f.draft('same-title',person.id),other=await f.ready(sameTitle,'photo');await f.save([workCandidate()],sameTitle);await f.submit(sameTitle);const same=await f.body(sameTitle,person.id);same.collectionDecisions=[];await f.review(same,randomUUID(),200,sameTitle);assert.equal((await f.store.transaction(tx=>tx.find('works'))).length,2);checks.push('same-title-no-automatic-merge-explicit-CREATE');
 const source=(await f.store.transaction(tx=>tx.get('sources',work.sourceId)))!;await f.expect(f.owner.cmd('POST','/sources/'+source.id+'/suspend',{expectedRevision:source.revision,reason:'正式案例和素材来源撤回'}));await f.expect(f.owner.raw('GET','/works/'+work.id),404);await f.expect(f.owner.raw('GET','/assets/'+f.photo),404);checks.push('formal-source-revoke-invalidates-work-media-projections');
 return {f,checks,personId:person.id,collectionId:collection.id,workId:work.id,creditId:credit.id};
}
export async function agentStructuresCounterexample(inner:Store,variant:string){
 const f=await agentStructuresFixture(inner);
 if(['asset-id','role-id','source-id','collection-id','work-id','scope-id'].includes(variant)){const i=variant==='work-id'?workCandidate():collectionCandidate();const field=({'asset-id':'assetId','role-id':'personRoleId','source-id':'sourceId','collection-id':'targetCollectionId','work-id':'targetWorkId','scope-id':'scopeId'} as Record<string,string>)[variant]!;await f.save([{...i,values:{...i.values,[field]:randomUUID()}}],f.root,400);return;}
 if(variant==='not-ready'){await f.store.transaction(async tx=>{const a=(await tx.get('assets',f.photo))!;await tx.replace('assets',{...a,state:'QUARANTINED'});});await f.save([collectionCandidate()],f.root,409);return;}
 if(variant==='missing-media'){const c=collectionCandidate('portfolio','PORTFOLIO','not-ready');await f.save([c],f.root,422);return;}
 if(variant==='type'){await f.save([collectionCandidate('portfolio','MODEL_CARD')]);await f.save([collectionCandidate('portfolio','PORTFOLIO')],f.root,409);return;}
 if(variant==='mime'){await f.save([collectionCandidate('showreel','SHOWREEL')],f.root,422);return;}
 if(variant==='role-key'){const c=collectionCandidate();await f.save([{...c,values:{...c.values,roleCandidateKey:'name'},dependsOn:['name','photo']}],f.root,422);return;}
 if(variant==='graph'){const c=collectionCandidate();await f.save([{...c,dependsOn:['role']}],f.root,422);return;}
 await f.add();await f.submit(f.root);const body=await f.body();
 if(variant==='partial'){body.acceptedKeys=body.acceptedKeys.filter((k:string)=>k!=='role');await f.review(body,randomUUID(),422);assert.equal((await f.store.transaction(tx=>tx.find('mediaCollections'))).length,0);return;}
 if(variant==='decision'){body.workDecisions=[];await f.review(body,randomUUID(),422);return;}
 // Create an adopted target, then freeze a separate existing-Person proposal.
 await f.review(body);const person=(await f.store.transaction(tx=>tx.get('talentSubmissions',f.root)))!.personId!,collection=(await f.store.transaction(tx=>tx.find('mediaCollections')))[0]!,work=(await f.store.transaction(tx=>tx.find('works')))[0]!,credit=(await f.store.transaction(tx=>tx.find('workCredits')))[0]!;
 const next=await f.draft('baseline-'+variant,person);await f.ready(next,'photo');await f.save([collectionCandidate(),workCandidate()],next);await f.submit(next);const d=await f.body(next,person);d.collectionDecisions[0]={clientItemKey:'portfolio',targetCollectionId:collection.id,expectedCollectionRevision:collection.revision};d.workDecisions[0]={clientItemKey:'work',decision:'LINK_EXISTING_WORK',targetWorkId:work.id,expectedWorkRevision:work.revision,basis:'明确关联冻结案例'};
 if(variant==='duplicate'){d.collectionDecisions[0]={clientItemKey:'portfolio',targetCollectionId:null,expectedCollectionRevision:null};const r=await f.review(d,randomUUID(),409,next);assert.equal(r.error.code,'COLLECTION_IDENTITY_EXISTS');return;}
 await f.store.transaction(async tx=>{
  if(variant==='role'){const r=(await tx.get('personRoles',credit.personRoleId!))!;await tx.replace('personRoles',touch(r,f.clock));}
  else if(variant==='tag'){const r=(await tx.find('mediaCollectionTags',{collectionId:collection.id}))[0]!;await tx.replace('mediaCollectionTags',{...touch(r,f.clock),status:'ARCHIVED'});}
  else if(variant==='order'){const r=(await tx.find('mediaCollectionItems',{collectionId:collection.id}))[0]!;await tx.replace('mediaCollectionItems',{...touch(r,f.clock),caption:'内部变动'});}
  else if(variant==='collection-cover'){await tx.replace('mediaCollections',{...touch(collection,f.clock),coverAssetId:null});}
  else if(variant==='cover'){await tx.replace('works',{...touch(work,f.clock),coverEntryId:null});}
  else if(variant==='work-facts'){await tx.replace('works',{...touch(work,f.clock),title:'内部改名'});}
  else if(variant==='work-assets'){const r=(await tx.find('workAssets',{workId:work.id}))[0]!;await tx.replace('workAssets',{...touch(r,f.clock),position:1});}
  else if(variant==='credit'){await tx.replace('workCredits',{...touch(credit,f.clock),note:'内部新增依据'});}
  else if(variant==='source'){const r=(await tx.get('sources',collection.sourceId))!;await tx.replace('sources',{...touch(r,f.clock),status:'SUSPENDED'});}
  else if(variant==='legacy'){await tx.replace('workCredits',{...touch(credit,f.clock),personRoleId:null,sourceId:null});}
 });
 if(variant==='legacy'){
  // Baseline is legitimately frozen AFTER a historical legacy Credit exists; normal review must still fail closed.
  const fresh=await f.draft('legacy-frozen',person);await f.ready(fresh,'photo');await f.save([workCandidate()],fresh);await f.submit(fresh);const legacy=await f.body(fresh,person);legacy.collectionDecisions=[];legacy.workDecisions=d.workDecisions;const before=await f.snapshot();const r=await f.review(legacy,randomUUID(),409,fresh);assert.equal(r.error.code,'WORK_CREDIT_UPGRADE_REQUIRED');assert.deepEqual(await f.snapshot(),before);return;
 }
 const before=await f.snapshot(),r=await f.review(d,randomUUID(),409,next);assert.ok(['TARGET_REBASE_REQUIRED','COLLECTION_REBASE_REQUIRED','WORK_REBASE_REQUIRED'].includes(r.error.code),r.error.code);assert.deepEqual(await f.snapshot(),before);
}
export async function agentStructuresLifecycle(inner:Store,targetStore?:Store,longBasis=false){
 const f=await agentStructuresFixture(inner);await f.add();await f.submit(f.root);const reviewBody=await f.body();if(longBasis){reviewBody.reviewBasis='审'.repeat(2000);reviewBody.workDecisions[0]!.basis='据'.repeat(2000);}await f.review(reviewBody);const person=(await f.store.transaction(tx=>tx.get('talentSubmissions',f.root)))!.personId!,p=(await f.store.transaction(tx=>tx.get('people',person)))!,collection=(await f.store.transaction(tx=>tx.find('mediaCollections')))[0]!,work=(await f.store.transaction(tx=>tx.find('works')))[0]!,credit=(await f.store.transaction(tx=>tx.find('workCredits')))[0]!,checks:string[]=[];
 const pending=await f.draft('pending-lifecycle',person),staged=await f.ready(pending,'staged');
 const sf=['source.title','source.type','source.providerClaim','source.basisMode','source.basisDescription','source.validFrom','source.validUntil','source.status'],pf=['person.displayName','person.aliases','person.intro','person.status','person.td2.talentProfiles','person.td2.personRoles','person.identityEvidence','person.td2.mediaCollections','person.td2.mediaCollectionTags','person.td2.fieldEvidence'],wf=['work.title','work.description','work.industryCode','work.workTypeCodes','work.origin','work.originNote','work.status','work.caseDate','work.datePrecision','work.location','work.brandDisplayName','work.relations'],refs:string[]=[];
 for(const source of await f.store.transaction(tx=>tx.find('sources')))refs.push((await f.expect(f.owner.cmd('POST','/use-permissions',{subjectKind:'SOURCE',subjectId:source.id,sourceId:source.id,fields:[...sf,...pf.filter(k=>k!=='person.status'),'work.relations','media.originals'],validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成 Agent 集合案例正式来源导出依据'}),201)).resourceId);
 for(const [subjectKind,subjectId,sourceId,fields] of [['PERSON',person,p.sourceId,pf],['WORK',work.id,work.sourceId,wf],['ASSET',f.photo,collection.sourceId,['media.identity','media.originals']]] as const)refs.push((await f.expect(f.owner.cmd('POST','/use-permissions',{subjectKind,subjectId,sourceId,fields:[...fields],validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成正式集合案例导出许可'}),201)).resourceId);
 const job=await f.expect(f.owner.cmd('POST','/exports',{format:'JSON',selectedIds:{people:[person],works:[work.id],projects:[]},fields:[...sf,...pf,...wf,'media.identity','media.originals'],usePermissionRefs:refs}),202),lease=await f.app.exports.claim();assert.ok(lease);await f.app.exports.process(lease);const {payload}=await f.expect(f.owner.raw('POST','/exports/'+job.resourceId+'/download',{}));if(longBasis){const src=(await f.store.transaction(tx=>tx.get('sources',p.sourceId)))!,basis=(await f.store.transaction(tx=>tx.find('sourceUseBases',{sourceId:p.sourceId})))[0]!;assert.equal(src.basisDescription.length,2000);assert.ok(work.originNote.length<=2000);assert.equal(JSON.parse(basis.reviewBasis!).workDecisions[0].basis.length,2000);}assert.equal(payload.manifest.talent.assets.length,1);assert.equal(payload.manifest.talent.assets[0].id,f.photo);assert.equal(payload.manifest.relations.workCredits[0].personRoleId,credit.personRoleId);assert.equal(payload.manifest.talent.tables.mediaCollections.length,1);assert.ok(!JSON.stringify(payload).includes(staged));checks.push('business-export-adopted-collection-work-exact-credit-only-private-baseline-staged-absent');
 if(targetStore){const {authFixture}=await import('./talent-auth.ts'),target=await authFixture(targetStore);target.clock.value=f.clock.value;const {JsonRebuild}=await import('../../packages/core/src/rebuild.ts'),{prepareRebuildMedia}=await import('../../scripts/rebuild-media.ts'),{sampleBytes,samplePreview}=await import('./agent-media.ts'),{mkdtemp,mkdir,writeFile,rm,realpath}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path');const tmp=await mkdtemp(join(await realpath(tmpdir()),'once-agent-structure-rebuild-'));try{const input=join(tmp,'input');await mkdir(input,{mode:0o700});await writeFile(join(input,f.photo+'.original.bin'),sampleBytes);await writeFile(join(input,f.photo+'.preview.jpg'),samplePreview);const actor=await targetStore.transaction(tx=>new JsonRebuild(target.clock).actorFromTarget(tx,'owner')),media=await prepareRebuildMedia(payload,actor.workspaceId,{REBUILD_MEDIA_INPUT_DIR:input,REBUILD_MEDIA_TARGET_DIR:join(tmp,'target')},true);await targetStore.transaction(tx=>new JsonRebuild(target.clock,undefined,media).apply(tx,actor,payload,{requestId:randomUUID(),ip:'synthetic'}));for(const t of ['talentAccounts','talentAccessGrants','talentSubmissions','servicePrincipals'] as const)assert.equal((await targetStore.transaction(tx=>tx.find(t))).length,0);assert.equal((await targetStore.transaction(tx=>tx.get('mediaCollections',collection.id)))!.personRoleId,credit.personRoleId);assert.equal((await targetStore.transaction(tx=>tx.find('workCredits',{workId:work.id,personId:person,personRoleId:credit.personRoleId!})))[0]!.sourceId,credit.sourceId);assert.equal((await targetStore.transaction(tx=>tx.find('workAssets')))[0]!.assetId,f.photo);const basis=(await targetStore.transaction(tx=>tx.find('sourceUseBases')))[0]!;assert.equal(basis.basisKind,'INTERNAL_REVIEW');assert.equal(basis.consentId,null);assert.equal(basis.importedBasis!.providerServicePrincipalId,f.principal.resourceId);checks.push('verified-byte-json-rebuild-preserves-formal-collection-work-credit-machine-provenance-no-live-principal-submission-grant');}finally{await rm(tmp,{recursive:true,force:true});}}
 const {inspectTalentIntegrity}=await import('../../packages/core/src/talent-v2-integrity.ts');assert.equal((await f.store.transaction(tx=>inspectTalentIntegrity(tx,f.w,f.app.config.contactKey))).relationFailures,0);checks.push('staged-and-formal-integrity-clean');return {f,person,collection,work,credit,staged,payload,checks};
}
export async function agentStructuresProtection(inner:Store,kind:'PERSON'|'MERGE'){
 const {f,person,collection,work,credit,staged}=await agentStructuresLifecycle(inner),p=(await f.store.transaction(tx=>tx.get('people',person)))!;
 if(kind==='MERGE'){const {sourceInput}=await import('./fixtures.ts'),source=await f.expect(f.owner.cmd('POST','/sources',{...sourceInput(),scopeId:f.formal.resourceId}),201);const canonical=await f.expect(f.owner.cmd('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',displayName:'合成结构化主档',originSourceId:source.resourceId,sourceRevision:1}),201),{mergePreview}=await import('./talent-v2-merge.ts'),preview=await mergePreview(f.store,f.owner,canonical.resourceId,person);assert.equal(preview.complete,false);assert.ok(JSON.stringify(preview.blockers).includes('EXACT_WORK_ROLE_CONFLICT'));assert.equal((await f.store.transaction(tx=>tx.get('mediaCollections',collection.id)))!.personId,person);assert.equal((await f.store.transaction(tx=>tx.get('workCredits',credit.id)))!.personRoleId,collection.personRoleId);return ['exact-role-merge-fail-closed-collection-work-media-never-dangling'];}
 const input={targetKind:'PERSON',targetId:person,expectedRevision:p.revision},preview=await f.expect(f.owner.raw('POST','/deletion-requests/preview',input));assert.equal(preview.complete,true,JSON.stringify(preview.unresolved));const deletion=await f.expect(f.owner.cmd('POST','/deletion-requests',{...input,previewDigest:preview.previewDigest,reason:'合成结构化人物删除保护'}),201);await f.expect(f.owner.cmd('POST','/deletion-requests/'+deletion.resourceId+'/block',{expectedRevision:1,previewDigest:preview.previewDigest,acknowledgeBlock:true}));await f.expect(f.owner.raw('GET','/assets/'+f.photo),404);const actor=await f.actor();await assert.rejects(f.store.transaction(tx=>f.app.media.staged(tx,actor,staged)));assert.equal((await f.store.transaction(tx=>tx.get('works',work.id)))!.status,'ACTIVE');assert.equal((await f.store.transaction(tx=>tx.get('assets',f.photo)))!.usageState,'ADOPTED');return ['person-deletion-blocks-staged-formal-no-physical-byte-or-shared-work-destruction'];
}
export async function agentStructuresPartialIsolation(inner:Store){
 const f=await agentStructuresFixture(inner);await f.add();const other=await f.expect(f.owner.raw('POST','/td2/principals',{schemaVersion:'once-talent-v2.1.0',displayName:'另一 Agent',scopeId:f.intake.resourceId,defaultMaintainerMembershipId:f.m.id,permissionCodes:f.permissions,expiresAt:'2026-11-01T00:00:00.000Z'}),201);
 const r=await f.app.handle({method:'POST',url:'/api/v1/ingestion/submissions/'+f.root+'/items',ip:'test',headers:{authorization:'Bearer '+other.token,'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({expectedRevision:await f.revision(f.root),items:[collectionCandidate()]})});assert.equal(r.status,404);
 const own=await f.expect(f.machine('GET','/ingestion/submissions/'+f.root));assert.ok(!('structureOptions' in own));assert.ok(own.items.every((i:any)=>!('baseline' in i)));await f.submit(f.root);
 const d=await f.body();d.acceptedKeys=d.acceptedKeys.filter((k:string)=>k!=='work');d.workDecisions=[];await f.review(d);const root=(await f.store.transaction(tx=>tx.get('talentSubmissions',f.root)))!;assert.equal(root.state,'PARTIALLY_APPROVED');assert.equal((await f.store.transaction(tx=>tx.find('works'))).length,0);assert.equal((await f.store.transaction(tx=>tx.find('mediaCollections'))).length,1);assert.equal((await f.store.transaction(tx=>tx.get('assets',f.photo)))!.usageState,'ADOPTED');return ['cross-Agent-structure-read-write-denied-private-baseline-never-in-machine-DTO','valid-partial-approval-dependency-closed-no-rejected-Work-created'];
}
export async function agentStructuresBasisRevocation(inner:Store){const f=await agentStructuresFixture(inner);await f.add();await f.submit(f.root);await f.review(await f.body());const collection=(await f.store.transaction(tx=>tx.find('mediaCollections')))[0]!,work=(await f.store.transaction(tx=>tx.find('works')))[0]!;await f.store.transaction(async tx=>{const source=(await tx.get('sources',collection.sourceId))!,basis=(await tx.find('sourceUseBases',{sourceId:source.id}))[0]!;await tx.replace('sourceUseBases',{...touch(basis,f.clock),state:'REVOKED'});await tx.replace('sources',{...touch(source,f.clock),internalUseUntil:f.clock.now().toISOString()});});await f.expect(f.owner.raw('GET','/works/'+work.id),404);await f.expect(f.owner.raw('GET','/assets/'+f.photo),404);return ['typed-internal-review-basis-revocation-clamps-source-formal-work-collection-media-unusable'];}
