import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {Store} from '../../packages/core/src/store.ts';
import {AppError} from '../../packages/core/src/errors.ts';
import {agentStructuresFixture,workCandidate} from './agent-structures.ts';
import {loginTalent} from './talent-auth.ts';
import {digest} from '../../packages/core/src/json.ts';
import {touch} from '../../packages/core/src/helpers.ts';
import {portalWorkCases} from '../../packages/core/src/talent-work-cases.ts';
import {talentFormalAsset} from '../../packages/core/src/media-collections.ts';
export async function handoffFixture(inner:Store){
 const f=await agentStructuresFixture(inner);await f.add();await f.submit(f.root);await f.review(await f.body());
 const root=(await f.store.transaction(tx=>tx.get('talentSubmissions',f.root)))!,personId=root.personId!,p=(await f.store.transaction(tx=>tx.get('people',personId)))!,collection=(await f.store.transaction(tx=>tx.find('mediaCollections')))[0]!,credit=(await f.store.transaction(tx=>tx.find('workCredits')))[0]!,work=(await f.store.transaction(tx=>tx.get('works',credit.workId)))!;
 const a=await loginTalent(f,'Handoff@example.com'),h=(key=randomUUID())=>({'x-once-talent-account':a.accountId,'idempotency-key':key}),portal=(method:string,path:string,body?:unknown,status=200)=>f.expect(a.client.raw(method,'/portal'+path,body,h()),status);
 const invite=async()=>{const r=await f.expect(f.owner.cmd('POST','/talent-invitations',{purpose:'CLAIM',targetPersonId:personId,scopeId:f.intake.resourceId,exposureFields:[]}));const issue=await f.expect(f.owner.raw('POST','/talent-invitations/'+r.resourceId+'/issue',{expectedRevision:1})),token=new URLSearchParams(new URL(issue.url).hash.slice(1)).get('t')!;const ctx=await f.expect(a.client.raw('POST','/portal/invitations/exchange',{invitationId:r.resourceId,token},{'x-once-portal':'1'}));return {inviteId:r.resourceId,token,contextId:ctx.contextId};};
 const inv=await invite(),claimBody={contextId:inv.contextId,relation:'SELF',applicantKey:'SELF',adultDeclared:true},claimKey=randomUUID(),claim=await f.expect(a.client.raw('POST','/portal/claims',claimBody,h(claimKey)));
 const decide=(id=claim.resourceId,key=randomUUID(),status=200)=>f.expect(f.owner.cmd('POST','/talent-claims/'+id+'/decide',{expectedRevision:1,decision:'APPROVE',ownershipBasis:'合成独立核实本人同档归属',guardianConfirmed:false},key),status);
 const approve=async()=>{await decide();return (await f.store.transaction(tx=>tx.find('talentAccessGrants',{personId,talentAccountId:a.accountId,state:'ACTIVE'})))[0]!;};
 const catalog=()=>f.expect(f.owner.raw('GET','/talent-handoff/people/'+personId));
 const assetRevision=(await f.store.transaction(tx=>tx.get('assets',f.photo)))!.revision;
 const exposure=async(g:any,extra={},key=randomUUID(),status=200)=>f.expect(f.owner.cmd('POST','/talent-grants/'+g.id+'/exposure',{expectedRevision:g.revision,decision:'ALLOW',fields:[{field:'displayName',expectedValueDigest:digest(p.displayName)}],assets:[{id:f.photo,expectedRevision:assetRevision}],collections:[{id:collection.id,expectedRevision:collection.revision}],credits:[{id:credit.id,expectedRevision:credit.revision}],approvalBasis:'员工逐项确认资料当前合法并批准本人可见',...extra},key),status);
 const actor={actorKind:'TALENT' as const,workspaceId:f.w,talentAccountId:a.accountId,sessionId:'',sessionEpoch:1};
 const readAsset=()=>f.store.transaction(tx=>talentFormalAsset(tx,actor,f.photo,f.clock,f.app.config));
 const ownWorks=()=>portal('GET','/profiles/'+personId+'/works');
 return {...f,a,h,portal,p,personId,collection,credit,work,inv,invite,claim,claimBody,claimKey,decide,approve,catalog,exposure,actor,readAsset,ownWorks};
}
export async function handoffScenario(inner:Store){
 const f=await handoffFixture(inner),checks:string[]=[],original=await f.store.transaction(async tx=>({attrs:await tx.find('sourceAttributions'),bases:await tx.find('sourceUseBases'),roles:await tx.find('personRoles'),assets:await tx.find('assets'),works:await tx.find('works'),collections:await tx.find('mediaCollections')}));
 assert.equal((await f.store.transaction(tx=>tx.find('talentConsents'))).length,0);await f.portal('GET','/profiles/'+f.personId,undefined,404);const g=await f.approve();assert.equal(g.personId,f.personId);assert.equal(g.relation,'SELF');assert.equal((await f.store.transaction(tx=>tx.find('people'))).length,1);assert.deepEqual(g.selfExposureManifest,[]);assert.equal((await f.store.transaction(tx=>tx.get('talentInvitations',f.inv.inviteId)))!.maxUses,1);assert.deepEqual((await f.portal('GET','/profiles/'+f.personId)).fields,{});await assert.rejects(f.readAsset());assert.equal((await f.portal('GET','/profiles/'+f.personId+'/collections')).collections.length,0);assert.equal((await f.ownWorks()).works.length,0);checks.push('same-original-Person-CLAIM-SELF-Grant-no-copy-no-Consent-default-hidden-media-collection-work');
 const replay=await f.expect(f.a.client.raw('POST','/portal/claims',f.claimBody,f.h(f.claimKey)));assert.equal(replay.replayed,true);assert.equal((await f.store.transaction(tx=>tx.find('talentAccessGrants'))).length,1);checks.push('original-claim-key-replay-no-second-SELF-Grant');
 const catalog=await f.catalog();assert.ok(catalog.grants[0].rows.every((r:any)=>r.status==='CLOSED'));const key=randomUUID();await f.exposure(g,{},key);await f.exposure(g,{},key);assert.equal((await f.catalog()).grants[0].rows.filter((r:any)=>r.status==='OPEN').length,4);await f.readAsset();assert.equal((await f.portal('GET','/profiles/'+f.personId+'/collections')).collections[0].id,f.collection.id);const cases=await f.ownWorks();assert.equal(cases.works[0].id,f.work.id);assert.equal(cases.works[0].credit.id,f.credit.id);assert.equal((await f.store.transaction(tx=>tx.find('talentConsents'))).length,0);checks.push('explicit-person-media-collection-exact-workCredit-exposure-readable-without-fake-WorkConsent');
 const other=await loginTalent(f,'OtherHandoff@example.com');await f.expect(other.client.raw('GET','/portal/profiles/'+f.personId,undefined,{'x-once-talent-account':other.accountId}),404);await f.expect(other.client.raw('GET','/portal/profiles/'+f.personId,undefined,{'x-once-talent-account':f.a.accountId}),409);await f.expect(f.machine('POST','/talent-invitations',{purpose:'CLAIM',targetPersonId:f.personId,scopeId:f.intake.resourceId,exposureFields:[]}),403);await f.expect(f.machine('GET','/portal/profiles/'+f.personId),401);checks.push('account-switch-cross-person-denied-machine-no-claim-invite-or-portal-control-plane');
 const d=await f.portal('POST','/submissions',{schemaVersion:'once-talent-text-v1',grantId:g.id,consentTextVersion:'internal-directory-2026-10-v1',consentAccepted:true,items:[{clientItemKey:'intro',field:'intro',text:'本人接手后独立提供的新介绍',dependencyGroup:'intro',dependsOn:[]}]}),sid=d.resourceId;
 const plan={clientItemKey:'case',mode:'LINK_EXISTING_WORK',targetWorkId:f.work.id,expectedWorkRevision:f.work.revision,personRoleId:f.credit.personRoleId,declaredRoleCode:null,title:f.work.title,description:'本人新增自己的案例说明',datePrecision:'UNKNOWN',caseDate:null,location:'深圳',industryCode:null,workTypeCodes:[],brandDisplayName:'合成品牌',creditNote:'本人新声明',coverAssetId:null,items:[]};
 await f.portal('POST','/submissions/'+sid+'/works',{expectedRevision:1,works:[plan]},409);assert.equal((await f.store.transaction(tx=>tx.get('talentSubmissions',sid)))!.revision,1);checks.push('historical-INTERNAL_REVIEW-read-exposure-never-bypasses-real-WorkConsent');
 await f.portal('POST','/submissions/'+sid+'/media-consent',{expectedRevision:1,textVersion:'internal-directory-media-work-2026-10-v1',accepted:true});await f.portal('POST','/submissions/'+sid+'/works',{expectedRevision:2,works:[plan]});await f.portal('POST','/submissions/'+sid+'/submit',{expectedRevision:3});await f.expect(f.owner.cmd('POST','/talent-submissions/'+sid+'/decide',{expectedRevision:4,acceptedKeys:['intro','case'],publicReason:'本人独立维护与已有 exact 署名接手',workDecisions:[{clientItemKey:'case',decision:'LINK_EXISTING',targetWorkId:f.work.id,expectedWorkRevision:f.work.revision,basis:'已核实同一人同一职业案例，仅复用原署名'}]}));
 const final=(await f.store.transaction(tx=>tx.get('talentSubmissions',sid)))!;assert.equal(final.personId,f.personId);assert.equal((await f.store.transaction(tx=>tx.find('people'))).length,1);assert.equal((await f.store.transaction(tx=>tx.get('people',f.personId)))!.intro,'本人接手后独立提供的新介绍');assert.deepEqual((await f.store.transaction(tx=>tx.get('workCredits',f.credit.id))),f.credit);assert.deepEqual((await f.store.transaction(tx=>tx.get('works',f.work.id))),f.work);assert.equal((await f.store.transaction(tx=>tx.find('sourceAttributions'))).filter(a=>(a.principalKind??'TALENT')==='TALENT').length,1);assert.ok((await f.store.transaction(tx=>tx.find('sourceUseBases'))).some(b=>(b.basisKind??'TALENT_CONSENT')==='TALENT_CONSENT'&&b.consentRevision!>0));assert.deepEqual((await f.store.transaction(tx=>tx.find('sourceAttributions'))).filter(a=>a.principalKind==='MACHINE'),original.attrs);assert.deepEqual((await f.store.transaction(tx=>tx.find('sourceUseBases'))).filter(b=>b.basisKind==='INTERNAL_REVIEW'),original.bases);checks.push('same-Person-new-Talent-Submission-real-Consent-TALENT-basis-original-MACHINE-provenance-unchanged','Work-capability-maintenance-LINK-preserves-shared-Work-exact-Credit');
 const source=(await f.store.transaction(tx=>tx.get('sources',f.work.sourceId)))!;await f.expect(f.owner.cmd('POST','/sources/'+source.id+'/suspend',{expectedRevision:source.revision,reason:'仅暂停机器来源的正式材料'}));await assert.rejects(f.readAsset());assert.equal((await f.ownWorks()).works.length,0);assert.equal((await f.portal('GET','/profiles/'+f.personId+'/collections')).collections.length,0);assert.equal((await f.portal('GET','/profiles/'+f.personId)).fields.intro,'本人接手后独立提供的新介绍');checks.push('Machine-Source-revoke-invalidates-stale-exposure-independent-Talent-Source-remains-readable');return {f,checks,sid};
}
export const handoffVariants=['rollback','revoke','basis','revision','delete','machine-revoke','integrity','claim-race','merge','scope','other-credit','basis-scope'] as const;
export async function handoffCounterexample(inner:Store,variant:string){
 const f=await handoffFixture(inner),checks:string[]=[];
 const snap=()=>f.store.transaction(async tx=>Object.fromEntries(await Promise.all(['talentClaims','talentAccessGrants','talentInvitations','talentInvitationContexts','receipts','audits'].map(async t=>[t,await tx.find(t as any)]))));
 if(variant==='rollback'){for(const table of ['audits','receipts']){const before=await snap();f.store.afterInsert=t=>{if(t===table)throw new AppError(503,'SYNTHETIC_FAULT','handoff rollback');};await f.decide(f.claim.resourceId,randomUUID(),503);f.store.afterInsert=null;assert.deepEqual(await snap(),before);}const g=await f.approve();for(const table of ['audits','receipts']){const before=await snap();f.store.afterInsert=t=>{if(t===table)throw new AppError(503,'SYNTHETIC_FAULT','exposure rollback');};await f.exposure(g,{},randomUUID(),503);f.store.afterInsert=null;assert.deepEqual(await snap(),before);}checks.push('Claim-Grant-and-exposure-audit-receipt-fault-full-rollback');return {f,checks};}
 if(variant==='claim-race'){const other=await loginTalent(f,'Concurrent@example.com'),i=await f.expect(f.owner.cmd('POST','/talent-invitations',{purpose:'CLAIM',targetPersonId:f.personId,scopeId:f.intake.resourceId,exposureFields:[]})),issued=await f.expect(f.owner.raw('POST','/talent-invitations/'+i.resourceId+'/issue',{expectedRevision:1})),ctx=await f.expect(other.client.raw('POST','/portal/invitations/exchange',{invitationId:i.resourceId,token:new URLSearchParams(new URL(issued.url).hash.slice(1)).get('t')},{'x-once-portal':'1'})),claim=await f.expect(other.client.raw('POST','/portal/claims',{contextId:ctx.contextId,relation:'SELF',applicantKey:'SELF',adultDeclared:true},{'x-once-talent-account':other.accountId,'idempotency-key':randomUUID()}));const outcomes=await Promise.all([f.owner.cmd('POST','/talent-claims/'+f.claim.resourceId+'/decide',{expectedRevision:1,decision:'APPROVE',ownershipBasis:'合成并发确认本人',guardianConfirmed:false}),f.owner.cmd('POST','/talent-claims/'+claim.resourceId+'/decide',{expectedRevision:1,decision:'APPROVE',ownershipBasis:'合成另一账号并发确认本人',guardianConfirmed:false})]);assert.deepEqual(outcomes.map(r=>r.status).sort(),[200,409]);assert.equal((await f.store.transaction(tx=>tx.find('talentAccessGrants',{personId:f.personId,state:'ACTIVE',relation:'SELF'}))).length,1);checks.push('two-accounts-concurrent-same-Person-approval-one-SELF-Grant');return {f,checks};}
 let g=await f.approve();await f.exposure(g);g=(await f.store.transaction(tx=>tx.get('talentAccessGrants',g.id)))!;
 if(variant==='merge'){const {mergePreview,mergeInput}=await import('./talent-v2-merge.ts'),{sourceInput}=await import('./fixtures.ts'),source=await f.expect(f.owner.cmd('POST','/sources',{...sourceInput(),scopeId:f.formal.resourceId}),201),duplicate=await f.expect(f.owner.cmd('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',displayName:'待合并独立重复人物',originSourceId:source.resourceId,sourceRevision:1}),201),blocked=await mergePreview(f.store,f.owner,duplicate.resourceId,f.personId);assert.equal(blocked.complete,false);assert.ok(JSON.stringify(blocked.blockers).includes('EXACT_WORK_ROLE_CONFLICT'));assert.equal((await f.store.transaction(tx=>tx.get('talentAccessGrants',g.id)))!.personId,f.personId);const pending=await f.draft('pending-target-merge',f.personId);await f.submit(pending);const body=await f.body(pending,f.personId);body.collectionDecisions=[];body.workDecisions=[];const safe=await mergePreview(f.store,f.owner,f.personId,duplicate.resourceId);assert.equal(safe.complete,true,JSON.stringify(safe.blockers));await f.expect(f.owner.cmd('POST','/people/merge',mergeInput(safe)));assert.equal((await f.store.transaction(tx=>tx.get('talentAccessGrants',g.id)))!.state,'REVOKED');assert.equal((await f.store.transaction(tx=>tx.get('talentAccessGrants',g.id)))!.personId,f.personId);const result=await f.review(body,randomUUID(),409,pending);assert.equal(result.error.code,'TARGET_REBASE_REQUIRED');const root=(await f.store.transaction(tx=>tx.get('talentSubmissions',pending)))!;assert.equal(root.personId,null);assert.equal(root.proposedPersonId,f.personId);checks.push('exact-role-merge-fail-closed-SELF-not-remapped','actual-merge-closes-old-Grant-pending-Agent-target-rebase-no-silent-alias-transfer');}
 if(variant==='scope'){const {Client}=await import('./fixtures.ts'),member=await f.expect(f.owner.raw('POST','/memberships',{loginName:'intake-only-handoff',displayName:'只有接收范围',role:'ADMIN',extraPermissions:[]}),201),c=new Client(f.app);await f.expect(c.activate(member.activationToken));await f.expect(c.login('intake-only-handoff'));const {base}=await import('../../packages/core/src/helpers.ts');await f.store.transaction(tx=>tx.insert('scopeMembers',{...base(f.w,f.clock),scopeId:f.intake.resourceId,membershipId:member.membershipId}));await f.expect(c.raw('GET','/talent-handoff/people/'+f.personId),404);await f.expect(c.cmd('POST','/talent-grants/'+g.id+'/exposure',{expectedRevision:g.revision,decision:'ALLOW',fields:[],assets:[{id:f.photo,expectedRevision:(await f.store.transaction(tx=>tx.get('assets',f.photo)))!.revision}],collections:[],credits:[],approvalBasis:'不具正式范围不得批准开放'}),404);checks.push('intake-only-employee-no-formal-scope-cannot-open-handoff-exposure');}
 if(variant==='other-credit'){const next=await f.draft('other-participant');await f.ready(next,'photo');const c=workCandidate();await f.save([{...c,values:{...c.values,creditNote:'其他参与者保密说明'}}],next);await f.submit(next);const body=await f.body(next);body.collectionDecisions=[];body.workDecisions=[{clientItemKey:'work',decision:'LINK_EXISTING_WORK',targetWorkId:f.work.id,expectedWorkRevision:f.work.revision,basis:'独立核实另一参与者的精确职业关系'}];await f.review(body,randomUUID(),200,next);const other=(await f.store.transaction(tx=>tx.get('talentSubmissions',next)))!;const own=await f.ownWorks();assert.equal(own.works.length,1);assert.ok(!JSON.stringify(own).includes(other.personId!));assert.ok(!JSON.stringify(own).includes('其他参与者保密说明'));assert.equal(own.works[0].credit.id,f.credit.id);checks.push('explicit-exact-own-Credit-only-other-participant-id-name-note-absent');}
 if(variant==='revoke'){const before=await f.snapshot();await f.expect(f.owner.cmd('POST','/talent-grants/'+g.id+'/revoke',{expectedRevision:g.revision}));await f.portal('GET','/profiles/'+f.personId,undefined,404);await assert.rejects(f.readAsset());const after=await f.snapshot();for(const t of ['sources','sourceAttributions','sourceUseBases','assets','works','mediaCollections','workCredits'])assert.deepEqual(after[t],before[t]);const inv=await f.invite(),claim=await f.portal('POST','/claims',{contextId:inv.contextId,relation:'SELF',applicantKey:'SELF',adultDeclared:true});await f.decide(claim.resourceId);const next=(await f.store.transaction(tx=>tx.find('talentAccessGrants',{personId:f.personId,state:'ACTIVE'})))[0]!;assert.notEqual(next.id,g.id);assert.deepEqual(next.selfExposureManifest,[]);await assert.rejects(f.readAsset());assert.equal((await f.ownWorks()).works.length,0);checks.push('Grant-revoke-only-access-formal-unchanged-new-Grant-no-old-exposure-inheritance');}
 if(variant==='basis'){await f.store.transaction(async tx=>{const b=(await tx.find('sourceUseBases',{sourceId:f.work.sourceId}))[0]!,s=(await tx.get('sources',f.work.sourceId))!;await tx.replace('sourceUseBases',{...touch(b,f.clock),state:'REVOKED'});await tx.replace('sources',{...touch(s,f.clock),internalUseUntil:f.clock.now().toISOString()});});await assert.rejects(f.readAsset());assert.equal((await f.ownWorks()).works.length,0);assert.equal((await f.portal('GET','/profiles/'+f.personId+'/collections')).collections.length,0);checks.push('current-basis-revoke-stale-manifest-fail-closed');}
 if(variant==='basis-scope'){await f.store.transaction(async tx=>{const b=(await tx.find('sourceUseBases',{sourceId:f.work.sourceId}))[0]!;await tx.replace('sourceUseBases',{...touch(b,f.clock),fieldScope:['intro']});});await assert.rejects(f.readAsset());assert.equal((await f.ownWorks()).works.length,0);assert.equal((await f.portal('GET','/profiles/'+f.personId+'/collections')).collections.length,0);const asset=(await f.store.transaction(tx=>tx.get('assets',f.photo)))!;await f.exposure(g,{fields:[],assets:[{id:asset.id,expectedRevision:asset.revision}],collections:[],credits:[]},randomUUID(),404);checks.push('current-basis-without-media-collection-work-fieldScope-cannot-open-or-read-through-stale-exposure');}
 if(variant==='revision'){await f.store.transaction(async tx=>{const c=(await tx.get('workCredits',f.credit.id))!;await tx.replace('workCredits',{...touch(c,f.clock),note:'内部已改署名说明'});});assert.equal((await f.ownWorks()).works.length,0);assert.equal((await f.catalog()).grants[0].rows.find((r:any)=>r.kind==='workCredit').status,'RECHECK_REQUIRED');await f.exposure(g,{},randomUUID(),409);checks.push('exact-Credit-revision-stale-exposure-recheck-and-old-approval-CAS-conflict');}
 if(variant==='machine-revoke'){const sp=(await f.store.transaction(tx=>tx.get('servicePrincipals',f.principal.resourceId)))!;await f.expect(f.owner.cmd('POST','/td2/principals/'+sp.id+'/revoke',{schemaVersion:'once-talent-v2.1.0',expectedRevision:sp.revision}));await f.readAsset();assert.equal((await f.ownWorks()).works.length,1);await f.expect(f.machine('GET','/ingestion/schema'),401);checks.push('Agent-revoke-does-not-revoke-adopted-formal-basis-or-Talent-exposure');}
 if(variant==='delete'){const p=(await f.store.transaction(tx=>tx.get('people',f.personId)))!,input={targetKind:'PERSON',targetId:p.id,expectedRevision:p.revision},preview=await f.expect(f.owner.raw('POST','/deletion-requests/preview',input));assert.equal(preview.complete,true,JSON.stringify(preview.unresolved));const r=await f.expect(f.owner.cmd('POST','/deletion-requests',{...input,previewDigest:preview.previewDigest,reason:'合成已接手人物删除保护'}),201);await f.expect(f.owner.cmd('POST','/deletion-requests/'+r.resourceId+'/block',{expectedRevision:1,previewDigest:preview.previewDigest,acknowledgeBlock:true}));await f.portal('GET','/profiles/'+f.personId,undefined,404);await f.portal('GET','/profiles/'+f.personId+'/works',undefined,404);await assert.rejects(f.readAsset());await f.expect(f.owner.raw('GET','/assets/'+f.photo),404);checks.push('Person-deletion-immediate-Portal-and-formal-media-block-without-early-byte-quota-release');}
 if(variant==='integrity'){const {inspectTalentIntegrity}=await import('../../packages/core/src/talent-v2-integrity.ts');assert.equal((await f.store.transaction(tx=>inspectTalentIntegrity(tx,f.w,f.app.config.contactKey))).relationFailures,0);await f.store.transaction(tx=>tx.replace('talentAccessGrants',{...g,selfExposureManifest:[...g.selfExposureManifest,{kind:'workCredit',targetId:randomUUID(),field:'OWN_WORK_CASE',sourceId:f.work.sourceId,sourceRevision:1,valueDigest:'a'.repeat(64)}]}));assert.ok((await f.store.transaction(tx=>inspectTalentIntegrity(tx,f.w,f.app.config.contactKey))).relationFailures>0);assert.equal((await f.ownWorks()).works.length,1);checks.push('integrity-current-Claim-Grant-explicit-exposure-orphan-fail-closed');}
 return {f,checks};
}
export async function handoffExport(inner:Store,targetStore:Store){
 const f=await handoffFixture(inner),g=await f.approve();await f.exposure(g);const d=await f.portal('POST','/submissions',{schemaVersion:'once-talent-text-v1',grantId:g.id,consentTextVersion:'internal-directory-2026-10-v1',consentAccepted:true,items:[{clientItemKey:'intro',field:'intro',text:'本人独立来源和机器来源共同导出',dependencyGroup:'intro',dependsOn:[]}]});await f.portal('POST','/submissions/'+d.resourceId+'/submit',{expectedRevision:1});await f.expect(f.owner.cmd('POST','/talent-submissions/'+d.resourceId+'/decide',{expectedRevision:2,acceptedKeys:['intro'],publicReason:'新本人资料采用'}));
 const pending=await f.draft('pending-export',f.personId),staged=await f.ready(pending,'not-exported');
 const sf=['source.title','source.type','source.providerClaim','source.basisMode','source.basisDescription','source.validFrom','source.validUntil','source.status'],pf=['person.displayName','person.aliases','person.intro','person.status','person.td2.talentProfiles','person.td2.personRoles','person.identityEvidence','person.td2.mediaCollections','person.td2.mediaCollectionTags','person.td2.fieldEvidence'],wf=['work.title','work.description','work.industryCode','work.workTypeCodes','work.origin','work.originNote','work.status','work.caseDate','work.datePrecision','work.location','work.brandDisplayName','work.relations'],refs:string[]=[];
 for(const source of await f.store.transaction(tx=>tx.find('sources')))refs.push((await f.expect(f.owner.cmd('POST','/use-permissions',{subjectKind:'SOURCE',subjectId:source.id,sourceId:source.id,fields:[...sf,...pf.filter(k=>k!=='person.status'),'work.relations','media.originals'],validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成同档双主体合法来源导出依据'}),201)).resourceId);
 for(const [subjectKind,subjectId,sourceId,fields]of [['PERSON',f.personId,f.p.sourceId,pf],['WORK',f.work.id,f.work.sourceId,wf],['ASSET',f.photo,f.collection.sourceId,['media.identity','media.originals']]]as const)refs.push((await f.expect(f.owner.cmd('POST','/use-permissions',{subjectKind,subjectId,sourceId,fields:[...fields],validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成接手原档业务导出许可'}),201)).resourceId);
 const e=await f.expect(f.owner.cmd('POST','/exports',{format:'JSON',selectedIds:{people:[f.personId],works:[f.work.id],projects:[]},fields:[...sf,...pf,...wf,'media.identity','media.originals'],usePermissionRefs:refs}),202),lease=await f.app.exports.claim();assert.ok(lease);await f.app.exports.process(lease);const {payload}=await f.expect(f.owner.raw('POST','/exports/'+e.resourceId+'/download',{}));assert.ok(!JSON.stringify(payload).includes(staged));assert.equal(payload.manifest.talent.assets[0].id,f.photo);const bases=payload.manifest.sources.map((s:any)=>s.talentBasis);assert.ok(bases.some((b:any)=>b?.basisKind==='INTERNAL_REVIEW'));assert.ok(bases.some((b:any)=>b?.providerAccountId===f.a.accountId));const inspectKeys=(v:any)=>{if(v&&typeof v==='object')for(const [k,value]of Object.entries(v)){assert.ok(!['authorizationEpoch','credentialHash','receiveToken','tokenHash','codeHash','token','talentAccounts','talentAccessGrants','talentSubmissions','servicePrincipals','talentSessions','talentClaims','talentInvitations'].includes(k),'private key in business JSON: '+k);inspectKeys(value);}};inspectKeys(payload);
 const {authFixture}=await import('./talent-auth.ts'),target=await authFixture(targetStore);target.clock.value=f.clock.value;const {JsonRebuild}=await import('../../packages/core/src/rebuild.ts'),{prepareRebuildMedia}=await import('../../scripts/rebuild-media.ts'),{sampleBytes,samplePreview}=await import('./agent-media.ts'),{mkdtemp,mkdir,writeFile,rm,realpath}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),dir=await mkdtemp(join(await realpath(tmpdir()),'once-handoff-json-'));
 try{const input=join(dir,'input');await mkdir(input,{mode:0o700});await writeFile(join(input,f.photo+'.original.bin'),sampleBytes);await writeFile(join(input,f.photo+'.preview.jpg'),samplePreview);const actor=await targetStore.transaction(tx=>new JsonRebuild(target.clock).actorFromTarget(tx,'owner')),media=await prepareRebuildMedia(payload,actor.workspaceId,{REBUILD_MEDIA_INPUT_DIR:input,REBUILD_MEDIA_TARGET_DIR:join(dir,'target')},true);await targetStore.transaction(tx=>new JsonRebuild(target.clock,undefined,media).apply(tx,actor,payload,{requestId:randomUUID(),ip:'synthetic'}));assert.equal((await targetStore.transaction(tx=>tx.get('people',f.personId)))!.intro,'本人独立来源和机器来源共同导出');assert.equal((await targetStore.transaction(tx=>tx.get('mediaCollections',f.collection.id)))!.personRoleId,f.credit.personRoleId);assert.deepEqual((await targetStore.transaction(tx=>tx.find('workCredits',{workId:f.work.id,personId:f.personId,personRoleId:f.credit.personRoleId!})))[0]!.personRoleId,f.credit.personRoleId);for(const t of ['talentAccounts','talentAccessGrants','talentClaims','talentInvitations','talentSessions','talentSubmissions','servicePrincipals']as const)assert.equal((await targetStore.transaction(tx=>tx.find(t))).length,0);const rebuilt=await targetStore.transaction(tx=>tx.find('sourceUseBases'));assert.ok(rebuilt.some(b=>b.basisKind==='INTERNAL_REVIEW'&&b.consentId===null&&b.importedBasis));assert.ok(rebuilt.some(b=>b.basisKind==='TALENT_CONSENT'&&b.importedBasis));const {inspectTalentIntegrity}=await import('../../packages/core/src/talent-v2-integrity.ts');assert.equal((await targetStore.transaction(tx=>inspectTalentIntegrity(tx,actor.workspaceId,target.app.config.contactKey,target.clock))).relationFailures,0);
 }finally{await rm(dir,{recursive:true,force:true});}
 return {f,payload,staged,checks:['same-Person-dual-MACHINE-INTERNAL_REVIEW-and-TALENT-CONSENT-business-export','verified-media-hash-exact-Person-Role-Collection-Work-Credit-rebuilt-without-account-session-Claim-Grant-Invitation-Submission-SP','no-STAGED-or-secret-or-authorizationEpoch-in-business-JSON','imported-INTERNAL_REVIEW-remains-non-Consent-and-TALENT-basis-remains-true-provenance']};
}
