import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {Store} from '../../packages/core/src/store.ts';
import type {verifyIngestion} from './ingestion.ts';
import {authFixture} from './talent-auth.ts';
import {result} from './fixtures.ts';
import {JsonRebuild} from '../../packages/core/src/rebuild.ts';
import {inspectTalentIntegrity} from '../../packages/core/src/talent-v2-integrity.ts';
import {maintenanceSnapshot,revokePersonMaintenance,isolateTalentMaintenance} from '../../packages/core/src/talent-maintenance-lifecycle.ts';
type R=Awaited<ReturnType<typeof verifyIngestion>>;
export async function ingestionExport(r:R){const {f,personId}=r;await f.owner.login();const sourceFields=['source.title','source.type','source.providerClaim','source.basisMode','source.basisDescription','source.validFrom','source.validUntil','source.status'],personFields=['person.displayName','person.aliases','person.intro','person.status','person.td2.talentProfiles','person.td2.personRoles','person.td2.castingProfiles','person.td2.measurementSets','person.identityEvidence','person.td2.fieldEvidence'],refs:string[]=[];
 const person=(await f.store.transaction(tx=>tx.get('people',personId)))!,sources=new Set([person.sourceId]);for(const s of await f.store.transaction(tx=>tx.find('talentSubmissions',{personId})))for(const a of await f.store.transaction(tx=>tx.find('sourceAttributions',{submissionId:s.id})))sources.add(a.sourceId);
 const permission=async(kind:string,id:string,sourceId:string,fields:string[])=>{const p=await f.owner.cmd('POST','/use-permissions',{subjectKind:kind,subjectId:id,sourceId,fields,validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成内部审核来源：受控导出，不授予任何机器或本人账号权限'});assert.equal(p.status,201,JSON.stringify(p.body));refs.push(result(p).resourceId);};await permission('PERSON',personId,person.sourceId,personFields);for(const id of sources)await permission('SOURCE',id,id,[...sourceFields,...personFields.filter(f=>f!=='person.status')]);const job=await f.owner.cmd('POST','/exports',{format:'JSON',selectedIds:{people:[personId],works:[],projects:[]},fields:[...sourceFields,...personFields],usePermissionRefs:refs});assert.equal(job.status,202,JSON.stringify(job.body));const claim=await f.app.exports.claim();assert.ok(claim);await f.app.exports.process(claim);const download=await f.owner.raw('POST','/exports/'+result(job).resourceId+'/download',{});assert.equal(download.status,200,JSON.stringify(download.body));const payload=result(download).payload;assert.ok(payload.manifest.sources.length>=2);assert.ok(payload.manifest.sources.every((s:any)=>s.talentBasis?.version==='internal-review-basis-v1'&&s.talentBasis.basisKind==='INTERNAL_REVIEW'&&s.talentBasis.reviewerId&&s.talentBasis.reviewBasisDigest));for(const forbidden of ['credentialHash','talentAccounts','talentSubmissions','talentSubmissionItems','sourceDeclaration','authorizationEpoch'])assert.ok(!JSON.stringify(payload).includes('"'+forbidden+'"'));return payload;}
export async function ingestionRebuild(r:R,store:Store,payload:unknown){const target=await authFixture(store);target.clock.value=r.f.clock.value;const rebuild=new JsonRebuild(target.clock),actor=await store.transaction(tx=>rebuild.actorFromTarget(tx,'owner'));await store.transaction(tx=>rebuild.apply(tx,actor,payload,{requestId:randomUUID(),ip:'test'}));const data=await store.transaction(async tx=>({principals:await tx.find('servicePrincipals'),accounts:await tx.find('talentAccounts'),grants:await tx.find('talentAccessGrants'),roots:await tx.find('talentSubmissions'),bases:await tx.find('sourceUseBases'),sources:await tx.find('sources')}));assert.equal(data.principals.length,0);assert.equal(data.accounts.length,0);assert.equal(data.grants.length,0);assert.equal(data.roots.length,0);assert.ok(data.bases.length>=2&&data.bases.every(b=>b.basisKind==='INTERNAL_REVIEW'&&b.consentId===null&&b.consentRevision===null&&b.submissionId==null&&b.importedBasis?.basisKind==='INTERNAL_REVIEW'));assert.ok(data.sources.every(s=>s.internalUseUntil));const report=await store.transaction(tx=>inspectTalentIntegrity(tx,actor.workspaceId,target.app.config.contactKey));assert.equal(report.relationFailures,0,JSON.stringify(report));return target;}
export async function ingestionLifecycle(r:R){const {f}=r,w=(await f.store.transaction(tx=>tx.find('workspaces')))[0]!;const report=await f.store.transaction(tx=>inspectTalentIntegrity(tx,w.id,f.app.config.contactKey));assert.equal(report.relationFailures,0,JSON.stringify(report));const person=(await f.store.transaction(tx=>tx.get('people',r.personId)))!,source=(await f.store.transaction(tx=>tx.get('sources',person.sourceId)))!;const suspended=await f.owner.cmd('POST','/sources/'+source.id+'/suspend',{expectedRevision:source.revision,reason:'合成主来源撤回；后续独立采纳的量尺与职业不应误失效'});assert.equal(suspended.status,200,JSON.stringify(suspended.body));const search=await f.owner.raw('GET','/td2/people?heightMin=177&heightMax=179');assert.equal(search.status,200,JSON.stringify(search.body));assert.ok(result(search).items.some((p:any)=>p.id===r.personId),'independently adopted measurement binding remains usable after original casting source withdrawal');const snapshot=await f.store.transaction(tx=>maintenanceSnapshot(tx,w.id,[r.personId]));assert.ok(snapshot.data.sourceUseBases!.some(b=>b.basisKind==='INTERNAL_REVIEW'));await f.store.transaction(tx=>revokePersonMaintenance(tx,w.id,[r.personId],f.clock,true));const roots=await f.store.transaction(tx=>tx.find('talentSubmissions',{personId:r.personId}));for(const s of roots)assert.ok((await f.store.transaction(tx=>tx.find('talentSubmissionItems',{submissionId:s.id}))).every(i=>i.values.erased));await f.store.transaction(tx=>isolateTalentMaintenance(tx,w.id,f.clock));assert.ok((await f.store.transaction(tx=>tx.find('talentSubmissions'))).every(s=>!['DRAFT','SUBMITTED'].includes(s.state)));return ['typed-basis-real-export-and-json-rebuild-preserve-safe-provenance-no-runtime-auth','formal-independent-measurement-binding-survives-original-source-withdrawal-without-relabeling-old-appearance','integrity-includes-machine-principal-root-typed-basis-and-evidence','erasure-covers-machine-items-and-recovery-expires-pending-machine-roots'];}
