import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {Store} from '../../packages/core/src/store.ts';
import type {ApiResponse} from '../../packages/core/src/api.ts';
import {base} from '../../packages/core/src/helpers.ts';
import {mergeInput,mergePreview} from './talent-v2-merge.ts';
import {digest} from '../../packages/core/src/json.ts';
import {Client,result,sourceInput} from './fixtures.ts';
import {authFixture} from './talent-auth.ts';
export const candidateItems=[
 {clientItemKey:'name',kind:'IDENTITY_TEXT',values:{field:'displayName',value:'合成外部人才'},dependencyGroup:'identity',dependsOn:[]},
 {clientItemKey:'aliases',kind:'IDENTITY_TEXT',values:{field:'aliases',value:[]},dependencyGroup:'identity',dependsOn:[]},
 {clientItemKey:'intro',kind:'IDENTITY_TEXT',values:{field:'intro',value:'外部文字材料，未经核验证件'},dependencyGroup:'identity',dependsOn:[]},
 {clientItemKey:'role',kind:'ROLE',values:{roleCode:'model',castingMarketCode:'INTERNATIONAL',experienceCode:'AMATEUR'},dependencyGroup:'role',dependsOn:['name']},
 {clientItemKey:'profile',kind:'PROFILE',values:{genderCode:'FEMALE',nationalityCodes:['CN']},dependencyGroup:'profile',dependsOn:['name']},
 {clientItemKey:'height',kind:'MEASUREMENT',values:{heightCm:178,measuredOn:null,datePrecision:'UNKNOWN'},dependencyGroup:'height',dependsOn:['role']}
];
export async function verifyIngestion(store:Store,failAudit:()=>Promise<void>,clearAudit:()=>Promise<void>){
 const f=await authFixture(store);f.app.config.ingestionEnabled=true;const checks:string[]=[];
 const expect=async(r:Promise<ApiResponse>,status=200)=>{const x=await r;assert.equal(x.status,status,JSON.stringify(x.body));return result(x);};
 const err=async(r:Promise<ApiResponse>,code:string,status=409)=>{const x=await expect(r,status);assert.equal(x.error.code,code);};
 const members=await store.transaction(tx=>tx.find('memberships')),ownerId=members[0]!.id,w=members[0]!.workspaceId;
 const intake=await expect(f.owner.cmd('POST','/scopes',{name:'机器材料接收',membershipIds:[ownerId]}),201),formal=await expect(f.owner.cmd('POST','/scopes',{name:'正式人才范围',membershipIds:[ownerId]}),201);
 const makePrincipal=async(name:string)=>expect(f.owner.raw('POST','/td2/principals',{schemaVersion:'once-talent-v2.1.0',displayName:name,scopeId:intake.resourceId,defaultMaintainerMembershipId:ownerId,permissionCodes:['ingestion.schema.read','ingestion.submit','ingestion.read.own','ingestion.withdraw.own'],expiresAt:'2026-11-01T00:00:00.000Z'}),201);
 const a=await makePrincipal('合成 Agent A'),b=await makePrincipal('合成 Agent B');let token=a.token as string;
 const machine=(method:string,path:string,body?:unknown,key=randomUUID(),which=token)=>f.app.handle({method,url:'/api/v1'+path,ip:'192.0.2.71',headers:{authorization:'Bearer '+which,'content-type':'application/json','idempotency-key':key},body:JSON.stringify(body??{})});
 const createInput=(externalSubmissionKey:string,proposedPersonId:string|null=null)=>({schemaVersion:'once-talent-experience-v1',externalSubmissionKey,proposedPersonId,sourceDeclaration:{title:'受控外部材料',providerClaim:'合成外部提供者',materialDescription:'仅自动化验证用的明确外部文字材料'}});
 const draft=async(key:string,target:string|null=null)=>{const c=await expect(machine('POST','/ingestion/submissions',createInput(key,target)));await expect(machine('POST','/ingestion/submissions/'+c.resourceId+'/items',{expectedRevision:1,items:candidateItems}));return c.resourceId as string;};
 const submit=async(id:string)=>expect(machine('POST','/ingestion/submissions/'+id+'/submit',{expectedRevision:2}));
 const reviewInput=(target?:string)=>({expectedRevision:3,acceptedKeys:candidateItems.map(i=>i.clientItemKey),decision:target?'LINK_EXISTING':'CREATE_NEW',...(target?{targetPersonId:target}:{formalScopeId:formal.resourceId}),reviewBasis:'合成内部审核：来源声明与本批候选资料可用于内部人才目录，不代表资质核验',validUntil:'2026-11-15T00:00:00.000Z',publicReason:'本批审核采纳'});
 await expect(machine('GET','/ingestion/schema'));await expect(machine('GET','/ingestion/dictionaries'));await err(f.owner.raw('GET','/ingestion/schema'),'MACHINE_REQUIRED',401);
 await err(f.owner.raw('GET','/ingestion/schema',{}, {authorization:'Bearer '+token}),'MIXED_AUTH_FORBIDDEN',400);
 await expect(machine('GET','/portal/me'),401);await err(machine('GET','/ingestion-review/submissions'),'MACHINE_OPERATION_FORBIDDEN',403);await err(machine('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',originSourceId:randomUUID(),sourceRevision:1,displayName:'forbidden',createTalent:true}),'FORBIDDEN',403);checks.push('real-machine-bearer-cookie-portal-review-and-formal-write-boundaries');
 const key=randomUUID(),input=createInput('concurrent-root');const responses=await Promise.all([machine('POST','/ingestion/submissions',input,key),machine('POST','/ingestion/submissions',input,key)]);assert.ok(responses.every(r=>r.status===200));const id=result(responses[0]!).resourceId as string;assert.equal(result(responses[1]!).resourceId,id);assert.ok(responses.some(r=>result(r).replayed));await err(machine('POST','/ingestion/submissions',{...input,externalSubmissionKey:'different'},key),'IDEMPOTENCY_KEY_CONFLICT');await err(machine('POST','/ingestion/submissions',input),'EXTERNAL_SUBMISSION_KEY_EXISTS');await expect(machine('GET','/ingestion/submissions/'+id,{},randomUUID(),b.token),404);checks.push('concurrent-external-key-one-root-original-key-replay-digest-conflict-owner-isolation');
 const concurrent=await Promise.all([machine('POST','/ingestion/submissions',createInput('new-key-concurrency')),machine('POST','/ingestion/submissions',createInput('new-key-concurrency'))]);assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);assert.equal((await store.transaction(tx=>tx.find('talentSubmissions',{servicePrincipalId:a.resourceId,externalSubmissionKey:'new-key-concurrency'}))).length,1);await expect(machine('POST','/ingestion/submissions/'+id+'/items',{expectedRevision:1,items:candidateItems},randomUUID(),b.token),404);await expect(machine('POST','/ingestion/submissions/'+id+'/withdraw',{expectedRevision:1},randomUUID(),b.token),404);checks.push('independent-command-keys-concurrent-root-unique-and-cross-machine-write-denied');
 await expect(machine('POST','/ingestion/submissions', {...createInput('no-scope'),formalScopeId:formal.resourceId}),400);await expect(machine('POST','/ingestion/submissions/'+id+'/items',{expectedRevision:1,items:[{...candidateItems[0],values:{field:'displayName',value:'bad',verified:true}}]}),400);
 await expect(machine('POST','/ingestion/submissions/'+id+'/items',{expectedRevision:1,items:candidateItems}));const before=await store.transaction(tx=>tx.find('people'));assert.equal(before.length,0);checks.push('strict-unknown-fields-no-agent-formal-scope-no-precreated-person');
 const rotated=await expect(f.owner.raw('POST','/td2/principals/'+a.resourceId+'/rotate',{schemaVersion:'once-talent-v2.1.0',expectedRevision:1}));token=rotated.token;assert.equal((await store.transaction(tx=>tx.get('servicePrincipals',a.resourceId)))!.authorizationEpoch,1);await expect(machine('POST','/ingestion/submissions/'+id+'/validate',{expectedRevision:2}));await submit(id);checks.push('rotate-token-keeps-authorization-epoch-and-existing-draft-valid');
 const snapshot=()=>store.transaction(async tx=>({people:await tx.find('people'),sources:await tx.find('sources'),basis:await tx.find('sourceUseBases'),attributions:await tx.find('sourceAttributions'),evidence:await tx.find('evidence'),roots:await tx.find('talentSubmissions'),items:await tx.find('talentSubmissionItems'),roles:await tx.find('personRoles'),receipts:await tx.find('receipts'),audits:await tx.find('audits')}));
 const reviewPath='/ingestion-review/submissions/'+id+'/review',body=reviewInput();const beforeFault=await snapshot();await failAudit();try{const failed=await f.owner.cmd('POST',reviewPath,body);assert.ok([500,503].includes(failed.status),JSON.stringify(failed.body));}finally{await clearAudit();}assert.deepEqual(await snapshot(),beforeFault);checks.push('review-audit-fault-rolls-back-person-source-basis-facts-and-receipt');
 const reviewKey=randomUUID(),r=await expect(f.owner.cmd('POST',reviewPath,body,reviewKey));await expect(f.owner.cmd('POST',reviewPath,body,reviewKey));const closedBefore=await snapshot();await err(f.owner.cmd('POST',reviewPath,body),'SUBMISSION_CLOSED');await err(f.owner.cmd('POST',reviewPath,{...body,acceptedKeys:[],decision:'REJECT'}),'SUBMISSION_CLOSED');assert.deepEqual(await snapshot(),closedBefore);checks.push('same-principal-key-digest-review-replays-new-key-terminal-closed');
 const root=(await store.transaction(tx=>tx.get('talentSubmissions',id)))!,personId=root.personId!;assert.equal(root.state,'APPROVED');assert.equal(root.scopeId,intake.resourceId);const person=(await store.transaction(tx=>tx.get('people',personId)))!;assert.equal(person.scopeId,formal.resourceId);const basis=(await store.transaction(tx=>tx.find('sourceUseBases')))[0]!;assert.equal(basis.basisKind,'INTERNAL_REVIEW');assert.equal(basis.consentId,null);assert.equal(basis.consentRevision,null);assert.equal((await store.transaction(tx=>tx.find('talentConsents'))).length,0);assert.equal((await store.transaction(tx=>tx.get('sources',person.sourceId)))!.scopeId,formal.resourceId);const detail=await expect(f.owner.raw('GET','/td2/people/'+personId));assert.equal(detail.facts.measurementSets[0].measuredOn,null);assert.equal(detail.facts.measurementSets[0].datePrecision,'UNKNOWN');assert.equal(detail.adultState,'UNKNOWN');checks.push('create-new-formal-scope-typed-internal-review-no-consent-preserves-unknown-measurement-and-adulthood');
 const receipts=await store.transaction(tx=>tx.find('receipts',{workspaceId:w,principalKind:'MACHINE'}));assert.ok(receipts.length>0&&receipts.every(r=>r.actorId===null&&r.servicePrincipalId));assert.ok(f.intents.some(i=>i.intentId==='intent:'+digest({workspaceId:w,servicePrincipalId:a.resourceId,operation:'ingestion.create',commandKey:key})));checks.push('receipt-audit-writeahead-real-machine-attribution');
 const linked=await draft('link-existing',personId);assert.equal((await store.transaction(tx=>tx.get('talentSubmissions',linked)))!.personId,null);await submit(linked);assert.equal((await store.transaction(tx=>tx.get('talentSubmissions',linked)))!.personId,null);
 await store.transaction(async tx=>{const p=(await tx.get('people',personId))!;await tx.replace('people',{...p,revision:p.revision+1});});await err(f.owner.cmd('POST','/ingestion-review/submissions/'+linked+'/review',reviewInput(personId)),'TARGET_REBASE_REQUIRED');
 const fork=await expect(machine('POST','/ingestion/submissions/'+linked+'/fork',{expectedRevision:3,externalSubmissionKey:'rebased-existing'}));await expect(machine('POST','/ingestion/submissions/'+fork.resourceId+'/submit',{expectedRevision:1}));await expect(f.owner.cmd('POST','/ingestion-review/submissions/'+fork.resourceId+'/review',{...reviewInput(personId),expectedRevision:2}));assert.equal((await store.transaction(tx=>tx.find('people'))).length,1);checks.push('existing-person-null-before-review-stale-target-conflict-explicit-fork-rebase-exact-link-no-duplicate');

 const reviewer=await expect(f.owner.raw('POST','/memberships',{loginName:'intake-only',displayName:'仅接收范围审核员',role:'ADMIN',extraPermissions:[]}),201),intakeOnly=new Client(f.app);await expect(intakeOnly.activate(reviewer.activationToken));await expect(intakeOnly.login('intake-only'));await store.transaction(async tx=>tx.insert('scopeMembers',{...base(w,f.clock),scopeId:intake.resourceId,membershipId:reviewer.membershipId}));
 const reviewer2=await expect(f.owner.raw('POST','/memberships',{loginName:'formal-only',displayName:'仅正式范围员工',role:'ADMIN',extraPermissions:[]}),201),formalOnly=new Client(f.app);await expect(formalOnly.activate(reviewer2.activationToken));await expect(formalOnly.login('formal-only'));await store.transaction(async tx=>tx.insert('scopeMembers',{...base(w,f.clock),scopeId:formal.resourceId,membershipId:reviewer2.membershipId}));
 const scopeRoot=await draft('two-scope-review',personId);await submit(scopeRoot);const scopePath='/ingestion-review/submissions/'+scopeRoot+'/review';await expect(intakeOnly.cmd('POST',scopePath,reviewInput(personId)),404);await expect(formalOnly.cmd('POST',scopePath,reviewInput(personId)),404);await expect(formalOnly.raw('GET','/td2/people/'+personId));await expect(intakeOnly.raw('GET','/td2/people/'+personId),404);checks.push('review-requires-both-intake-and-formal-formal-read-independent-of-intake');
 const rawSource=await expect(f.owner.cmd('POST','/sources',{...sourceInput(),scopeId:formal.resourceId}),201);
 const supported=await expect(f.owner.cmd('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',originSourceId:rawSource.resourceId,sourceRevision:1,displayName:'合成跨来源依据目标',createTalent:true}),201),support=await expect(f.owner.cmd('POST','/sources',{...sourceInput(),title:'独立字段支持来源',scopeId:formal.resourceId}),201);const profileRow=(await store.transaction(tx=>tx.find('talentProfiles',{personId:supported.resourceId})))[0]!;await expect(f.owner.cmd('POST','/td2/evidence',{schemaVersion:'once-talent-v2.1.0',ownerKind:'talentProfiles',ownerId:profileRow.id,fieldPath:'genderCode',expectedRevision:profileRow.revision,sourceId:support.resourceId,sourceRevision:1}));const supportedRoot=await draft('support-source-target',supported.resourceId);await submit(supportedRoot);const stablePerson=(await store.transaction(tx=>tx.get('people',supported.resourceId)))!.revision;await expect(f.owner.cmd('POST','/sources/'+support.resourceId+'/suspend',{expectedRevision:1,reason:'合成独立字段依据失效，应冻结第二来源而非只冻结事实主来源'}));assert.equal((await store.transaction(tx=>tx.get('people',supported.resourceId)))!.revision,stablePerson);await err(f.owner.cmd('POST','/ingestion-review/submissions/'+supportedRoot+'/review',reviewInput(supported.resourceId)),'TARGET_REBASE_REQUIRED');checks.push('independent-field-evidence-source-withdrawal-invalidates-target-with-unchanged-person-and-fact-revisions');
 const target=await expect(f.owner.cmd('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',originSourceId:rawSource.resourceId,sourceRevision:1,displayName:'合成待合并目标',createTalent:true}),201);
 const mergeRoot=await draft('merge-target',target.resourceId);await submit(mergeRoot);const canonical=await expect(f.owner.cmd('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',originSourceId:rawSource.resourceId,sourceRevision:1,displayName:'合成合并主档'}),201);const preview=await mergePreview(store,f.owner,canonical.resourceId,target.resourceId);assert.equal(preview.complete,true,JSON.stringify(preview.blockers));await expect(f.owner.cmd('POST','/people/merge',{...mergeInput(preview),professionalConflicts:preview.professional.conflicts.map((c:any)=>({table:c.table,canonicalId:c.canonicalId,duplicateId:c.duplicateId,choice:c.choices.includes('RETAIN_DUPLICATE_HISTORY')?'RETAIN_DUPLICATE_HISTORY':'KEEP_CANONICAL_ACTIVE'}))}));await err(f.owner.cmd('POST','/ingestion-review/submissions/'+mergeRoot+'/review',reviewInput(target.resourceId)),'TARGET_REBASE_REQUIRED');assert.equal((await store.transaction(tx=>tx.get('talentSubmissions',mergeRoot)))!.proposedPersonId,target.resourceId);checks.push('actual-person-merge-stale-target-fail-closed-no-canonical-following');
 const deleted=await expect(f.owner.cmd('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',originSourceId:rawSource.resourceId,sourceRevision:1,displayName:'合成待删除目标',createTalent:true}),201);const deleteRoot=await draft('delete-target',deleted.resourceId);await submit(deleteRoot);const delInput={targetKind:'PERSON',targetId:deleted.resourceId,expectedRevision:1},impact=await expect(f.owner.raw('POST','/deletion-requests/preview',delInput));assert.equal(impact.complete,true,JSON.stringify(impact.unresolved));const del=await expect(f.owner.cmd('POST','/deletion-requests',{...delInput,previewDigest:impact.previewDigest,reason:'合成摄取目标删除保护验收'}),201);await expect(f.owner.cmd('POST','/deletion-requests/'+del.resourceId+'/block',{expectedRevision:1,previewDigest:impact.previewDigest,acknowledgeBlock:true}));await err(f.owner.cmd('POST','/ingestion-review/submissions/'+deleteRoot+'/review',reviewInput(deleted.resourceId)),'TARGET_REBASE_REQUIRED');checks.push('actual-person-deletion-block-stale-target-rebase-required');
 for(const mode of ['permission','scope','maintainer','revoke','disabled'] as const){const c=await makePrincipal('边界 '+mode),staleToken=c.token;const old=token;token=staleToken;const d=await draft('stale-'+mode);token=old;if(mode==='disabled')await store.transaction(async tx=>{const m=(await tx.get('memberships',ownerId))!,u=(await tx.get('users',m.userId))!;await tx.replace('users',{...u,status:'DISABLED'});});else if(mode==='revoke')await expect(f.owner.cmd('POST','/td2/principals/'+c.resourceId+'/revoke',{schemaVersion:'once-talent-v2.1.0',expectedRevision:1}));else await expect(f.owner.cmd('POST','/td2/principals/'+c.resourceId+'/authorization',{expectedRevision:1,scopeId:mode==='scope'?formal.resourceId:intake.resourceId,defaultMaintainerMembershipId:mode==='maintainer'?reviewer.membershipId:ownerId,permissionCodes:mode==='permission'?['ingestion.read.own']:['ingestion.schema.read','ingestion.submit','ingestion.read.own','ingestion.withdraw.own']}));if(mode!=='disabled')assert.equal((await store.transaction(tx=>tx.get('servicePrincipals',c.resourceId)))!.authorizationEpoch,2);const res=await machine('POST','/ingestion/submissions/'+d+'/submit',{expectedRevision:2},randomUUID(),staleToken);assert.ok(res.status>=400);if(mode==='disabled')await store.transaction(async tx=>{const m=(await tx.get('memberships',ownerId))!,u=(await tx.get('users',m.userId))!;await tx.replace('users',{...u,status:'ACTIVE'});});}checks.push('permission-scope-maintainer-disable-and-revoke-invalidate-old-drafts');
 return {f,checks,id,personId,basisId:basis.id,servicePrincipalId:a.resourceId};
}
