import {AppError} from '../../packages/core/src/errors.ts';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {Store} from '../../packages/core/src/store.ts';
import type {CollectionPlan} from '../../packages/core/src/media-collections.ts';
import {stagingFixture,unitReady} from './media-staging.ts';
import {FaultStore} from './fault-store.ts';
export async function collectionScenario(inner:Store){
 const store=new FaultStore(inner),f=await stagingFixture(store),first=await unitReady(f),second=await unitReady(f),checks:string[]=[];
 const plan:CollectionPlan={clientItemKey:'modelcard',targetCollectionId:null,expectedCollectionRevision:null,personRoleId:null,collectionTypeCode:'MODEL_CARD',title:'秋季模卡',isCurrent:true,coverAssetId:second,tagCodes:['FASHION','BEAUTY'],items:[second,first].map(assetId=>({referenceKind:'SUBMISSION_STAGED_ASSET',assetId,caption:assetId===second?'正面':'侧面',featured:true}))};
 const save=async(collections:CollectionPlan[],status=200)=>f.expect(f.a.client.raw('POST','/portal/submissions/'+f.submissionId+'/collections',{expectedRevision:await f.revision(),collections},f.headers()),status);
 await f.expect(f.owner.cmd('POST','/td2/people/'+f.personId+'/media-collections',{schemaVersion:'once-talent-v2.1.0',expectedPersonRevision:(await store.transaction(tx=>tx.get('people',f.personId)))!.revision,sourceId:f.sourceId,sourceRevision:1,collection:{...plan,items:plan.items.map(i=>({...i,referenceKind:'EXISTING_ADOPTED_ASSET_REFERENCE'}))}}),404);checks.push('ready-staged-cannot-enter-formal-collection');
 await save([plan]);checks.push('typed-staged-collection-draft-saved');
 const saved=await f.expect(f.a.client.raw('GET','/portal/submissions/'+f.submissionId,undefined,{'x-once-talent-account':f.a.accountId}));assert.deepEqual(saved.items.find((i:any)=>i.kind==='COLLECTION').collection,plan);checks.push('server-draft-order-cover-tags-roundtrip');
 await save([{...plan,items:[...plan.items,plan.items[0]!]}],422);await save([{...plan,coverAssetId:randomUUID()}],422);checks.push('duplicate-asset-and-foreign-cover-rejected');
 await f.expect(f.a.client.raw('POST','/portal/submissions/'+f.submissionId+'/submit',{expectedRevision:await f.revision()},f.headers()));await save([plan],409);checks.push('submitted-collection-frozen');
 const body={expectedRevision:await f.revision(),acceptedKeys:['name','aliases','intro','media_'+first,'media_'+second,'modelcard'],publicReason:'模卡顺序、封面和来源核对通过'},key=randomUUID();
 await f.expect(f.owner.cmd('POST','/talent-submissions/'+f.submissionId+'/decide',{...body,acceptedKeys:['modelcard']}),422);checks.push('collection-cannot-adopt-without-staged-dependencies');
 store.afterInsert=(table)=>{if(table==='audits'){store.afterInsert=null;throw new AppError(503,'AUDIT_FAULT','synthetic');}};await f.expect(f.owner.cmd('POST','/talent-submissions/'+f.submissionId+'/decide',body),503);assert.equal((await store.transaction(tx=>tx.find('mediaCollections'))).length,0);assert.equal((await store.transaction(tx=>tx.get('assets',first)))!.usageState,'STAGED');checks.push('audit-failure-rolls-back-adoption-and-collection');
 await f.expect(f.owner.cmd('POST','/talent-submissions/'+f.submissionId+'/decide',body,key));await f.expect(f.owner.cmd('POST','/talent-submissions/'+f.submissionId+'/decide',body,key));checks.push('review-atomic-and-same-key-replayed');
 const collection=(await store.transaction(tx=>tx.find('mediaCollections')))[0]!,items=await store.transaction(tx=>tx.find('mediaCollectionItems',{collectionId:collection.id}));assert.equal(collection.coverAssetId,second);assert.equal(collection.isCurrent,true);assert.deepEqual(items.sort((a,b)=>a.orderIndex-b.orderIndex).map(i=>i.assetId),[second,first]);assert.equal((await store.transaction(tx=>tx.find('mediaCollectionTags'))).length,2);checks.push('formal-same-assets-order-cover-tags');
 const own=await f.expect(f.a.client.raw('GET','/portal/profiles/'+f.personId+'/collections',undefined,{'x-once-talent-account':f.a.accountId}));assert.equal(own.collections[0].title,'秋季模卡');await store.transaction(tx=>f.app.media.talentRead(tx,f.actor,first));await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,{...f.actor,talentAccountId:f.b.accountId},first)));checks.push('formal-self-read-and-cross-account-denied');
 const next=await f.expect(f.a.client.raw('POST','/portal/submissions',{schemaVersion:'once-talent-text-v1',grantId:f.grantId,consentTextVersion:'internal-directory-2026-10-v1',consentAccepted:true,items:[]},f.headers()));
 await f.expect(f.a.client.raw('POST','/portal/submissions/'+next.resourceId+'/media-consent',{expectedRevision:1,textVersion:'internal-directory-media-2026-10-v1',accepted:true},f.headers()));
 const reuse={...plan,title:'第二版模卡',coverAssetId:first,tagCodes:['COMMERCIAL'],items:[{referenceKind:'EXISTING_ADOPTED_ASSET_REFERENCE',assetId:first,caption:'原件复用',featured:true}]};
 await f.expect(f.a.client.raw('POST','/portal/submissions/'+next.resourceId+'/collections',{expectedRevision:2,collections:[reuse]},f.headers()));await f.expect(f.a.client.raw('POST','/portal/submissions/'+next.resourceId+'/submit',{expectedRevision:3},f.headers()));await f.expect(f.owner.cmd('POST','/talent-submissions/'+next.resourceId+'/decide',{expectedRevision:4,acceptedKeys:['modelcard'],publicReason:'跨提交正式素材复用'}));assert.equal((await store.transaction(tx=>tx.find('assets'))).length,2);const versions=await store.transaction(tx=>tx.find('mediaCollections'));assert.equal(versions.filter(c=>c.isCurrent).length,1);assert.equal(versions.find(c=>c.id===collection.id)!.isCurrent,false);checks.push('cross-submission-adopted-reference-no-file-copy-one-current-version');
 const latest=versions.find(c=>c.isCurrent)!;const detail=await f.expect(f.owner.raw('GET','/td2/people/'+f.personId));assert.ok(detail.facts.mediaCollections.some((c:any)=>c.id===latest.id&&c.isCurrent));assert.equal(detail.facts.talentProfiles[0].coverAssetId,null);checks.push('collection-cover-never-mutates-person-cover');
 const remove=items[0]!;await f.expect(f.owner.cmd('POST','/td2/collections/'+collection.id+'/items/remove',{schemaVersion:'once-talent-v2.1.0',expectedRevision:(await store.transaction(tx=>tx.get('mediaCollections',collection.id)))!.revision,expectedPersonRevision:(await store.transaction(tx=>tx.get('people',f.personId)))!.revision,itemId:remove.id}));assert.equal((await store.transaction(tx=>tx.get('assets',remove.assetId)))!.usageState,'ADOPTED');assert.equal((await store.transaction(tx=>tx.get('mediaCollections',collection.id)))!.coverAssetId,null);checks.push('remove-link-clears-cover-without-retiring-original');
 return {f,checks,first,second,collection:latest};
}
export async function collectionSecurityScenario(store:Store){
 const {f,first,second,collection,checks}=await collectionScenario(store);
 const actor=await store.transaction(tx=>f.app.identity.authenticate(tx,f.owner.jar.once_session!));
 const request=async(plan:CollectionPlan,key=randomUUID())=>f.owner.cmd('POST','/td2/people/'+f.personId+'/media-collections',{schemaVersion:'once-talent-v2.1.0',expectedPersonRevision:(await store.transaction(tx=>tx.get('people',f.personId)))!.revision,sourceId:f.sourceId,sourceRevision:1,collection:plan},key);
 const upload=await f.expect(f.owner.cmd('POST','/uploads',{sourceId:f.sourceId,expectedSourceRevision:1,personId:f.personId,fileName:'independent.jpg',mime:'image/jpeg',expectedBytes:100,sha256:'c'.repeat(64)}),201);const internalId=upload.resourceId;
 const receive=await store.transaction(tx=>f.app.media.beginReceive(tx,actor,internalId,100));await store.transaction(tx=>f.app.media.finishReceive(tx,actor,internalId,receive.receiveToken!,100,'c'.repeat(64)));await f.expect(f.owner.cmd('POST','/uploads/'+internalId+'/complete',{expectedRevision:(await store.transaction(tx=>tx.get('uploads',internalId)))!.revision}),202);const lease=await f.app.media.claim();assert.ok(lease);await f.app.media.finish(lease,{mime:'image/jpeg',bytes:100,sha256:'c'.repeat(64),width:10,height:10,previewBytes:50,previewHash:'d'.repeat(64)});
 const plan:CollectionPlan={clientItemKey:'portfolio',targetCollectionId:null,expectedCollectionRevision:null,personRoleId:null,collectionTypeCode:'PORTFOLIO',title:'跨来源作品集',isCurrent:false,coverAssetId:first,tagCodes:['COMMERCIAL'],items:[first,internalId].map(assetId=>({referenceKind:'EXISTING_ADOPTED_ASSET_REFERENCE',assetId,caption:'正式素材',featured:false}))};
 const saved=await f.expect(request(plan));checks.push('internal-collection-formal-person-source-authority');
 const forbidden=await f.expect(request({...plan,collectionTypeCode:'SHOWREEL'}),422);assert.equal(forbidden.error.code,'COLLECTION_MEDIA_TYPE');checks.push('image-in-showreel-rejected');
 const duplicate=await request({...plan,tagCodes:['FASHION','FASHION']});assert.equal(duplicate.status,422);checks.push('duplicate-tag-rejected');
 const unknown=await request({...plan,tagCodes:['unknown'] as any});assert.equal(unknown.status,400);checks.push('unknown-tag-code-rejected');
 const foreign=await f.expect(f.owner.cmd('POST','/directory/talents',{schemaVersion:'once-talent-experience-v1',kind:'TALENT',displayName:'另一人',sourceId:f.sourceId,sourceRevision:1}),201);
 const response=await f.owner.cmd('POST','/td2/people/'+foreign.resourceId+'/media-collections',{schemaVersion:'once-talent-v2.1.0',expectedPersonRevision:foreign.revision,sourceId:f.sourceId,sourceRevision:1,collection:plan});assert.equal(response.status,422);checks.push('foreign-person-formal-asset-rejected');
 const role=(await store.transaction(tx=>tx.find('personRoles',{personId:f.personId})))[0]!;
 const old=(await store.transaction(tx=>tx.find('personMedia',{assetId:first})))[0]!;
 await store.transaction(tx=>tx.replace('personMedia',{...old,personRoleId:role.id}));await f.expect(request(plan),422);await store.transaction(tx=>tx.replace('personMedia',old));checks.push('role-specific-asset-cannot-be-borrowed-by-person-general-collection');
 const a=(await store.transaction(tx=>tx.get('assets',first)))!;await store.transaction(tx=>tx.replace('assets',{...a,state:'QUARANTINED'}));await f.expect(request(plan),404);await store.transaction(tx=>tx.replace('assets',a));checks.push('quarantined-media-rejected');
 await store.transaction(async tx=>{await tx.replace('assets',{...a,usageState:'RETIRED'});await tx.replace('personMedia',{...old,usageState:'RETIRED',retiredAt:f.clock.now().toISOString()});});await f.expect(request(plan),404);await store.transaction(async tx=>{await tx.replace('assets',a);await tx.replace('personMedia',old);});checks.push('retired-media-rejected');

 const draft=await f.expect(f.a.client.raw('POST','/portal/submissions',{schemaVersion:'once-talent-text-v1',grantId:f.grantId,consentTextVersion:'internal-directory-2026-10-v1',consentAccepted:true,items:[]},f.headers()));
 const ref={...plan,items:[{...plan.items[0]!,referenceKind:'SUBMISSION_STAGED_ASSET'}]};await f.expect(f.a.client.raw('POST','/portal/submissions/'+draft.resourceId+'/collections',{expectedRevision:1,collections:[ref]},f.headers()),409);checks.push('media-consent-required-even-existing-reference');
 const input={schemaVersion:'once-talent-v2.1.0',expectedPersonRevision:(await store.transaction(tx=>tx.get('people',f.personId)))!.revision,sourceId:f.sourceId,sourceRevision:1,collection:{...plan,targetCollectionId:saved.resourceId,expectedCollectionRevision:1,items:[...plan.items].reverse()}};
 const key=randomUUID(),race=await Promise.all([1,2].map(()=>f.owner.cmd('POST','/td2/people/'+f.personId+'/media-collections',input,key)));assert.ok(race.every(r=>r.status===200),JSON.stringify(race.map(r=>r.body)));assert.equal((race[0]!.body as any).resourceId,(race[1]!.body as any).resourceId);checks.push('concurrent-same-key-single-order-command');
 const c=(await store.transaction(tx=>tx.get('mediaCollections',saved.resourceId)))!;const next={...input,expectedPersonRevision:(await store.transaction(tx=>tx.get('people',f.personId)))!.revision,collection:{...input.collection,expectedCollectionRevision:c.revision}};
 const conflict=await Promise.all([1,2].map(()=>f.owner.cmd('POST','/td2/people/'+f.personId+'/media-collections',next)));assert.deepEqual(conflict.map(r=>r.status).sort(),[200,409]);checks.push('concurrent-new-keys-cas-conflict-no-duplicate-order');
 // Source A is original Person source; source B is self material. Withdrawing B must not erase the independent collection A.
 const relation=(await store.transaction(tx=>tx.find('personMedia',{assetId:first})))[0]!,source=(await store.transaction(tx=>tx.get('sources',relation.sourceId!)))!;
 await store.transaction(tx=>tx.replace('sources',{...source,internalUseUntil:f.clock.now().toISOString()}));
 const visible=await f.expect(f.owner.raw('GET','/td2/people/'+f.personId));const retained=visible.facts.mediaCollections.find((v:any)=>v.id===saved.resourceId);assert.ok(retained);assert.equal(retained.items.length,1);assert.equal(retained.items[0].assetId,internalId);assert.equal(retained.coverAssetId,null);await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,f.actor,first)));checks.push('withdraw-item-source-filters-items-cover-without-deleting-independent-collection');
 await store.transaction(tx=>tx.replace('sources',source));const collectionSource=(await store.transaction(tx=>tx.get('sources',f.sourceId)))!;await store.transaction(tx=>tx.replace('sources',{...collectionSource,status:'SUSPENDED'}));const hidden=await f.expect(f.owner.raw('GET','/td2/people/'+f.personId));assert.equal(hidden.facts.mediaCollections.find((c:any)=>c.id===saved.resourceId)?.usable??false,false);await store.transaction(tx=>tx.replace('sources',collectionSource));checks.push('collection-own-source-suspension-disables-whole-collection');const grant=(await store.transaction(tx=>tx.get('talentAccessGrants',f.grantId!)))!;await f.expect(f.owner.cmd('POST','/talent-grants/'+grant.id+'/revoke',{expectedRevision:grant.revision}));await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,f.actor,first)));const denied=await f.a.client.raw('GET','/portal/profiles/'+f.personId+'/collections',undefined,{'x-once-talent-account':f.a.accountId});assert.equal(denied.status,404);checks.push('revoked-grant-blocks-formal-gallery-and-original');
 return {checks};
}
export async function collectionEnrollScenario(store:Store){
 const f=await stagingFixture(store,false),assetId=await unitReady(f),checks:string[]=[];
 const plan:CollectionPlan={clientItemKey:'enroll-card',targetCollectionId:null,expectedCollectionRevision:null,personRoleId:null,collectionTypeCode:'MODEL_CARD',title:'加入申请模卡',isCurrent:true,coverAssetId:assetId,tagCodes:['LIFESTYLE'],items:[{assetId,referenceKind:'SUBMISSION_STAGED_ASSET',caption:'本人新材料',featured:true}]};
 const save=async(p:CollectionPlan,status=200)=>f.expect(f.a.client.raw('POST','/portal/submissions/'+f.submissionId+'/collections',{expectedRevision:await f.revision(),collections:[p]},f.headers()),status);
 await save({...plan,items:[{...plan.items[0]!,referenceKind:'EXISTING_ADOPTED_ASSET_REFERENCE'}]},422);checks.push('enroll-existing-reference-always-denied');
 await save(plan);assert.equal((await store.transaction(tx=>tx.get('talentSubmissions',f.submissionId)))!.personId,null);assert.equal((await store.transaction(tx=>tx.find('mediaCollections'))).length,0);checks.push('enroll-collection-draft-no-fake-person');
 await f.expect(f.a.client.raw('POST','/portal/submissions/'+f.submissionId+'/submit',{expectedRevision:await f.revision()},f.headers()));await f.expect(f.owner.cmd('POST','/talent-submissions/'+f.submissionId+'/decide',{expectedRevision:await f.revision(),acceptedKeys:['name','aliases','intro','media_'+assetId,'enroll-card'],createPerson:true,ownershipBasis:'真实加入本人的独立确认',guardianConfirmed:false,publicReason:'采纳模卡'}));
 const c=(await store.transaction(tx=>tx.find('mediaCollections')))[0]!,r=(await store.transaction(tx=>tx.find('personMedia',{assetId})))[0]!;assert.equal(c.personId,r.personId);assert.equal(c.coverAssetId,assetId);await store.transaction(tx=>f.app.media.talentRead(tx,f.actor,assetId));checks.push('enroll-adoption-creates-person-grant-collection-in-one-transaction');
 const person=(await store.transaction(tx=>tx.get('people',c.personId)))!,input={targetKind:'PERSON',targetId:person.id,expectedRevision:person.revision};const preview=await f.expect(f.owner.raw('POST','/deletion-requests/preview',input));assert.equal(preview.complete,true,JSON.stringify(preview.unresolved));const deletion=await f.expect(f.owner.cmd('POST','/deletion-requests',{...input,previewDigest:preview.previewDigest,reason:'合成集合删除阻断验收'}),201);await f.expect(f.owner.cmd('POST','/deletion-requests/'+deletion.resourceId+'/block',{expectedRevision:1,previewDigest:preview.previewDigest,acknowledgeBlock:true}));await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,f.actor,assetId)));assert.equal((await f.a.client.raw('GET','/portal/profiles/'+person.id+'/collections',undefined,{'x-once-talent-account':f.a.accountId})).status,404);assert.equal((await store.transaction(tx=>tx.get('uploads',assetId)))!.purgedAt,null);checks.push('person-deletion-blocks-collection-and-bytes-before-physical-cleanup');return {checks};
}
export async function collectionExportScenario(store:Store){
 const {f,first,second,collection,checks}=await collectionScenario(store);
 const sourceFields=['source.title','source.type','source.providerClaim','source.basisMode','source.basisDescription','source.validFrom','source.validUntil','source.status'];
 const personFields=['person.displayName','person.aliases','person.intro','person.status','person.td2.talentProfiles','person.td2.personRoles','person.identityEvidence','person.td2.mediaCollections','person.td2.mediaCollectionTags','person.td2.fieldEvidence'];const refs:string[]=[];
 for(const source of await store.transaction(tx=>tx.find('sources')))refs.push((await f.expect(f.owner.cmd('POST','/use-permissions',{subjectKind:'SOURCE',subjectId:source.id,sourceId:source.id,fields:[...sourceFields,...personFields.filter(k=>k!=='person.status'),'media.originals'],validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成集合多来源导出许可'}),201)).resourceId);
 refs.push((await f.expect(f.owner.cmd('POST','/use-permissions',{subjectKind:'PERSON',subjectId:f.personId,sourceId:f.sourceId,fields:personFields,validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成集合整个人物导出许可'}),201)).resourceId);
 for(const id of [first,second]){const r=(await store.transaction(tx=>tx.find('personMedia',{assetId:id})))[0]!;refs.push((await f.expect(f.owner.cmd('POST','/use-permissions',{subjectKind:'ASSET',subjectId:id,sourceId:r.sourceId,fields:['media.originals'],validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成集合原件导出许可'}),201)).resourceId);}
 const exported=await f.expect(f.owner.cmd('POST','/exports',{format:'JSON',selectedIds:{people:[f.personId],works:[],projects:[]},fields:[...sourceFields,...personFields,'media.originals'],usePermissionRefs:refs}),202);const claim=await f.app.exports.claim();assert.ok(claim);await f.app.exports.process(claim);const download=await f.expect(f.owner.raw('POST','/exports/'+exported.resourceId+'/download',{}));const payload=download.payload;
 const row=payload.manifest.talent.tables.mediaCollections.find((r:any)=>r.id===collection.id);assert.equal(row.data.coverAssetId,first);assert.equal(row.data.isCurrent,true);assert.equal(payload.manifest.talent.assets.length,2);assert.ok(!JSON.stringify(payload).includes('SUBMISSION_STAGED_ASSET'));checks.push('real-export-worker-formal-collection-cover-current-order-tags-without-draft');return {f,payload,first,second,collection,checks};
}
export async function collectionMergeScenario(store:Store){
 const {f,first,collection,checks}=await collectionScenario(store);const {mergePreview,mergeInput}=await import('./talent-v2-merge.ts');
 const canonical=await f.expect(f.owner.cmd('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',displayName:'主档案',originSourceId:f.sourceId,sourceRevision:1}),201);const preview=await mergePreview(store,f.owner,canonical.resourceId,f.personId);assert.equal(preview.complete,true,JSON.stringify(preview.blockers));await f.expect(f.owner.cmd('POST','/people/merge',mergeInput(preview)));
 assert.equal((await store.transaction(tx=>tx.get('mediaCollections',collection.id)))!.personId,canonical.resourceId);assert.equal((await store.transaction(tx=>tx.find('mediaCollectionItems',{collectionId:collection.id})))[0]!.personId,canonical.resourceId);assert.equal((await store.transaction(tx=>tx.find('personMedia',{assetId:first})))[0]!.personId,canonical.resourceId);await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,f.actor,first)));checks.push('actual-person-merge-moves-formal-collections-cover-items-and-revokes-old-grant');return {checks};
}
export async function collectionRebuildScenario(store:Store,targetStore:Store){
 const {f,payload,first,collection,checks}=await collectionExportScenario(store),{authFixture}=await import('./talent-auth.ts'),target=await authFixture(targetStore);target.clock.value=f.clock.value;
 const {JsonRebuild}=await import('../../packages/core/src/rebuild.ts'),{prepareRebuildMedia}=await import('../../scripts/rebuild-media.ts'),{unitOriginal,unitPreview}=await import('./media-staging.ts');const {mkdtemp,mkdir,writeFile,rm,realpath}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path');
 const root=await mkdtemp(join(await realpath(tmpdir()),'once-collection-rebuild-'));try{const input=join(root,'input');await mkdir(input,{mode:0o700});for(const asset of payload.manifest.talent.assets){await writeFile(join(input,asset.id+'.original.bin'),unitOriginal);await writeFile(join(input,asset.id+'.preview.jpg'),unitPreview);}const r=new JsonRebuild(target.clock),actor=await targetStore.transaction(tx=>r.actorFromTarget(tx,'owner')),media=await prepareRebuildMedia(payload,actor.workspaceId,{REBUILD_MEDIA_INPUT_DIR:input,REBUILD_MEDIA_TARGET_DIR:join(root,'target')},true);await targetStore.transaction(tx=>new JsonRebuild(target.clock,undefined,media).apply(tx,actor,payload,{requestId:randomUUID(),ip:'test'}));const rebuilt=(await targetStore.transaction(tx=>tx.get('mediaCollections',collection.id)))!;assert.equal(rebuilt.coverAssetId,first);assert.equal(rebuilt.isCurrent,true);assert.equal((await targetStore.transaction(tx=>tx.find('mediaCollectionItems'))).length,payload.manifest.talent.collectionItems.length);assert.equal((await targetStore.transaction(tx=>tx.find('talentAccessGrants'))).length,0);assert.equal((await targetStore.transaction(tx=>tx.find('talentSubmissions'))).length,0);checks.push('json-rebuild-preserves-cover-current-order-tags-sources-without-authorizations-or-drafts');return {checks};}finally{await rm(root,{recursive:true,force:true});}
}
