import {AppError} from '../../packages/core/src/errors.ts';
import {base} from '../../packages/core/src/helpers.ts';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {Store} from '../../packages/core/src/store.ts';
import type {CollectionPlan} from '../../packages/core/src/media-collections.ts';
import {collectionScenario} from './media-collections.ts';
import {sourceInput,Client} from './fixtures.ts';
export async function collectionFinalizationScenario(store:Store){
 const {f,collection,first,checks}=await collectionScenario(store);
 const get=<K extends import('../../packages/core/src/model.ts').Table>(table:K,id:string)=>store.transaction(tx=>tx.get(table,id));
 const personRev=async()=>(await get('people',f.personId))!.revision;
 const gallery=()=>f.expect(f.a.client.raw('GET','/portal/profiles/'+f.personId+'/collections',undefined,{'x-once-talent-account':f.a.accountId}));
 const plan:CollectionPlan={clientItemKey:'final-card',targetCollectionId:collection.id,expectedCollectionRevision:collection.revision,personRoleId:null,collectionTypeCode:'MODEL_CARD',title:'明确开放的模卡',isCurrent:true,coverAssetId:first,tagCodes:['COMMERCIAL'],items:[{referenceKind:'EXISTING_ADOPTED_ASSET_REFERENCE',assetId:first,caption:'原图',featured:false}]};
 const saveInternal=async(p:CollectionPlan,sourceId=f.sourceId)=>f.owner.cmd('POST','/td2/people/'+f.personId+'/media-collections',{schemaVersion:'once-talent-v2.1.0',expectedPersonRevision:await personRev(),sourceId,sourceRevision:(await get('sources',sourceId))!.revision,collection:p});
 const grant=()=>get('talentAccessGrants',f.grantId!);
 const expose=async(assets:string[],collections:string[]=[],decision='ALLOW',key=randomUUID())=>f.owner.cmd('POST','/talent-grants/'+f.grantId+'/media-exposure',{expectedRevision:(await grant())!.revision,decision,assets:await Promise.all(assets.map(async id=>({id,expectedRevision:(await get('assets',id))!.revision}))),collections:await Promise.all(collections.map(async id=>({id,expectedRevision:(await get('mediaCollections',id))!.revision}))),approvalBasis:'内部核对当前版本，明确开放给当前本人维护'},key);
 const draft=async(p:CollectionPlan)=>{const r=await f.expect(f.a.client.raw('POST','/portal/submissions',{schemaVersion:'once-talent-text-v1',grantId:f.grantId,consentTextVersion:'internal-directory-2026-10-v1',consentAccepted:true,items:[]},f.headers()));await f.expect(f.a.client.raw('POST','/portal/submissions/'+r.resourceId+'/media-consent',{expectedRevision:1,textVersion:'internal-directory-media-2026-10-v1',accepted:true},f.headers()));return {id:r.resourceId,save:()=>f.a.client.raw('POST','/portal/submissions/'+r.resourceId+'/collections',{expectedRevision:2,collections:[p]},f.headers())};};
 // Existing collection identity is immutable across all three commands.
 const bad={...plan,collectionTypeCode:'PORTFOLIO' as const};assert.equal((await f.expect(saveInternal(bad),409)).error.code,'COLLECTION_IDENTITY_CONFLICT');
 const badDraft=await draft(bad);assert.equal((await f.expect(badDraft.save(),409)).error.code,'COLLECTION_IDENTITY_CONFLICT');
 const genericBad=await f.owner.cmd('PATCH','/td2/collections/'+collection.id,{schemaVersion:'once-talent-v2.1.0',expectedRevision:collection.revision,expectedPersonRevision:await personRev(),sourceId:collection.sourceId,sourceRevision:(await get('sources',collection.sourceId))!.revision,values:{collectionTypeCode:'PORTFOLIO'}});assert.equal(genericBad.status,409,JSON.stringify(genericBad.body));
 const portfolio=await f.expect(saveInternal({...bad,targetCollectionId:null,expectedCollectionRevision:null,isCurrent:false}));checks.push('collection-type-identity-portal-internal-generic-conflict-new-type-allowed');
 // Actual employee upload goes through all technical stages; no synthetic Membership/uploader mutation.
 const actor=await store.transaction(tx=>f.app.identity.authenticate(tx,f.owner.jar.once_session!));
 const uploaded=await f.expect(f.owner.cmd('POST','/uploads',{sourceId:f.sourceId,expectedSourceRevision:1,personId:f.personId,fileName:'employee-approved.jpg',mime:'image/jpeg',expectedBytes:100,sha256:'c'.repeat(64)}),201),id=uploaded.resourceId;
 const receive=await store.transaction(tx=>f.app.media.beginReceive(tx,actor,id,100));await store.transaction(tx=>f.app.media.finishReceive(tx,actor,id,receive.receiveToken!,100,'c'.repeat(64)));await f.expect(f.owner.cmd('POST','/uploads/'+id+'/complete',{expectedRevision:(await get('uploads',id))!.revision}),202);const lease=await f.app.media.claim();assert.ok(lease);await f.app.media.finish(lease,{mime:'image/jpeg',bytes:100,sha256:'c'.repeat(64),width:10,height:10,previewBytes:50,previewHash:'d'.repeat(64)});
 assert.ok(!(await gallery()).assets.some((a:any)=>a.id===id));assert.ok(!(await gallery()).collections.some((c:any)=>c.id===portfolio.resourceId));await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,f.actor,id)));
 const newPlan={...plan,targetCollectionId:null,expectedCollectionRevision:null,isCurrent:false,items:[{...plan.items[0]!,assetId:id}],coverAssetId:id};const denied=await draft(newPlan);await f.expect(denied.save(),404);
 await f.expect(expose([id],[portfolio.resourceId]));assert.ok((await gallery()).assets.some((a:any)=>a.id===id));assert.ok((await gallery()).collections.some((c:any)=>c.id===portfolio.resourceId));await store.transaction(tx=>f.app.media.talentRead(tx,f.actor,id));await f.expect(denied.save());await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,{...f.actor,talentAccountId:f.b.accountId},id)));checks.push('employee-formal-media-and-collection-explicit-grant-exposure-current-account-only');
 await f.expect(expose([id],[],'REVOKE'));await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,f.actor,id)));await f.expect(expose([id]));checks.push('explicit-exposure-revocation-immediately-denies-formal-original');
 // The same grant-bound descriptor works for future machine-origin relations without opening any ingestion route.
 const original=(await get('uploads',id))!;assert.equal(original.principalKind,'INTERNAL');
 const exposure=(await grant())!.selfExposureManifest.find(e=>e.kind==='mediaAsset'&&e.targetId===id)!;assert.ok(exposure.approvedById&&exposure.approvedAt&&exposure.approvalBasis);assert.ok(!exposure.valueDigest.includes(original.actorId!));
 const exposureBody={expectedRevision:(await grant())!.revision,decision:'ALLOW',assets:[{id,expectedRevision:(await get('assets',id))!.revision}],collections:[],approvalBasis:'合成明确批准及原键回执重放'},exposureKey=randomUUID(),beforeGrant=await grant();
 const fault=f.store as import('./fault-store.ts').FaultStore;
 fault.afterInsert=(table)=>{if(table==='audits'){fault.afterInsert=null;throw new AppError(503,'SYNTHETIC_EXPOSURE_AUDIT','synthetic');}};
 await f.expect(f.owner.cmd('POST','/talent-grants/'+f.grantId+'/media-exposure',exposureBody,exposureKey),503);assert.deepEqual(await grant(),beforeGrant);
 await f.expect(f.owner.cmd('POST','/talent-grants/'+f.grantId+'/media-exposure',exposureBody,exposureKey));const replay=await f.expect(f.owner.cmd('POST','/talent-grants/'+f.grantId+'/media-exposure',exposureBody,exposureKey));assert.equal(replay.replayed,true);checks.push('exposure-audit-failure-rolls-back-grant-and-receipt-original-key-replays');
 // Simulate only a future Agent-provided, already reviewed formal origin. Keep the real INTERNAL byte uploader unchanged; PR04 machine uploads remain closed.
 const futureSource=await f.expect(f.owner.cmd('POST','/sources',{...sourceInput(),providerClaim:'合成：未来 Agent 提供并已由内部采纳的来源'}),201);
 await store.transaction(tx=>tx.insert('personMedia',{...base(actor.workspaceId,f.clock),personId:f.personId,personRoleId:null,assetId:id,sourceId:futureSource.resourceId,submissionId:null,usageState:'ADOPTED',purpose:'SUBMITTED_MATERIAL',protectionEpoch:1,retainUntil:null,retiredAt:null,purgedAt:null}));
 await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,f.actor,id)));await f.expect(expose([id]));await store.transaction(tx=>f.app.media.talentRead(tx,f.actor,id));assert.equal((await get('uploads',id))!.actorId,original.actorId);assert.equal((await get('assets',id))!.sourceId,f.sourceId);checks.push('simulated-future-agent-formal-source-needs-new-explicit-exposure-no-uploader-rewrite-or-machine-entry');
 const primary=(await get('sources',f.sourceId))!;await store.transaction(tx=>tx.replace('sources',{...primary,status:'SUSPENDED'}));await store.transaction(tx=>f.app.media.talentRead(tx,f.actor,id));await store.transaction(tx=>tx.replace('sources',primary));checks.push('independent-exposed-source-survives-primary-source-withdrawal');
 const sourceBefore=(await get('sources',futureSource.resourceId))!;await f.expect(f.owner.cmd('POST','/sources/'+futureSource.resourceId+'/suspend',{expectedRevision:sourceBefore.revision,reason:'已经开放的独立来源撤回'}));await assert.rejects(store.transaction(tx=>f.app.media.talentRead(tx,f.actor,id)));checks.push('source-revocation-invalidates-explicit-grant-exposure');
 // Tag generic create and patch both advance parent; a saved and submitted Talent plan cannot overwrite either.
 const stale=await draft({...plan,expectedCollectionRevision:(await get('mediaCollections',collection.id))!.revision});await f.expect(stale.save());await f.expect(f.a.client.raw('POST','/portal/submissions/'+stale.id+'/submit',{expectedRevision:3},f.headers()));
 const tagSource=await f.expect(f.owner.cmd('POST','/sources',{...sourceInput(),title:'标签旧来源 A'}),201);
 const before=(await get('mediaCollections',collection.id))!;
 const tag=await f.expect(f.owner.cmd('POST','/td2/people/'+f.personId+'/collection-tags',{schemaVersion:'once-talent-v2.1.0',expectedPersonRevision:await personRev(),sourceId:tagSource.resourceId,sourceRevision:1,values:{collectionId:collection.id,tagCode:'FASHION',status:'ACTIVE'}}),201);assert.equal((await get('mediaCollections',collection.id))!.revision,before.revision+1);
 const review={expectedRevision:4,acceptedKeys:[plan.clientItemKey],publicReason:'旧集合草稿必须发生版本冲突'};await f.expect(f.owner.cmd('POST','/talent-submissions/'+stale.id+'/decide',review),409);
 await f.expect(f.owner.cmd('PATCH','/td2/collection-tags/'+tag.resourceId,{schemaVersion:'once-talent-v2.1.0',expectedPersonRevision:await personRev(),expectedRevision:1,sourceId:tagSource.resourceId,sourceRevision:1,values:{status:'ARCHIVED'}}));assert.equal((await get('mediaCollections',collection.id))!.revision,before.revision+2);await f.expect(f.owner.cmd('POST','/talent-submissions/'+stale.id+'/decide',review),409);assert.equal((await get('talentSubmissions',stale.id))!.state,'SUBMITTED');checks.push('generic-tag-create-and-patch-advance-parent-saved-draft-review-conflicts');
 // Tag A can expire independently of its collection; reconfirmation records Source B and keeps A's evidence.
 await f.expect(f.owner.cmd('POST','/sources/'+tagSource.resourceId+'/suspend',{expectedRevision:1,reason:'标签旧依据已撤回'}));
 await f.expect(saveInternal({...plan,expectedCollectionRevision:(await get('mediaCollections',collection.id))!.revision,tagCodes:['FASHION','COMMERCIAL']}));const renewed=(await get('mediaCollectionTags',tag.resourceId))!;assert.equal(renewed.sourceId,f.sourceId);assert.equal(renewed.status,'ACTIVE');
 const detail=await f.expect(f.owner.raw('GET','/td2/people/'+f.personId));assert.ok(detail.facts.mediaCollectionTags.some((r:any)=>r.id===renewed.id));const history=await store.transaction(tx=>tx.find('evidence',{mediaCollectionTagId:renewed.id}));assert.ok(history.length>=3);assert.ok(history.some(e=>e.sourceId===tagSource.resourceId));assert.ok(history.some(e=>e.sourceId===f.sourceId&&e.reviewerId===actor.membershipId));checks.push('archived-tag-reenabled-with-current-approval-source-history-preserved');
 // A current collection's old Source may be suspended: clearing current uses new Source, but still requires old scope.
 const staleSource=await f.expect(f.owner.cmd('POST','/sources',{...sourceInput(),title:'旧 current 来源'}),201);
 const oldCurrent=await f.expect(saveInternal({...plan,targetCollectionId:null,expectedCollectionRevision:null,items:[],coverAssetId:null,tagCodes:[]},staleSource.resourceId));await f.expect(f.owner.cmd('POST','/sources/'+staleSource.resourceId+'/suspend',{expectedRevision:1,reason:'旧 current 来源撤回'}));
 const latest=await f.expect(saveInternal({...plan,targetCollectionId:null,expectedCollectionRevision:null,items:[],coverAssetId:null,tagCodes:[]}));assert.equal((await get('mediaCollections',oldCurrent.resourceId))!.isCurrent,false);assert.equal((await get('mediaCollections',latest.resourceId))!.isCurrent,true);const proof=await store.transaction(tx=>tx.find('evidence',{mediaCollectionId:oldCurrent.resourceId,fieldPath:'isCurrent'}));assert.ok(proof.some(e=>e.sourceId===f.sourceId&&e.reviewerId===actor.membershipId));checks.push('suspended-old-current-can-be-retired-with-new-valid-review-basis');
 const other=await f.expect(f.owner.raw('POST','/memberships',{loginName:'collection-scope-negative',displayName:'无旧范围员工',role:'ADMIN',extraPermissions:[]}),201),staff=new Client(f.app,'192.0.2.66');await f.expect(staff.activate(other.activationToken));await f.expect(staff.login('collection-scope-negative'));
 const hiddenScope=await f.expect(f.owner.cmd('POST','/scopes',{name:'隐藏旧集合来源',membershipIds:[actor.membershipId]}),201),hiddenSource=await f.expect(f.owner.cmd('POST','/sources',{...sourceInput(),scopeId:hiddenScope.resourceId}),201);
 await f.expect(saveInternal({...plan,targetCollectionId:null,expectedCollectionRevision:null,items:[],coverAssetId:null,tagCodes:[]},hiddenSource.resourceId));await f.expect(f.owner.cmd('POST','/sources/'+hiddenSource.resourceId+'/suspend',{expectedRevision:1,reason:'隐藏来源撤回'}));
 const hidden=await staff.cmd('POST','/td2/people/'+f.personId+'/media-collections',{schemaVersion:'once-talent-v2.1.0',expectedPersonRevision:await personRev(),sourceId:f.sourceId,sourceRevision:1,collection:{...plan,targetCollectionId:null,expectedCollectionRevision:null,items:[],coverAssetId:null,tagCodes:[]}});assert.equal(hidden.status,404,JSON.stringify(hidden.body));checks.push('hidden-old-current-scope-fails-closed');
 return {checks};
}
