import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import type {Store} from '../../packages/core/src/store.ts';
import {authFixture,loginTalent} from './talent-auth.ts';
import {result,sourceInput} from './fixtures.ts';
export async function maintenanceFixture(store:Store){const f=await authFixture(store),a=await loginTalent(f,'Anna@example.com'),b=await loginTalent(f,'Other@example.com');const source=await f.owner.cmd('POST','/sources',sourceInput());assert.equal(source.status,201,JSON.stringify(source.body));const person=await f.owner.cmd('POST','/directory/talents',{schemaVersion:'once-talent-experience-v1',kind:'TALENT',displayName:'Anna internal',sourceId:result(source).resourceId,sourceRevision:1});assert.equal(person.status,201,JSON.stringify(person.body));const personId=result(person).resourceId;const scopes=await f.owner.raw('GET','/scopes');const scope=await f.owner.cmd('POST','/scopes',{name:'申请限定审核',membershipIds:[(await store.transaction(tx=>tx.find('memberships')))[0]!.id]});assert.equal(scope.status,201,JSON.stringify(scope.body));return {...f,a,b,personId,scopeId:result(scope).resourceId,sourceId:result(source).resourceId};}
export async function verifyTalentMaintenance(store:Store){const f=await maintenanceFixture(store),checks:string[]=[];const mark=(s:string)=>checks.push(s);const headers=(who=f.a,key=randomUUID())=>({'x-once-talent-account':who.accountId,'idempotency-key':key});
 const makeInvite=async(purpose='CLAIM',extra={})=>{const create=await f.owner.cmd('POST','/talent-invitations',{purpose,...(purpose==='CLAIM'?{targetPersonId:f.personId}:{}),scopeId:f.scopeId,exposureFields:['displayName'],...extra});assert.equal(create.status,200,JSON.stringify(create.body));const issue=await f.owner.raw('POST','/talent-invitations/'+result(create).resourceId+'/issue',{expectedRevision:1});assert.equal(issue.status,200,JSON.stringify(issue.body));const link=new URL(result(issue).url),frag=new URLSearchParams(link.hash.slice(1));return {id:result(create).resourceId,token:frag.get('t'),revision:result(issue).revision};};
 const exchange=async(inv:Awaited<ReturnType<typeof makeInvite>>,who=f.a)=>{const res=await who.client.raw('POST','/portal/invitations/exchange',{invitationId:inv.id,token:inv.token},{'x-once-portal':'1'});assert.equal(res.status,200,JSON.stringify(res.body));return result(res).contextId;};
 const inv=await makeInvite('CLAIM',{recipientKind:'EMAIL',recipient:'Anna@example.com'}),context=await exchange(inv),wrongContext=await exchange(inv,f.b);
 const wrong=await f.b.client.raw('POST','/portal/claims',{contextId:wrongContext,relation:'SELF',applicantKey:'SELF',adultDeclared:true},headers(f.b));assert.equal(wrong.status,403);mark('directed-recipient-mismatch-denied');
 const key=randomUUID(),claimInput={contextId:context,relation:'SELF',applicantKey:'SELF',adultDeclared:true};const claim=await f.a.client.raw('POST','/portal/claims',claimInput,headers(f.a,key));assert.equal(claim.status,200,JSON.stringify(claim.body));const claimId=result(claim).resourceId;
 assert.equal((await f.a.client.raw('GET','/portal/profiles/'+f.personId,undefined,headers())).status,404);assert.equal((await f.a.client.raw('GET','/portal/profiles',undefined,headers())).status,200);mark('pending-claim-no-person-access');
 const decide=await f.owner.cmd('POST','/talent-claims/'+claimId+'/decide',{expectedRevision:1,decision:'APPROVE',ownershipBasis:'测试：独立电话联系确认本人归属',guardianConfirmed:false});assert.equal(decide.status,200,JSON.stringify(decide.body));
 const replay=await f.a.client.raw('POST','/portal/claims',claimInput,headers(f.a,key));assert.equal(replay.status,200,JSON.stringify(replay.body));assert.equal(result(replay).replayed,true);mark('claim-replay-after-invitation-consumption');
 const profile=await f.a.client.raw('GET','/portal/profiles/'+f.personId,undefined,headers());assert.equal(profile.status,200);assert.deepEqual(result(profile).fields,{displayName:'Anna internal'});const grantId=result(profile).grantId;
 assert.equal((await f.a.client.raw('GET','/portal/profiles/'+f.personId)).status,409);assert.equal((await f.b.client.raw('GET','/portal/profiles/'+f.personId,undefined,headers(f.a))).status,409);assert.equal((await f.b.client.raw('GET','/portal/profiles/'+f.personId,undefined,headers(f.b))).status,404);mark('read-account-header-and-grant-person-ownership');
 const items=[{clientItemKey:'name',field:'displayName',text:'Anna self',dependencyGroup:'identity',dependsOn:[]},{clientItemKey:'aliases',field:'aliases',aliases:[],dependencyGroup:'identity',dependsOn:[]},{clientItemKey:'intro',field:'intro',text:'本人新的文字介绍',dependencyGroup:'identity',dependsOn:['name']}];
 const draftInput={schemaVersion:'once-talent-text-v1',grantId,consentTextVersion:'internal-directory-2026-10-v1',consentAccepted:true,items};const draft=await f.a.client.raw('POST','/portal/submissions',draftInput,headers());assert.equal(draft.status,200,JSON.stringify(draft.body));const sid=result(draft).resourceId;
 assert.equal((await f.b.client.raw('GET','/portal/submissions/'+sid,undefined,headers(f.b))).status,404);assert.equal((await f.b.client.raw('PATCH','/portal/submissions/'+sid,{expectedRevision:1,items},headers(f.b))).status,404);mark('draft-owner-read-write-isolation');
 const saved=await f.a.client.raw('PATCH','/portal/submissions/'+sid,{expectedRevision:1,items},headers());assert.equal(saved.status,200,JSON.stringify(saved.body));const submit=await f.a.client.raw('POST','/portal/submissions/'+sid+'/submit',{expectedRevision:2},headers());assert.equal(submit.status,200,JSON.stringify(submit.body));assert.equal((await f.a.client.raw('PATCH','/portal/submissions/'+sid,{expectedRevision:3,items},headers())).status,409);mark('server-draft-cas-and-submitted-immutable');
 const partial=await f.owner.cmd('POST','/talent-submissions/'+sid+'/decide',{expectedRevision:3,acceptedKeys:['name'],publicReason:''});assert.equal(partial.status,422,JSON.stringify(partial.body));assert.equal((await store.transaction(tx=>tx.get('people',f.personId)))!.displayName,'Anna internal');mark('dependency-group-atomic-rejection');
 const approved=await f.owner.cmd('POST','/talent-submissions/'+sid+'/decide',{expectedRevision:3,acceptedKeys:['name','aliases','intro'],publicReason:'已采纳文字声明'});assert.equal(approved.status,200,JSON.stringify(approved.body));assert.equal((await store.transaction(tx=>tx.get('people',f.personId)))!.displayName,'Anna self');
 const after=await f.a.client.raw('GET','/portal/profiles/'+f.personId,undefined,headers());assert.equal(result(after).fields.intro,'本人新的文字介绍');const rows=await store.transaction(async tx=>({attribution:await tx.find('sourceAttributions'),basis:await tx.find('sourceUseBases'),receipts:await tx.find('receipts')}));assert.equal(rows.attribution[0]!.talentAccountId,f.a.accountId);assert.ok(rows.attribution[0]!.reviewerId);assert.ok(!JSON.stringify(rows.receipts).includes('本人新的文字介绍'));mark('same-person-adoption-source-provider-reviewer-and-minimal-receipt');
 const dto=await f.a.client.raw('GET','/portal/submissions/'+sid,undefined,headers());const consent=result(dto).consent;assert.equal((await f.a.client.raw('POST','/portal/consents/'+consent.id+'/revoke',{expectedRevision:consent.revision},headers())).status,200);const hidden=await f.a.client.raw('GET','/portal/profiles/'+f.personId,undefined,headers());assert.deepEqual(result(hidden).fields,{});mark('consent-revocation-immediately-hides-self-fields');
 const directory=await f.owner.raw('POST','/directory/talents/search',{q:'Anna self'});assert.equal(directory.status,200,JSON.stringify(directory.body));assert.equal(result(directory).total,0);
 const legacy=await f.owner.raw('GET','/people?q=Anna%20self');assert.equal(legacy.status,200);assert.equal(result(legacy).total,0);mark('consent-revocation-new-old-directory-and-counts');
 const enroll=await makeInvite('ENROLL',{maxUses:1}),enrollContext=await exchange(enroll,f.b);const enrollInput={contextId:enrollContext,relation:'SELF',applicantKey:'SELF',adultDeclared:true};const application=await f.b.client.raw('POST','/portal/claims',enrollInput,headers(f.b));assert.equal(application.status,200,JSON.stringify(application.body));const again=await f.b.client.raw('POST','/portal/claims',enrollInput,headers(f.b));assert.equal(result(again).resourceId,result(application).resourceId);assert.equal((await store.transaction(tx=>tx.get('talentInvitations',enroll.id)))!.reservedCount,1);mark('enroll-reservation-business-deduplication');
 const enrollDraft=await f.b.client.raw('POST','/portal/submissions',{...draftInput,grantId:undefined,claimId:result(application).resourceId},headers(f.b));assert.equal(enrollDraft.status,200,JSON.stringify(enrollDraft.body));const eid=result(enrollDraft).resourceId;assert.equal((await f.b.client.raw('POST','/portal/submissions/'+eid+'/submit',{expectedRevision:1},headers(f.b))).status,200);
 const enrollReview=await f.owner.cmd('POST','/talent-submissions/'+eid+'/decide',{expectedRevision:2,acceptedKeys:['name','aliases','intro'],publicReason:'加入通过',createPerson:true,ownershipBasis:'合成申请独立归属核对',guardianConfirmed:false});assert.equal(enrollReview.status,200,JSON.stringify(enrollReview.body));const final=await store.transaction(tx=>tx.get('talentInvitations',enroll.id));assert.equal(final!.usedCount,1);assert.equal(final!.reservedCount,0);assert.equal(final!.state,'EXHAUSTED');mark('enroll-approval-person-grant-quota-atomic');

 const c=await loginTalent(f,'RaceOne@example.com'),d=await loginTalent(f,'RaceTwo@example.com');const quota=await makeInvite('ENROLL',{maxUses:1}),cc=await exchange(quota,c),dc=await exchange(quota,d);
 const race=await Promise.all([c,d].map((who,n)=>who.client.raw('POST','/portal/claims',{contextId:n===0?cc:dc,relation:'SELF',applicantKey:'SELF',adultDeclared:true},headers(who))));assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);assert.equal((await store.transaction(tx=>tx.get('talentInvitations',quota.id)))!.reservedCount,1);mark('concurrent-last-enroll-slot-one-reservation');
 const winner=race[0]!.status===200?c:d,winning=race.find(r=>r.status===200)!;
 const expiredDraft=await winner.client.raw('POST','/portal/submissions',{...draftInput,grantId:undefined,claimId:result(winning).resourceId},headers(winner));assert.equal(expiredDraft.status,200);f.clock.advance(7*86400000+1);
 const oldDraft=await winner.client.raw('GET','/portal/submissions/'+result(expiredDraft).resourceId,undefined,headers(winner));assert.equal(oldDraft.status,401,'session idle expiry is independently enforced');
 const fresh=await loginTalent(f,winner===c?'RaceOne@example.com':'RaceTwo@example.com');assert.equal((await fresh.client.raw('GET','/portal/submissions/'+result(expiredDraft).resourceId,undefined,headers(fresh))).status,200);assert.equal((await fresh.client.raw('POST','/portal/submissions/'+result(expiredDraft).resourceId+'/submit',{expectedRevision:1},headers(fresh))).status,409);mark('expired-admission-retains-owned-draft-no-new-submit-after-relogin');
 return {checks,f,makeInvite,exchange,headers,draftInput,items,grantId,sid};
}
export async function reviewRollbackScenario(f:Awaited<ReturnType<typeof maintenanceFixture>>,grantId:string,items:unknown[],failAudit:()=>Promise<void>,clearAudit:()=>Promise<void>){
 await f.owner.login();const a=await loginTalent(f,'Anna@example.com'),headers={'x-once-talent-account':a.accountId};const create=await a.client.raw('POST','/portal/submissions',{schemaVersion:'once-talent-text-v1',grantId,consentTextVersion:'internal-directory-2026-10-v1',consentAccepted:true,items},{...headers,'idempotency-key':randomUUID()});assert.equal(create.status,200,JSON.stringify(create.body));const id=result(create).resourceId;assert.equal((await a.client.raw('POST','/portal/submissions/'+id+'/submit',{expectedRevision:1},{...headers,'idempotency-key':randomUUID()})).status,200);
 const snapshot=()=>f.store.transaction(async tx=>({people:await tx.find('people'),sources:await tx.find('sources'),evidence:await tx.find('evidence'),attributions:await tx.find('sourceAttributions'),submissions:await tx.find('talentSubmissions'),items:await tx.find('talentSubmissionItems')}));const before=await snapshot(),key=randomUUID(),body={expectedRevision:2,acceptedKeys:['name','aliases','intro'],publicReason:'采纳文字声明'};await failAudit();const response=await f.owner.raw('POST','/talent-submissions/'+id+'/decide',body,{'idempotency-key':key});assert.ok([500,503].includes(response.status),JSON.stringify(response.body));assert.deepEqual(await snapshot(),before);await clearAudit();const again=await f.owner.raw('POST','/talent-submissions/'+id+'/decide',body,{'idempotency-key':key});assert.equal(again.status,200,JSON.stringify(again.body));assert.equal((await f.store.transaction(tx=>tx.find('receipts',{commandKey:key}))).length,1);return {id,a,headers};
}
export async function exportMaintenance(f:Awaited<ReturnType<typeof maintenanceFixture>>){
 await f.owner.login();const grant=(await f.store.transaction(tx=>tx.find('talentAccessGrants',{talentAccountId:f.b.accountId,state:'ACTIVE'})))[0]!;const person=(await f.store.transaction(tx=>tx.get('people',grant.personId)))!;
 const sourceFields=['source.title','source.type','source.providerClaim','source.basisMode','source.basisDescription','source.validFrom','source.validUntil','source.status'],personFields=['person.displayName','person.aliases','person.intro','person.status','person.td2.talentProfiles','person.td2.personRoles','person.identityEvidence'];const refs=[];for(const [kind,id,fields] of [['PERSON',person.id,personFields],['SOURCE',person.sourceId,[...sourceFields,...personFields.filter(f=>f!=='person.status')]]] as const){const permission=await f.owner.cmd('POST','/use-permissions',{subjectKind:kind,subjectId:id,sourceId:person.sourceId,fields,validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成本人来源受控导出重建验证'});assert.equal(permission.status,201,JSON.stringify(permission.body));refs.push(result(permission).resourceId);}
 const created=await f.owner.cmd('POST','/exports',{format:'JSON',selectedIds:{people:[person.id],works:[],projects:[]},fields:[...personFields,...sourceFields],usePermissionRefs:refs});assert.equal(created.status,202,JSON.stringify(created.body));const claim=await f.app.exports.claim();assert.ok(claim);await f.app.exports.process(claim);const download=await f.owner.raw('POST','/exports/'+result(created).resourceId+'/download',{});assert.equal(download.status,200,JSON.stringify(download.body));const payload=result(download).payload;assert.equal(payload.manifest.sources[0].talentBasis.providerAccountId,f.b.accountId);assert.equal(payload.manifest.sources[0].talentBasis.purpose,'INTERNAL_DIRECTORY');for(const forbidden of ['tokenHash','token','codeHash','encryptedPayload','sessionEpoch','talentSessions','talentInvitationContexts'])assert.ok(!Object.hasOwn(payload,forbidden));return payload;
}

import {mergePreview,mergeInput} from './talent-v2-merge.ts';
import {DeletionCleanup} from '../../packages/core/src/deletion-cleanup.ts';
export async function maintenanceMergeDelete(f:Awaited<ReturnType<typeof maintenanceFixture>>){
 await f.owner.login();const b=await loginTalent(f,'Other@example.com'),headers={'x-once-talent-account':b.accountId};
 const grant=(await f.store.transaction(tx=>tx.find('talentAccessGrants',{talentAccountId:b.accountId,state:'ACTIVE'})))[0]!;
 const source=result(await f.owner.cmd('POST','/sources',{...sourceInput(),scopeId:f.scopeId})).resourceId;
 const duplicate=result(await f.owner.cmd('POST','/td2/people',{schemaVersion:'once-talent-v2.1.0',originSourceId:source,sourceRevision:1,displayName:'合成待合并身份'})).resourceId;
 const preview=await mergePreview(f.store,f.owner,grant.personId,duplicate);assert.equal(preview.complete,true,JSON.stringify(preview));assert.ok(preview.externalAccessRevocations>0);
 const merged=await f.owner.cmd('POST','/people/merge',mergeInput(preview));assert.equal(merged.status,200,JSON.stringify(merged.body));assert.equal((await f.store.transaction(tx=>tx.get('talentAccessGrants',grant.id)))!.state,'REVOKED');assert.equal((await b.client.raw('GET','/portal/profiles/'+grant.personId,undefined,headers)).status,404);assert.equal((await f.store.transaction(tx=>tx.find('personAliases',{oldPersonId:duplicate})))[0]!.canonicalPersonId,grant.personId);
 const p=(await f.store.transaction(tx=>tx.get('people',grant.personId)))!,input={targetKind:'PERSON',targetId:p.id,expectedRevision:p.revision};
 const impact=await f.owner.raw('POST','/deletion-requests/preview',input);assert.equal(impact.status,200,JSON.stringify(impact.body));const plan=result(impact);assert.equal(plan.complete,true,JSON.stringify(plan.unresolved));
 const created=await f.owner.cmd('POST','/deletion-requests',{...input,previewDigest:plan.previewDigest,reason:'合成删除本人服务器镜像和合并历史'});assert.equal(created.status,201,JSON.stringify(created.body));const rid=result(created).resourceId,current=()=>f.store.transaction(async tx=>(await tx.get('deletionRequests',rid))!);
 const ok=async(response:Promise<Awaited<ReturnType<typeof f.owner.raw>>>)=>{const r=await response;assert.equal(r.status,200,JSON.stringify(r.body));};
 await ok(f.owner.cmd('POST',`/deletion-requests/${rid}/block`,{expectedRevision:1,previewDigest:plan.previewDigest,acknowledgeBlock:true}));
 for(const item of await f.store.transaction(tx=>tx.find('deletionItems',{requestId:rid})))if(item.decision==='PENDING')await ok(f.owner.cmd('POST',`/deletion-requests/${rid}/decisions`,{expectedRevision:(await current()).revision,entryId:item.id,decision:'APPLY_PROPOSED',decisionReason:'合成确认删除关联文字及证据'}));
 await ok(f.owner.cmd('POST',`/deletion-requests/${rid}/plan/freeze`,{expectedRevision:(await current()).revision,acknowledgePlan:true}));await ok(f.owner.cmd('POST',`/deletion-requests/${rid}/cleaning/start`,{expectedRevision:(await current()).revision,planDigest:(await current()).planDigest,acknowledgeIrreversible:true}));
 const cleanup=new DeletionCleanup(f.store,f.clock,f.app.config),job=await cleanup.claim();assert.ok(job);await cleanup.process(job);const final=await f.app.deletionFinalization.claim();assert.ok(final,JSON.stringify(await f.store.transaction(tx=>tx.find('deletionItems',{requestId:rid}))));await f.app.deletionFinalization.finish(final);assert.equal((await current()).state,'COMPLETED');assert.equal((await f.store.transaction(tx=>tx.get('people',p.id)))!.status,'ERASED');
 const submissions=await f.store.transaction(tx=>tx.find('talentSubmissions',{personId:p.id}));for(const s of submissions)for(const i of await f.store.transaction(tx=>tx.find('talentSubmissionItems',{submissionId:s.id})))assert.deepEqual(i.values,{erased:true});
 return ['actual-person-merge-closes-grant-without-transferring-account','actual-person-deletion-clears-server-submission-mirrors'];
}

export async function maintenanceReviewBoundaries(f:Awaited<ReturnType<typeof maintenanceFixture>>,grantId:string,existing?:Awaited<ReturnType<typeof loginTalent>>){
 await f.owner.login();const a=existing??await loginTalent(f,'Anna@example.com'),h=()=>({'x-once-talent-account':a.accountId,'idempotency-key':randomUUID()});
 const items=[{clientItemKey:'name',field:'displayName',text:'Anna self',dependencyGroup:'name',dependsOn:[]},{clientItemKey:'intro',field:'intro',text:'新的独立简介条目',dependencyGroup:'intro',dependsOn:[]}];
 const make=async()=>{const r=await a.client.raw('POST','/portal/submissions',{schemaVersion:'once-talent-text-v1',grantId,consentTextVersion:'internal-directory-2026-10-v1',consentAccepted:true,items},h());assert.equal(r.status,200,JSON.stringify(r.body));return result(r).resourceId;};
 const id=await make();assert.equal((await a.client.raw('POST','/portal/submissions/'+id+'/submit',{expectedRevision:1},h())).status,200);
 const patch=async(intro:string)=>{const p=(await f.store.transaction(tx=>tx.get('people',f.personId)))!;const r=await f.owner.cmd('PATCH','/td2/people/'+p.id,{schemaVersion:'once-talent-v2.1.0',expectedRevision:p.revision,intro});assert.equal(r.status,200,JSON.stringify(r.body));};
 await patch('员工更新了另一字段');const decision=await f.owner.cmd('POST','/talent-submissions/'+id+'/decide',{expectedRevision:2,acceptedKeys:['name'],publicReason:'只采纳独立姓名条目'});assert.equal(decision.status,200,JSON.stringify(decision.body));assert.equal((await f.store.transaction(tx=>tx.get('talentSubmissions',id)))!.state,'PARTIALLY_APPROVED');assert.equal((await f.store.transaction(tx=>tx.get('people',f.personId)))!.intro,'员工更新了另一字段');
 const current=(await f.store.transaction(tx=>tx.get('talentSubmissions',id)))!,fork=await a.client.raw('POST','/portal/submissions/'+id+'/fork',{expectedRevision:current.revision},h());assert.equal(fork.status,200,JSON.stringify(fork.body));const fid=result(fork).resourceId,fitems=await f.store.transaction(tx=>tx.find('talentSubmissionItems',{submissionId:fid}));assert.deepEqual(fitems.map(i=>i.values.field),['intro']);
 await patch('员工再次更新同一简介');assert.equal((await a.client.raw('PATCH','/portal/submissions/'+fid,{expectedRevision:1,items:[items[1]]},h())).status,200);assert.equal((await a.client.raw('POST','/portal/submissions/'+fid+'/submit',{expectedRevision:2},h())).status,200);const stale=await f.owner.cmd('POST','/talent-submissions/'+fid+'/decide',{expectedRevision:3,acceptedKeys:['intro'],publicReason:''});assert.equal(stale.status,200,JSON.stringify(stale.body));assert.equal((await f.store.transaction(tx=>tx.get('talentSubmissions',fid)))!.state,'NEEDS_REBASE');assert.equal((await f.store.transaction(tx=>tx.get('people',f.personId)))!.intro,'员工再次更新同一简介');
 return ['partial-independent-items-ignore-unrelated-person-revision','fork-only-unapplied-items','save-retains-original-field-baseline-and-stale-review-needs-rebase'];
}
export async function maintenanceGuardianBoundaries(f:Awaited<ReturnType<typeof maintenanceFixture>>){
 await f.owner.login();const c=await loginTalent(f,'GuardianTests@example.com'),h=()=>({'x-once-talent-account':c.accountId,'idempotency-key':randomUUID()});
 const pid=result(await f.owner.cmd('POST','/directory/talents',{schemaVersion:'once-talent-experience-v1',kind:'TALENT',displayName:'合成未成年申请',sourceId:f.sourceId,sourceRevision:1})).resourceId;
 const inv=result(await f.owner.cmd('POST','/talent-invitations',{purpose:'CLAIM',targetPersonId:pid,scopeId:f.scopeId,exposureFields:[]})).resourceId,issued=await f.owner.raw('POST','/talent-invitations/'+inv+'/issue',{expectedRevision:1}),fragment=new URLSearchParams(new URL(result(issued).url).hash.slice(1));
 const context=result(await c.client.raw('POST','/portal/invitations/exchange',{invitationId:inv,token:fragment.get('t')},{'x-once-portal':'1'})).contextId;
 const claim=async(relation:string,adultDeclared:boolean)=>{const r=await c.client.raw('POST','/portal/claims',{contextId:context,relation,applicantKey:relation==='SELF'?'SELF':'child-1',adultDeclared},h());assert.equal(r.status,200,JSON.stringify(r.body));return result(r).resourceId;};
 const decide=(id:string,guardianConfirmed=false)=>f.owner.cmd('POST','/talent-claims/'+id+'/decide',{expectedRevision:1,decision:'APPROVE',ownershipBasis:'合成独立关系核实',guardianConfirmed});
 const unknown=await claim('SELF',false);assert.equal((await decide(unknown)).status,409);assert.equal((await f.store.transaction(tx=>tx.find('talentAccessGrants',{personId:pid}))).length,0);
 assert.equal((await f.owner.cmd('POST','/talent-claims/'+unknown+'/decide',{expectedRevision:1,decision:'REJECT',ownershipBasis:'合成未知成年声明不成立',guardianConfirmed:false})).status,200);
 const p=(await f.store.transaction(tx=>tx.get('people',pid)))!;assert.equal((await f.owner.cmd('PATCH','/directory/talents/'+pid,{schemaVersion:'once-talent-experience-v1',expectedRevision:p.revision,sourceId:f.sourceId,sourceRevision:1,profile:{birthPrecision:'YEAR_ONLY',birthYear:2015}})).status,200);
 const minor=await claim('SELF',true);assert.equal((await decide(minor)).status,409);const guardian=await claim('GUARDIAN',false);assert.equal((await decide(guardian)).status,409);assert.equal((await decide(guardian,true)).status,200);const grants=await f.store.transaction(tx=>tx.find('talentAccessGrants',{personId:pid}));assert.equal(grants.length,1);assert.equal(grants[0]!.relation,'GUARDIAN');
 return ['unknown-age-no-self-grant-without-adult-declaration','known-minor-cannot-bypass-with-adult-checkbox','guardian-independent-proof-required'];
}
