import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Application} from '../../packages/core/src/api.ts';
import type {Store} from '../../packages/core/src/store.ts';
import {TALENT_SCHEMA_VERSION as schemaVersion} from '../../packages/core/src/talent-v2-model.ts';
import {Client,FakeClock,sourceInput} from './fixtures.ts';
import {FaultStore} from './fault-store.ts';
import {expectResponse as ok} from './talent-v2-maintenance.ts';
export async function verifyManualMaintenance(f:{app:Application;store:Store;clock:FakeClock;owner:Client},failureStatus:500|503=500,existing?:{credentialId:string;personId:string}){
 const sourceId=ok(await f.owner.cmd('POST','/sources',sourceInput())).resourceId as string;
 const personId=ok(await f.owner.cmd('POST','/people',{sourceId,displayName:'合成人工迁移复核',roles:['model'],heightCm:179})).resourceId as string;
 ok(await f.owner.cmd('POST',`/td2/people/${personId}/enroll`,{schemaVersion,expectedRevision:1,sourceRevision:1}),200);
 const listing=ok(await f.owner.raw('GET',`/td2/people/${personId}/height-reviews`),200),review=listing.items[0];assert.equal(listing.legacyHeightCm,179);assert.equal(listing.canDismiss,true);assert.equal(review.state,'PENDING');
 const before=await f.store.transaction(tx=>tx.get('people',personId)),request={schemaVersion,expectedRevision:review.revision,expectedPersonRevision:listing.personRevision,sourceRevision:listing.sourceRevision,resolution:'DO_NOT_USE_LEGACY_HEIGHT',acknowledge:true};
 assert.equal((await f.owner.cmd('POST',`/td2/height-reviews/${review.id}/dismiss`,{...request,acknowledge:false})).status,422);assert.equal((await f.owner.cmd('POST',`/td2/height-reviews/${review.id}/dismiss`,{...request,resolution:'ASSUME_OLD_HEIGHT_CONFIRMED'})).status,400);assert.equal((await f.owner.cmd('POST',`/td2/height-reviews/${review.id}/dismiss`,{...request,expectedPersonRevision:1})).status,409);
 const fault=new FaultStore(f.store),client=new Client(new Application(fault,f.app.config,f.clock));client.jar={...f.owner.jar};client.csrf=f.owner.csrf;
 let fired=false;const fail=()=>{fired=false;fault.afterInsert=table=>{if(table==='audits'){fired=true;throw new Error('synthetic manual maintenance audit failure');}};};
 const errorCheck=(response:any)=>{assert.equal(response.status,failureStatus);assert.equal(fired,true);if(failureStatus===503)assert.equal(response.body.error.code,'STORE_UNAVAILABLE');};
 fail();const key=randomUUID();errorCheck(await client.cmd('POST',`/td2/height-reviews/${review.id}/dismiss`,request,key));assert.equal((await f.store.transaction(tx=>tx.get('talentMigrationReviews',review.id)))?.state,'PENDING');assert.deepEqual(await f.store.transaction(tx=>tx.get('people',personId)),before);
 fault.afterInsert=null;ok(await client.cmd('POST',`/td2/height-reviews/${review.id}/dismiss`,request,key),200);assert.equal(ok(await client.cmd('POST',`/td2/height-reviews/${review.id}/dismiss`,request,key),200).replayed,true);
 const resolved=ok(await f.owner.raw('GET',`/td2/people/${personId}/height-reviews`),200);assert.equal(resolved.items[0].state,'RESOLVED');assert.ok(resolved.items[0].resolvedAt);assert.equal((await f.store.transaction(tx=>tx.get('people',personId)))?.heightCm,179);assert.equal((await f.store.transaction(tx=>tx.find('measurementSets',{personId}))).length,0);assert.equal(ok(await f.owner.raw('GET',`/people/${personId}`),200).heightCm,null);
 const audit=(await f.store.transaction(tx=>tx.find('audits',{resourceId:review.id,action:'td2.heightReview.dismiss'})));assert.equal(audit.length,1);assert.equal(audit[0]?.resourceKind,'talentMigrationReview');
 const receipt=(await f.store.transaction(tx=>tx.find('receipts',{resourceId:review.id,operation:'td2.heightReview.dismiss'})))[0]!;assert.equal(receipt.resourceKind,'talentMigrationReview');
 let credentialId=existing?.credentialId,credentialPersonId=existing?.personId??personId;
 if(!credentialId){const p=(await f.store.transaction(tx=>tx.get('people',personId)))!;credentialId=ok(await f.owner.cmd('POST',`/td2/people/${personId}/credentials`,{schemaVersion,expectedPersonRevision:p.revision,sourceId,sourceRevision:1,values:{credentialTypeCode:'DRONE_LICENSE',issuerName:'合成人工清除机构'}})).resourceId as string;const after=(await f.store.transaction(tx=>tx.get('people',personId)))!;ok(await f.owner.cmd('POST',`/td2/credentials/${credentialId}/identifier`,{schemaVersion,expectedRevision:1,expectedPersonRevision:after.revision,identifier:'SYNTHETIC-MANUAL-PRIVATE-9876'}),200);}
 const credential=(await f.store.transaction(tx=>tx.get('personCredentials',credentialId!)))!,subject=(await f.store.transaction(tx=>tx.get('people',credentialPersonId)))!,basis=(await f.store.transaction(tx=>tx.get('sources',credential.sourceId)))!;
 assert.ok(credential.identifierCiphertext);const clear={schemaVersion,expectedRevision:credential.revision,expectedPersonRevision:subject.revision,sourceRevision:basis.revision,acknowledge:true},clearPath=`/td2/credentials/${credentialId}/identifier/clear`;
 assert.equal((await f.owner.cmd('POST',clearPath,{...clear,acknowledge:false})).status,422);assert.equal((await f.owner.cmd('POST',clearPath,{...clear,sourceRevision:basis.revision+1})).status,409);
 fail();const clearKey=randomUUID();errorCheck(await client.cmd('POST',clearPath,clear,clearKey));assert.deepEqual(await f.store.transaction(tx=>tx.get('personCredentials',credentialId!)),credential);assert.deepEqual(await f.store.transaction(tx=>tx.get('people',credentialPersonId)),subject);
 fault.afterInsert=null;ok(await client.cmd('POST',clearPath,clear,clearKey),200);assert.equal(ok(await client.cmd('POST',clearPath,clear,clearKey),200).replayed,true);const cleared=(await f.store.transaction(tx=>tx.get('personCredentials',credentialId!)))!;assert.equal(cleared.identifierCiphertext,null);assert.equal(cleared.maskedIdentifier,null);for(const field of ['status','sourceId','credentialTypeCode','evidenceAssetId','issuerName','issuedOn','expiresOn'] as const)assert.deepEqual(cleared[field],credential[field]);
 const ordinary=ok(await f.owner.raw('GET',`/td2/people/${credentialPersonId}`),200);assert.ok(!JSON.stringify(ordinary).includes('SYNTHETIC-MANUAL-PRIVATE-9876'));assert.equal((await f.store.transaction(tx=>tx.find('audits',{resourceId:credentialId,action:'td2.credential.secret.clear'}))).length,1);
 const viewerLogin='manual-viewer-'+randomUUID().slice(0,8),viewerMember=ok(await f.owner.raw('POST','/memberships',{loginName:viewerLogin,displayName:'合成人工维护只读人',role:'VIEWER',extraPermissions:[]})),viewer=new Client(f.app,'192.0.2.203');ok(await viewer.activate(viewerMember.activationToken),200);ok(await viewer.login(viewerLogin),200);assert.equal((await viewer.raw('GET',`/td2/people/${personId}/height-reviews`)).status,403);assert.equal((await viewer.cmd('POST',`/td2/height-reviews/${review.id}/dismiss`,request)).status,403);assert.equal((await viewer.cmd('POST',clearPath,clear)).status,403);
 const me=ok(await f.owner.raw('GET','/me'),200),principal=ok(await f.owner.raw('POST','/td2/principals',{schemaVersion,displayName:'合成人工维护机器拒绝',scopeId:subject.scopeId,defaultMaintainerMembershipId:me.membershipId,permissionCodes:['records.read','talent.fact.write'],expiresAt:new Date(f.clock.now().getTime()+3600000).toISOString()}));
 for(const [method,path,body]of [['GET',`/td2/people/${personId}/height-reviews`,{}],['POST',`/td2/height-reviews/${review.id}/dismiss`,request],['POST',clearPath,clear]] as const){const response=await f.app.handle({method,url:'/api/v1'+path,ip:'192.0.2.204',headers:{authorization:'Bearer '+principal.token,'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify(body)});assert.equal(response.status,403);}
 ok(await f.owner.cmd('POST',`/sources/${sourceId}/suspend`,{expectedRevision:1,reason:'合成人工复核后来源暂停'}),200);assert.equal((await client.cmd('POST',`/td2/height-reviews/${review.id}/dismiss`,request,key)).status,404);assert.equal((await f.owner.raw('GET',`/td2/people/${personId}/height-reviews`)).status,404);
 return {personId,reviewId:review.id,credentialId};
}
