import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {Application} from '../../packages/core/src/api.ts';
import type {Store} from '../../packages/core/src/store.ts';
import type {AuthProvider,TalentAuthConfig} from '../../packages/core/src/talent-auth-model.ts';
import {FakeClock,Client,SYNTHETIC_PASSWORD,result,sourceInput} from './fixtures.ts';
import {normalizeTalentIdentity,isolateTalentAuth} from '../../packages/core/src/talent-auth.ts';
export function testAuthConfig():TalentAuthConfig{return {enabled:true,providerType:'test',endpoint:'http://127.0.0.1:1',credential:'synthetic-provider-secret',sender:'synthetic',template:'synthetic',timeoutMs:1000,identityKey:randomBytes(32),codeKey:randomBytes(32),sessionKey:randomBytes(32),messageKey:randomBytes(32),csrfKey:randomBytes(32),idleMs:7*86400000,absoluteMs:30*86400000,contextMs:900000,challengeMs:600000,maxAttempts:5,resendMs:60000,identityHourly:5,identityDaily:10,ipHourly:20,workspaceHourly:100,workspaceDaily:200};}
export async function authFixture(store:Store){const clock=new FakeClock(),sent:Array<Parameters<AuthProvider['send']>[0]>=[],intents:any[]=[];let deliveryState:'ACCEPTED'|'UNKNOWN'='ACCEPTED';const provider:AuthProvider={async send(input){sent.push(input);return deliveryState;}};
 const app=new Application(store,{origin:'https://talent.test.invalid',environment:'test',secureCookies:true,accessMode:'INTERNAL',dataEgressMode:'INTERNAL_APPROVED',dataCleanupMode:'INTERNAL_APPROVED',dataMergeMode:'INTERNAL_APPROVED',contactKey:randomBytes(32),csrfKey:randomBytes(32),recoveryEpoch:randomBytes(24).toString('hex'),talentAuth:testAuthConfig()},clock,{async writeAhead(i){intents.push(i);},async committed(){},async aborted(){}},provider);
 await app.identity.bootstrap('owner','合成管理员',SYNTHETIC_PASSWORD);const owner=new Client(app);await owner.login();return {store,app,clock,owner,sent,intents,unknown(){deliveryState='UNKNOWN';},accepted(){deliveryState='ACCEPTED';}};
}
export type AuthFixture=Awaited<ReturnType<typeof authFixture>>;
export async function challenge(f:AuthFixture,email:string,client=new Client(f.app),kind:'EMAIL'|'PHONE'='EMAIL'){
 const ctx=await client.raw('POST','/portal/auth/context',{purpose:'LOGIN'},{'x-once-portal':'1'});assert.equal(ctx.status,200,JSON.stringify(ctx.body));client.csrf=result(ctx).csrfToken;
 const c=await client.raw('POST','/portal/auth/challenges',{contextId:result(ctx).contextId,purpose:'LOGIN',kind,identity:email});assert.equal(c.status,200,JSON.stringify(c.body));
 const input={contextId:result(ctx).contextId,challengeId:result(c).id,purpose:'LOGIN',code:f.sent.at(-1)!.code};return {client,input,c};
}
export async function loginTalent(f:AuthFixture,email:string,client?:Client){const x=await challenge(f,email,client);const r=await x.client.raw('POST','/portal/auth/verify',x.input);assert.equal(r.status,200,JSON.stringify(r.body));x.client.csrf=result(r).csrfToken;return {...x,accountId:result(r).talentAccountId,token:x.client.jar.once_talent_session!};}
export async function verifyTalentAuth(f:AuthFixture){
 const checks:string[]=[];const mark=(s:string)=>checks.push(s);
 assert.equal(normalizeTalentIdentity('EMAIL',' Anna.Example+book@EXAMPLE.COM '),'Anna.Example+book@example.com');assert.notEqual(normalizeTalentIdentity('EMAIL','Anna@example.com'),normalizeTalentIdentity('EMAIL','anna@example.com'));assert.notEqual(normalizeTalentIdentity('EMAIL','a.b@example.com'),normalizeTalentIdentity('EMAIL','ab@example.com'));assert.notEqual(normalizeTalentIdentity('EMAIL','a+book@example.com'),normalizeTalentIdentity('EMAIL','a@example.com'));assert.equal(normalizeTalentIdentity('PHONE',' +8613800000000 '),'+8613800000000');assert.throws(()=>normalizeTalentIdentity('PHONE','13800000000'));mark('identity-v1-domain-only-case-folding-preserves-local-dots-plus-and-case');
 const anna=await loginTalent(f,'Anna@EXAMPLE.COM');assert.equal((await anna.client.raw('GET','/portal/me')).status,200);assert.equal((await anna.client.raw('GET','/me')).status,401);assert.equal((await f.owner.raw('GET','/portal/me')).status,401);assert.equal((await anna.client.raw('GET','/portal/me',undefined,{authorization:'Bearer once_machine.synthetic'})).status,401);assert.equal((await anna.client.raw('GET','/portal/profiles/'+randomUUID())).status,404);assert.equal((await anna.client.raw('POST','/portal/auth/verify',anna.input)).status,403);mark('cookie-bearer-and-person-boundary');
 const both=new Client(f.app);both.jar={...f.owner.jar,...anna.client.jar};assert.equal((await both.raw('GET','/me')).status,200);assert.equal((await both.raw('GET','/portal/me')).status,200);mark('coexisting-cookies-select-correct-identity');
 const before=await f.store.transaction(tx=>tx.find('talentAccounts'));f.clock.advance(60001);const again=await loginTalent(f,'Anna@example.com');assert.equal(again.accountId,anna.accountId);assert.equal((await f.store.transaction(tx=>tx.find('talentAccounts'))).length,before.length);mark('same-verified-identity-one-account');
 const key=randomUUID(),headers={'idempotency-key':key,'x-once-talent-account':again.accountId};const first=await again.client.raw('POST','/portal/auth/revoke-other-sessions',{},headers);assert.equal(first.status,200,JSON.stringify(first.body));const replay=await again.client.raw('POST','/portal/auth/revoke-other-sessions',{},headers);assert.equal(result(replay).replayed,true);assert.equal(result(first).operationId,result(replay).operationId);assert.equal((await anna.client.raw('GET','/portal/me')).status,401);mark('talent-command-stable-receipt-and-other-sessions-revoked');
 f.clock.advance(60001);const fresh=await loginTalent(f,'Anna@example.com');const rerun=await fresh.client.raw('POST','/portal/auth/revoke-other-sessions',{},headers);assert.equal(result(rerun).operationId,result(first).operationId);const intent=f.intents.filter(i=>i.operation==='portal.sessions.revoke');assert.equal(new Set(intent.map(i=>i.intentId)).size,1);mark('new-session-same-account-receipt-and-write-ahead');
 const other=await loginTalent(f,'Bob@example.com');const wrong=await other.client.raw('POST','/portal/auth/revoke-other-sessions',{},headers);assert.equal(wrong.status,409);const own=await other.client.raw('POST','/portal/auth/revoke-other-sessions',{}, {...headers,'x-once-talent-account':other.accountId});assert.equal(own.status,200);assert.notEqual(result(own).operationId,result(first).operationId);mark('cross-account-header-rejected-and-key-isolated');
 const invalid=await challenge(f,'limit@example.com');const bad=invalid.input.code==='000000'?'000001':'000000';for(let n=0;n<5;n++)assert.equal((await invalid.client.raw('POST','/portal/auth/verify',{...invalid.input,code:bad})).status,401);assert.equal((await invalid.client.raw('POST','/portal/auth/verify',invalid.input)).status,401);assert.equal((await f.store.transaction(tx=>tx.get('talentAuthChallenges',invalid.input.challengeId)))?.attempts,5);mark('wrong-attempts-commit-and-lock-challenge');
 const expired=await challenge(f,'expired@example.com');f.clock.advance(600001);assert.equal((await expired.client.raw('POST','/portal/auth/verify',expired.input)).status,401);mark('expired-code-rejected');
 const purpose=await challenge(f,'purpose@example.com');assert.equal((await purpose.client.raw('POST','/portal/auth/verify',{...purpose.input,purpose:'RECOVER'})).status,401);assert.equal((await purpose.client.raw('POST','/portal/auth/verify',{...purpose.input,verified:true})).status,400);mark('purpose-binding-and-unknown-fields');
 const tab2=await challenge(f,'tab2@example.com',new Client(f.app));assert.equal((await tab2.client.raw('POST','/portal/auth/verify',purpose.input)).status,401);mark('context-browser-binding');
 f.unknown();const unknown=await challenge(f,'unknown@example.com');assert.equal(result(unknown.c).state,'UNKNOWN');const sentCount=f.sent.length;await f.app.portal.auth.dispatch(unknown.input.challengeId);assert.equal(f.sent.length,sentCount);const old=await unknown.client.raw('POST','/portal/auth/challenges',{contextId:unknown.input.contextId,purpose:'LOGIN',kind:'EMAIL',identity:'unknown@example.com'});assert.equal(old.status,429);f.clock.advance(60001);const replacement=await unknown.client.raw('POST','/portal/auth/challenges',{contextId:unknown.input.contextId,purpose:'LOGIN',kind:'EMAIL',identity:'unknown@example.com'});assert.equal(replacement.status,200);assert.equal((await unknown.client.raw('POST','/portal/auth/verify',unknown.input)).status,401);assert.equal((await f.store.transaction(tx=>tx.get('talentAuthChallenges',unknown.input.challengeId)))?.state,'EXPIRED');f.accepted();mark('unknown-never-resends-new-explicit-challenge-invalidates-old');
 const once=await challenge(f,'once@example.com');const responses=await Promise.all([once.client.raw('POST','/portal/auth/verify',once.input),once.client.raw('POST','/portal/auth/verify',once.input)]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,401]);mark('concurrent-verify-consumes-once');
 const pending=await challenge(f,'Bob@example.com');const rev=(await f.store.transaction(tx=>tx.get('talentAccounts',other.accountId)))!.revision;assert.equal((await f.owner.cmd('POST','/talent-accounts/'+other.accountId+'/disable',{expectedRevision:rev})).status,200);assert.equal((await other.client.raw('GET','/portal/me')).status,401);assert.equal((await pending.client.raw('POST','/portal/auth/verify',pending.input)).status,401);mark('disable-invalidates-session-and-challenge');
 const rows=await f.store.transaction(async tx=>({audits:await tx.find('audits'),receipts:await tx.find('receipts'),deliveries:await tx.find('talentAuthDeliveries')}));const serialized=JSON.stringify(rows);for(const secret of [...f.sent.map(x=>x.code),anna.token,f.app.config.talentAuth!.codeKey.toString('hex')])assert.ok(!serialized.includes(secret));assert.ok(rows.deliveries.every(d=>d.encryptedPayload===null));assert.ok(rows.receipts.filter(r=>r.principalKind==='TALENT').every(r=>r.actorId===null&&r.servicePrincipalId===null&&r.talentAccountId));mark('no-secrets-in-receipts-audits-terminal-deliveries');
 const source=await f.owner.cmd('POST','/sources',sourceInput());assert.equal(source.status,201);const sourceId=result(source).resourceId;const person=await f.owner.cmd('POST','/people',{displayName:'合成导出隔离',roles:['model'],sourceId});assert.equal(person.status,201);const personId=result(person).resourceId;const permission=await f.owner.cmd('POST','/use-permissions',{sourceId,subjectKind:'PERSON',subjectId:personId,fields:['person.displayName'],validUntil:'2026-10-15T00:00:00.000Z',evidenceNote:'合成本人认证隔离验证'});assert.equal(permission.status,201);const job=await f.owner.cmd('POST','/exports',{format:'JSON',selectedIds:{people:[personId],works:[],projects:[]},fields:['person.displayName'],usePermissionRefs:[result(permission).resourceId]});assert.equal(job.status,202);const claim=await f.app.exports.claim();assert.ok(claim);await f.app.exports.process(claim);const download=await f.owner.raw('POST','/exports/'+result(job).resourceId+'/download',{});assert.equal(download.status,200);const exported=JSON.stringify(result(download).payload);for(const value of [anna.token,...f.sent.map(x=>x.code),f.app.config.talentAuth!.codeKey.toString('hex'),'talentIdentities','codeHash','tokenHash','encryptedPayload'])assert.ok(!exported.includes(value));mark('actual-business-json-export-excludes-auth-entities-and-secrets');
 const restoreChallenge=await challenge(f,'restore@example.com');const priorEpoch=f.app.config.recoveryEpoch;f.app.config.recoveryEpoch=randomBytes(24).toString('hex');assert.equal((await fresh.client.raw('GET','/portal/me')).status,503);assert.equal((await restoreChallenge.client.raw('POST','/portal/auth/verify',restoreChallenge.input)).status,503);await f.store.transaction(async tx=>{const w=(await tx.find('workspaces'))[0]!;await isolateTalentAuth(tx,w.id,f.clock);await tx.replace('workspaces',{...w,recoveryEpoch:f.app.config.recoveryEpoch});});assert.equal((await fresh.client.raw('GET','/portal/me')).status,401);assert.equal((await restoreChallenge.client.raw('POST','/portal/auth/verify',restoreChallenge.input)).status,401);assert.notEqual(priorEpoch,f.app.config.recoveryEpoch);mark('recovery-epoch-rejects-before-and-after-isolation');
 return checks;
}
