import {queryValues} from '../../../packages/core/src/talent-directory-contract.ts';
import {Prisma} from '@prisma/client';
import type {DirectoryDatabaseQuery} from '../../../packages/core/src/talent-directory-query.ts';
/** Only constant identifiers enter SQL fragments; all values (including IDs) are bound. */
export function directorySql(input:DirectoryDatabaseQuery){
 const q=input.query,values=(key:string)=>Prisma.join(queryValues(q[key])),ids=(values:string[])=>Prisma.join(values.map(id=>Prisma.sql`${id}::uuid`));
 const clauses:Prisma.Sql[]=[Prisma.sql`p."workspaceId"=${input.workspaceId}::uuid`,Prisma.sql`p."status"<>'ERASED'`,input.visibleScopeIds.length?Prisma.sql`p."scopeId" IN (${ids(input.visibleScopeIds)})`:Prisma.sql`FALSE`,Prisma.sql`NOT EXISTS(SELECT 1 FROM "personAliases" a WHERE a."workspaceId"=p."workspaceId" AND a."oldPersonId"=p.id)`,Prisma.sql`NOT EXISTS(SELECT 1 FROM "deletionRequests" d WHERE d."workspaceId"=p."workspaceId" AND d."targetKind"='PERSON' AND d."targetId"=p.id AND d.state<>'DRAFT')`];
 if(input.phase==='PAGE'){clauses.push(input.verifiedIds?.length?Prisma.sql`p.id IN (${ids(input.verifiedIds)})`:Prisma.sql`FALSE`);const where=Prisma.join(clauses,' AND ');return {rows:Prisma.sql`SELECT p.id FROM people p WHERE ${where} ORDER BY p."updatedAt" DESC,p.id ASC LIMIT ${input.pageSize??20} OFFSET ${((input.page??1)-1)*(input.pageSize??20)}`,count:Prisma.sql`SELECT count(DISTINCT p.id)::int AS total FROM people p WHERE ${where}`};}
 const profile=Prisma.sql`LEFT JOIN "talentProfiles" tp ON tp."workspaceId"=p."workspaceId" AND tp."personId"=p.id AND tp."supersededById" IS NULL AND tp.status='ACTIVE'`;
 if(q.q)clauses.push(Prisma.sql`(strpos(lower(p."displayName"||' '||p.intro||' '||array_to_string(p.aliases,' ')),lower(${q.q}))>0 OR EXISTS(SELECT 1 FROM "evidence" e WHERE e."workspaceId"=p."workspaceId" AND e."personId"=p.id) OR NOT EXISTS(SELECT 1 FROM "sources" s WHERE s."workspaceId"=p."workspaceId" AND s.id=p."sourceId" AND s.status NOT IN ('SUSPENDED','ERASED') AND s."validFrom"<=${new Date(input.now)} AND s."validUntil">${new Date(input.now)} AND (s."basisMode"='TEMP_ORGANIZE' OR s.status='CONFIRMED')))`);
 if(q.status)clauses.push(Prisma.sql`p.status=${q.status}`);else clauses.push(Prisma.sql`p.status<>'ARCHIVED'`);
 if(q.mode==='TALENT')clauses.push(Prisma.sql`tp.id IS NOT NULL`);if(q.mode==='CONTACT')clauses.push(Prisma.sql`tp.id IS NULL`);
 if(q.gender)clauses.push(Prisma.sql`tp.id IS NOT NULL AND coalesce(tp."genderCode",'UNKNOWN') IN (${values('gender')})`);
 if(q.nationality)clauses.push(Prisma.sql`tp."nationalityCodes" && ARRAY[${values('nationality')}]::text[]`);
 if(q.ageUnknown)clauses.push(Prisma.sql`tp."birthPrecision"='UNKNOWN'`);
 // The full possible birth interval; calendar shifting clamps leap dates just as the core reference does.
 const today=Prisma.sql`${input.asOf}::date`;
 const first=Prisma.sql`CASE tp."birthPrecision" WHEN 'EXACT_DATE' THEN tp."birthDate"::date WHEN 'YEAR_ONLY' THEN make_date(tp."birthYear",1,1) WHEN 'DECLARED_RANGE' THEN (tp."ageAsOfDate"::date-make_interval(years=>tp."maxAgeYears"+1)+interval '1 day')::date END`;
 const last=Prisma.sql`LEAST(${today},CASE tp."birthPrecision" WHEN 'EXACT_DATE' THEN tp."birthDate"::date WHEN 'YEAR_ONLY' THEN make_date(tp."birthYear",12,31) WHEN 'DECLARED_RANGE' THEN (tp."ageAsOfDate"::date-make_interval(years=>tp."minAgeYears"))::date END)`;
 const age=(birth:Prisma.Sql)=>Prisma.sql`GREATEST(0,extract(year FROM ${today})::int-extract(year FROM ${birth})::int-CASE WHEN to_char(${today},'MM-DD')<to_char(${birth},'MM-DD') THEN 1 ELSE 0 END)`;
 if(q.ageMin||q.ageMax){clauses.push(Prisma.sql`tp."birthPrecision"<>'UNKNOWN'`);if(q.ageMin)clauses.push(Prisma.sql`${age(last)}>=${Number(q.ageMin)}`);if(q.ageMax)clauses.push(Prisma.sql`${age(first)}<=${Number(q.ageMax)}`);}
 const period=(r:Prisma.Sql)=>Prisma.sql`(${r}."validFrom" IS NULL OR ${r}."validFrom"<=${new Date(input.now)}) AND (${r}."validUntil" IS NULL OR ${r}."validUntil">${new Date(input.now)})`;
 let roleConditions:Prisma.Sql[]=[];
 if(q.role||q.market||q.experience||q.style||q.service){const r=Prisma.raw('r'),checks=[Prisma.sql`r."workspaceId"=p."workspaceId" AND r."personId"=p.id AND r.status='ACTIVE'`,period(r),Prisma.sql`EXISTS(SELECT 1 FROM dictionary di WHERE di."workspaceId"=p."workspaceId" AND di.namespace='role' AND di.code=r."roleCode" AND di.status='ACTIVE')`];if(q.role)checks.push(Prisma.sql`r."roleCode" IN (${values('role')})`);if(q.market||q.experience)checks.push(Prisma.sql`r."roleCode"='model'`);if(q.market)checks.push(Prisma.sql`r."castingMarketCode" IN (${values('market')})`);if(q.experience)checks.push(Prisma.sql`r."experienceCode" IN (${values('experience')})`);if(q.style)checks.push(Prisma.sql`r."styleCodes" && ARRAY[${values('style')}]::text[]`);if(q.service)checks.push(Prisma.sql`r."serviceCodes" && ARRAY[${values('service')}]::text[]`);roleConditions=checks;clauses.push(Prisma.sql`EXISTS(SELECT 1 FROM "personRoles" r WHERE ${Prisma.join(checks,' AND ')})`);}
 for(const [key,table,column,namespace] of [['location','talentLocations','locationCode','city'],['language','personLanguages','languageCode','language']] as const)if(q[key]){const t=Prisma.raw('"'+table+'"'),col=Prisma.raw('"'+column+'"');clauses.push(Prisma.sql`EXISTS(SELECT 1 FROM ${t} r WHERE r."workspaceId"=p."workspaceId" AND r."personId"=p.id AND r.status='ACTIVE' AND ${period(Prisma.raw('r'))} AND r.${col} IN (${values(key)}) AND EXISTS(SELECT 1 FROM dictionary di WHERE di."workspaceId"=p."workspaceId" AND di.namespace=${namespace} AND di.code=r.${col} AND di.status='ACTIVE'))`);}
 if(q.heightMin||q.heightMax){const checks=[Prisma.sql`c."workspaceId"=p."workspaceId" AND c."personId"=p.id AND c."supersededById" IS NULL AND m."personId"=p.id AND m.status='CONFIRMED' AND m."heightCm" IS NOT NULL`];if(q.heightMin)checks.push(Prisma.sql`m."heightCm">=${Number(q.heightMin)}`);if(q.heightMax)checks.push(Prisma.sql`m."heightCm"<=${Number(q.heightMax)}`);clauses.push(Prisma.sql`EXISTS(SELECT 1 FROM "castingProfiles" c JOIN "measurementSets" m ON m."workspaceId"=c."workspaceId" AND m.id=c."currentMeasurementSetId" WHERE ${Prisma.join(checks,' AND ')})`);}
 if(q.industryCode||q.workTypeCode){const checks=[Prisma.sql`c."workspaceId"=p."workspaceId" AND c."personId"=p.id AND w.status<>'ERASED'`];if(q.role)checks.push(Prisma.sql`c."roleCode" IN (${values('role')})`);if(roleConditions.length)checks.push(Prisma.sql`EXISTS(SELECT 1 FROM "personRoles" r WHERE ${Prisma.join(roleConditions,' AND ')} AND r."roleCode"=c."roleCode")`);if(q.industryCode)checks.push(Prisma.sql`w."industryCode" IN (${values('industryCode')})`);if(q.workTypeCode)checks.push(Prisma.sql`w."workTypeCodes" && ARRAY[${values('workTypeCode')}]::text[]`);clauses.push(Prisma.sql`EXISTS(SELECT 1 FROM "workCredits" c JOIN works w ON w."workspaceId"=c."workspaceId" AND w.id=c."workId" WHERE ${Prisma.join(checks,' AND ')})`);}
 return {rows:Prisma.sql`SELECT DISTINCT p.id FROM people p ${profile} WHERE ${Prisma.join(clauses,' AND ')} LIMIT 50001`,count:null};
}
