import {readFileSync} from 'node:fs';
import {isAbsolute} from 'node:path';
import type {TalentAuthConfig} from '../../../packages/core/src/talent-auth-model.ts';
export function loadTalentAuthConfig(environment:string):TalentAuthConfig|undefined {
 const flag=process.env.TALENT_PORTAL_ENABLED??'false';if(!['true','false'].includes(flag))throw new Error('TALENT_PORTAL_ENABLED invalid');if(flag==='false')return undefined;
 const value=(name:string)=>{const v=process.env[name];if(!v)throw new Error(name+' required');return v;};
 const key=(name:string)=>{const path=value(name);if(!isAbsolute(path))throw new Error(name+' must be absolute');const text=readFileSync(path,'utf8').trim();if(!/^[a-f0-9]{64}$/i.test(text))throw new Error(name+' invalid');return Buffer.from(text,'hex');};
 const number=(name:string,def:number,max:number)=>{const n=Number(process.env[name]??def);if(!Number.isSafeInteger(n)||n<1||n>max)throw new Error(name+' invalid');return n;};
 const providerType=value('TALENT_AUTH_PROVIDER');if(!['test','http'].includes(providerType))throw new Error('TALENT_AUTH_PROVIDER invalid');if(providerType==='test'&&!['local','test'].includes(environment))throw new Error('Test auth provider forbidden');
 const endpoint=value('TALENT_AUTH_ENDPOINT');const url=new URL(endpoint);if(url.username||url.password||url.hash||url.search||!(url.protocol==='https:'||providerType==='test'&&url.protocol==='http:'&&['127.0.0.1','[::1]'].includes(url.hostname)))throw new Error('TALENT_AUTH_ENDPOINT invalid');
 const credentialFile=value('TALENT_AUTH_CREDENTIAL_FILE');if(!isAbsolute(credentialFile))throw new Error('TALENT_AUTH_CREDENTIAL_FILE invalid');const credential=readFileSync(credentialFile,'utf8').trim();if(credential.length<16||credential.length>4096||/[\r\n]/.test(credential))throw new Error('TALENT_AUTH_CREDENTIAL_FILE invalid');
 const c:TalentAuthConfig={enabled:true,providerType:providerType as 'test'|'http',endpoint,credential,sender:value('TALENT_AUTH_SENDER'),template:value('TALENT_AUTH_TEMPLATE'),timeoutMs:number('TALENT_AUTH_TIMEOUT_MS',10000,30000),identityKey:key('TALENT_IDENTITY_KEY_FILE'),codeKey:key('TALENT_CODE_KEY_FILE'),sessionKey:key('TALENT_SESSION_KEY_FILE'),messageKey:key('TALENT_MESSAGE_KEY_FILE'),csrfKey:key('TALENT_CSRF_KEY_FILE'),idleMs:number('TALENT_SESSION_IDLE_DAYS',7,7)*86400000,absoluteMs:number('TALENT_SESSION_ABSOLUTE_DAYS',30,30)*86400000,contextMs:number('TALENT_CONTEXT_MINUTES',15,15)*60000,challengeMs:number('TALENT_OTP_MINUTES',10,10)*60000,maxAttempts:number('TALENT_OTP_MAX_ATTEMPTS',5,5),resendMs:number('TALENT_OTP_RESEND_SECONDS',60,3600)*1000,identityHourly:number('TALENT_OTP_IDENTITY_HOURLY',5,5),identityDaily:number('TALENT_OTP_IDENTITY_DAILY',10,10),ipHourly:number('TALENT_OTP_IP_HOURLY',20,20),workspaceHourly:number('TALENT_AUTH_HOURLY',100,100),workspaceDaily:number('TALENT_AUTH_DAILY',200,200)};
 if(c.idleMs>c.absoluteMs||c.resendMs<60000||c.sender.length>200||c.template.length>200)throw new Error('Talent auth limits invalid');
 const keys=[c.identityKey,c.codeKey,c.sessionKey,c.messageKey,c.csrfKey];if(new Set(keys.map(k=>k.toString('hex'))).size!==keys.length)throw new Error('Talent keys must be independent');return c;
}
