-- M1 additive private image tables. Prior applied migrations are immutable.
BEGIN;
CREATE TABLE "uploads" (
  "id" UUID NOT NULL PRIMARY KEY,
  "workspaceId" UUID NOT NULL,
  "createdAt" TIMESTAMPTZ(3) NOT NULL,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL,
  "revision" INTEGER NOT NULL,
  "actorId" UUID NOT NULL,
  "sourceId" UUID NOT NULL,
  "scopeId" UUID NOT NULL,
  "actorRevision" INTEGER NOT NULL,
  "actorEpoch" INTEGER NOT NULL,
  "sourceRevision" INTEGER NOT NULL,
  "sourceEpoch" INTEGER NOT NULL,
  "scopeRevision" INTEGER NOT NULL,
  "personId" UUID,
  "personScopeId" UUID,
  "personEpoch" INTEGER,
  "personScopeRevision" INTEGER,
  "fileName" TEXT NOT NULL,
  "mime" TEXT NOT NULL,
  "expectedHash" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "expectedBytes" INTEGER NOT NULL,
  "expiresAt" TIMESTAMPTZ(3) NOT NULL,
  "renewals" INTEGER NOT NULL,
  "attempts" INTEGER NOT NULL,
  "receiveToken" UUID,
  "leaseToken" UUID,
  "leaseUntil" TIMESTAMPTZ(3),
  "errorCode" TEXT,
  "purgedAt" TIMESTAMPTZ(3),
  CONSTRAINT "uploads_workspace_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "uploads_actorIdRef_fkey" FOREIGN KEY ("workspaceId", "actorId") REFERENCES "memberships"("workspaceId", "id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "uploads_sourceIdRef_fkey" FOREIGN KEY ("workspaceId", "sourceId") REFERENCES "sources"("workspaceId", "id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "uploads_scopeIdRef_fkey" FOREIGN KEY ("workspaceId", "scopeId") REFERENCES "scopes"("workspaceId", "id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "uploads_personIdRef_fkey" FOREIGN KEY ("workspaceId", "personId") REFERENCES "people"("workspaceId", "id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "uploads_personScopeIdRef_fkey" FOREIGN KEY ("workspaceId", "personScopeId") REFERENCES "scopes"("workspaceId", "id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "uploads_m1_check_0" CHECK ("revision" > 0),
  CONSTRAINT "uploads_m1_check_1" CHECK ("updatedAt" >= "createdAt"),
  CONSTRAINT "uploads_m1_check_2" CHECK ("mime" IN ('image/jpeg','image/png','image/webp')),
  CONSTRAINT "uploads_m1_check_3" CHECK ("expectedBytes" BETWEEN 1 AND 30000000),
  CONSTRAINT "uploads_m1_check_4" CHECK ("expectedHash" ~ '^[a-f0-9]{64}$'),
  CONSTRAINT "uploads_m1_check_5" CHECK ("renewals" BETWEEN 0 AND 2),
  CONSTRAINT "uploads_m1_check_6" CHECK ("attempts" BETWEEN 0 AND 3),
  CONSTRAINT "uploads_m1_check_7" CHECK ("state" IN ('OPEN','RECEIVING','UPLOADED','QUEUED','PROCESSING','READY','FAILED','CANCELLED')),
  CONSTRAINT "uploads_m1_check_8" CHECK ((("state" IN ('RECEIVING','PROCESSING')) = ("leaseToken" IS NOT NULL AND "leaseUntil" IS NOT NULL)) AND (("leaseToken" IS NULL) = ("leaseUntil" IS NULL))),
  CONSTRAINT "uploads_m1_check_9" CHECK ("state" NOT IN ('RECEIVING','UPLOADED','QUEUED','PROCESSING','READY') OR "receiveToken" IS NOT NULL),
  CONSTRAINT "uploads_m1_check_10" CHECK ("purgedAt" IS NULL OR "state" IN ('FAILED','CANCELLED')),
  CONSTRAINT "uploads_m1_check_11" CHECK (("personId" IS NULL AND "personScopeId" IS NULL AND "personEpoch" IS NULL AND "personScopeRevision" IS NULL) OR ("personId" IS NOT NULL AND "personScopeId" IS NOT NULL AND "personEpoch" IS NOT NULL AND "personScopeRevision" IS NOT NULL AND "personEpoch" > 0 AND "personScopeRevision" > 0)),
  CONSTRAINT "uploads_m1_check_12" CHECK ("expiresAt" > "createdAt"),
  CONSTRAINT "uploads_m1_check_13" CHECK ("actorRevision" > 0),
  CONSTRAINT "uploads_m1_check_14" CHECK ("actorEpoch" > 0),
  CONSTRAINT "uploads_m1_check_15" CHECK ("sourceRevision" > 0),
  CONSTRAINT "uploads_m1_check_16" CHECK ("sourceEpoch" > 0),
  CONSTRAINT "uploads_m1_check_17" CHECK ("scopeRevision" > 0)
);
CREATE UNIQUE INDEX "uploads_workspaceId_id_key" ON "uploads"("workspaceId","id");
CREATE INDEX "uploads_lookup_idx" ON "uploads"("workspaceId","actorId","state");
CREATE TABLE "assets" (
  "id" UUID NOT NULL PRIMARY KEY,
  "workspaceId" UUID NOT NULL,
  "createdAt" TIMESTAMPTZ(3) NOT NULL,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL,
  "revision" INTEGER NOT NULL,
  "uploadId" UUID NOT NULL,
  "sourceId" UUID NOT NULL,
  "scopeId" UUID NOT NULL,
  "objectToken" UUID NOT NULL,
  "personId" UUID,
  "fileName" TEXT NOT NULL,
  "mime" TEXT NOT NULL,
  "sha256" TEXT NOT NULL,
  "previewHash" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "bytes" INTEGER NOT NULL,
  "width" INTEGER NOT NULL,
  "height" INTEGER NOT NULL,
  "previewBytes" INTEGER NOT NULL,
  CONSTRAINT "assets_workspace_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "assets_uploadIdRef_fkey" FOREIGN KEY ("workspaceId", "uploadId") REFERENCES "uploads"("workspaceId", "id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "assets_sourceIdRef_fkey" FOREIGN KEY ("workspaceId", "sourceId") REFERENCES "sources"("workspaceId", "id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "assets_scopeIdRef_fkey" FOREIGN KEY ("workspaceId", "scopeId") REFERENCES "scopes"("workspaceId", "id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "assets_personIdRef_fkey" FOREIGN KEY ("workspaceId", "personId") REFERENCES "people"("workspaceId", "id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "assets_m1_check_0" CHECK ("revision" > 0),
  CONSTRAINT "assets_m1_check_1" CHECK ("updatedAt" >= "createdAt"),
  CONSTRAINT "assets_m1_check_2" CHECK ("mime" IN ('image/jpeg','image/png','image/webp')),
  CONSTRAINT "assets_m1_check_3" CHECK ("state" IN ('READY','QUARANTINED')),
  CONSTRAINT "assets_m1_check_4" CHECK ("bytes" BETWEEN 1 AND 30000000),
  CONSTRAINT "assets_m1_check_5" CHECK ("previewBytes" BETWEEN 1 AND 5000000),
  CONSTRAINT "assets_m1_check_6" CHECK ("width" > 0 AND "height" > 0 AND "width"::bigint * "height"::bigint <= 60000000),
  CONSTRAINT "assets_m1_check_7" CHECK ("sha256" ~ '^[a-f0-9]{64}$' AND "previewHash" ~ '^[a-f0-9]{64}$'),
  CONSTRAINT "assets_m1_check_8" CHECK ("id" = "uploadId")
);
CREATE UNIQUE INDEX "assets_workspaceId_id_key" ON "assets"("workspaceId","id");
CREATE INDEX "assets_lookup_idx" ON "assets"("workspaceId","sourceId","personId");
COMMIT;
